### ISSUE TITLE
Minishift fails to deploy on hyper-v on windows

### ISSUE THREAD

**Issue by dgauda** [minishift/minishift#2105] opened 2018-03-09 09:13 UTC
### General information

  * Minishift version: 1.7.0
  * OS:  Windows 10 Pro
  * Hypervisor:  Hyper-V 

### Steps to reproduce

  1.  minishift fails to find hyper-v virtual switch on windows

### Logs

PS C:\Users\dgauda\Minishift> minishift start --show-libmachine-logs -v5
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at C:\Users\dgauda\Minishift\minishift.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:53719
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
(minishift) Calling .SetConfigFromFlags
(minishift) Trying to access option engine-install-url which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key engine-install-url
(minishift) Trying to access option swarm-master which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) Type assertion did not go smoothly to bool for key swarm-master
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Command Get-VM).ModuleName
(minishift) Trying to access option swarm-host which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-host
(minishift) Trying to access option swarm-discovery which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-discovery
(minishift) DBG | [stdout =====>] : Hyper-V
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
 @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Hyper-V Administra
tors")
.(minishift) DBG | [stdout =====>] : True
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (Get-VMSwitch).Name
.(minishift) DBG | [stdout =====>] : Default Switch
(minishift) DBG | External Virtual Switch
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetConfigRaw
Creating machine...
(minishift) Calling .Create
(minishift) Downloading C:\Users\dgauda\.minishift\cache\boot2docker.iso from file://C:/Users/dgauda/.minishift/cache/iso/minishift-b2d.iso...
(minishift) Creating SSH key...
(minishift) Creating VM...
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (Get-VMSwitch).Name
.(minishift) DBG | [stdout =====>] : Default Switch
(minishift) DBG | External Virtual Switch
(minishift) Using switch "External Virtual Switch"
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
(minishift) DBG | [stdout =====>] : True
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
 New-VHD -Path 'C:\Users\dgauda\.minishift\machines\minishift\fixed.vhd' -SizeBytes 10MB -Fixed
(minishift) Creating VHD
.(minishift) DBG | [stdout =====>] :
(minishift) DBG |
(minishift) DBG | ComputerName            : LIN39000557
(minishift) DBG | Path                    : C:\Users\dgauda\.minishift\machines\minishift\fixed.vhd
(minishift) DBG | VhdFormat               : VHD
(minishift) DBG | VhdType                 : Fixed
(minishift) DBG | FileSize                : 10486272
(minishift) DBG | Size                    : 10485760
(minishift) DBG | MinimumSize             :
(minishift) DBG | LogicalSectorSize       : 512
(minishift) DBG | PhysicalSectorSize      : 512
(minishift) DBG | BlockSize               : 0
(minishift) DBG | ParentPath              :
(minishift) DBG | DiskIdentifier          : B0423F64-92D1-4313-A3FB-D21641DD910F
(minishift) DBG | FragmentationPercentage : 0
(minishift) DBG | Alignment               : 1
(minishift) DBG | Attached                : False
(minishift) DBG | DiskNumber              :
(minishift) DBG | IsPMEMCompatible        : False
(minishift) DBG | AddressAbstractionType  : None
(minishift) DBG | Number                  :
(minishift) DBG |
(minishift) DBG |
(minishift) DBG |
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | Writing magic tar header
(minishift) DBG | Writing SSH key tar header
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive
 Convert-VHD -Path 'C:\Users\dgauda\.minishift\machines\minishift\fixed.vhd' -DestinationPath 'C:\Users\dgauda\.minishif
t\machines\minishift\disk.vhd' -VHDType Dynamic -DeleteSource
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Resize-VHD -Path 'C:\Users\dgauda\.minishift\machines\minishift\disk.vhd' -SizeBytes 20000MB
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive New-VM minishift -Path 'C:\Users\dgauda\.minishift\machines\minishift' -SwitchName 'External Virtual Switch' -MemoryStartupBytes 2048MB
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | Name      State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
(minishift) DBG | ----      ----- ----------- ----------------- ------   ------             -------
(minishift) DBG | minishift Off   0           0                 00:00:00 Operating normally 8.2
(minishift) DBG |
(minishift) DBG |
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Set-VMProcessor minishift -Count 2
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Set-VMDvdDrive -VMName minishift -Path 'C:\Users\dgauda\.minishift\machines\minishift\boot2docker.iso'
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Add-VMHardDiskDrive -VMName minishift -Path 'C:\Users\dgauda\.minishift\machines\minishift\disk.vhd'
.(minishift) DBG | [stdout =====>] :
(minishift) Starting VM...
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Start-VM minishift
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] : Start-VM : 'minishift' failed to start. (Virtual machine ID 13DF6E1F-F066-47C7-879A-BCA72C1B9ADF)
(minishift) DBG | 'minishift' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID
(minishift) DBG | 13DF6E1F-F066-47C7-879A-BCA72C1B9ADF)
(minishift) DBG | At line:1 char:1
(minishift) DBG | + Start-VM minishift
(minishift) DBG | + ~~~~~~~~~~~~~~~~~~
(minishift) DBG |     + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
(minishift) DBG |     + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM
(minishift) DBG |
(minishift) DBG |
. FAIL E0309 14:39:44.202358    5764 start.go:355] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: exit status 1

**Comment by amitkrout** [comment] 2018-03-12 11:56
> Steps to reproduce

    minishift fails to find hyper-v virtual switch on windows


@dgauda The section ```Steps to reproduce``` is not clear. Can you please elaborate it more.

**Comment by amitkrout** [comment] 2018-03-12 12:59
https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v-driver @dgauda

**Comment by dgauda** [comment] 2018-03-14 06:55
@amitkrout I did followed steps fot setup driver plugin   . https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#hyper-v-driver

**Comment by gbraad** [comment] 2018-03-15 05:58
Make sure you have enough memory and/or disk space available.

**Comment by amitkrout** [comment] 2018-03-16 09:31
@dgauda i am able get the same error while running the second profile with ```memory 5120```. Profile fails if Hyper-V does not get the claimed memory. And these Hyper-V failure is not reported properly in docker machine.

To see the actual error you can use the command in powershell ```start-vm -name foo``` 
```
PS C:\minishift> Start-VM -name foo
Start-VM : 'foo' failed to start.
Not enough memory in the system to start the virtual machine foo.
Could not initialize memory: Ran out of memory (0x8007000E).
'foo' failed to start. (Virtual machine ID 150075D8-C047-4A52-8068-472333CCFDD6)
Not enough memory in the system to start the virtual machine foo with ram size 5120 megabytes. (Virtual machine ID
150075D8-C047-4A52-8068-472333CCFDD6)
'foo' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID
150075D8-C047-4A52-8068-472333CCFDD6)
At line:1 char:1
+ Start-VM -name foo
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

PS C:\minishift>
```

**Comment by gbraad** [comment] 2018-03-19 10:04
@dgauda any update on this?

**Comment by amitkrout** [comment] 2018-03-22 09:20
@dgauda are you there ?
@LalatenduMohanty As i mentioned above the failure is due to the resource issue and can be seen clearly in 
```
PS C:\minishift> Start-VM -name foo
[...]
Not enough memory in the system to start the virtual machine foo with ram size 5120 megabytes. (Virtual machine ID
150075D8-C047-4A52-8068-472333CCFDD6)
[...]
PS C:\minishift>
```
I think this is not a bug on minishift

**Comment by budhrg** [comment] 2018-03-22 09:37
> I think this is not a bug on minishift

Ya not a bug. I have experience this before.

**Comment by budhrg** [comment] 2018-03-26 14:19
Closing as it is not a bug. Please feel free if you have different opinion.

**Closed by budhrg** 2018-03-26 14:19 UTC
Labels: kind/bug, priority/major, status/needs-info
