### ISSUE TITLE
Inconsistent output between oc and web interface

### ISSUE THREAD

**Issue by jduncan-rva** [minishift/minishift#568] opened 2017-03-19 00:44 UTC
I'm using origin 1.4 from a minishift setup with the CentOS image. All functioning and up and running. It is in a kvm VM on Fedora 25.

The list of projects between the web interface and oc are pretty drastically different.

logged into the web UI and oc as system:admin

in the web interface you cannot see the default, openshift, openshift-infra, etc. projects. However they are visible to oc.
If you create a project in the web interface you can see it in oc
If you create a project in oc, you cannot see it in the web interface
I would assume that the project listings would be consistent in the web interface and with oc.

Version

OpenShift Master:
v1.4.1+3f9807a
Kubernetes Master:
v1.4.0+776c994

I've confirmed the same functionality with oc v1.4.1+3f9807a and oc v1.3.1

Steps To Reproduce

set up minishift with a CentOS image
log in as system:admin in the gui and with oc
create a project in the gui
create a project with oc
compare the lists
Current Result

in the web interface you cannot see the default, openshift, openshift-infra, etc. projects. However they are visible to oc.
If you create a project in the web interface you can see it in oc
If you create a project in oc, you cannot see it in the web interface
Expected Result

The project listings should be consistent using both methods.

I also opened this as https://github.com/openshift/origin/issues/13440

**Comment by jduncan-rva** [comment] 2017-03-19 00:46
it's configured with an AllowAll identity provider. 
ta-da.

**Comment by hferentschik** [comment] 2017-03-19 10:27
You really should not use system:admin for creating applications. The default namespace has a special meaning. It is encouraged to use the created 'developer' user  to create applications. 

Also whether you see the same projects via the oc CLI and the Web Console will depend on which user you are using. You won't be able to log in to the Console as system:admin (per default). So you cannot really compare what you see via oc using system:admin. However, if you are logged in as 'developer' on the CLI as well as the Web Console the view should be consistent.

**Comment by hferentschik** [comment] 2017-03-19 10:29
Closing this issue, since also  openshift/origin#13440 is closed. This is really expected behaviour.

**Closed by hferentschik** 2017-03-19 10:29 UTC
Labels: kind/bug, priority/major
