### ISSUE TITLE
Allow specification of VM IP address

### ISSUE THREAD

**Issue by marekjelen** [minishift/minishift#348] opened 2017-01-30 17:06 UTC
Please introduce something like

```
minishift start --ip-adress=<ip adress>
```

so that users are able to override the randomly selected IP address.

**Comment by hferentschik** [comment] 2017-01-30 21:38
Duplicate of issue #41

**Closed by hferentschik** 2017-01-30 21:38 UTC

**Comment by gbraad** [comment] 2017-10-07 01:45
@marekjelen It is a difficult problem to solve, but you can have a look at: #1316 which solves this for HyperV, and #1457 which allows you to fix the address in place (hopefully prevents the situation as described in #343). Let me know what you think...
