### ISSUE TITLE
Add a profile for openshiftonline e.g. --profile=openshiftonline

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#549] opened 2017-03-15 07:34 UTC
As OpenShift is currently provisioned with different configs when running online; DevPreview, Dedicated, Online ..., it could be interesting to propose a parameter to Minishift to specify the setup to be used.
Currently, OSO instances are more restrictive concerning the cpu, memory & disk usage like also the number of projects that an end user can create [1]

`minishift start --profile=openshiftonline`

As openshift team has created using ansible such provisioning scripts, minishift could rely on such work to provision the machine using a profile parameter

 [1] : https://github.com/obsidian-toaster/platform/blob/master/tooling/openshift/openshift-vm.adoc#limitation-setup

**Comment by jorgemoralespou** [comment] 2017-03-15 11:13
@hferentschik I think this should belong to an addon/bundle as it is a specific feature for a specific user.

**Comment by hferentschik** [comment] 2017-03-15 12:45
Would be my first guess as well.

**Comment by LalatenduMohanty** [comment] 2017-03-23 01:22
This is duplicate of #177.

**Comment by LalatenduMohanty** [comment] 2018-02-15 07:00
@minishift/minishift-dev Do we need this anymore? I do not see this requests anymore. So it would be better to close this issue. WDYT?

**Comment by budhrg** [comment] 2018-02-15 08:13
+1 for close @LalatenduMohanty

**Closed** 2018-03-06 19:08 UTC
Labels: kind/feature, priority/major
