### ISSUE TITLE
Hide the rate limit exceeded messages

### ISSUE THREAD

**Issue by chirino** [minishift/minishift#192] opened 2016-12-15 19:21 UTC
The github "403 API rate limit exceeded" message is kinda common, would be nice if it could be hidden unless your in some verbose mode.

**Comment by hferentschik** [comment] 2016-12-16 13:40
Where and how did you see that?

**Comment by chirino** [comment] 2016-12-16 16:13
Happens after a while of using minishift intensely..  Think it's due to the update check it does against github apis.

**Comment by hferentschik** [comment] 2016-12-19 08:45
> Happens after a while of using minishift intensely.. 

Intensely in sense of starting/stopping/deleting the machine very often in a short time frame or in the sense of having it running for a long time. In the former case, I can see that the above error occurs, but afaik there are no checks while the VM is running. Either way, we will look into it.

**Comment by hferentschik** [comment] 2016-12-19 09:55
Duplicate of issue #112

**Comment by hferentschik** [comment] 2017-01-09 10:22
This will be "fixed" by issue #246 which (temporarily) disables automatic update checks.

**Comment by hferentschik** [comment] 2017-01-09 12:19
merged via pull request #246

**Closed by hferentschik** 2017-01-09 12:19 UTC
Labels: bug, minor
