### ISSUE TITLE
Error accessing web console in Safari browser after minishift start 

### ISSUE THREAD

**Issue by mmalina** [minishift/minishift#199] opened 2016-12-19 14:08 UTC
I tried out Minishift 1.0.0-beta.1 on macOS Sierra with VirtualBox.
Started with this command:
./minishift --vm-driver=virtualbox start

After it successfully started, I entered https://192.168.99.100:8443 in my browser.
It asked me which certificate to use. There were two offered, I chose the first, not sure what this is about. Then I allowed everything when prompted.
But in the end, I keep being redirected to the error page:
https://192.168.99.100:8443/console/error?error_description=Unable%20to%20load%20details%20about%20the%20server.%20If%20the%20problem%20continues,%20please%20contact%20your%20system%20administrator.&error=API_DISCOVERY

**Comment by mmalina** [comment] 2016-12-19 14:13
Update: I tried to access the console again in an anonymous web browser window and it just keeps Loading... (4 minutes already)

**Comment by hferentschik** [comment] 2016-12-19 23:15
> It asked me which certificate to use.

What exactly do you mean? I don't think I have seen this. It should behave as current CDK. OpenShift uses self signed certificates, so you will need to add a security exception, but I am not sure what this "selection" you describe is about. Can you re-produce the problem and how? Can you give some more context about what you had to do. Messages displayed or maybe a screenshot?

If you want to try from scratch, delete your ~/.minishift directory and start over. Does the problem still occur?

**Comment by mmalina** [comment] 2016-12-20 09:53
So I tried again. In Chrome, it works exactly as you describe - I am told that the connection is not safe (self-issued cert) and am able to add an exception and then see the console ok.
But in Safari, this doesn't work for me right now.
When I entered the url now, first thing the browser showed me was this:
https://www.dropbox.com/s/mangb10uejssdxt/Screenshot%202016-12-20%2010.47.50.png?dl=0
Strange.
Then I got this:
https://www.dropbox.com/s/dc3ctnxu10c7rf1/Screenshot%202016-12-20%2010.48.10.png?dl=0
And when I clicked Continue, I got the same message again and again and again and was not able to access the console at all.
I guess it's a problem of Safari, but I'm not exactly sure what's the problem here.
Restarting the browser may help, I will try that.

**Comment by hferentschik** [comment] 2016-12-20 13:01
> I guess it's a problem of Safari, but I'm not exactly sure what's the problem here.

Now that you mention it, I remember seeing this once as well. I forgot about it, since I usually use Firefox or Chrome. I am also not sure what the cause for this is. There should really by no difference.
I guess what would interest me, is whether one can use Safari with ADB / CDK? Have you tried. If this works with ADB / CDK we need to take a closer look at the differences here.

**Comment by mmalina** [comment] 2016-12-21 13:12
So I tried with CDK 2.3 and exactly the same thing happens there - in Chrome it works fine, but in Safari, I got this prompt:
https://www.dropbox.com/s/r9l04eai2uwj9vf/Screenshot%202016-12-21%2014.11.03.png?dl=0
And then I accepted everything but it still ended up with an error.

**Comment by hferentschik** [comment] 2016-12-21 20:17
> So I tried with CDK 2.3 and exactly the same thing happens there

Interesting, so we never really tested on Safari it seems? Wonder whether this is reported somewhere else? Surely someone else must have noticed this before.

**Comment by LutzLange** [comment] 2017-08-03 08:40
Safari does not work for me all well. 

Tested on 
minishift v1.3.1+f4900b0
CDK v3.0.0-01082017-1

I get an error message : "Unable to load details about the server" And the option to "Return to console". I can click this, but get sent back to the same page. I was never asked to authenticate at all.

Chrome works fine.

**Comment by hferentschik** [comment] 2017-08-03 08:45
This is not really a Minishift issue, but rather how Safari handles the self signed certificates. It might work, if you trust the certificate first, but you would have to do this for each cluster you create. See also #1031.

**Comment by LutzLange** [comment] 2017-08-03 09:04
I did trust the certificate. This is part of the dialog that pops up when I connect initially.

I just found that tha URL for that page has an error description that reads : "Unable to load details"
Is there a way to make minishift console use chrome instead? Other than changing the default browser that is?

**Comment by hferentschik** [comment] 2017-08-03 09:08
Trust in the keychain app, not in the browser. You tell the OS (and hence Safari) that you trust the certificate. See also https://blog.openshift.com/local-development-self-signed-certificates/

**Comment by praveenkumar** [comment] 2017-10-12 13:19
@hferentschik @LalatenduMohanty As we discussed this is something we can put in the known issue doc for minishift and close it.

**Comment by anjannath** [comment] 2017-10-13 06:35
@praveenkumar i currently don't see a known issues section in the docs. A new section will be added?

**Comment by budhrg** [comment] 2017-10-13 07:13
Probably in the troubleshooting guide.

**Comment by anjannath** [comment] 2017-10-13 07:40
I was thinking of taking it up, but i don't have safari so can't really be sure, to describe it well.

**Comment by mmalina** [comment] 2017-10-18 13:53
Hi all, I tried this now with cdk 3.1.1. I started it and then entered https://192.168.99.100:8443 in an anonymous window of Safari. I got the "not safe" message, i.e. invalid certificate. When I clicked "proceed anyway", the openshift login window appeared normally.

So I guess this is no longer an issue?

**Comment by hferentschik** [comment] 2017-10-30 14:46
Same here.

**Comment by JimTyrrell** [comment] 2018-02-07 14:24
Talking with Lalatendu Mohanty and Praveen Kumar, it seems Safari 10.1.2 is not working.

**Comment by LalatenduMohanty** [comment] 2018-02-07 14:39
I would suggest we add this to the documentation and suggest users use Chrome or Firefox when they use the web console.

**Comment by praveenkumar** [comment] 2018-02-08 04:16
Today I tried again with updated safari- `Version 11.0.2 (13604.4.7.1.3)` and there it works as expected. @JimTyrrell can you please provide below details? We still need to put in the documents for older versions of safari.

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.2 (17C88)
      Kernel Version: Darwin 17.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 19:16
```

**Comment by JimTyrrell** [comment] 2018-02-08 15:40
system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Jim’s MacBook Pro (2)
      User Name: Jim Tyrrell (jimtyrrell)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 9 days 11:27

With Safari Version 10.1.2 (12603.3.8) 

I still see an error message as shown.
<img width="1149" alt="screen shot 2018-02-08 at 8 39 46 am" src="https://user-images.githubusercontent.com/4389749/35981882-a2f2af46-0cab-11e8-9f87-33d155504400.png">

**Comment by robin-owen** [comment] 2018-02-08 15:51
> I would suggest we add this to the documentation and suggest users use Chrome or Firefox when they use the web console.

Manually via `minishift console --url`, or is there a way to change which browser Minishift uses to open the console?

**Comment by wagnersza** [comment] 2018-02-09 16:31
+1

**Comment by anjannath** [comment] 2018-02-13 07:14
@robin-owen you can use this to open the url in chrome: 
```
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome `minishift console --url`
```

**Comment by praveenkumar** [comment] 2018-02-16 06:38
> $ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome `minishift console --url`

That looks bit cryptic so better to add the manual steps in the document in case lower version of Safari used. @robin-owen wdyt?

**Comment by LalatenduMohanty** [comment] 2018-02-16 09:09
I agree with @praveenkumar. We should mention that an issue like this exist and they should be aware of it.

**Comment by robin-owen** [comment] 2018-02-16 10:19
@anjannath @LalatenduMohanty I agree with @praveenkumar here as well. We also can't be sure that any particular user has the application in a reliable location, particularly on macOS.

**Comment by LalatenduMohanty** [comment] 2018-03-11 19:31
@JimTyrrell Please take a look at https://github.com/minishift/minishift/pull/2113/ . I am trying add this information to documentation.

**Comment by JimTyrrell** [comment] 2018-03-12 15:58
@LalatenduMohanty not sure how to see this?  Any links would be helpful?  Sorry.

**Comment by budhrg** [comment] 2018-03-22 16:00
Resolved via https://github.com/minishift/minishift/pull/2113

**Closed by budhrg** 2018-03-22 16:00 UTC
Labels: component/documentation, kind/bug, priority/major, resolution/done
