### ISSUE TITLE
Edit expected values in cmd-config.feature which fails on Mac

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1471] opened 2017-10-02 13:35 UTC
On macOS when testing CDK, the expected memory value does not match the real value:
```
Expected: 'MemTotal:\s*35[0-1][0-9]{4} kB', Actual: 'MemTotal:        3444768 kB
```

**Comment by gbraad** [comment] 2017-10-02 14:59
This has to do with how some drivers use GB or GiB.

**Comment by agajdosi** [comment] 2017-10-03 08:10
@gbraad My understanding is the same, so I think we can just update the feature. Not a bug in Minishift AFAIU.

**Comment by gbraad** [comment] 2017-10-04 08:49
@agajdosi surely not a bug in Minishift, but rather the drivers/libmachine and how the hypervisors handle the request. More has been motivated on the dup #1484

**Comment by LalatenduMohanty** [comment] 2017-10-05 19:26
Resolved by https://github.com/minishift/minishift/pull/1495

**Closed by LalatenduMohanty** 2017-10-05 19:26 UTC
Labels: component/integration-test, easyfix, kind/bug, priority/major
