### ISSUE TITLE
hostPath not allowed in templates

### ISSUE THREAD

**Issue by mazzy89** [minishift/minishift#879] opened 2017-05-10 23:38 UTC
This is my `DeploymentConfig` which is part of my template

```yaml
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: "${NAME}"
  spec:
    replicas: 1
    selector:
      name: "${NAME}"
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: "${NAME}"
        name: "${NAME}"
      spec:
        containers:
        - env: []
          image: "${IMAGE}"
          volumeMounts:
          - mountPath: /home/app
            name: vol-app
          livenessProbe:
            httpGet:
              path: "${PROBE}"
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: minishift-demo
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: "${PROBE}"
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
        volumes:
        - name: vol-app
          hostPath:
            path: /Users/me/app
    triggers:
    - type: ConfigChange
```

when I try to deploy this template I got an error:

`Error creating: pods "server-2-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]`

Any resolution on this?

**Comment by gbraad** [comment] 2017-05-11 04:23
This is a duplicate of https://github.com/openshift/origin/issues/11153

I believe you would have to edit the following: https://docs.openshift.org/latest/admin_guide/manage_scc.html#use-the-hostpath-volume-plugin

**Comment by php-coder** [comment] 2017-05-17 12:43
While modifying `restricted` SCC should work, there is a better way -- granting permissions to the `default` service account to the `hostaccess` SCC. `oadm policy add-scc-to-user hostaccess -z default` should work. Note that in contrast to the issue in OpenShift, you need to grant permissions to a service account (because of using DeploymentConfig, not a simple Pod).

@mazzy89 If one of these comments works for you, could you close the issue then?

**Comment by agajdosi** [comment] 2017-09-26 08:47
Hi @mazzy89, have you tried suggested solutions? Did it worked for you?

**Comment by agajdosi** [comment] 2017-11-21 10:53
Hi @mazzy89 please let us know whether you are still facing this issue or it got resolved by using advices from comments above. Thank you for your time.

**Comment by praveenkumar** [comment] 2018-01-19 07:10
Closing this issue, no response from the reporter.

**Closed by praveenkumar** 2018-01-19 07:10 UTC
Labels: kind/bug, priority/major, status/needs-investigation
