### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by thatdocslady** [minishift/minishift#157] opened 2016-11-24 11:13 UTC
This issue covers the following requirements:

- Restructure existing files in a hierarchical way, right now everything is in the root folder and some files need to be placed in /docs/ directory, etc
- Convert all docs to ASCIIDoc
- Clean up readme and other files as needed to be more user-friendly

**Comment by LalatenduMohanty** [comment] 2016-11-24 11:21
@jimmidyson thoughts?

**Comment by jimmidyson** [comment] 2016-11-24 11:22
:100: I have spent no time on docs since forking minikube so all help appreciated.

**Comment by thatdocslady** [comment] 2016-11-24 11:23
@jimmidyson this is what I'm here for :-)

**Comment by jimmidyson** [comment] 2016-11-24 11:28
Then make it so, docs wiz - thanks!

**Comment by hferentschik** [comment] 2016-11-28 10:07
Duplicate of #138

**Closed by hferentschik** 2016-11-28 10:07 UTC
Labels: documentation
