### ISSUE TITLE
minishift openshift version list and --openshift-version is broken

### ISSUE THREAD

**Issue by containscafeine** [minishift/minishift#2134] opened 2018-03-15 08:31 UTC
### General information

  * Minishift version: minishift v1.14.0+1ec5877
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

```console
$ minishift openshift version list
The following OpenShift versions are available: 
        - v1.4.1
        - v1.5.0
        - v1.5.1
        - v3.10.0
        - v3.10.0-alpha.0
        - v3.6.0
        - v3.6.1
        - v3.7.0
        - v3.7.1
        - v3.8.0
        - v3.8.0-alpha.0
        - v3.8.0-alpha.1
        - v3.9.0
        - v3.9.0-alpha.0
        - v3.9.0-alpha.1
        - v3.9.0-alpha.2
        - v3.9.0-alpha.3
        - v3.9.0-alpha.4
$ minishift start --openshift-version v3.8.0
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.8.0' is valid ... FAIL
   v3.8.0 is not a valid OpenShift version
```
### Expected
There are invalid versions being shown in `minishift openshift version list` and hence it fails to start is `minishift start --openshift v3.8.0`.

**Comment by praveenkumar** [comment] 2018-03-15 08:36
We have a PR in place to fix list command out.

**Comment by LalatenduMohanty** [comment] 2018-03-16 07:44
@containscafeine we are aware of the issue . This is a duplicate of https://github.com/minishift/minishift/issues/2069 . Hence I am going to close this issue.

**Closed by LalatenduMohanty** 2018-03-16 07:44 UTC
