### ISSUE TITLE
Context is not switched while changing/creating profiles

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#1812] opened 2017-12-07 07:55 UTC
### General information

  * Minishift version: v1.9.0+a511b25
  * OS: macOS (should be in all )
  * Hypervisor: xhyve

### Steps to reproduce

  1.  create minishift instance with a `--profile ` like `minishift --profile demo1 start`, deploy some pods 
  2. do oc get pods , should see all pods, check and note the minishift ip
  3. now stop the cluster via minishift stop 
  4. again create minishift instance with a `--profile`  like `minishift --profile demo1 start`

### Expected
doing any kind of oc, e.g. oc get pods --all-namespaces should either return some pods or just show empty result

### Actual
But after waiting for sometime you will get `Unable to connect to the server: dial tcp <master-ip>: i/o timeout`, the master-ip is the minishift ip of the previous instance created in step 1

**Comment by LalatenduMohanty** [comment] 2017-12-07 08:03
@kameshsampath Two commands can only change the context:

* minishift profile set
* minishift start --profile <PROFILE_NAME>

When you are using `--profile` with other commands it is not supposed to change the context, this is as designed.  Hence we are fixing https://github.com/minishift/minishift/pull/1731/

Can you please update the steps to reproduce with the exact commands you used.

**Comment by LalatenduMohanty** [comment] 2017-12-07 08:05
With #1731 profiles will not be created when you pass `--profile`. But you can use `--profile` for existing profiles. Profile creating and running a profile (which is required for changing the context) are different things.

**Comment by kameshsampath** [comment] 2017-12-07 11:19
here is the sequence of commands that I ran
```
minishift set profile redhat-msa-3-workshop
minishift start
minishift stop 
minishift --profile sandbox start
oc get pods -w --all-namespaces # this will throw timeout error
```

> When you are using --profile with other commands it is not supposed to change the context, this is as designed. Hence we are fixing #1731 
I dont understand why

**Comment by kameshsampath** [comment] 2017-12-07 11:36
this is something i just saw now 
```
➜  apps minishift profile set redhat-msa-3-workshop
oc cli context could not changed for 'redhat-msa-3-workshop'. Make sure the profile is in running state or restart if the problem persists.
Profile 'redhat-msa-3-workshop' set as active profile
```

**Comment by LalatenduMohanty** [comment] 2017-12-07 11:46
> minishift set profile redhat-msa-3-workshop minishift start minishift stop minishift --profile sandbox start oc get pods -w --all-namespaces # this will throw timeout error

Can you run `oc status` and see if it is pointing to the correct IP i.e. `minishift ip`? 

Also did `minishift --profile sandbox start` completed successfully?

> I dont understand why

Because we do not expect users would want to change the `oc` context when they use `--profile` with commands other than `start`. `--profile` should be only used to run a `minishift` command for a profile which is not active. 

Changing oc context is an expensive operation and you do not want to do it unless you want to run oc commands against a particular OpenShift instance. For changing the context running of the profile is a prerequisite and the way `--profile` is expected to be used, we do not expect that the profile would be in running state always.

**Comment by LalatenduMohanty** [comment] 2017-12-07 11:52
@kameshsampath Also we had an issue https://github.com/minishift/minishift/issues/1591 wgich is fixed in 1.10.0.

**Comment by LalatenduMohanty** [comment] 2017-12-07 11:53
> apps minishift profile set redhat-msa-3-workshop
> oc cli context could not changed for 'redhat-msa-3-workshop'. Make sure the profile is in running state or restart if the problem persists.
> Profile 'redhat-msa-3-workshop' set as active profile

@kameshsampath This was an issue #1591, which is fixed in 1.10.0.

**Comment by LalatenduMohanty** [comment] 2017-12-07 11:54
> this is something i just saw now
> 
> ➜  apps minishift profile set redhat-msa-3-workshop
> oc cli context could not changed for 'redhat-msa-3-workshop'. Make sure the profile is in running state or restart if the problem persists.
> Profile 'redhat-msa-3-workshop' set as active profile

@kameshsampath This is fixed as part of #1591 and will be available in 1.10.0.

**Comment by jorgemoralespou** [comment] 2017-12-11 20:21
I think that the problem, as it happens with oc cluster, is that only first time a profile is created the context is switched.

**Comment by anjannath** [comment] 2017-12-12 06:37
@kameshsampath Can you try out the [latest relase](https://github.com/minishift/minishift/releases/tag/v1.10.0), and verify if the issue got fixed.

**Comment by anjannath** [comment] 2017-12-12 06:39
@jorgemoralespou Now the context is set when switching from a profile, at startup and also on creation of new profile.

**Comment by jorgemoralespou** [comment] 2017-12-12 10:18
+1
Great news.
You mean it will be in 1.11?

**Comment by kameshsampath** [comment] 2017-12-12 14:19
@anjannath 

> @kameshsampath Can you try out the latest relase, and verify if the issue got fixed.

will try later and keep this updated

**Comment by LalatenduMohanty** [comment] 2017-12-14 08:02
@kameshsampath confirmed that it is working for him now and we can close the issue. Thanks.

**Closed by LalatenduMohanty** 2017-12-14 08:02 UTC
Labels: component/profile, kind/bug, priority/major, status/needs-info
