### ISSUE TITLE
Error during cluster up - 

### ISSUE THREAD

**Issue by jwlai** [minishift/minishift#2182] opened 2018-03-27 00:08 UTC
### General information

  * Minishift version: minishift v1.14.0+1ec5877
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1. minishift start --iso-url http://artifacts.ci.centos.org/minishift/minishift-centos-iso/pr/232/m
inishift-centos7.iso --show-libmachine-logs -v 5

### Expected
1.  Minishift to print the server names and work.

### Actual
An Error occurs. Cannot verify Docker Version and fails to cluster up

-- Checking Docker version ...
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... FAIL
   Error: unexpected error while checking OpenShift container state
   Caused By:
     Error: An error occurred trying to connect: Get https://192.168.86.42:2376/v1.26/containers/origin/json: EOF
Error during 'cluster up' execution: Error starting the cluster.

### Logs

https://gist.github.com/jwlai/201c81ad0c74175289c3651a5596b36d

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment] 2018-03-27 00:20
Hyper-V has an issue with statup with the current release.
A new release will be issued today...

It look ooks a lot like a duplicate of #2087
<https://github.com/minishift/minishift/issues/2087>

**Comment by gbraad** [comment] 2018-03-27 07:28
Finally got some time to observe the log... and this probably is not a duplicate... why use PR 232 as ISO?
From the log i can see startup till `oc cluster up` works as expected. I also see it is a new instance... but fails on the call to see if the origin container exists.

```
-- Running 'oc' with: 'cluster up --use-existing-config --host-pv-dir /var/lib/minishift/openshift.local.pv --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.86.42.nip.io --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata'
Starting OpenShift using openshift/origin:v3.7.1 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ...
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... FAIL
   Error: unexpected error while checking OpenShift container state
   Caused By:
     Error: An error occurred trying to connect: Get https://192.168.86.42:2376/v1.26/containers/origin/json: EOF
Error during 'cluster up' execution: Error starting the cluster.
```

Is this reproducible? Also, you are using a slightly older version of Minishift. Is there a reason for this?

**Comment by jwlai** [comment] 2018-03-27 14:24
Hm, I didn't notice that I was using an older minishift. The PR232 was just to try a diff image since there were concerns with the image from a previous bug. I am guessing I didn't restart powershell when I updated. I will try with the new version and report status..

**Comment by jwlai** [comment] 2018-03-27 15:11
Here's the update: 

General information
Minishift version: minishift v1.15.0+e07e789
OS: Windows
Hypervisor: Hyper-V
Steps to reproduce
minishift start --show-libmachine-logs -v 5
Expected
Minishift to print the server names and work.
Actual
I ran it twice, looks like the first time it fails on validating.
The first time.
`. FAIL E0327 10:34:33.313640   14680 start.go:368] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.86.49:2376": EOF
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.86.49:2376": EOF
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.`

2nd Time
```
-- Checking Docker version ...
WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... FAIL
Error: unexpected error while checking OpenShift container state
Caused By:
Error: An error occurred trying to connect: Get https://192.168.86.42:2376/v1.26/containers/origin/json: EOF
Error during 'cluster up' execution: Error starting the cluster.
```

Logs
Here is run 1.
https://gist.github.com/jwlai/0c7dd4508fa6cc5dfe862aa661e7bdd1
Here is run 2.
https://gist.github.com/jwlai/ca88e53107e838861e3842c37d291270

You can start Minishift with minishift start --show-libmachine-logs -v5 to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment] 2018-03-27 23:24
Are you using minishift start for restarting a slightly older VM?

Likely the IP address has changed from previous runs. This causes issues
for both docker and openshift.

Consider deleting the VM and rerun start as it is a new VM. Tmif this is
the problem, this can be solved with later changes we have introduced...
Such as have the IP addressed be fixed as static to the VM.

On Tuesday, March 27, 2018, jwlai <notifications@github.com> wrote:
> Here's the update:
>
> General information
> Minishift version: minishift v1.15.0+e07e789
> OS: Windows
> Hypervisor: Hyper-V
> Steps to reproduce
> minishift start --show-libmachine-logs -v 5
> Expected
> Minishift to print the server names and work.
> Actual
> I ran it twice, looks like the first time it fails on validating.
> The first time.
> . FAIL E0327 10:34:33.313640 14680 start.go:368] Error starting the VM:
Error creating the VM. Error creating machine: Error checking the host:
Error checking and/or regenerating the certs: There was an error validating
certificates for host "192.168.86.49:2376": EOF You can attempt to
regenerate them using 'docker-machine regenerate-certs [name]'. Be advised
that this will trigger a Docker daemon restart which might stop running
containers. . Retrying. Error starting the VM: Error creating the VM. Error
creating machine: Error checking the host: Error checking and/or
regenerating the certs: There was an error validating certificates for host
"192.168.86.49:2376": EOF You can attempt to regenerate them using
'docker-machine regenerate-certs [name]'. Be advised that this will trigger
a Docker daemon restart which might stop running containers.
>
> 2nd Time
>
> -- Checking Docker version ...
> WARNING: Cannot verify Docker version
> -- Checking for existing OpenShift container ... FAIL
> Error: unexpected error while checking OpenShift container state
> Caused By:
> Error: An error occurred trying to connect: Get
https://192.168.86.42:2376/v1.26/containers/origin/json: EOF
> Error during 'cluster up' execution: Error starting the cluster.
>
> Logs
> Here is run 1.
> https://gist.github.com/jwlai/0c7dd4508fa6cc5dfe862aa661e7bdd1
> Here is run 2.
> https://gist.github.com/jwlai/ca88e53107e838861e3842c37d291270
>
> You can start Minishift with minishift start --show-libmachine-logs -v5
to collect logs.
> Please consider posting this on http://gist.github.com/ and post the link
in the issue.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/iVjsWOMSX4ntpOJXm2VxW4Z0tS9Kq-XD00w2gQsKvqbkC6AQeyBs0YQC4LrgH_8HTiwTX4vY9l2-YsxAb_qQJH3eAXuj3umCIcBMyym6hwdX0BjtmVtjwg0nYGLXyeoflqQGE5R1MHpyHlgk7sjHaxNSmsQb7w=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZsJ6Ft9TPYfUUf654sR_OwQhOZ6Uks5tilaIgaJpZM4S8FvX.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by jwlai** [comment] 2018-03-28 13:16
I'll give it a shot. But I did delete the VM, the .minishift folder and restart my computer to see. Will report shortly. Thanks for the support!

**Comment by gbraad** [comment] 2018-03-28 13:28
I am confused about the error... as I know where this happens, and it needs to check for an exsiting container.... else it will pull this container. The container is needed to perform tests if ports are available...

it seems the call to the docker daemon fails... but I would not know why. Are you by any chance on a company netwok or using a VPN?

**Comment by jwlai** [comment] 2018-03-28 13:40
No I am not using either. I do have a different switch up and my network is on "Private mode". I'll try turning off my firewall to see if that helps.

**Comment by jwlai** [comment] 2018-03-28 13:51
So I am getting that same error as the first run. Here's what I did...

minishift stop
minishift delete --clear-cache
Went into C:/Users/ojust/ and deleted .minishift folder
Restarted computer

minishift start --show-libmachine-logs -v5

I get error 1 again. 

. FAIL E0327 10:34:33.313640 14680 start.go:368] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.86.49:2376": EOF You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'. Be advised that this will trigger a Docker daemon restart which might stop running containers. . Retrying. Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.86.49:2376": EOF You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'. Be advised that this will trigger a Docker daemon restart which might stop running containers.

Do you knw what may cause this?

**Comment by gbraad** [comment] 2018-03-28 14:05
can you check the Hyper-V manager?
you should see a VM called minishift...

can you try to login as user 'root' ('centos' as password). And check the
IP address with `ip a`, and maybe the log from `journalctl -u
minishift-handle-user-data`

**Comment by jwlai** [comment] 2018-03-28 14:25
Have to put it in a picture..

**ip -a**
![image](https://user-images.githubusercontent.com/4219846/38035241-f9b3b776-3271-11e8-9a6b-b853c13de2a9.png)

"journalctl -u minishift-handle-user-data" 
![image](https://user-images.githubusercontent.com/4219846/38035402-548ca00e-3272-11e8-800f-8f5dc256cd95.png)

![image](https://user-images.githubusercontent.com/4219846/38035404-58051158-3272-11e8-85c0-77d501d824d9.png)

**Comment by gbraad** [comment] 2018-03-28 14:50
So, that seems to be OK

let me think ...

**Comment by jwlai** [comment] 2018-03-28 20:55
Hm.. I see.. Maybe hosed on my machine? Are there any hidden cache things for hyper-v you're aware of? Network interfaces.. I can ping the machine just fine... 

What's the part of the process that's throwing that error? How are the certificates for the vm generated and validated..? (Or is it a red herring error?)

**Comment by gbraad** [comment] 2018-05-27 21:57
Any update?

**Comment by gunjansharma18** [comment] 2018-06-21 08:49
The issue is not stale even I am facing the same issue with VMBox as a hypervisor as well could someone please help

**Comment by gbraad** [comment] 2018-06-21 09:00
Please describe your issue. Merely a cry for help will not result in a
solution.

**Comment by budhrg** [comment] 2018-06-29 12:19
@gunjansharma18 , could you describe the issue with more debug logs?

**Comment by budhram** [comment] 2018-09-25 08:18
Closing this due to inactivity. 
Please feel free to reopen it when you encounter the issue again.

**Closed by budhram** 2018-09-25 08:18 UTC
Labels: kind/bug, priority/major, status/needs-info
