### ISSUE TITLE
Proxy connection issue on "oc new-app" and "create sample app in web console"

### ISSUE THREAD

**Issue by asonhung** [minishift/minishift#3101] opened 2019-01-02 07:15 UTC
### General information

  * Minishift version: 1.29.0
  * OS: Windows 10
  * Hypervisor: VirtualBox 5.2.22

### Steps to reproduce

  1. minishift VM start successully with proxy information
  2. minishift ssh the docker VM and try docker pull some images. It also works to get through our corporate proxy server to download such images 
  3. however, when trying this commnad "oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp", it throws below error:

$ oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
warning: Cannot check if git requires authentication.
W0102 14:30:37.346521    7968 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: only a partial match was found for "nodejs": "openshift/nodejs"

  4. besides, when using the web console to new a sample Node.js application, it pops up the following error:

"An error occurred connecting to the server. 
   Failed to get imagestreamtags/image.openshift.io/v1/nodejs:10 (status 404)"

**Comment by birajdarabhishek1** [comment] 2019-01-03 06:19
Getting similar kind of error, Please help. 

Minishift version: 1.29.0
OS:  CentOs7
Hypervisor: KVM

Getting below Error:
[root@minishift ~]# oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
warning: Cannot check if git requires authentication.
W0103 10:46:07.983731 23618 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.42.1:53: server misbehaving
error: no tags found on matching image stream: "openshift/nodejs"

The image stream "openshift/nodejs" exists, but it has no tags.

Use --allow-missing-imagestream-tags to use this image stream

Also getting error from console : Failed to get imagestreamtags/image.openshift.io/v1/nodejs:10(status404)

@asonhung  Is your console is accessible from outside?

**Comment by asonhung** [comment] 2019-01-04 07:01
@birajdarabhishek1 Since the minishift VM hosting on Windows 10 Virtual box is getting NAT ip address, the web console is accessible from the Windows 10 desktop only.

Already turn on logging "minishift start -v5 --show-libmachine-logs" and see that the "oc cluster up" has such "http-proxy" parameter. Wildly guessing that the proxy configuration may have bug. Hope it could be fixed asap so that corporate users could enjoy the minishift.

**Comment by birajdarabhishek1** [comment] 2019-01-04 07:09
#1287 
Still they are working on same.

**Comment by birajdarabhishek1** [comment] 2019-01-10 05:45
Any Updates @gbraad @praveenkumar

**Comment by shockogit** [comment] 2019-01-20 21:46
Same here. Holding me up. Any updates?

**Comment by anjannath** [comment] 2019-01-29 07:38
@birajdarabhishek1 @shockogit @asonhung This is also a duplicate of #3125 
We are using #3125 to track this work, please ask questions/discussions in that issue, Closing this!

**Closed by anjannath** 2019-01-29 07:38 UTC
