### ISSUE TITLE
Issue #1628 Pre-flight connectivity check should honor proxy settings

### ISSUE THREAD

**Issue by svenstaro** [minishift/minishift#2245] opened 2018-04-05 13:55 UTC
Duplicate of #1628

---

~~In relation to #2244, the internet connectivity check should honor proxy settings.~~

**Comment by praveenkumar** [comment] 2018-04-06 04:49
@svenstaro I am not sure how you are running the minishift but check the following logs, for me, it's working. Can you paste log output which might help us to find what causing the issue for you?

```
$ ./minishift start --https-proxy=https://xxx:xxx@x.x.x.x:xxx
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
```

**Comment by anjannath** [comment] 2018-04-07 12:54
duplicate of #1628

**Comment by gbraad** [comment] 2018-04-07 12:56
Sorry to be picky. Can we close this issue instead as invalid, as the skip
is available, it was a warning by design for this purpose and it is
documented.

On Saturday, April 7, 2018, Anjan Nath <notifications@github.com> wrote:
> duplicate of #1628
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/dZpR9zFy3hAttMVGi1YkxzrrlJPB1sxC7ouEkaxvkDXb5WaWldkrlmXfdJGRNwJIOcO6uZFmtUgqbTwVaSmGMwXYLzyFQrTf5HYsKB1mk-0mLjiXq0RNnYvYj5tmJtqC9e-Jcz3A0zzR440JGLSDENfMPa2asA=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZmzgPqMkesK73Xguq_PQi8SDz5yoks5tmLcegaJpZM4TIf8q.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by svenstaro** [comment] 2018-04-07 13:00
I don't think it's technically speaking the same issue. The thing I fixed was only implemented a few days ago. Could you double check?

**Comment by LalatenduMohanty** [comment] 2018-04-08 08:06
@svenstaro this is a duplicate of  #1628. Hence closing it. Let us know if you do not agree.

**Closed by LalatenduMohanty** 2018-04-08 08:06 UTC
Labels: kind/bug, priority/major, resolution/duplicate, status/needs-info

**Comment by gbraad** [comment] 2018-04-08 08:12
accidently had changed the wrong issue/pr to change title

**Comment by svenstaro** [comment] 2018-04-08 08:14
Nah, it's all good. We have the other issue to track this.
