### ISSUE TITLE
Cannot start minishift: Error creating the VM. Error creating machine.

### ISSUE THREAD

**Issue by garyyang6** [minishift/minishift#1625] opened 2017-10-26 19:57 UTC
I cannot successfully start the minishift. Can someone help?

I installed docker, minishift, KVM Driver and Virtural box at CentOS 7
```
docker --version
Docker version 17.09.0-ce, build afdb6d4

minishift version
minishift v1.7.0+1549135
```

I got errors when I start the minishift.
```
[root@docker ~]# minishift start
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [=======================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ...................... FAIL E1026 19:54:45.973303    7663 start.go:355] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.42.64:2376": remote error: tls: bad certificate
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.42.64:2376": remote error: tls: bad certificate
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
```

**Comment by gbraad** [comment] 2017-10-27 03:46
Does this work now, as you also filed #1627 which shows a running VM.

Also, do not use KVM and VirtualBox on the same host (as you described in your description)

**Comment by budhrg** [comment] 2018-01-09 11:43
Any update @garyyang6  ?

**Comment by praveenkumar** [comment] 2018-01-19 05:25
Closing this because there is no update from the reporter.

**Comment by haohanbuti** [comment] 2018-01-21 21:10
I got exactly the same problem -- still struggling -- and would like to know what was the solution.

**Comment by haohanbuti** [comment] 2018-01-21 21:23
I am using the latest version of minishift and latest version of virtualbox, on a Windows 10 machine inside corporate firewall. http_proxy and https_proxy were used on the minishift start command line -- but always get stuck at the same point as in the OP's post. minishift status shows "minishift" is up but "openshift" stopped. I can do minishift ssh.

**Comment by haohanbuti** [comment] 2018-01-21 21:26
I have spent a lot of time on this -- very frustrating!   Can you re-open this issue? @gbraad

**Comment by sidd-harth** [comment] 2018-02-07 15:31
Any update an this,...I am scratching my head for the last 3 hours on the same error on Win10.

**Comment by gbraad** [comment] 2018-02-07 16:33
Please provide logs as the error message itself is not clear to determine
the cause. I also suggest to open a new issue... It might be an unrelated
issue, plus the fact that the issue template contains instructions on how
to collect the logs requested.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment] 2018-02-07 16:35
@lalatenduMohanty please close this issue as the follow up comments are for
Windows and not Linux+KVM as in the original issue. Please create new
issues instead of reopening (unless we are sure of a regression)

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by budhrg** [comment] 2018-03-26 14:16
Closing as per the comment.

**Closed by budhrg** 2018-03-26 14:16 UTC
Labels: status/needs-info
