### ISSUE TITLE
Atttempting to access minishift from behind corporate proxy with corporate cert

### ISSUE THREAD

**Issue by darkedges** [minishift/minishift#2255] opened 2018-04-09 00:11 UTC
When behind a corporate proxy with SSL Certificates signed by Corporate, there does not appear to be a way to add those certificates to the SSL Configuration so that a) curl and b) docker works.
You can do it manually but then you lose the configuration for the proxy between restarts as it looks like those HTTP_PROXY and HTTPS_PROXY environment variables are not persisted.

Any ideas on how I can import the Corporate CA's from initial startup and have the proxy configuration persisted.

### General information

  * Minishift version: 3.7.2
  * OS: Windows
  * Hypervisor:  VirtualBox

**Comment by anjannath** [comment] 2018-04-09 06:28
you can persist the proxy configs by using the `minishift config set` command:
`minishift config set http-proxy` and `minishift config set https-proxy`.

To import the certs in the vm from start you can use host-folder mount to mount a directory from the host to the correct location in the vm for the certs.

https://docs.openshift.org/latest/minishift/using/host-folders.html#sshfs-2

**Comment by gbraad** [comment] 2018-04-09 07:03
This is a duplicate of several other issues revolving around the same
problem.

At the moment we do not handle self-created CA-signed certs. You can try to
import them, but on restart they get hosed...

The best alternative is to use an intermediate proxy that only forwards,
such as `privoxy`. perhaps we should include this in the troubleshooting or
somewhere on our wiki.

**Comment by gbraad** [comment] 2018-04-09 07:03
See #1534

On Mon, Apr 9, 2018 at 3:03 PM, Gerard Braad <me@gbraad.nl> wrote:
> This is a duplicate of several other issues revolving around the same
> problem.
>
> At the moment we do not handle self-created CA-signed certs. You can try to
> import them, but on restart they get hosed...
>
> The best alternative is to use an intermediate proxy that only forwards,
> such as `privoxy`. perhaps we should include this in the troubleshooting or
> somewhere on our wiki.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment] 2018-04-09 07:50
Please comment on one of the issues in the previous message.

**Closed by gbraad** 2018-04-09 07:50 UTC
Labels: kind/question
