### ISSUE TITLE
`minishift start` should verify the minishift-b2d.iso

### ISSUE THREAD

**Issue by tobias** [minishift/minishift#984] opened 2017-06-02 17:48 UTC
If `~/.minishift/cache/iso/minishift-b2d.iso` exists, it is assumed to be the complete iso. If it is from a previous `minishift start` call that was interrupted, it may not be a complete download. One solution would be to check the `sha256` sum of the file, comparing it to the published sum, and redownloading if it doesn't match.

**Comment by LalatenduMohanty** [comment] 2017-06-02 18:06
@tobias I think this is duplicate of https://github.com/minishift/minishift/issues/344. If you agree lets close this issue and track it in the former issue.

**Comment by hferentschik** [comment] 2017-06-02 18:36
Duplicate of #344

**Closed** 2017-06-02 18:35 UTC

**Comment by tobias** [comment] 2017-06-02 18:52
Yes, I agree it is a dupe. Thanks!
