### ISSUE TITLE
Trying to understand hostfolders

### ISSUE THREAD

**Issue by magick93** [minishift/minishift#822] opened 2017-04-25 16:49 UTC
Hello

Im trying to map a folder on my host machine (Ubuntu 17.04) to the minishift kvm. My goal is to be able to ssh to the vm, so that I can build docker images, and have them immediately available in minishift. 

I have tried running `minishift  hostfolder add myfolder`  and I am prompted to enter a UNC path.

- What is the hostname/ip address I should use for this?
- Will this ip address change each time I start minishift?
- How do I specify the local and remote directories to use?

**Comment by hferentschik** [comment] 2017-04-25 18:03
This is  a duplicate of #655. Minishift 1.0.0 will include documentation for host folders.

> My goal is to be able to ssh to the vm, so that I can build docker images, and have them immediately available in minishift.

You don't need host folders for that and you don't need to ssh into the VM. You should be able to build the image against the Minishift Docker daemon using a Docker client on your host configured to use Minishift's Docker daemon (minishift docker-env). Once build, you push the image to the OpenShift registry using the appropriate name and tag.

**Closed by hferentschik** 2017-04-25 18:03 UTC

**Comment by magick93** [comment] 2017-04-25 18:15
> You should be able to build the image against the Minishift Docker daemon using a Docker client on your host configured to use Minishift's Docker daemon (minishift docker-env). Once build, you push the image to the OpenShift registry using the appropriate name and tag.

Unfortunately I'm unable to push - https://github.com/minishift/minishift/issues/817
