### ISSUE TITLE
Error 2 in make integration

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#582] opened 2017-03-21 08:30 UTC
```
[amit@dhcp35-153 minishift]$ make integration
go install -ldflags="-X github.com/minishift/minishift/pkg/version.version=1.0.0-beta.5 -X github.co
m/minishift/minishift/pkg/version.isoVersion=v1.0.2 -X github.com/minishift/minishift/pkg/version.op
enshiftVersion=v1.4.1 -s -w -extldflags '-static'" ./cmd/minishift
# github.com/minishift/minishift/cmd/minishift
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

Makefile:40: recipe for target '/home/amit/go/bin/minishift' failed
make: *** [/home/amit/go/bin/minishift] Error 2
```

**Comment by gbraad** [comment] 2017-03-21 08:38
duplicate of #579

**Closed by gbraad** 2017-03-21 08:38 UTC
