### ISSUE TITLE
Windows 10 not working with Beta4

### ISSUE THREAD

**Issue by thesteve0** [minishift/minishift#497] opened 2017-03-01 19:34 UTC
So I did minishift delete then deleted .minishift and then replaced the beta3 binary with my beta4 binary. 

I do this command:
PS C:\Users\steve> minishift start
Starting local OpenShift cluster using 'hyperv' hypervisor...

and it just hangs there. The VM starts up - I can see it running and connect it to from the hyper-v console. But when I connect in I just see the boot2docker prompt and nothing else. 

I then ctrl-c to get prompt back  and do 
PS C:\Users\steve> minishift stop
Stopping local OpenShift cluster...
Error stopping cluster:  Error unregistring the VM: IP not found

I am not sure how to diagnose at this point since there is almost nothing on boot2docker image to use.

HELP ;)

**Comment by gbraad** [comment] 2017-03-02 05:09
Can you verify the virtual switch that has been assigned to the virtual machine? You can see this from the Hyper-V Manager interface. At the moment it is suggested to use an External switch, so DHCP can provide an address.

**Comment by gbraad** [comment] 2017-03-02 05:10
Related to #417, maybe #419

**Comment by LalatenduMohanty** [comment] 2017-03-02 07:33
@gbraad I think there might be something else is an issue here as @thesteve0 mentioned beta3 was working for him.

**Comment by gbraad** [comment] 2017-03-02 07:40
@LalatenduMohanty he removed the configuration/virtual machine with `minishift delete`

**Comment by gbraad** [comment] 2017-03-02 08:00
@thesteve0 can you check the content of: `C:\Users\[username]\.minishift\machines\minishift\config.json`. Specifically the value of `VSwitch` as mentioned above. If the value is `""`, it means the default option was chosen.

After this, please verify the Virtual Switch assigned to the network adapter of the Minishift instance. you can find this in the settings page of the virtual instance in Hyper-V manager.

Finally, still in Hyper-V manager, you can open the Virtual Switch Manager, and check the type of the switch that was assigned to the virtual instance. At the moment this has to be 'external'.

Note: you could run a small DHCP server on a virtual switch to mitigate this problem. This is what I use at the moment: http://www.dhcpserver.de/cms/

**Comment by budhrg** [comment] 2017-03-02 08:18
I am not able to reproduce this issue.
I did :
- `minishift start` with binary version 1.0.0-beta3
- `minishift delete` and removed `.minishift` folder
- Replaced the beta3 binary with my beta4 binary
- Performed minishift start and able to see the Openshift server started message.

Before anything above, I need to create a proper *external* switch with working network.

@thesteve0 Could you show us the Virtual Switch Manager screenshot ?

**Comment by gbraad** [comment] 2017-03-02 08:21
I added the 'Cannot reproduce' tag, but will keep it open because of 'Need info'. Although the reported issue looks so much like reported in #419.

**Comment by gbraad** [comment] 2017-03-02 08:26
Example of a working configuration:
![external](https://cloud.githubusercontent.com/assets/1894/23498940/e9290fb4-ff64-11e6-810f-1e63de195479.png)
Note: as long as Wireless is connected to a network that has a DHCP server (like a home router)

**Comment by thesteve0** [comment] 2017-03-02 18:22
Just to clear up - each time I delete the .minishift dir as well. Is that the wrong thing to do. 

Both times I tried this on the RH network at Mtn View. 

It is also not working when I try to go back to beta3 
![externallan](https://cloud.githubusercontent.com/assets/1404099/23520987/01f8a564-ff32-11e6-9671-e516f206ea92.png)
![machinelan](https://cloud.githubusercontent.com/assets/1404099/23520988/01f9b8dc-ff32-11e6-80d3-0d8c3a3f4137.png)

**Comment by thesteve0** [comment] 2017-03-02 18:24
CRAP - it is attaching to the non-wifi external. I just noticed when looking for the bazillionth time. I have to go to a Drs appt this morning. Will try later when I get back and on a network. Thanks for working with me and hold off on putting any more effort into this until I bump again.

It would be great if we could "automagic" away some of this difficult network experience. How does Docker do this so smoothly?

**Comment by gbraad** [comment] 2017-03-02 18:37
I was about to ask, "are you on cable or WiFi?". It is a common mistake that I really wanna tackle soon. Part of this is #485 and doing preflight checks and reporting to the user.

Docker does not do it very smoothly either, but they utilize the fact that IPv6 is enabled. This is why I have #418 as a reported error...

**Comment by gbraad** [comment] 2017-03-02 18:39
I will close the issue for now. But please do find me... as I really want to solve this, but it needs several things before we get there.

**Closed by gbraad** 2017-03-02 18:39 UTC
Labels: kind/bug, priority/major, resolution/cannot-reproduce, status/needs-info

**Comment by thesteve0** [comment] 2017-03-02 21:56
Ok @gbraad @budhrg  works with the alpha 3 binary. Now will try with the alpha4 binary - if you don't hear from me assume it worked. Sorry for the alarm.

**Comment by thesteve0** [comment] 2017-03-02 23:26
Ok everything is working but I do think we should have upgrade instructions for people who do minishift delete. They are going to have to ctrl-c to quit the command. Manually stop the VM. Change to network adapter to whichever one is on the network. Then do oc cluster up and wait.

**Comment by gbraad** [comment] 2017-03-02 23:31
This procedure applies in general... and yes, better instructions for this are needed. Will mention this again during the standup. /cc: @LalatenduMohanty
