### ISSUE TITLE
How to add my own insecure docker registry

### ISSUE THREAD

**Issue by sokoow** [minishift/minishift#430] opened 2017-02-18 19:13 UTC
Hey, is there any way to add your own keys to **/etc/docker/certs.d**? Without it I'm getting **x509: certificate signed by unknown authority** ? Is minishift mounting /etc/docker persistently somewhere?

**Comment by LalatenduMohanty** [comment] 2017-02-19 04:00
@sokoow By default minishift uses boot2docker ISO i.e. https://github.com/minishift/minishift-b2d-iso. For this ISO `/var/lib/boot2docker/profile` is the file. For CentOS and RHEL it is in `/etc/sysconfig/docker`

There is a flag i.e --insecure-registry to `minishift start` command but I am not sure if it accepts multiple values. 
```
docker@minishift:~$ cat /var/lib/boot2docker/profile 

EXTRA_ARGS='
--label provider=kvm
--insecure-registry 172.30.0.0/16

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem
```

**Comment by hferentschik** [comment] 2017-02-19 19:57
_--insecure-registry_ is the way to go. You can specify a comma separated list of registries. Could you please try and let us know whether this works?

**Comment by hferentschik** [comment] 2017-02-19 19:58
In the long run we also want to offer the ability to provide your own certificates. See issue #391.

**Comment by hferentschik** [comment] 2017-02-19 19:59
--insecure-registry stringSlice   Non-secure Docker registries to pass to the Docker daemon. (default [172.30.0.0/16])

I think as part of this we should improve on the help a bit. It should mention comma separated set of registries.

**Comment by sokoow** [comment] 2017-02-19 21:06
Unfortunately that doesn't resolve my problem, still getting **x509: certificate signed by unknown authority** when trying to access my own repo :/

**Comment by LalatenduMohanty** [comment] 2017-02-20 19:42
@sokoow What steps you did to add the insecure registry?

**Comment by sokoow** [comment] 2017-02-20 19:46
I just did:
```
minishift start --vm-driver virtualbox --insecure-registry 172.30.0.0/16,http://registry.my-company.me
```

**Comment by sokoow** [comment] 2017-02-20 20:25
okay, I think I know what's going on: 

 --insecure-registry stringSlice  - this doesn't work at all, when I add another repo after the comma, it is not adding it to **/var/lib/boot2docker/profile**

I think it should be adding multiple lines to that file, as following:

```
EXTRA_ARGS='
--label provider=virtualbox
--insecure-registry 172.30.0.0/16
--insecure-registry my.registry.no2
'
```

**Comment by sokoow** [comment] 2017-03-11 11:52
also, for some strange reasons, adding certs to **/etc/docker/certs.d** doesn't work at all, any ideas?

**Comment by praveenkumar** [comment] 2017-05-31 10:13
@sokoow you need below command to do it, let us know if that works for you.

```
minishift start --vm-driver virtualbox --insecure-registry 172.30.0.0/16 --insecure-registry http://registry.my-company.me
```

**Comment by praveenkumar** [comment] 2017-06-05 09:21
@hferentschik So what action we need to take for this issue (add document around how to include a insecure registry)?

**Comment by LalatenduMohanty** [comment] 2017-06-08 07:36
> add document around how to include a insecure registry?

+1

**Comment by jhcook** [comment] 2017-06-13 15:37
With minishift shipped in CDK3 please see the following error when starting an instance:

`$ minishift --vm-driver virtualbox --insecure-registry docker.mgmt.licensing.service.trade.gov.uk.test:80 start
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Registering machine using subscription-manager
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.5.5.8 image ...
   Pulling image registry.access.redhat.com/openshift3/ose:v3.5.5.8
   Pulled 1/4 layers, 25% complete
   Pulled 2/4 layers, 50% complete
   Pulled 3/4 layers, 75% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... FAIL
   Error: did not detect an --insecure-registry argument on the Docker daemon
   Solution:

     Ensure that the Docker daemon is running with the following argument:
     	--insecure-registry 172.30.0.0/16

Error starting the cluster.`

**Comment by hferentschik** [comment] 2017-06-16 11:10
The problematic part here is that "172.30.0.0/16" is a required parameter. We use it as default value for the flag creation which will then pass this value along, if _insecure-registry_ is not specified at all. 

The problem is that, if you want to use an additional insecure-registry, then you also need to add "172.30.0.0/16", otherwise a required setting is missing. 

Really it is wrong to handle this registry as a default value in this way. "172.30.0.0/16" should be added to the list of insecure registries transparently independent to what the user specifies.

**Comment by hferentschik** [comment] 2017-06-16 11:11
@praveenkumar can you take of this as part of your current work on #1002 (I believe)?

**Comment by hferentschik** [comment] 2017-06-26 13:08
Fixed via pull request #1027 which will transparently apply "172.30.0.0/16" as  insecure docker registry, even if additional insecure registries are applied on the CLI.

**Closed by hferentschik** 2017-06-26 13:08 UTC
Labels: component/documentation, kind/task, priority/major

**Comment by cmoulliard** [comment] 2017-09-04 06:28
The command to set multiple values doesn't work using minishift 1.5, boot2docker - xhyve

```
minishift config set insecure-registry 172.30.0.0/16,docker-registry-default.192.168.64.2.nip.io                    
minishift config view                                                                                               
- insecure-registry    : [172.30.0.0/16 docker-registry-default.192.168.64.2.nip.io]
- memory               : 8000

minishift stop/start
minishift ssh
root      1904     1  6 06:24 ?        00:00:07 dockerd -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=xhyve --insecure-registry 172.30.0.0/16 --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs

docker login -u developer -p wELArrG02v78TsXxfr6mWNacPsPak2U4Cr1lHhvEEvU docker-registry-default.192.168.64.2.nip.io
Error response from daemon: Get https://docker-registry-default.192.168.64.2.nip.io/v1/users/: x509: certificate signed by unknown authority
```

**Comment by praveenkumar** [comment] 2017-09-04 06:43
@cmoulliard I am hoping that you want to expose your internal docker-registry with route. To make it work you need to have `registry-route` addon enabled/applied. You don't need to add that route as insecure registry because required cert should be auto created. 

```
$ minishift start
$ minishift addon apply registry-route
$ eval (minishift docker-env)
$ minishift openshift registry
docker-registry-default.<VM_IP>.nip.io:443
$ docker login -u developer -p <token> <exposed_registry_uri>
```

**Comment by cmoulliard** [comment] 2017-09-04 06:51
The addon you mentioned doesn't exist

```
minishift addon apply registry-route
No add-on with the name registry-route is installed.
minishift addon list
- admin-user     : disabled   P(0)
- anyuid         : disabled   P(0)
- xpaas          : disabled   P(0)
```

**Comment by cmoulliard** [comment] 2017-09-04 07:03
No sure if this is related but I get unauthorized: authentication required

```
docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.64.2.nip.io:443       
Login Succeeded
docker push 172.30.1.1:5000/ci-cd/jenkins-slave-maven-prod                                 
The push refers to a repository [172.30.1.1:5000/ci-cd/jenkins-slave-maven-prod]
96c30621123b: Preparing 
9e6910bf421c: Preparing 
9e8f67b88771: Preparing 
e67cccfa2cec: Preparing 
7197ca6c6ad4: Preparing 
0dd5bdda1234: Waiting 
c1ddbc1c43d9: Waiting 
cd55a6440755: Waiting 
b5dab8d7b014: Waiting 
92ebdfa135af: Waiting 
8e23335c14fe: Waiting 
8ff2697130e9: Waiting 
a0470fa933e4: Waiting 
9f0f36e746df: Waiting 
30005d468969: Waiting 
af9e78e1aefa: Waiting 
c1f0edf52a88: Waiting 
e8f04ddb6c68: Waiting 
5d775778fcb9: Waiting 
f46d15dbe9cd: Waiting 
e0478903d169: Waiting 
714599c9ba57: Waiting 
bfe256ddb4b1: Waiting 
7c991995ce2f: Waiting 
bee5c2a5ec03: Waiting 
b0620bc27ff6: Waiting 
b21a96c516cb: Waiting 
762cbde810b0: Waiting 
unauthorized: authentication required
```

**Comment by praveenkumar** [comment] 2017-09-04 07:20
```
docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.64.2.nip.io:443       
Login Succeeded
docker push 172.30.1.1:5000/ci-cd/jenkins-slave-maven-prod  
```

@cmoulliard here looks like logged into docker registry using route and then try to push image using internal service url `172.30.1.1` which also should be success. Can you check if you have tagged this image properly `ci-cd` should be project/namespace where developer have registry push access.

**Comment by cmoulliard** [comment] 2017-09-04 07:32
Same issue if I issue these commands

```
docker images
REPOSITORY                                                                   TAG                  IMAGE ID            CREATED             SIZE
172.30.1.1:5000/ci-cd/jenkins-slave-maven-prod                               latest               990a81a1ca1d        20 minutes ago      782MB
docker-registry-default.192.168.64.2.nip.io/ci-cd/jenkins-slave-maven-prod   latest               990a81a1ca1d        20 minutes ago      782MB
jenkins-slave-maven-prod                                                     latest               990a81a1ca1d        20 minutes ago      782MB
docker tag 990a81a1ca1d docker-registry-default.192.168.64.2.nip.io/ci-cd/jenkins-slave-maven-prod
docker push docker-registry-default.192.168.64.2.nip.io/ci-cd/jenkins-slave-maven-prod
```

How can I check if `developer` user has registry access to push ?

**Comment by praveenkumar** [comment] 2017-09-07 05:15
@cmoulliard looks like you want to push an image from your host docker daemon to VM (I think you built those images using host). Can you try below.

1. `$ minishift docker-env` => which will connect to docker daemon running inside the VM.
2. Build your images here or pull it from registry
3. Tag your image with respective project.
4. `docker push`

**Comment by LalatenduMohanty** [comment] 2017-09-15 19:41
Lets track it in https://github.com/minishift/minishift/issues/1390 as it seems it is the same issue.
