### ISSUE TITLE
Implement CDK related test cases in Minishift

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1433] opened 2017-09-22 09:50 UTC
I am creating this to get more open answer to the fact, **if we are fine with having few CDK-related tests here in repository or not?**

Please let me know your attitude on this topic. 

If we agree on that it is fine for us, then I will follow with this issue and will add few CDK variants to scenarios which are currently tagged as `minishift-only`. As result these conflict scenarios will be duplicated - once with tag `minishift-only` which will be run with Minishift binary, once with tag `cdk-only` which will be run only with CDK binary. Code for making this to work from technical point of view is already implemented.

**Comment by praveenkumar** [comment] 2017-09-22 11:13
@minishift/minishift-dev Please have a look and provide your view. For me it's +1, so we don't need to rebase lot of stuff downstream.

**Comment by budhrg** [comment] 2017-09-22 12:57
Looks fine to me as well. :+1:

**Comment by agajdosi** [comment] 2017-09-26 07:08
Ping @gbraad, @LalatenduMohanty. What do you think about this?

**Comment by amitkrout** [comment] 2017-09-29 18:45
#1466

**Comment by agajdosi** [comment] 2017-10-02 08:24
There weren't any negative comments or any other kind of feedback in time window of 10 days, so I am closing this issue with result that the community around Minishift is fine with these proposed changes. Will create a follow up issues for implementation of these soon.

**Comment by hferentschik** [comment] 2017-10-04 07:40
@agajdosi sorry late to the game, but that's a -1 from me. See also https://github.com/minishift/minishift/issues/1477#issuecomment-334073938. This is against what we always have discussed. 

What do you try to gain by it? What is your motivation?

**Comment by hferentschik** [comment] 2017-10-04 07:42
> For me it's +1, so we don't need to rebase lot of stuff downstream.

Just because it makes it "easier" for us, does not make it right.

**Comment by agajdosi** [comment] 2017-10-04 07:56
@hferentschik Yes, it is more practical to have it here, however I understand and understood your arguments on keeping a line between CDK and Minishift. I was fine with having all of the cases in downstream - for example I still have a PR in Gitlab for addition of these cases, same for @amitkrout. However then there were voices to keep these in upstream, as result I have created this issue to let community and everybody to say what she or he thinks and kept it open for 10 days, so it would not be a time pressed resolution.

I am neutral on this, really. More and more this feels to me like a philosophical question. But it would be nice to have an answer on this - last thing we want is to mess some downstream here, then add it into downstream again and create a mixture of nonsense.

I have reopened this issue. Pinging others from @minishift/minishift-dev (again) to get some feedback on this issue. Please give it a minute or two, it would really help us to move forward.

**Comment by gbraad** [comment] 2017-10-04 08:48
It also looks fine to me.

> Just because it makes it "easier" for us, does not make it right.

What is not right about this?

**Comment by hferentschik** [comment] 2017-10-04 08:54
Making things easier is not wrong per se. However, blurring the line between Minishift and CDK is. These tests are not even "runnable" from this repo. You need a CDK for that. The code changes which makes a CDK out of Minishift live in another repo, so that's where imo the CDK specific tests belong together with eventually CDK specific doc changes.

**Comment by gbraad** [comment] 2017-10-04 08:59
> blurring the line between Minishift and CDK is.

Well, this is an interesting discussion by itself. I think the lines are blurred anyway, as many reports for CDK are going in here.

should we not actually have everything upstream anyways? Or, why prevent people to run these tests using the release of CDKs sources, and reproduce what we do? (As at the moment we do not release the tests... why not?)

**Comment by LalatenduMohanty** [comment] 2017-10-04 11:25
> am creating this to get more open answer to the fact, if we are fine with having few CDK-related tests here in repository or not?
> 
> Please let me know your attitude on this topic.

@agajdosi Sorry for not commenting earlier as I did not think it means we will put CDK specific tests in upstream. I should have asked what is it means.  

As a principle we must keep the upstream as a community project. So this should contain things which is related to upstream project .  I know that it is difficult to maintain when everyone works for CDK and upstream Minishift both. But we have to be careful about it and whether it makes sense for an external contributor or not. 





> Well, this is an interesting discussion by itself. I think the lines are blurred anyway, as many reports for CDK are going in here.
> 
> should we not actually have everything upstream anyways?

I think in the interest of upstream and downstream  we should keep things separate as much as possible. That keeps the things transparent which is in general a good thing.

**Comment by agajdosi** [comment] 2017-10-04 11:39
@LalatenduMohanty Np, I am glad we have a consent now.

**Comment by hferentschik** [comment] 2017-10-04 13:40
>  I think in the interest of upstream and downstream we should keep things separate as much as possible. That keeps the things transparent which is in general a good thing.

+1 

@agajdosi what we really should have is a CI system which runs the downstream pull requests to verify they work. This is something we never could do here in this repo.

**Comment by LalatenduMohanty** [comment] 2017-10-05 06:35
Closing the issue as we have agreed not to keep downstream specific tests in upstream repository.

**Closed by LalatenduMohanty** 2017-10-05 06:35 UTC
Labels: component/integration-test, kind/question, priority/critical, status/needs-info
