### ISSUE TITLE
No symlink from /var/lib/docker/containers/ to /var/log/containers

### ISSUE THREAD

**Issue by dominicalston** [minishift/minishift#510] opened 2017-03-03 10:59 UTC
According to the fluentd documentation, it states the kubelet creates symlinks that
capture the pod name, namespace, container name & Docker container ID
to the docker logs for pods in the `/var/log/containers` directory on the host. We see no such containers directory in the host. 

##### Version
Host is running 4.4.27-boot2docker
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Create a pod with a volume spec to host path /var/lib/docker/containers and mount to `/var/lib/docker/containers`
2. Examine the contents of `/var/log/containers`

##### Current Result
The `/var/log/containers` directory is empty.

##### Expected Result
A Docker container's logs might be in the directory:

` /var/lib/docker/containers/997599971ee6366d4a5920d25b79286ad45ff37a74494f262e3bc98d909d0a7b`

and in the file:

` 997599971ee6366d4a5920d25b79286ad45ff37a74494f262e3bc98d909d0a7b-json.log`

where 997599971ee6... is the Docker ID of the running container.
The Kubernetes kubelet makes a symbolic link to this file on the host machine
in the /var/log/containers directory which includes the pod name and the Kubernetes
container name:

   `synthetic-logger-0.25lps-pod_default_synth-lgr-997599971ee6366d4a5920d25b79286ad45ff37a74494f262e3bc98d909d0a7b.log`
   ->
   `/var/lib/docker/containers/997599971ee6366d4a5920d25b79286ad45ff37a74494f262e3bc98d909d0a7b/997599971ee6366d4a5920d25b79286ad45ff37a74494f262e3bc98d909d0a7b-json.log`

**Comment by hferentschik** [comment] 2017-03-03 12:46
Can you provide a pointer to the documentation you are referring to? And can you also describe what you want to do? 

Personally I never heard of this, so this needs some investigation first.

**Comment by dominicalston** [comment] 2017-03-03 12:57
The documentation is part of the fluentd implementation of origin-aggregated-logging, documentation here:
https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/README

The symlink creation is required by the origin-aggregated-logging stack fluentd implementation.

**Comment by gbraad** [comment] 2017-06-07 13:28
can you have a look at: 
https://github.com/kubernetes/kubernetes/issues/39225#issuecomment-269588375 if this would help you?

**Comment by dominicalston** [comment] 2017-07-12 13:28
On v1.2, I now see symlinks in /var/log/containers but they point to invalid locations e.g.

lrwxrwxrwx 1 root root 174 Jul 12 10:34 docker-registry-1-gmzrf_default_POD-fe5aeb28e81f1d05aed0b22e0c0ff2330b43beecfe6e2f3ffc3bf3f8331e823a.log -> /mnt/sda1/var/lib/docker/containers/fe5ae
b28e81f1d05aed0b22e0c0ff2330b43beecfe6e2f3ffc3bf3f8331e823a/fe5aeb28e81f1d05aed0b22e0c0ff2330b43beecfe6e2f3ffc3bf3f8331e823a-json.log

/mnt/sda1 doesn't exist.

**Comment by hferentschik** [comment] 2017-08-17 10:21
So, what are you trying to do? Have you started Minishift with --logging enabled? Also can you access the Kibana UI? Or are you doing all this without the aggregates logging feature enabled. I am trying to understand where you are coming from.

**Comment by dominicalston** [comment] 2017-08-17 10:23
I’m trying to run the origin logging stack on minishift. This currently isn’t possible without symlinks working correctly.

**Comment by hferentschik** [comment] 2017-08-17 10:26
> I’m trying to run the origin logging stack on minishift. 

And how do you provision it? Using `minishift start --logging`?

**Comment by dominicalston** [comment] 2017-08-17 10:31
I don’t use –logging. I minishift start and deploy origin aggregated logging using the steps described (https://github.com/openshift/origin-aggregated-logging)

**Comment by praveenkumar** [comment] 2017-08-17 11:18
> I don’t use –logging. I minishift start and deploy origin aggregated logging using the steps described 

Can you please provide step by step because repo you provided doesn't have much info about deployment on a running openshift cluster. Also if you go through README then there is note section.

**NOTE:** If you are running OpenShift Origin using the All-In-One docker container method, you MUST add `-v /var/log:/var/log` to the docker command line. OpenShift must have access to the container logs in order for Fluentd to read and process them.

**Comment by dominicalston** [comment] 2017-08-17 11:25
The documentation for deploying can be found here:
https://github.com/openshift/origin-aggregated-logging/tree/master/deployer

We aren’t using the all-in-one docker container for openshift.

**Comment by hferentschik** [comment] 2017-08-21 19:07
@csrwng I am trying to use '--logging' with the latest version of _oc_ (3.6), but I don't see any logging pods coming up. Looking at the code, it seems as of 3.6, Ansible is used for provisioning aggregated logging - https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/up.go#L983. Is this tested? Is this working?

I get a _logging_ namespace created, but nothing in there. AFAIU, the provisioning is now happing via a job _openshift-ansible-logging-job_, but there seems to be no progress.

     $ oc --as system:admin get jobs -n logging
     NAME                            DESIRED   SUCCESSFUL   AGE
     openshift-ansible-logging-job   1         0            3h

Is there a way to get the logs for a job or in any other form see what's going on?

**Comment by praveenkumar** [comment] 2017-08-22 11:45
I tried `--logging` and yes it now use ansible job to provision it. For me I am able to deployed it.

```

**Comment by hferentschik** [comment] 2017-08-23 09:28
Regarding provisioning logging, I am running into a similar issue as in #1252. Basically another timeout. When starting Minishift with '--logging' I see the logging job being created, but logging never finishes provisioning. After some time I did:

    $ oc --as system:admin describe jobs/openshift-ansible-logging-job -n logging
    Name:				openshift-ansible-logging-job
    Namespace:			logging
    Selector:			controller-uid=e31c84a4-87e1-11e7-a3e6-fe9710e0febd
    Labels:				controller-uid=e31c84a4-87e1-11e7-a3e6-fe9710e0febd
    				job-name=openshift-ansible-logging-job
    Annotations:			<none>
    Parallelism:			1
    Completions:			1
    Start Time:			Wed, 23 Aug 2017 11:03:10 +0200
    Active Deadline Seconds:	300s
    Pods Statuses:			0 Running / 0 Succeeded / 1 Failed
    Pod Template:
      Labels:		controller-uid=e31c84a4-87e1-11e7-a3e6-fe9710e0febd
    			job-name=openshift-ansible-logging-job
      Service Account:	openshift-ansible
      Containers:
       openshift-ansible-logging-job:
        Image:	openshift/origin-ansible:v3.6.0
        Port:
        Environment:
          INVENTORY_FILE:	/tmp/inventory
          PLAYBOOK_FILE:	playbooks/byo/openshift-cluster/openshift-logging.yml
        Mounts:
          /etc/origin/master from configdir (rw)
          /tmp/inventory from inventoryfile (rw)
      Volumes:
       configdir:
        Type:	HostPath (bare host directory volume)
        Path:	/var/lib/minishift/openshift.local.config/master
       inventoryfile:
        Type:	HostPath (bare host directory volume)
        Path:	/var/lib/minishift/openshift.local.config/logging.inventory
    Events:
      FirstSeen	LastSeen	Count	From		SubObjectPath	Type		Reason			Message
      ---------	--------	-----	----		-------------	--------	------			-------
      13m		13m		1	job-controller			Normal		SuccessfulCreate	Created pod: openshift-ansible-logging-job-nb4z4
      6m		6m		1	job-controller			Normal		SuccessfulDelete	Deleted pod: openshift-ansible-logging-job-nb4z4
      6m		6m		1	job-controller			Normal		DeadlineExceeded	Job was active longer than specified deadline

So it looks like, there is a timeout for the logging job to complete and it gets exceeded at which stage provisioning aborts.

**Comment by hferentschik** [comment] 2017-08-25 12:31
@dominicalston, would you mind trying with the latest version of Minishift. Run:

    $ minishift start --logging

As you OpenShift 3.6, this will provision using the Ansible installer. AFAIC, things are actually deploying as they should (provided no timeout occurs see https://github.com/minishift/minishift/issues/510#issuecomment-324274370). I don't think there is a missing symbolic link. All logs are available under _/var/log/containers_ on the Minishift VM. Using _docker inspect_ on the [fluentd](https://www.fluentd.org/) container also shows, that _/var/log/_ this  mounted into container:

       "Mounts": [
            {
                "Source": "/var/log",
                "Destination": "/var/log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
           ....
            {
                "Source": "/var/lib/docker/containers",
                "Destination": "/var/lib/docker/containers",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            } 

However, when running `docker logs` on the fluentd container, one finds the following entries:

    2017-08-25 08:02:10 +0000 [warn]: /var/log/containers/php-1-build_myproject_sti-build-d93cd714411aee704e25138c6a63c80f64f941ee2c4f864922764e1f85e1d03d.log unreadable. It is excluded and would be examined next time.
    2017-08-25 08:02:10 +0000 [warn]: /var/log/containers/logging-kibana-2-5f2ds_logging_kibana-proxy-b5fb78c53172845338de3ecfd935b8261575e218a25ba2439279805f817d170d.log unreadable. It is excluded and would be examined next time.

**Comment by hferentschik** [comment] 2017-08-25 13:34
See also https://github.com/openshift/origin/issues/13212

**Comment by hferentschik** [comment] 2017-08-28 07:44
Looks like the symbolic link itself is something Kubernetes creates. It might be that for some reasons it "resolves" the symbolic links when creating the log file. Even if we find the root cause, it would take a long time to get the fix as part of Minishift. Trying to use bind mounts instead of symbolic links, on the other hand would put us into control. Probably easiest to try with the CentOS ISO first (https://github.com/minishift/minishift-centos-iso/issues/136) and see whether bind mounts work and whether they fix the issue.

**Comment by praveenkumar** [comment] 2017-08-28 07:56
@hferentschik Problem with blind mount is it will duplicate the data so if logs are 1GB then for us it will cost 2GB iirc.

**Comment by hferentschik** [comment] 2017-08-28 08:10
> Problem with bind mount is it will duplicate the data so if logs are 1GB then for us it will cost 2GB iirc.

Why? I don't get that.

**Comment by gbraad** [comment] 2017-08-28 08:20
This is only visual, due to the way some of these tools calculate disk usage. A bind mount is an alternate view of a directory tree. It takes an existing directory tree and replicates it under a different point. Any modification is immediately reflected on the other side as the two views show the same data.

**Comment by praveenkumar** [comment] 2017-08-28 08:23
> Why? I don't get that.

My bad as @gbraad said it just a visual and replicate data to mounted directory/file.

**Comment by hferentschik** [comment] 2017-08-28 08:30
> My bad as @gbraad said it just a visual and replicate data to mounted directory/file.

Right. That makes sense :-)

**Comment by gbraad** [comment] 2017-08-28 11:25
* Changes on ISO side:
  * [ ] CentOS https://github.com/minishift/minishift-centos-iso/issues/136
  * [ ] B2D https://github.com/minishift/minishift-b2d-iso/issues/57

**Comment by praveenkumar** [comment] 2017-09-19 07:04
@dominicalston So I gave it latest minishift a try and looks like it does fix your issue. I am closing this issue now, Please let us know if you still have query around it.

```
$ cat volume_mount.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - name: test-container
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
    - mountPath: /var/lib/docker/containers
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var/lib/docker/containers

$  oc create -f volume_mount.yaml 

$ oc get pods
NAME      READY     STATUS    RESTARTS   AGE
test-pd   1/1       Running   0          16m

$ ./minishift ssh
docker@minishift:~$  ls /var/log/containers/ | grep test-pd
test-pd_myproject_test-container-0a3e50815a2b0b3e232199b05c8f305c7af20132943749527983814e2c7c992e.log
```

**Closed by praveenkumar** 2017-09-19 07:04 UTC
Labels: kind/task, priority/major, status/needs-investigation

**Comment by budhrg** [comment] 2017-09-19 09:22
Working for me too with latest version `1.6.0`
