### ISSUE TITLE
--insecure-registry does not work when minishift VM started from stop state. 

### ISSUE THREAD

**Issue by thrix** [minishift/minishift#1797] opened 2017-12-05 05:21 UTC
The --insecure-registry does now work on created minishift VM and the tool does not print a warning about this. This can cause confusion for the users in some cases. If the tool cannot update the config for an existing VM, a warning should be displayed or even refuse to start with the non-functioning option and a proper error.

Steps to reproduce:

```
$ minishift delete
$ minishift start
$ minishift stop
$ minishift start --insecure-registry 172.30.0.0/16 --insecure-registry 10.0.0.0/8
$ minishift ssh
$ docker info
```

**Comment by budhrg** [comment] 2017-12-05 09:50
I think we need to maintain the options we provide as part of start command and then validate these options as part of next start command.

Apart from this config, we only populate <MACHINE_NAME>_kubeconfig as part of 1st start command.

**Comment by hferentschik** [comment] 2017-12-05 14:04
This is not a valid use case. You can only specify flags when a new VM is created. If you stop and then start an existing VM, options don't apply. The VM just is woken up. Depending on the type of flag it would not even be possible to change specific settings. This is really issue #179 in green.

Effectively we need to warn or even prevent a use to specify any flags when reviving a stopped VM. Something like:

    $ minishift start --vm-driver=virtualbox
    Starting stopped Minishift instance. Command line flags don't apply. Delete and re-create if you want to change any settings

Closing this as duplicate of #179

**Closed by hferentschik** 2017-12-05 14:04 UTC
Labels: kind/feature, priority/minor
