### ISSUE TITLE
Ability to configure templates and other resources

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#59] opened 2016-08-30 06:34 UTC
The CDK provides a list of Kubernetes applications (= templates) that we can use to create some pods (EAP, Ruby, Php, NodeJs, ...).

![screenshot 2016-08-29 12 06 41](https://cloud.githubusercontent.com/assets/463790/18078569/85bad3e0-6e8c-11e6-9b3e-bcb92f7e49c0.png)

I would like to suggest that we have an option to deploy `--add-templates` such templates within minishift :  

Here is a list of such templates : 

DBs:
https://github.com/openshift/origin/tree/master/examples/db-templates

Sample apps/Quickstarts:
https://github.com/openshift/origin/tree/master/examples/quickstarts  (note, the files in this dir are drawn from upstream repos as described here: https://github.com/openshift/origin/blob/master/examples/quickstarts/README.md

Jenkins:
https://github.com/openshift/origin/tree/master/examples/jenkins

Middleware image templates:
https://github.com/jboss-openshift/application-templates

xPaas:
https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v1.3

**Comment by jorgemoralespou** [comment] 2016-10-19 19:28
@jimmidyson Eventually, using cluster up internally could give you this feature, but I would also be happy to have a way to bootstrap more templates in cluster creation. I know I can do that afterwards via a script, but would maybe make sense have minishift be able to bootstrap different flavours of openshift (minimal, regular, extended) depending on what would be provisioned (minimal=registry, regular=registry,router,templates and extended=registry,router,templates,metrics,logging) even also additional stuff could be awesome.

**Comment by hferentschik** [comment] 2016-12-19 11:11
This has a quite high priority really. Minishift 1.0.0-beta.1 is now using 'oc cluster up' to bootstrap and provision OpenShift, but there is still a need for a mechanism to further customize the server.

**Comment by hferentschik** [comment] 2017-03-01 09:56
I am closing this as a duplicate of #177 which seems to have the more relevant discussion.

**Closed by hferentschik** 2017-03-01 09:56 UTC
Labels: kind/feature, priority/critical
