### ISSUE TITLE
oc login changes the current context from minishift 

### ISSUE THREAD

**Issue by rawlingsj** [minishift/minishift#94] opened 2016-09-16 16:42 UTC
The current context is changed following an `oc login`.  Steps to recreate:

After minishift starts the current context is **minishift**

```
➜  minishift start
Starting local OpenShift cluster...
oc is now configured to use the cluster.
Run this command to use the cluster:
oc login --username=admin --password=admin
➜  kubectl config current-context
minishift
```

login

```
➜ oc login --username=admin --password=admin
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-system
    openshift
    openshift-infra

Using project "default".
```

check the current context again

```
➜ kubectl config current-context
default/192-168-64-89:8443/admin
```

**Comment by rawlingsj** [comment] 2016-09-19 13:19
After a bit of digging I found we can use a really crude workaround.  If we set the username name to the same format that oc login uses we can set the current-context back to `minishift` during `gofabric8 start` after we've logged in.  `oc login -u admin -p admin` updates the minikube username config with the token which means we can reuse the minishift context.

This is not a good approach though as minishift would still use the incorrect context if run without fabric8.

Is there anyone from the openshift team working on minishift that can help advise if there's a way to keep the current `minishift` context when logging in?

**Comment by rawlingsj** [comment] 2016-09-21 09:54
FWIW this was the idea that I had to reuse the username format that `oc login` uses https://github.com/rawlingsj/minishift/commit/d2c89e59505814d50b1da396c114f4a365967d5b

**Comment by budhrg** [comment] 2017-01-20 07:12
@rawlingsj I am not able to reproduce this issue with [latest minishift release](https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.2)

```
$ minishift version
Minishift version: 1.0.0-beta.2

$ minishift start --vm-driver virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Downloading ISO
Provisioning OpenShift via '/home/budhram/.minishift/cache/oc/v1.3.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.1 image ... 
   Pulling image openshift/origin:v1.3.1
   Pulled 0/3 layers, 3% complete
   Pulled 0/3 layers, 27% complete
   Pulled 0/3 layers, 49% complete
   Pulled 1/3 layers, 64% complete
   Pulled 1/3 layers, 83% complete
   Pulled 2/3 layers, 87% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.99.100 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.100:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

$ kubectl config current-context
myproject/192-168-99-100:8443/developer

$ export PATH=$PATH:~/.minishift/cache/oc/v1.3.1

$ oc login -u system:admin                      
Logged into "https://192.168.99.100:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-system
  * myproject
    openshift
    openshift-infra

Using project "myproject".

$ kubectl config current-context                
myproject/192-168-99-100:8443/system:admin
```

I am closing this issue at the moment but feel free to reopen it if you still experiencing it.

**Closed by budhrg** 2017-01-20 07:12 UTC
