### ISSUE TITLE
Windows, 'Error creating new host: dial tcp: missing address' error from minishift start

### ISSUE THREAD

**Issue by gashcrumb** [minishift/minishift#102] opened 2016-09-21 13:15 UTC
Finally had a chance to give this a go, using the latest release:

```
PS C:\Users\gashcrumb> minishift start --memory=8192
Starting local OpenShift cluster...
E0921 09:11:57.932205   16704 start.go:89] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E0921 09:11:58.072763   16704 start.go:89] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E0921 09:11:58.210321   16704 start.go:89] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E0921 09:11:58.211320   16704 start.go:95] Error starting host:  Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
```

Am using hyperv, also minikube works fine for me on this machine.

**Comment by nanomad** [comment] 2016-09-23 15:47
Same issue for me also

OS: Windows 10 (1607 build 14393.187)

**Comment by hferentschik** [comment] 2016-12-21 09:30
Do you mind giving it another go with the latest Minishift release - 1.0.0-beta.1?

**Comment by hferentschik** [comment] 2016-12-23 12:51
Closing this, as I cannot reproduce this. We can create a new issue once we can confirm that this is still an issue with the latest release of minishift.

**Closed by hferentschik** 2016-12-23 12:51 UTC
Labels: bug, cannot reproduce, major
