### ISSUE TITLE
Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jjwallaby** [minishift/minishift#2954] opened 2018-10-29 03:19 UTC
### General information

  * Minishift version: v1.26.1+1e20f27
  * OS: Windows
  * Hypervisor:  VirtualBox
  * guest box: Centos 7

Problem is why when it pulls docker the Certificate is unknown authority ?

**Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

Error pulling the openshift container image: ssh command error:
command : docker pull openshift/origin-control-plane:v3.11.0
err     : Process exited with status 1
output  : Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority'**

Behind a Proxy,  but http-proxy and https_proxy has been set.

The other problem when **minishift ssh**  funny character appears.
unable to do vi.

How do you add certificates to minishift  ?  I added in cert file.  BUT that still does not update
the ISO image ?

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Error

SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 62299 <nil> <nil>}
About to run SSH command:
echo REVWSUNFPWV0aDAKVVNFREhDUD10cnVlCg== | base64 --decode | sudo tee /var/lib/minishift/networking-eth0 > /dev/null
SSH cmd err, output: <nil>:
OK
Found binary path at minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:62615
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 62299 <nil> <nil>}
About to run SSH command:
docker version --format '{{.Server.APIVersion}}'
SSH cmd err, output: <nil>: 1.26

(minishift) Calling .GetIP
(minishift) DBG | COMMAND: C:\NotBackedup\docker\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | name="minishift"
(minishift) DBG | groups="/"
(minishift) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(minishift) DBG | UUID="26b3da41-3cb3-4806-b8b3-6ba0b40a90aa"
(minishift) DBG | CfgFile="C:\\NotBackedUp\\Dev\\minishift\\.minishift\\machines\\minishift\\minishift\\minishift.vbox"
(minishift) DBG | SnapFldr="C:\\NotBackedUp\\Dev\\minishift\\.minishift\\machines\\minishift\\minishift\\Snapshots"
(minishift) DBG | LogFldr="C:\\NotBackedUp\\Dev\\minishift\\.minishift\\machines\\minishift\\minishift\\Logs"
(minishift) DBG | hardwareuuid="26b3da41-3cb3-4806-b8b3-6ba0b40a90aa"
(minishift) DBG | memory=4096
(minishift) DBG | pagefusion="off"
(minishift) DBG | vram=8
(minishift) DBG | cpuexecutioncap=100
(minishift) DBG | hpet="on"
(minishift) DBG | chipset="piix3"
(minishift) DBG | firmware="BIOS"
(minishift) DBG | cpus=2
(minishift) DBG | pae="on"
(minishift) DBG | longmode="on"
(minishift) DBG | triplefaultreset="off"
(minishift) DBG | apic="on"
(minishift) DBG | x2apic="off"
(minishift) DBG | cpuid-portability-level=0
(minishift) DBG | bootmenu="disabled"
(minishift) DBG | boot1="dvd"
(minishift) DBG | boot2="dvd"
(minishift) DBG | boot3="disk"
(minishift) DBG | boot4="none"
(minishift) DBG | acpi="on"
(minishift) DBG | ioapic="on"
(minishift) DBG | biosapic="apic"
(minishift) DBG | biossystemtimeoffset=0
(minishift) DBG | rtcuseutc="on"
(minishift) DBG | hwvirtex="on"
(minishift) DBG | nestedpaging="on"
(minishift) DBG | largepages="on"
(minishift) DBG | vtxvpid="on"
(minishift) DBG | vtxux="on"
(minishift) DBG | paravirtprovider="default"
(minishift) DBG | effparavirtprovider="kvm"
(minishift) DBG | VMState="running"
(minishift) DBG | VMStateChangeTime="2018-10-29T03:04:40.003000000"
(minishift) DBG | monitorcount=1
(minishift) DBG | accelerate3d="off"
(minishift) DBG | accelerate2dvideo="off"
(minishift) DBG | teleporterenabled="off"
(minishift) DBG | teleporterport=0
(minishift) DBG | teleporteraddress=""
(minishift) DBG | teleporterpassword=""
(minishift) DBG | tracing-enabled="off"
(minishift) DBG | tracing-allow-vm-access="off"
(minishift) DBG | tracing-config=""
(minishift) DBG | autostart-enabled="off"
(minishift) DBG | autostart-delay=0
(minishift) DBG | defaultfrontend=""
(minishift) DBG | storagecontrollername0="SATA"
(minishift) DBG | storagecontrollertype0="IntelAhci"
(minishift) DBG | storagecontrollerinstance0="0"
(minishift) DBG | storagecontrollermaxportcount0="30"
(minishift) DBG | storagecontrollerportcount0="30"
(minishift) DBG | storagecontrollerbootable0="on"
(minishift) DBG | "SATA-0-0"="C:\NotBackedUp\Dev\minishift\.minishift\machines\minishift\boot2docker.iso"
(minishift) DBG | "SATA-ImageUUID-0-0"="09c3027e-c071-4b5e-a323-2d9f4f7b62dd"
(minishift) DBG | "SATA-tempeject"="off"
(minishift) DBG | "SATA-IsEjected"="off"
(minishift) DBG | "SATA-1-0"="C:\NotBackedUp\Dev\minishift\.minishift\machines\minishift\disk.vmdk"
(minishift) DBG | "SATA-ImageUUID-1-0"="b4214518-d10a-4fb7-83ae-0a9b8c3ab286"
(minishift) DBG | "SATA-2-0"="none"
(minishift) DBG | "SATA-3-0"="none"
(minishift) DBG | "SATA-4-0"="none"
(minishift) DBG | "SATA-5-0"="none"
(minishift) DBG | "SATA-6-0"="none"
(minishift) DBG | "SATA-7-0"="none"
(minishift) DBG | "SATA-8-0"="none"
(minishift) DBG | "SATA-9-0"="none"
(minishift) DBG | "SATA-10-0"="none"
(minishift) DBG | "SATA-11-0"="none"
(minishift) DBG | "SATA-12-0"="none"
(minishift) DBG | "SATA-13-0"="none"
(minishift) DBG | "SATA-14-0"="none"
(minishift) DBG | "SATA-15-0"="none"
(minishift) DBG | "SATA-16-0"="none"
(minishift) DBG | "SATA-17-0"="none"
(minishift) DBG | "SATA-18-0"="none"
(minishift) DBG | "SATA-19-0"="none"
(minishift) DBG | "SATA-20-0"="none"
(minishift) DBG | "SATA-21-0"="none"
(minishift) DBG | "SATA-22-0"="none"
(minishift) DBG | "SATA-23-0"="none"
(minishift) DBG | "SATA-24-0"="none"
(minishift) DBG | "SATA-25-0"="none"
(minishift) DBG | "SATA-26-0"="none"
(minishift) DBG | "SATA-27-0"="none"
(minishift) DBG | "SATA-28-0"="none"
(minishift) DBG | "SATA-29-0"="none"
(minishift) DBG | natnet1="nat"
(minishift) DBG | macaddress1="080027E4C822"
(minishift) DBG | cableconnected1="on"
(minishift) DBG | nic1="nat"
(minishift) DBG | nictype1="82540EM"
(minishift) DBG | nicspeed1="0"
(minishift) DBG | mtu="0"
(minishift) DBG | sockSnd="64"
(minishift) DBG | sockRcv="64"
(minishift) DBG | tcpWndSnd="64"
(minishift) DBG | tcpWndRcv="64"
(minishift) DBG | Forwarding(0)="ssh,tcp,127.0.0.1,62299,,22"
(minishift) DBG | hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #4"
(minishift) DBG | macaddress2="080027C0576B"
(minishift) DBG | cableconnected2="on"
(minishift) DBG | nic2="hostonly"
(minishift) DBG | nictype2="82540EM"
(minishift) DBG | nicspeed2="0"
(minishift) DBG | nic3="none"
(minishift) DBG | nic4="none"
(minishift) DBG | nic5="none"
(minishift) DBG | nic6="none"
(minishift) DBG | nic7="none"
(minishift) DBG | nic8="none"
(minishift) DBG | hidpointing="ps2mouse"
(minishift) DBG | hidkeyboard="ps2kbd"
(minishift) DBG | uart1="off"
(minishift) DBG | uart2="off"
(minishift) DBG | uart3="off"
(minishift) DBG | uart4="off"
(minishift) DBG | lpt1="off"
(minishift) DBG | lpt2="off"
(minishift) DBG | audio="dsound"
(minishift) DBG | audio_in="false"
(minishift) DBG | audio_out="false"
(minishift) DBG | clipboard="disabled"
(minishift) DBG | draganddrop="disabled"
(minishift) DBG | SessionName="headless"
(minishift) DBG | VideoMode="720,400,0"@0,0 1
(minishift) DBG | vrde="off"
(minishift) DBG | usb="off"
(minishift) DBG | ehci="off"
(minishift) DBG | xhci="off"
(minishift) DBG | SharedFolderNameMachineMapping1="c/Users"
(minishift) DBG | SharedFolderPathMachineMapping1="\\?\c:\Users"
(minishift) DBG | VRDEActiveConnection="off"
(minishift) DBG | VRDEClients=0
(minishift) DBG | videocap="off"
(minishift) DBG | videocap_audio="off"
(minishift) DBG | videocapscreens=0
(minishift) DBG | videocapfile="C:\NotBackedUp\Dev\minishift\.minishift\machines\minishift\minishift\minishift.webm"
(minishift) DBG | videocapres=1024x768
(minishift) DBG | videocaprate=512
(minishift) DBG | videocapfps=25
(minishift) DBG | videocapopts=
(minishift) DBG | GuestMemoryBalloon=0
(minishift) DBG | GuestOSType="Linux26_64"
(minishift) DBG | GuestAdditionsRunLevel=0
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | COMMAND: C:\NotBackedup\docker\Oracle\VirtualBox\VBoxManage.exe showvminfo minishift --machinereadable
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | name="minishift"
(minishift) DBG | groups="/"
(minishift) DBG | ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
(minishift) DBG | UUID="26b3da41-3cb3-4806-b8b3-6ba0b40a90aa"
(minishift) DBG | CfgFile="C:\\NotBackedUp\\Dev\\minishift\\.minishift\\machines\\minishift\\minishift\\minishift.vbox"
(minishift) DBG | SnapFldr="C:\\NotBackedUp\\Dev\\minishift\\.minishift\\machines\\minishift\\minishift\\Snapshots"
(minishift) DBG | LogFldr="C:\\NotBackedUp\\Dev\\minishift\\.minishift\\machines\\minishift\\minishift\\Logs"
(minishift) DBG | hardwareuuid="26b3da41-3cb3-4806-b8b3-6ba0b40a90aa"
(minishift) DBG | memory=4096
(minishift) DBG | pagefusion="off"
(minishift) DBG | vram=8
(minishift) DBG | cpuexecutioncap=100
(minishift) DBG | hpet="on"
(minishift) DBG | chipset="piix3"
(minishift) DBG | firmware="BIOS"
(minishift) DBG | cpus=2
(minishift) DBG | pae="on"
(minishift) DBG | longmode="on"
(minishift) DBG | triplefaultreset="off"
(minishift) DBG | apic="on"
(minishift) DBG | x2apic="off"
(minishift) DBG | cpuid-portability-level=0
(minishift) DBG | bootmenu="disabled"
(minishift) DBG | boot1="dvd"
(minishift) DBG | boot2="dvd"
(minishift) DBG | boot3="disk"
(minishift) DBG | boot4="none"
(minishift) DBG | acpi="on"
(minishift) DBG | ioapic="on"
(minishift) DBG | biosapic="apic"
(minishift) DBG | biossystemtimeoffset=0
(minishift) DBG | rtcuseutc="on"
(minishift) DBG | hwvirtex="on"
(minishift) DBG | nestedpaging="on"
(minishift) DBG | largepages="on"
(minishift) DBG | vtxvpid="on"
(minishift) DBG | vtxux="on"
(minishift) DBG | paravirtprovider="default"
(minishift) DBG | effparavirtprovider="kvm"
(minishift) DBG | VMState="running"
(minishift) DBG | VMStateChangeTime="2018-10-29T03:04:40.003000000"
(minishift) DBG | monitorcount=1
(minishift) DBG | accelerate3d="off"
(minishift) DBG | accelerate2dvideo="off"
(minishift) DBG | teleporterenabled="off"
(minishift) DBG | teleporterport=0
(minishift) DBG | teleporteraddress=""
(minishift) DBG | teleporterpassword=""
(minishift) DBG | tracing-enabled="off"
(minishift) DBG | tracing-allow-vm-access="off"
(minishift) DBG | tracing-config=""
(minishift) DBG | autostart-enabled="off"
(minishift) DBG | autostart-delay=0
(minishift) DBG | defaultfrontend=""
(minishift) DBG | storagecontrollername0="SATA"
(minishift) DBG | storagecontrollertype0="IntelAhci"
(minishift) DBG | storagecontrollerinstance0="0"
(minishift) DBG | storagecontrollermaxportcount0="30"
(minishift) DBG | storagecontrollerportcount0="30"
(minishift) DBG | storagecontrollerbootable0="on"
(minishift) DBG | "SATA-0-0"="C:\NotBackedUp\Dev\minishift\.minishift\machines\minishift\boot2docker.iso"
(minishift) DBG | "SATA-ImageUUID-0-0"="09c3027e-c071-4b5e-a323-2d9f4f7b62dd"
(minishift) DBG | "SATA-tempeject"="off"
(minishift) DBG | "SATA-IsEjected"="off"
(minishift) DBG | "SATA-1-0"="C:\NotBackedUp\Dev\minishift\.minishift\machines\minishift\disk.vmdk"
(minishift) DBG | "SATA-ImageUUID-1-0"="b4214518-d10a-4fb7-83ae-0a9b8c3ab286"
(minishift) DBG | "SATA-2-0"="none"
(minishift) DBG | "SATA-3-0"="none"
(minishift) DBG | "SATA-4-0"="none"
(minishift) DBG | "SATA-5-0"="none"
(minishift) DBG | "SATA-6-0"="none"
(minishift) DBG | "SATA-7-0"="none"
(minishift) DBG | "SATA-8-0"="none"
(minishift) DBG | "SATA-9-0"="none"
(minishift) DBG | "SATA-10-0"="none"
(minishift) DBG | "SATA-11-0"="none"
(minishift) DBG | "SATA-12-0"="none"
(minishift) DBG | "SATA-13-0"="none"
(minishift) DBG | "SATA-14-0"="none"
(minishift) DBG | "SATA-15-0"="none"
(minishift) DBG | "SATA-16-0"="none"
(minishift) DBG | "SATA-17-0"="none"
(minishift) DBG | "SATA-18-0"="none"
(minishift) DBG | "SATA-19-0"="none"
(minishift) DBG | "SATA-20-0"="none"
(minishift) DBG | "SATA-21-0"="none"
(minishift) DBG | "SATA-22-0"="none"
(minishift) DBG | "SATA-23-0"="none"
(minishift) DBG | "SATA-24-0"="none"
(minishift) DBG | "SATA-25-0"="none"
(minishift) DBG | "SATA-26-0"="none"
(minishift) DBG | "SATA-27-0"="none"
(minishift) DBG | "SATA-28-0"="none"
(minishift) DBG | "SATA-29-0"="none"
(minishift) DBG | natnet1="nat"
(minishift) DBG | macaddress1="080027E4C822"
(minishift) DBG | cableconnected1="on"
(minishift) DBG | nic1="nat"
(minishift) DBG | nictype1="82540EM"
(minishift) DBG | nicspeed1="0"
(minishift) DBG | mtu="0"
(minishift) DBG | sockSnd="64"
(minishift) DBG | sockRcv="64"
(minishift) DBG | tcpWndSnd="64"
(minishift) DBG | tcpWndRcv="64"
(minishift) DBG | Forwarding(0)="ssh,tcp,127.0.0.1,62299,,22"
(minishift) DBG | hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #4"
(minishift) DBG | macaddress2="080027C0576B"
(minishift) DBG | cableconnected2="on"
(minishift) DBG | nic2="hostonly"
(minishift) DBG | nictype2="82540EM"
(minishift) DBG | nicspeed2="0"
(minishift) DBG | nic3="none"
(minishift) DBG | nic4="none"
(minishift) DBG | nic5="none"
(minishift) DBG | nic6="none"
(minishift) DBG | nic7="none"
(minishift) DBG | nic8="none"
(minishift) DBG | hidpointing="ps2mouse"
(minishift) DBG | hidkeyboard="ps2kbd"
(minishift) DBG | uart1="off"
(minishift) DBG | uart2="off"
(minishift) DBG | uart3="off"
(minishift) DBG | uart4="off"
(minishift) DBG | lpt1="off"
(minishift) DBG | lpt2="off"
(minishift) DBG | audio="dsound"
(minishift) DBG | audio_in="false"
(minishift) DBG | audio_out="false"
(minishift) DBG | clipboard="disabled"
(minishift) DBG | draganddrop="disabled"
(minishift) DBG | SessionName="headless"
(minishift) DBG | VideoMode="720,400,0"@0,0 1
(minishift) DBG | vrde="off"
(minishift) DBG | usb="off"
(minishift) DBG | ehci="off"
(minishift) DBG | xhci="off"
(minishift) DBG | SharedFolderNameMachineMapping1="c/Users"
(minishift) DBG | SharedFolderPathMachineMapping1="\\?\c:\Users"
(minishift) DBG | VRDEActiveConnection="off"
(minishift) DBG | VRDEClients=0
(minishift) DBG | videocap="off"
(minishift) DBG | videocap_audio="off"
(minishift) DBG | videocapscreens=0
(minishift) DBG | videocapfile="C:\NotBackedUp\Dev\minishift\.minishift\machines\minishift\minishift\minishift.webm"
(minishift) DBG | videocapres=1024x768
(minishift) DBG | videocaprate=512
(minishift) DBG | videocapfps=25
(minishift) DBG | videocapopts=
(minishift) DBG | GuestMemoryBalloon=0
(minishift) DBG | GuestOSType="Linux26_64"
(minishift) DBG | GuestAdditionsRunLevel=0
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Host-only MAC: 080027c0576b
(minishift) DBG |
(minishift) DBG | SSH binary not found, using native Go implementation
(minishift) DBG | &{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 62299 <nil> <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | ip addr show
(minishift) DBG | SSH cmd err, output: <nil>: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
(minishift) DBG |     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
(minishift) DBG |     inet 127.0.0.1/8 scope host lo
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG |     inet6 ::1/128 scope host
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG | 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
(minishift) DBG |     link/ether 08:00:27:e4:c8:22 brd ff:ff:ff:ff:ff:ff
(minishift) DBG |     inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
(minishift) DBG |        valid_lft 86355sec preferred_lft 86355sec
(minishift) DBG |     inet6 fe80::a00:27ff:fee4:c822/64 scope link
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG | 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
(minishift) DBG |     link/ether 08:00:27:c0:57:6b brd ff:ff:ff:ff:ff:ff
(minishift) DBG |     inet 192.168.99.106/24 brd 192.168.99.255 scope global noprefixroute dynamic eth1
(minishift) DBG |        valid_lft 1088sec preferred_lft 1088sec
(minishift) DBG |     inet6 fe80::a00:27ff:fec0:576b/64 scope link
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG | 5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
(minishift) DBG |     link/ether 02:42:73:2e:66:38 brd ff:ff:ff:ff:ff:ff
(minishift) DBG |     inet 172.17.0.1/16 scope global docker0
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG |
(minishift) DBG | SSH returned: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
(minishift) DBG |     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
(minishift) DBG |     inet 127.0.0.1/8 scope host lo
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG |     inet6 ::1/128 scope host
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG | 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
(minishift) DBG |     link/ether 08:00:27:e4:c8:22 brd ff:ff:ff:ff:ff:ff
(minishift) DBG |     inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
(minishift) DBG |        valid_lft 86355sec preferred_lft 86355sec
(minishift) DBG |     inet6 fe80::a00:27ff:fee4:c822/64 scope link
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG | 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
(minishift) DBG |     link/ether 08:00:27:c0:57:6b brd ff:ff:ff:ff:ff:ff
(minishift) DBG |     inet 192.168.99.106/24 brd 192.168.99.255 scope global noprefixroute dynamic eth1
(minishift) DBG |        valid_lft 1088sec preferred_lft 1088sec
(minishift) DBG |     inet6 fe80::a00:27ff:fec0:576b/64 scope link
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG | 5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
(minishift) DBG |     link/ether 02:42:73:2e:66:38 brd ff:ff:ff:ff:ff:ff
(minishift) DBG |     inet 172.17.0.1/16 scope global docker0
(minishift) DBG |        valid_lft forever preferred_lft forever
(minishift) DBG |
(minishift) DBG | END SSH
(minishift) DBG |
(minishift) Calling .GetSSHUsername
(minishift) Calling .GetSSHUsername
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 62299 <nil> <nil>}
About to run SSH command:
sudo install -d -o docker -g docker -m 755 /var/lib/minishift/base /var/lib/minishift/bin
SSH cmd err, output: <nil>:
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 62299 <nil> <nil>}
About to run SSH command:
docker network inspect -f "{{range .IPAM.Config }}{{ .Subnet }}{{end}}" bridge
SSH cmd err, output: <nil>: 172.17.0.0/16

(minishift) Calling .GetSSHUsername
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 62299 <nil> <nil>}
About to run SSH command:
docker images -q openshift/origin-control-plane:v3.11.0
SSH cmd err, output: <nil>:
-- Pulling the Openshift Container Image (minishift) Calling .GetSSHHostname
.(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x7aed70] 0x7aed40 <nil>  [] 0s} 127.0.0.1 62299 <nil> <nil>}
About to run SSH command:
docker pull openshift/origin-control-plane:v3.11.0
.SSH cmd err, output: Process exited with status 1: Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

Error pulling the openshift container image: ssh command error:
command : docker pull openshift/origin-control-plane:v3.11.0
err     : Process exited with status 1
output  : Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment] 2018-10-29 04:11
This is a duplicate of an earlier issue. You are behind a proxy that uses re-ecnryption. This will be looked into with #2880.

**Comment by gbraad** [comment] 2018-10-29 04:12
Same issue as #2941

**Closed by gbraad** 2018-10-29 04:11 UTC
