### ISSUE TITLE
minishift fails to restart if starting with service-catalog

### ISSUE THREAD

**Issue by cunningt** [minishift/minishift#1910] opened 2018-01-12 19:29 UTC
### General information

  * Minishift version: minishift v1.10.0+10461c6
  * OS: Mac OS X 10.13.2

### Steps to reproduce

  1. Start a fresh minishift with servicecatalog:
MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --openshift-version=v3.7.0 --memory 4GB --service-catalog --extra-clusterup-flags "--loglevel 1 --service-catalog"

--> minishift starts cleanly
  2.  Stop minishift 
  3. Start up minishift again with the same options
MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --openshift-version=v3.7.0-rc.0 --memory 4GB --service-catalog --extra-clusterup-flags "--loglevel 1 --service-catalog"

### Expected

Minishift starts up again cleanly

### Actual

-- Starting OpenShift container ... 
I0112 14:14:17.445219    3806 helper.go:585] Copying OpenShift config to local directory /var/folders/bt/c4_bx2yx3h51f5zb96b79gfr0000gp/T/openshift-config522530176

   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Registering template service broker with service catalog ... 
FAIL
   Error: cannot register the template service broker
   Caused By:
     Error: cannot create objects from template openshift-infra/template-service-broker-registration
     Caused By:
       Error: an error on the server ("Error: 'dial tcp 172.30.1.2:443: getsockopt: no route to host'\nTrying to reach: 'https://172.30.1.2:443/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers'") has prevented the request from succeeding (post clusterservicebrokers.servicecatalog.k8s.io)
Error during 'cluster up' execution: Error starting the cluster.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5
` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

[servicerbroker.log](https://github.com/minishift/minishift/files/1627204/servicerbroker.log)
[minishift-libmachine-logs.log](https://github.com/minishift/minishift/files/1627227/minishift-libmachine-logs.log)

**Comment by cunningt** [comment] 2018-01-12 19:29
Gisted log : https://gist.github.com/cunningt/c51478dbacaeb9a77b3e0b4feb9ad979

**Comment by praveenkumar** [comment] 2018-01-15 08:52
@cunningt Thanks for reporting the issue. I am also able to reproduce it when restart minishift. @csrwng, @jorgemoralespou  any idea?

```
-- Registering template service broker with service catalog ... FAIL
   Error: cannot register the template service broker
   Caused By:
     Error: cannot create objects from template openshift-infra/template-service-broker-registration
     Caused By:
       Error: an error on the server ("Error: 'dial tcp 172.30.1.2:443: getsockopt: connection refused'\nTrying to reach: 'https://172.30.1.2:443/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers'") has prevented the request from succeeding (post clusterservicebrokers.servicecatalog.k8s.io)
Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by jorgemoralespou** [comment] 2018-01-15 10:23
@praveenkumar @cunningt It seems as --service-catalog flag in "oc cluster up" is not idempotent, and hence on the second run, it tries to provision a cluster that has already been provisioned.

If you do:

First run:
```
MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start  <EXTRA_PARAMS> --extra-clusterup-flags "--service-catalog"
```

and in second run:
```
minishift start 
```

The service catalog works.

@csrwng Is this expected? 

@praveenkumar I would consider opening a bug in origin repo for this.

**Comment by csrwng** [comment] 2018-01-15 14:52
> @csrwng Is this expected?

I wouldn't think so. But will defer to @bparees and @deads2k to comment.

**Comment by bparees** [comment] 2018-01-15 17:30
No it's not expected.  Is minishift reusing an existing cluster config in this scenario, or is it a clean start?

**Comment by jorgemoralespou** [comment] 2018-01-15 21:28
@bparees, reusing. Minishift did create the config in the VM that reuses when it starts.
If you see my (comment)[https://github.com/minishift/minishift/issues/1910#issuecomment-357641231], if you pass the flag 2 consecutive times, it fails. If on the second run, you no longer provide the flag, it runs successfully.
This means that the catalog provisioning logic is not idempotent, or does not check if it has already been provisioned.

**Comment by bparees** [comment] 2018-01-15 21:34
> This means that the catalog provisioning logic is not idempotent, or does not check if it has already been provisioned.

It does, actually. The part that is failing is supposed to be rerun even on a restart because the broker must be re-registered.  What is happening here is something more complicated, hence the error being that we can't reach the service, not that we've attempted a redundant action.

only install if we're not reusing data:
https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/up.go#L448-L451

intentionally attempt to register the broker regardless because the service catalog doesn't preserve the list of brokers during a restart:
https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/up.go#L458-L462

So again, something else is causing this:
```
Error: an error on the server ("Error: 'dial tcp 172.30.1.2:443: getsockopt: connection refused'\nTrying to reach: 'https://172.30.1.2:443/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers'") has prevented the request from succeeding (post clusterservicebrokers.servicecatalog.k8s.io
```

possibly it's us trying to make the request before the service catalog is back up and running on the restart.

**Comment by jorgemoralespou** [comment] 2018-01-15 22:29
Does what you say match with the behavior seen. I mean, you say that this logic is meant to be re-n even if the flag is not passed again? As in that scenario it seems to be working, but not if the flag is passed on the second start.

Maybe in that second case, there's a race condition that happens because of the timings?

Anyway, you seem to pretty much understand the problem, so we're good.

Thanks so much. Should we open a bug in origin?

**Comment by bparees** [comment] 2018-01-15 23:14
> Thanks so much. Should we open a bug in origin?

only if you see the same problem w/ straight oc cluster up invocations instead of minishift.

**Comment by gbraad** [comment] 2018-01-16 04:52
@praveenkumar and for this kind of testing we would prefer to use a 'none' driver, as the general idea seems to be that we provide a lot around the `oc cluster up` command that might make it fail. If we can run against a local docker/host, this can easily be verified.

**Comment by praveenkumar** [comment] 2018-01-16 05:28
@jorgemoralespou @bparees I was able to reproduce it `oc cluster up` alone also. Created issue https://github.com/openshift/origin/issues/18119 to origin side.

**Comment by praveenkumar** [comment] 2018-01-16 05:29
> @praveenkumar and for this kind of testing we would prefer to use a 'none' driver, as the general idea seems to be that we provide a lot around the oc cluster up command that might make it fail. If we can run against a local docker/host, this can easily be verified.

Agree, may be we investigate in it and put it in our milestone.

**Comment by gbraad** [comment] 2018-01-16 06:30
It does not have to be exposed as a primary driver option, but can help pin point problems. Anyway, using `-v5` you can see the command that is used to execute `oc cluster up`. In this case it was:

```
$ oc cluster up --use-existing-config --host-volumes-dir /var/lib/minishift/openshift.local.volumes --version v3.7.0 --routing-suffix 192.168.64.16.nip.io --service-catalog true --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-pv-dir /var/lib/minishift/openshift.local.pv --loglevel 1 --service-catalog
```

**Comment by jorgemoralespou** [comment] 2018-03-21 14:08
Keep

**Comment by cmoulliard** [comment] 2018-03-21 17:35
I also experiment the same issue when `oc cluster up` systemctl service is restarted
with an openshift config using service catalog. OpenShift version is 3.7

As my problem doesn't happen without using `minishift`, then I would like to suggest that OpenShift Dev team investigate the question @bparees ?

```
[root@cloud ~]# systemctl status openshift.service
● openshift.service - OpenShift oc cluster up Service
   Loaded: loaded (/etc/systemd/system/openshift.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-03-21 17:24:17 UTC; 3min 43s ago
  Process: 32422 ExecStop=/usr/local/bin/oc cluster down (code=exited, status=0/SUCCESS)
  Process: 302 ExecStart=/usr/local/bin/oc cluster up --service-catalog=true --version=v3.7.0 --host-config-dir=/var/lib/openshift/config --host-data-dir=/var/lib/openshift/data --host-pv-dir=/tmp --host-volumes-dir=/var/lib/openshift/volumes --use-existing-config=true --public-hostname=192.168.99.50 --routing-suffix=192.168.99.50.nip.io --loglevel=1 (code=exited, status=1/FAILURE)
 Main PID: 302 (code=exited, status=1/FAILURE)

Mar 21 17:24:17 cloud occlusterup[302]: FAIL
Mar 21 17:24:17 cloud occlusterup[302]: Error: cannot register the template service broker
Mar 21 17:24:17 cloud occlusterup[302]: Caused By:
Mar 21 17:24:17 cloud occlusterup[302]: Error: cannot create objects from template openshift-infra/template-service-broker-registration
Mar 21 17:24:17 cloud occlusterup[302]: Caused By:
Mar 21 17:24:17 cloud occlusterup[302]: Error: an error on the server ("Error: 'dial tcp 172.30.1.2:443: getsockopt: connection refused'\nTrying to reach: 'https://172.30.1.2:443/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers'...vicecatalog.k8s.io)
Mar 21 17:24:17 cloud systemd[1]: openshift.service: main process exited, code=exited, status=1/FAILURE
Mar 21 17:24:17 cloud systemd[1]: Failed to start OpenShift oc cluster up Service.
Mar 21 17:24:17 cloud systemd[1]: Unit openshift.service entered failed state.
Mar 21 17:24:17 cloud systemd[1]: openshift.service failed.
```

Script used to install openshift is available here : https://github.com/snowdrop/cloud-native-infra/blob/master/oc/install_ocp.sh

**Comment by anjannath** [comment] 2018-05-23 12:15
Is this still an issue?

**Comment by cunningt** [comment] 2018-05-23 12:44
Yes, this is still an issue.   Tried it this morning on minishift 1.17.0

**Comment by gbraad** [comment] 2018-05-23 16:13
Since it is also an issue with 'oc cluster up', I suggest to have an
upstream issue.

/Cc: @deads2k

On Wednesday, May 23, 2018, Tom Cunningham <notifications@github.com> wrote:
> Yes, this is still an issue. Tried it this morning on minishift 1.17.0
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/aEBBXPGmqPx2qpSrYb2PbNltGiSVaJ3RAhNQBMX7PpYvcBp98-tS710PmeJJbMB23mIh_wugaWQ6KtGyZEcH0FSa-NKx1R9Bewjp-PZgVtICHxeRZlSLMDr-eZTHh6zbaAL4MgYIMfGyC9b6el4GOESHFGtDmQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZqb9rYNbXzP1Y6H5dlwTF2KWVT_0ks5t1VmUgaJpZM4Rcv4G.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by praveenkumar** [comment] 2018-05-24 05:49
We do have upstream issue https://github.com/openshift/origin/issues/18119 for it.

**Comment by LalatenduMohanty** [comment] 2018-07-23 10:32
Lets check with Origin 3.10 and see if it is still an issue.

**Comment by LalatenduMohanty** [comment] 2018-07-24 07:11
As per https://github.com/openshift/origin/issues/18119#issuecomment-407052375 it is fixed in 3.10.

**Comment by LalatenduMohanty** [comment] 2018-09-14 07:42
@amitkrout @agajdosi Can you guys check if this is reproducible?

**Comment by agajdosi** [comment] 2018-09-14 10:05
@LalatenduMohanty will take a look today

**Comment by agajdosi** [comment] 2018-09-14 12:58
So I am able to start Minishift with service-catalog enabled:

```
[agajdosi@dhcp-24-156 ~]$ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --memory 4GB --extra-clusterup-flags '--enable centos-imagestreams --enable persistent-volumes --enable registry --enable router --enable sample-templates --enable service-catalog --enable web-console'
-- Starting profile 'minishift'
[...]
-- Starting OpenShift cluster -- Extra 'oc' cluster up flags (experimental) ... 
   '--enable centos-imagestreams --enable persistent-volumes --enable registry --enable router --enable sample-templates --enable service-catalog --enable web-console'
.......................................................
[...]
Adding default OAuthClient redirect URIs ...
Adding registry ...
Adding sample-templates ...
Adding web-console ...
Adding centos-imagestreams ...
Adding router ...
Adding persistent-volumes ...
Adding service-catalog ...
[...]
I0914 08:28:40.448608    2099 interface.go:41] Finished installing "openshift-image-registry" "sample-templates" "openshift-web-console-operator" "centos-imagestreams" "openshift-router" "persistent-volumes" "openshift-service-catalog"
[...]
```

Then I stop Minishift and try to start it again. However I face the problem that `oc cluster up` does not accept the `--enable` again:

```
-- Starting OpenShift cluster -- Extra 'oc' cluster up flags (experimental) ... 
   '--enable centos-imagestreams --enable persistent-volumes --enable registry --enable router --enable sample-templates --enable service-catalog --enable web-console'
.Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --public-hostname 192.168.42.23 --routing-suffix 192.168.42.23.nip.io --base-dir /var/lib/minishift/base --enable centos-imagestreams --enable persistent-volumes --enable registry --enable router --enable sample-templates --enable service-catalog --enable web-console
err     : exit status 1
output  : error: cannot use --enable when the cluster is already initialized, use cluster add instead
```
`oc cluster add` however does not have any flag `--enable` or similar AFAIU (also can't start Minishift using `cluster add`). Maybe @bparees @jorgemoralespou you are aware of some workaround against this problem?

If I try it without all the `--enable` flags selected, the cluster is started, however `service-catalog` is not present - seems like cluster up's default values for `--enable` are used:

```
MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --memory 4GB
[...]
I0914 08:31:59.032790    2037 interface.go:41] Finished installing "openshift-image-registry" "centos-imagestreams" "sample-templates" "persistent-volumes" "openshift-web-console-operator" "openshift-router"
Server Information ...
OpenShift server started.
```

**Comment by jorgemoralespou** [comment] 2018-09-14 14:12
@praveenkumar ^^^This is the problem I described. AFAIK in 3.11 the components used when you first start `oc cluster up` are saved in a `componentes.json` file. This functionality does not exist in 3.10 making it a total mess.

In 3.11 though, even the option of persisting the components exist, if you add components to the cluster, they are not added to this json file (which should be an origin bug to solve IMHO), but given that I don't know where `oc cluster` is going in upcoming 4.0 release, and the lack of information on who owns that now, I just have given up on it.

I think we need @sspecihe to own this and to get all the relevant information on what is the future and how is going to be the future of `oc cluster up`.

**Comment by gbraad** [comment] 2018-09-14 14:43
> I think we need @sspeiche to own this

Agree

**Comment by sspeiche** [comment] 2018-09-14 14:56
@jorgemoralespou I have already been communicating with the CDK/minishift team and the OpenShift (oc cluster up) team. They are aware roughly the changes coming to `oc cluster up` in 4.0 and that OpenShift team knows they need to layout the work needed in minishift / CDK _v4_ to support this.

**Comment by jorgemoralespou** [comment] 2018-09-14 14:57
@sspeiche never doubted you ;-)

**Comment by cmoulliard** [comment] 2018-09-14 17:09
> going to be the future of `oc cluster up`.

This is really important to stabilize the next version of `oc cluster up` as using `3.10` is really hard for different reasons including the size of the images to be downloaded (which explain the timeout that we get), the new approach followed to install addons such as service catalog, that docker-machine is not supported for mac's developer, ...

**Comment by gbraad** [comment] 2018-09-16 16:55
> that docker-machine is not supported for mac's developer

Can you elaborate on this?

**Comment by cmoulliard** [comment] 2018-09-17 08:04
> Can you elaborate on this?

okd - origin project doesn't [support](https://github.com/openshift/origin/issues/20753#issuecomment-416207880) anymore mac's users running `oc cluster up` top of `docker ce = hyperkit` or `docker-machine` BUT only if you run `oc cluster up` wirthin a VM (VM created using virtualbox, ....). Doc's page of `oc cluster up` doesn't include anymore `mac section` - https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#getting-started

**Comment by praveenkumar** [comment] 2018-09-27 04:46
User should able to now use `minishift openshift component add service-catalog` and this actually works after restart also. Right now we are using `oc cluster add` functionality under the hood and this will be there atleast till 3.11

**Comment by gbraad** [comment] 2018-09-27 04:51
> okd - origin project doesn't support anymore mac's users running oc cluster up top of docker ce = hyperkit or docker-machine BUT


When you said 'docker-machine' is not supported you mean `oc cluster up` targeting' docker on mac'. This is not the same... we are using docker-machine and this works on mac and. Windows

But right, we are aware of this... and I helped to get rid of this with Ben. This is due to a lot of issues and missing functionality. But not sure why this got brought up, as it does not concern us directly. Note; same goes for Windows.

**Comment by anjannath** [comment] 2018-10-05 08:05
Not reproducible consistently using the latest minishift, i was able to add the `service-catalog` component using `minishift openshift component add service-catalog` and consecutive restarts works fine.

Although it failed for the first restart, after that it was working fine, ATM this is not consistently reproducible.

**Comment by anjannath** [comment] 2018-10-16 05:48
@cunningt Did you try the method mentioned in https://github.com/minishift/minishift/issues/1910#issuecomment-424957737
If it is not reproducible any more, feel free to close this issue.

**Comment by LalatenduMohanty** [comment] 2018-10-23 18:02
This issue is resolved now, here are the steps I performed on master i.e. 1.26.0 version

```
$ minishift start
$ minishift openshift component list
The following OpenShift components are available: 
	- automation-service-broker
	- service-catalog
	- template-service-broker
$ minishift openshift component add service-catalog
Adding service-catalog ...
I1023 16:26:09.302118   19619 interface.go:26] Installing "openshift-service-catalog" ...
I1023 16:26:09.438034   19619 apply_template.go:81] Installing "service-catalog"
I1023 16:27:07.970718   19619 interface.go:41] Finished installing "openshift-service-catalog"


$ minishift stop
Stopping the OpenShift cluster...
Cluster stopped.

$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ................ OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 14% used OK
-- Writing current configuration for static assignment of IP address ... WARN
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ...........................
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.42.101 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I1023 17:47:44.298579    2109 flags.go:30] Running "create-kubelet-flags"
I1023 17:47:44.934244    2109 run_kubelet.go:49] Running "start-kubelet"
I1023 17:47:45.329269    2109 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1023 17:48:05.380443    2109 interface.go:26] Installing "kube-proxy" ...
I1023 17:48:05.380925    2109 interface.go:26] Installing "kube-dns" ...
I1023 17:48:05.380953    2109 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1023 17:48:05.380960    2109 interface.go:26] Installing "openshift-apiserver" ...
I1023 17:48:05.380991    2109 apply_template.go:81] Installing "openshift-apiserver"
I1023 17:48:05.381668    2109 apply_template.go:81] Installing "kube-proxy"
I1023 17:48:05.382575    2109 apply_template.go:81] Installing "kube-dns"
I1023 17:48:05.382709    2109 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1023 17:48:43.468778    2109 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I1023 17:48:43.497401    2109 run_self_hosted.go:242] openshift-apiserver available
I1023 17:48:43.497427    2109 interface.go:26] Installing "openshift-controller-manager" ...
I1023 17:48:43.497456    2109 apply_template.go:81] Installing "openshift-controller-manager"
I1023 17:48:47.583449    2109 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding sample-templates ...
Adding persistent-volumes ...
Adding web-console ...
Adding registry ...
Adding router ...
Adding centos-imagestreams ...
I1023 17:48:47.658395    2109 interface.go:26] Installing "sample-templates" ...
I1023 17:48:47.658405    2109 interface.go:26] Installing "persistent-volumes" ...
I1023 17:48:47.658414    2109 interface.go:26] Installing "openshift-web-console-operator" ...
I1023 17:48:47.658422    2109 interface.go:26] Installing "openshift-image-registry" ...
I1023 17:48:47.658427    2109 interface.go:26] Installing "openshift-router" ...
I1023 17:48:47.658435    2109 interface.go:26] Installing "centos-imagestreams" ...
I1023 17:48:47.658503    2109 apply_list.go:67] Installing "centos-imagestreams"
I1023 17:48:47.658678    2109 interface.go:26] Installing "sample-templates/mysql" ...
I1023 17:48:47.658690    2109 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I1023 17:48:47.658708    2109 interface.go:26] Installing "sample-templates/django quickstart" ...
I1023 17:48:47.658719    2109 interface.go:26] Installing "sample-templates/rails quickstart" ...
I1023 17:48:47.658728    2109 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I1023 17:48:47.658736    2109 interface.go:26] Installing "sample-templates/mongodb" ...
I1023 17:48:47.658746    2109 interface.go:26] Installing "sample-templates/mariadb" ...
I1023 17:48:47.658770    2109 interface.go:26] Installing "sample-templates/postgresql" ...
I1023 17:48:47.658777    2109 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I1023 17:48:47.658784    2109 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I1023 17:48:47.658793    2109 interface.go:26] Installing "sample-templates/sample pipeline" ...
I1023 17:48:47.658862    2109 apply_list.go:67] Installing "sample-templates/sample pipeline"
I1023 17:48:47.660085    2109 apply_template.go:81] Installing "openshift-web-console-operator"
I1023 17:48:47.661116    2109 apply_list.go:67] Installing "sample-templates/mysql"
I1023 17:48:47.661282    2109 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I1023 17:48:47.661420    2109 apply_list.go:67] Installing "sample-templates/django quickstart"
I1023 17:48:47.661557    2109 apply_list.go:67] Installing "sample-templates/rails quickstart"
I1023 17:48:47.661685    2109 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I1023 17:48:47.661819    2109 apply_list.go:67] Installing "sample-templates/mongodb"
I1023 17:48:47.661969    2109 apply_list.go:67] Installing "sample-templates/mariadb"
I1023 17:48:47.662106    2109 apply_list.go:67] Installing "sample-templates/postgresql"
I1023 17:48:47.662236    2109 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I1023 17:48:47.662363    2109 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I1023 17:48:58.956074    2109 interface.go:41] Finished installing "sample-templates/mysql" "sample-templates/nodejs quickstart" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mongodb" "sample-templates/mariadb" "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/sample pipeline"
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.101:8443/console

I1023 17:48:59.993900    2109 interface.go:41] Finished installing "sample-templates" "persistent-volumes" "openshift-web-console-operator" "openshift-image-registry" "openshift-router" "centos-imagestreams"

```

**Closed** 2018-10-23 18:03 UTC
Labels: kind/bug, priority/major, status/pinned
