### ISSUE TITLE
Machine didn't return an IP after 120 seconds, aborting

### ISSUE THREAD

**Issue by heiko-braun** [minishift/minishift#110] opened 2016-10-04 08:43 UTC
```
hbraun:~/dev/prj/redhat-msa/quick_swarm_camel-test (master)$ minishift start --deploy-registry=true --deploy-router=true --memory=4048 --vm-driver="xhyve" --logtostderr=true
W1004 09:21:29.524531   80650 root.go:120] Error reading config file at /Users/hbraun/.minishift/config: Unsupported Config Type ""
Starting local OpenShift cluster...
I1004 09:21:30.076907   80650 cluster.go:77] Machine exists!
I1004 09:21:30.093646   80650 cluster.go:85] Machine state:  Stopped
E1004 09:23:31.473453   80650 start.go:89] Error starting host: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
I1004 09:23:31.473530   80650 cluster.go:77] Machine exists!
I1004 09:23:31.490020   80650 cluster.go:85] Machine state:  Running
E1004 09:26:31.574569   80650 start.go:89] Error starting host: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
I1004 09:26:31.574671   80650 cluster.go:77] Machine exists!
I1004 09:26:31.590898   80650 cluster.go:85] Machine state:  Running
E1004 09:29:31.676246   80650 start.go:89] Error starting host: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1004 09:29:31.676297   80650 start.go:95] Error starting host:  Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

```

**Comment by heiko-braun** [comment] 2016-10-04 08:43
Related to #106?

**Comment by heiko-braun** [comment] 2016-10-04 08:44
Related to https://github.com/docker/toolbox/issues/317?

**Comment by heiko-braun** [comment] 2016-10-04 13:04
https://github.com/kubernetes/minikube/issues/646 ?

**Comment by jimmidyson** [comment] 2016-10-04 14:01
Wondering if it's a problem with xhyve driver? Are you running OS X Sierra?

**Comment by heiko-braun** [comment] 2016-10-04 14:24
No, I am still on 10.11.6

**Comment by heiko-braun** [comment] 2016-10-04 14:24
What's described in kubernetes/minikube#646 is what I have installed. And the problem descriptions matches as well.

**Comment by rafabene** [comment] 2016-10-11 00:02
I had the same issue and I was able to solve by typing

>  sudo rm -rf ~/.minishift

**Comment by LalatenduMohanty** [comment] 2016-11-27 11:08
@heiko-braun Is this still an issue for you?

**Comment by websemantics** [comment] 2016-12-08 23:09
Having same issue, tried, `sudo rm -rf ~/.minishift`, didn't help,  running Yosemite, 10.10.5

**Comment by astefanutti** [comment] 2016-12-20 12:12
I faced the same issue. Deleting the  `~/.minishift` directory did not help.

I reinstall the latest version of xhyve and docker-machine-driver-xhyve and it worked, e.g.:

```
$ brew update
$ brew install --HEAD xhyve
$ brew install docker-machine-driver-xhyve
$ sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
$ sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
```
I may have removed the minishift entry in `/var/db/dhcpd_leases` though I don't think that changes anything.

**Comment by praveenkumar** [comment] 2016-12-21 09:55
@astefanutti there are some bug fixes from xhyve side recently so glad to hear it worked for you. xhyve have known issue for `dhcpd_lease` and currently if you face issue with `vnet` creation then remove `minishift` entry from listed file make it work.

**Comment by rhuss** [comment] 2017-01-05 10:03
@astefanutti thx, that worked for me, too, but only when using docker-machine from brew, not that one coming with Docker for Mac (1.13.0-rc4-beta34.1 (14853)). Had to do this, too:

```
brew link --overwrite  docker-machine
brew unlink docker-machine-driver-xhyve
```
before 

```
brew install docker-machine-driver-xhyve
```

**Comment by rhuss** [comment] 2017-01-05 10:30
thanks for the heads up. will go back to 0.9.0 because of time constraints, but will try to find out later again (if not someone is faster ;-)

**Comment by astefanutti** [comment] 2017-01-05 13:28
@rhuss, it works with the following command:

```
minishift start \
  --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-alpha.1/minishift-centos.iso \
  --use-existing-config \
  --host-data-dir=/var/lib/boot2docker
```

**Comment by rhuss** [comment] 2017-01-06 08:39
@astefanutti thanks !

@christian-posta guess its because of the change to 'oc cluster-up' internally which is a big change.

**Comment by rhuss** [comment] 2017-01-06 08:42
There also seems some xhyve issues, and, probably more seriously, issues with docker-machine which comes with 'Docker for Mac'. I had to use brew's docker-machine to make it work. I consider this a show-stopper if minishift doesn't work well together when 'Docker for Mac' is installed, since I consider this a very common setup.

**Comment by jimmidyson** [comment] 2017-01-06 09:11
libmachine is used as a library with no dependency on docker machine so I'm not sure why there should be a conflict there tbh.

**Comment by rhuss** [comment] 2017-01-06 09:15
I had to remove the link `/usr/local/bin/docker-machine`, to that `brew install docker-machine` succeeds which is a prerequisite of `brew install docker-machine-driver-xhyve`. So, tbh, it might be a brew issue, too.

**Comment by jimmidyson** [comment] 2017-01-06 12:22
Ah OK now that makes sense.

**Comment by praveenkumar** [comment] 2017-01-06 12:41
@christian-posta We just did internal change to use `oc cluster up` nothing actually changed from user side. you might have issue with a outdated xhyve driver as @rhuss told please try to update driver and give it another try, let us know if still didn't work. We tested it against `docker-machine-xhyve-0.3.1`.

**Comment by christian-posta** [comment] 2017-01-06 14:48
so removing boot2docker/minishift entries from the dhcpd_lease file was important for me to resolve this.. fyi

**Comment by praveenkumar** [comment] 2017-01-06 16:59
@christian-posta Great to hear, also we did mention it in troubleshooting guide https://github.com/minishift/minishift/blob/master/docs/troubleshooting.md#error-could-not-create-vmnet-interface-permission-denied-or-no-entitlement.

Will close this issue once @heiko-braun and @websemantics confirms it works for them also.

**Comment by hferentschik** [comment] 2017-01-09 10:20
This could be put down then as a duplicate of issue  #214 I guess.

**Comment by praveenkumar** [comment] 2017-01-17 06:25
@hferentschik I think we are enough waited for confirmation and yes it's already added as part of the troubleshooting doc. l am closing it right now.

**Closed by praveenkumar** 2017-01-17 06:25 UTC
Labels: bug, major

**Comment by bcronrath** [comment] 2017-04-10 17:28
what resolves this for me is if I just run minikube delete and then retry starting it up

**Comment by jared201** [comment] 2020-08-29 02:13
> what resolves this for me is if I just run minikube delete and then retry starting it up

how do you that specifically with minishift?

**Comment by jared201** [comment] 2020-08-29 02:31
followed all instructions here using MacOs catalina, anyone can point me to the most updated instructions? or Minishift is just way too old?
