### ISSUE TITLE
Unable to start minishift 1.0.0.beta1 on Windows 10 with Hyper-V

### ISSUE THREAD

**Issue by rhopp** [minishift/minishift#244] opened 2017-01-03 09:30 UTC
Output of `minishift start --show-libmachine-logs --v=5`:
https://paste.fedoraproject.org/519240/14834354/

Running with CentOS image does not work either, but the error is different: https://paste.fedoraproject.org/519245/34357981/

**Comment by budhrg** [comment] 2017-01-03 09:40
@rhopp By any chance you ran the second minishift build without deleting the previous builds using `minishift delete` ?

**Comment by rhopp** [comment] 2017-01-03 09:50
Nope... Allways did "delete" before another start... And sometimes I even deleted .minishift folder in home. Did not help.

**Comment by budhrg** [comment] 2017-01-03 09:52
> Nope... Allways did "delete" before another start... And sometimes I even deleted .minishift folder in home. Did not help.

Thanks for confirming @rhopp

**Comment by hferentschik** [comment] 2017-01-04 10:17
> Output of minishift start --show-libmachine-logs --v=5:
> https://paste.fedoraproject.org/519240/14834354/

Regarding this error:

    Provisioning OpenShift via 'C:\Users\jboss-qa\.minishift\cache\oc\v1.3.1\oc [cluster up]'
    -- Checking OpenShift client ... OK
    -- Checking Docker client ... FAIL

This looks like _oc cluster up_ not being able to connect to the Docker daemon. What's happening is the following:

* Minishift uses libmachine to start a VM and provide a Docker daemon
* Minishift then downloads the _oc_ binary and and executes 'oc cluster up' via a system call
* To make this work, the right environment variables need to be set for the process calling _cluster up_. This looks like this - https://github.com/minishift/minishift/blob/master/cmd/minikube/cmd/start.go#L147:
        
                 envMap, err := cluster.GetHostDockerEnv(libMachineClient)
	         for k, v := range envMap {
		       os.Setenv(k, v)
                 }

So either this setting of the Docker env variables failed in your case, in which case _oc cluster up_ cannot connect to the Docker daemon to provision OpenShift or the Docker daemon did not start properly. 

So, is this error re-producable? If so, can you connect to the VM when it fails. I would expect that the VM is running, even though the OpenShift provisioning failed. If so, `minishift ssh` and on the VM determine whether the Docker daemon is running. If it is running there seems to be a problem with the env variables. Not sure what could cause it. What type of shell are you using for running _minishift_?

**Comment by rhopp** [comment] 2017-01-05 10:25
The machine is running (minishift status returns "Running" and I can see it in Hyper-V manager).
But 'minishift ssh' is not working. Here is the output with debug log: 
```
C:\Users\jboss-qa\minishift>minishift ssh --show-libmachine-logs --v=5
Found binary path at minishift.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:60274
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHHostname
(minishift) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minishift ).state
(minishift) DBG | [stdout =====>] : Running
(minishift) DBG |
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM minishift ).networkadapters[0]).ipaddresses[0]
(minishift) DBG | [stdout =====>] : fe80::215:5dff:fe05:6214
(minishift) DBG |
(minishift) Calling .GetSSHPort
(minishift) DBG | [stderr =====>] :
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0xa337b0] <nil>  []} fe80::215:5dff:fe05:6214 22 <nil>}
Making call to close driver server
(minishift) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
(minishift) DBG | Closing plugin on server side
```
I'm using windows command line (cmd) with administrator rights.

**Comment by rhopp** [comment] 2017-01-05 10:32
Btw... Trying to run this from cygwin terminal I get this (but I guess this is not supported): 
```
jboss-qa@DESKTOP-BVH4HJO /cygdrive/c/Users/jboss-qa/minishift
$ ./minishift.exe status
E0105 11:28:44.521826    4956 status.go:41] Error getting machine status: open C:\Users\jboss-qa\.minishift\machines\minishift\config.json: The system cannot find the file specified.
```

**Comment by budhrg** [comment] 2017-01-05 10:43
@rhopp , Ya we haven't tested minishift with cygwin thoroughly yet as default terminals (CMD.exe or Powershell) are working fine.

For me I am not able to reproduce this issue as it works fine for me with Powershell in Windows 10.

Could you start minishift cleanly with Powershell ? (Just to make sure whether same get reproduce in Powershell or not)

**Comment by rhopp** [comment] 2017-01-05 11:02
Using powershell seems to be exactly the same: https://paste.fedoraproject.org/520166/83614134/

**Comment by budhrg** [comment] 2017-01-05 11:18
@rhopp I doubt this is due to IPv6 IP protocol. 

Could you disable it and try again?

https://support.microsoft.com/en-in/kb/929852

**Comment by rhopp** [comment] 2017-01-10 13:20
After BlueJeans session with @budhrg we found out I had wrongly configured virtual switch in HyperV manager. We had to delete the old one and create new one with correct settings. After that I was finally able to start minishift.
As an outcome of this issue could be better documentation for users on Windows on Hyper-V.

**Comment by budhrg** [comment] 2017-01-10 13:29
I am closing this issue as we are tracking its documentation here https://github.com/minishift/minishift/issues/265.

**Closed by budhrg** 2017-01-10 13:29 UTC
Labels: bug, major
