### ISSUE TITLE
fmtcheck and fmt targets are using different command line flags

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#443] opened 2017-02-21 02:21 UTC
Currently, `gofmt` is failing in master HEAD due to commit https://github.com/minishift/minishift/commit/60b8ddcc504113313d81bd6e32e4b66053a02530.

Weird how it passed last time.

```
gofmt check failed for:
00:08:43.716 pkg/minishift/util/proxy_util.go
```

Check https://ci.centos.org/job/minishift/199/console  ---> `00:08:43.561` time.

**Comment by gbraad** [comment] 2017-02-21 07:56
LGTM

**Comment by hferentschik** [comment] 2017-02-21 08:58
The problem is that the _fmt_ and the _fmtcheck_ target don't use the same command line switches. The latter also applies the '-s' option which applies some code transformations as well (on top of pure formatting). The _fmt_ target did not do that, leading to a disconnect between the two targets.

They both needs to apply/check for the same formatting and transformations, but whereas _fmt_ applies them, _fmtcheck_ only reports on the files which violates the rules.

**Comment by LalatenduMohanty** [comment] 2017-02-21 09:02
+1 @hferentschik I am was wondering about the same too. I do not think we need two different ways to check code formatting.

**Comment by hferentschik** [comment] 2017-02-21 09:03
Merged via pull request #444.

**Closed by hferentschik** 2017-02-21 09:03 UTC
Labels: kind/bug, priority/minor

**Comment by hferentschik** [comment] 2017-02-21 09:04
>  I am was wondering about the same too. I do not think we need two different ways to check code formatting.

There are two different things. One is a check one is an actual check and transform. Both are valid targets to have imo. They just need to be configured properly. On a CI environment for example you want to use _fmtcheck_.

**Comment by gbraad** [comment] 2017-02-21 09:06
OK, agree. Note: I did correct my comment earlier ;-)

**Comment by LalatenduMohanty** [comment] 2017-02-21 09:17
> One is a check one is an actual check and transform. Both are valid targets to have imo. They just need to be configured properly. On a CI environment for example you want to use fmtcheck.

I understand.  I was trying to say that if `make fmt` does not suggest any code changes `make fmtcheck` should not complain. So I am suggesting either we use `-s` in make fmt also or completly drop it from `make fmtcheck`.  I would go for including -s in make fmt.
