### ISSUE TITLE
Minishift can't download 3.7.0 oc binary

### ISSUE THREAD

**Issue by pearj** [minishift/minishift#1771] opened 2017-11-29 23:49 UTC
I'm trying to install 3.7.0 in minishift in windows, but it fails to find the oc binary, so it doesn't even try installing. This is pretty annoying as I'm able to find the 3.7.0 binary myself, and I tried putting it in the oc cache folder, but it still didn't work.

```
$ minishift start --cpus 4 --memory 16384 --vm-driver virtualbox --openshift-version 3.7.0
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Starting profile '3.7'
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ..................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
Error starting the cluster: Error attempting to download and cache oc: Cannot get binary 'oc' in version v3.7.0 for the target environment Windows
```

It seems for 3.7 the oc binaries don't live on github anymore, maybe that's why minishift fell over. I went to https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/branch-logs/origin/v3.7.0/builds/test_branch_origin_cross/1032/artifacts/zips/ and found them there. Is there any way to tell minishift to ignore oc and plow forward? Or even if I could tell it the oc url, that'd be handy too.

**Comment by pearj** [comment] 2017-11-30 00:03
Ok, so I found a workaround. It turns out minishift cache structure has changed since I used it last.

I needed to put the oc binary in `.minishift\profiles\minishift370\cache\oc\v3.7.0\windows` instead of just `.minishift\profiles\minishift370\cache\oc\v3.7.0`

**Comment by gbraad** [comment] 2017-11-30 03:05
@praveenkumar Can you have a look why this is an issue? It shouldn't fail...

**Comment by praveenkumar** [comment] 2017-11-30 04:17
> I hope this is temporary.... ?

I do hope so, let talk to openshift ML about it.

**Comment by gbraad** [comment] 2017-11-30 04:33
Have filed the issue with Chinese users as: https://github.com/openshift/origin/issues/17525

**Comment by LalatenduMohanty** [comment] 2017-11-30 06:32
Filed an issue from Minishift point of view https://github.com/openshift/origin/issues/17527

**Comment by gbraad** [comment] 2017-11-30 06:36
@lalatenduM agree, as I also tweeted this: "The reason for Minishift is that the new location is harder to locate. It needs to be extracted from the Github release message to be usable for us. Hope this is temporary or has an 'official' mirror." https://twitter.com/gbraad/status/936104043142791168

The link seems to contain a build id `/1032/` which makes this more complicated for any third party.

**Comment by budhrg** [comment] 2017-11-30 08:07
Same is reproducible in Linux (Fedora 26) as well.

**Comment by hferentschik** [comment] 2017-11-30 21:08
For all I can tell what we are after is still on GitHub - https://github.com/openshift/origin/releases/tag/v3.7.0

**Comment by praveenkumar** [comment] 2017-12-01 05:31
@LalatenduMohanty Since binaries are published and now it works should we close this issue. To track future plan I created #1775

**Closed by praveenkumar** 2017-12-01 05:31 UTC
Labels: kind/bug, priority/critical

**Comment by gbraad** [comment] 2017-12-01 08:10
@hferentschik They have since been published; this wasn't the case yesterday as can be seen here: https://github.com/openshift/origin/issues/17527#issuecomment-348102372
