### ISSUE TITLE
Unable to use 'openshift-version' flag of start command  to run specific OpenShift version

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#288] opened 2017-01-13 11:53 UTC
See error reported 

```
minishift start --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-beta.1/minishift-centos.iso --memory=6000 --openshift-version=v1.4.0-rc1 --docker-env=[storage-driver=devicemapper] --vm-driver=virtualbox
Starting local OpenShift instance using 'virtualbox' hypervisor...
Provisioning OpenShift via '/Users/chmoulli/.minishift/cache/oc/v1.4.0-rc1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.0-rc1 image ...
   Pulling image openshift/origin:v1.4.0-rc1
   Pulled 0/3 layers, 4% complete
   Pulled 1/3 layers, 67% complete
   Pulled 2/3 layers, 96% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... FAIL
   Error: Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
E0113 12:49:08.408930    2148 start.go:246] Error starting 'cluster up':  exit status 1
```

**Comment by hferentschik** [comment] 2017-01-13 20:09
You are getting in untested territories here. You are trying to use a newer version of OpenShift as the one which is default. Given the existing flags this makes perfect sense. Unfortunately, we have not really tested this yet. I guess the problem are mismatches in the Docker version provided by the VM and what 'oc cluster up' expects. We might need to do a better job detecting compatible versions.

It might also relate to issue #252 or when it comes to do a better job of selecting compatible versions issue #197. 

This is definitely a big and we should look into this asap.

**Comment by LalatenduMohanty** [comment] 2017-01-13 20:52
I am not able to reproduce the issue. The only difference is my minishift is compiled from master branch.

```
$ rm -rf ~/.minishift/

$ minishift start --iso-url file:/Users/lmohanty/Downloads/minishift-centos.iso --memory=6000 --openshift-version=v1.4.0-rc1 --docker-env=[storage-driver=devicemapper] --vm-driver=virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
 21.26 MB / 21.26 MB [==========================================================================================================================================================================] 100.00% 0s
Provisioning OpenShift via '/Users/lmohanty/.minishift/cache/oc/v1.4.0-rc1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.0-rc1 image ... 
   Pulling image openshift/origin:v1.4.0-rc1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 63% complete
   Pulled 2/3 layers, 93% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.99.100 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.100:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

**Comment by cmoulliard** [comment] 2017-01-14 10:37
If I try to use a builded version of minishift, I can't create a VM as minishift looks for a hard coded folder !!!!

```
m -rf ~/.minishift/
dabou-macosx:~/MyApplications/go-wks/src/github.com/minishift/minishift$ ./out/darwin-amd64/minishift start --iso-url file:/Users/lmohanty/Downloads/minishift-centos.iso --memory=6000 --openshift-version=v1.4.0-rc1 --docker-env=[storage-driver=devicemapper] --vm-driver=virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0114 11:19:31.330147   16914 start.go:135] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/lmohanty/Downloads/minishift-centos.iso: no such file or directory. Retrying.
E0114 11:19:31.390551   16914 start.go:135] Error starting the VM: Error getting the state for host: machine does not exist. Retrying.
E0114 11:19:31.446745   16914 start.go:135] Error starting the VM: Error getting the state for host: machine does not exist. Retrying.
E0114 11:19:31.446778   16914 start.go:141] Error starting the VM:  Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/lmohanty/Downloads/minishift-centos.iso: no such file or directory
Error getting the state for host: machine does not exist
Error getting the state for host: machine does not exist
```

**Comment by gbraad** [comment] 2017-01-16 04:24
@cmoulliard I think you made a typo in the last try. You specified the exact same command as @LalatenduMohanty. What happened here is that you also specified the cached path for the boot image `--iso-url file:/Users/lmohanty/Downloads/minishift-centos.iso`. You can either specify `--iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-beta.1/minishift-centos.iso` or download the image locally and use the `file:///` scheme to point to it.

Retry the command as you used when reporting the issue.

**Comment by praveenkumar** [comment] 2017-01-16 05:41
> -- Checking Docker daemon configuration ... FAIL
   Error: Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
E0113 12:49:08.408930    2148 start.go:246] Error starting 'cluster up':  exit status 1

@cmoulliard This error you are getting because you already have docker env variable set on the same bash session where you tried again using latest version of openshift. To avoid this better to perform it in a new terminal tab or clear docker env which set by `$ minishift docker-env`.

**Comment by hferentschik** [comment] 2017-01-16 08:44
@cmoulliard, could you confirm this? If this is the case we have another bug in _start.go_. We might have to unset all Docker related variables prior to bootstrapping to avoid this.

**Comment by cmoulliard** [comment] 2017-01-16 11:34
I can create minishift (using local build) with the minihistf centos iso 

```
dabou-macosx:~/MyApplications/go-wks/bin$ ./minishift start --iso-url=file:///Users/chmoulli/Temp/_centos7/centos-minishift.iso --memory=1000 --openshift-version=v1.4.0-rc1 --vm-driver=virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
 21.26 MB / 21.26 MB [====================================================================================================================================================================================================================================] 100.00% 0
Provisioning OpenShift via '/Users/chmoulli/.minishift/cache/oc/v1.4.0-rc1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.0-rc1 image ... 
   Pulling image openshift/origin:v1.4.0-rc1
   Pulled 0/3 layers, 3% complete
   Pulled 0/3 layers, 62% complete
   Pulled 1/3 layers, 72% complete
   Pulled 2/3 layers, 89% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.99.100 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.100:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

**Comment by praveenkumar** [comment] 2017-01-16 13:11
@cmoulliard Great to know local build worked for you. Even you can try latest released version and that also works as it did for your local build. I tried to explain why you get that error.

**Comment by budhrg** [comment] 2017-01-30 11:18
@cmoulliard , I am closing this issue as we are not able to reproduce it. Also checked with v1.0.0-beta.3

Feel free to reopen it when you came across with this issue.

**Closed by budhrg** 2017-01-30 11:18 UTC
Labels: kind/bug, priority/critical
