### ISSUE TITLE
Deleting a profile that doesn't exist will install default add-ons

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1411] opened 2017-09-19 08:45 UTC
```powershell
PS > C:\work\src\github.com\minishift\minishift\out\windows-amd64\minishift.exe delete --profile undefined
-- Installing default add-ons ... OK
Running this command requires an existing 'undefined' VM, but no VM is defined.
```

```powershell
PS > dir C:\Users\gbraad\.minishift\profiles\

    Directory: C:\Users\gbraad\.minishift\profiles

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        19-Sep-17     16:42                default
d-----        19-Sep-17     14:32                test2
d-----        19-Sep-17     14:46                test3
d-----        19-Sep-17     16:43                undefined

PS > dir C:\Users\gbraad\.minishift\profiles\undefined\

    Directory: C:\Users\gbraad\.minishift\profiles\undefined

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        19-Sep-17     16:43                addons
d-----        19-Sep-17     16:43                cache
d-----        19-Sep-17     16:43                certs
d-----        19-Sep-17     16:43                config
d-----        19-Sep-17     16:43                logs
d-----        19-Sep-17     16:43                machines
d-----        19-Sep-17     16:43                tmp

PS > dir C:\Users\gbraad\.minishift\profiles\undefined\addons\

    Directory: C:\Users\gbraad\.minishift\profiles\undefined\addons

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        19-Sep-17     16:43                admin-user
d-----        19-Sep-17     16:43                anyuid
d-----        19-Sep-17     16:43                registry-route
d-----        19-Sep-17     16:43                xpaas
```

**Comment by gbraad** [comment] 2017-09-19 08:47
```
PS > dir C:\Users\gbraad\.minishift\profiles\

    Directory: C:\Users\gbraad\.minishift\profiles

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        19-Sep-17     16:42                default
d-----        19-Sep-17     14:32                test2
d-----        19-Sep-17     14:46                test3
d-----        19-Sep-17     16:43                undefined

PS > dir C:\Users\gbraad\.minishift\profiles\undefined\

    Directory: C:\Users\gbraad\.minishift\profiles\undefined

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        19-Sep-17     16:43                addons
d-----        19-Sep-17     16:43                cache
d-----        19-Sep-17     16:43                certs
d-----        19-Sep-17     16:43                config
d-----        19-Sep-17     16:43                logs
d-----        19-Sep-17     16:43                machines
d-----        19-Sep-17     16:43                tmp

PS > dir C:\Users\gbraad\.minishift\profiles\undefined\addons\

    Directory: C:\Users\gbraad\.minishift\profiles\undefined\addons

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        19-Sep-17     16:43                admin-user
d-----        19-Sep-17     16:43                anyuid
d-----        19-Sep-17     16:43                registry-route
d-----        19-Sep-17     16:43                xpaas
```

**Comment by agajdosi** [comment] 2017-09-19 10:17
I have this question in my mind for few weeks: if all addons are not enabled and thus have no effect on minishift, wouldn't it be better to leave their installation just for `minishift addons install --default`? Maybe it would be more clear and explicit than automatic installation "here or there".

**Comment by gbraad** [comment] 2017-09-19 10:25
Installation of add-ons now happen as a side-effect of a command, and this is in my opinion not good. It breaks expectation, as we also have seen with @amitkrout and the integration tests.

The install should ONLY run on an explicit `m addons` call, or as part of `m start`.

**Comment by LalatenduMohanty** [comment] 2017-09-19 13:01
This is a duplicate of https://github.com/minishift/minishift/issues/1342. Because installing add-ons currently happens for all commands if the add-ons directory does not exist. once #1342 is fixed you will not see this.

**Comment by LalatenduMohanty** [comment] 2017-09-19 13:03
@gbraad  We can close this issue as this is issue about installing default add-ons for the delete command. Let me know if you differ on this

**Comment by gbraad** [comment] 2017-09-20 04:13
In this case it should track the installation of the add-ons related to add-ons. This report differs from the original report as it discusses the relation with new functionality.

For testing purposes (manual and test case creation) I advise this to be remain open or specifically described in the original report.

**Comment by LalatenduMohanty** [comment] 2017-10-09 13:58
Tested this again and this is fixed now. 
```
$ minishift profile list
- minishift	Running	(active)
- test		Does Not Exist

$ minishift delete --profile undefined
Running this command requires an existing 'undefined' VM, but no VM is defined.
```

**Closed by LalatenduMohanty** 2017-10-09 13:58 UTC
Labels: component/profiles, kind/bug, priority/major, resolution/duplicate
