### ISSUE TITLE
Minishift with enabled addons failes to set profile

### ISSUE THREAD

**Issue by rhnewtron** [minishift/minishift#2665] opened 2018-08-04 20:00 UTC
### General information

  * Minishift version: minishift v1.22.0+7163416
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Start minishift with a custom profile name
  2. Enable and install addons
  3. Stop Minishift
  4. Start again

### Expected

* addons are executed on every run

### Actual

* addons are only executed on first run, then an error is printed:

```
Could not set oc CLI context for 'minishift-virtualbox-default' profile: Error during setting 'minishift-virtualbox-default' as active profile: The specified path to oc '' does not exist
```

### Logs

```
Profile 'minishift-virtualbox-default' set as active profile.
Default add-ons 'anyuid, admin-user, xpaas, registry-route' installed
Add-on 'admin-user' is already disabled.
Starting Minishift with virtualbox
-- Starting profile 'minishift-virtualbox-default'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ................................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 8% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ............
Deleted existing OpenShift container
Using nsenter mounter for OpenShift volumes
Using public hostname IP 172.30.168.100 as the host IP
Using 172.30.168.100 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://172.30.168.100:8443


Could not set oc CLI context for 'minishift-virtualbox-default' profile: Error during setting 'minishift-virtualbox-default' as active profile: The specified path to oc '' does not exis
```

**Comment by praveenkumar** [comment] 2018-08-20 06:45
This is fixed and was same as https://github.com/minishift/minishift/issues/2679 one.

@rhnewtron Can you verify once with below artifacts?

- http://artifacts.ci.centos.org/minishift/minishift/pr/2704/

**Comment by szEvEz** [comment] 2018-08-22 12:00
Using the artifact provided by @praveenkumar solved this issue:

I've executed the following steps
1. Started minishift with a custom profile name
2. Enabled an addon
3. Stopped Minishift
4. Started Minishift

Add-ons are now executed on every run - the error message ` Could not set oc CLI context for 'minishift-virtualbox-default' profile: Error during setting 'minishift-virtualbox-default' as active profile: The specified path to oc '' does not exist` is gone 

Thanks!

**Comment by LalatenduMohanty** [comment] 2018-08-22 19:34
Duplicate of #2679

**Closed by LalatenduMohanty** 2018-08-22 19:34 UTC
Labels: component/profile, kind/bug, priority/major
