### ISSUE TITLE
PHP S2I Not Working

### ISSUE THREAD

**Issue by johnfosborneiii** [minishift/minishift#242] opened 2017-01-02 18:34 UTC
Whenever I run any source to image with PHP 5.5 or 5.6 from the service catalog the build works fine but then after it is deployed it immediately exists and restart in a loop. The logs from the pod show:
Permission denied: AH00058: Error retrieving pid file /opt/rh/httpd24/root/var/run/httpd/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

I've tried several different source code repositories. S2I works fine for other languages that I have tried (NodeJS, Python, Ruby). It seems like there is a possible permissions problem with the Red Hat base images and minishift.

**Comment by praveenkumar** [comment] 2017-01-03 05:07
@johnfosborneiii Thanks for trying out minishift, Can you put some steps with required source links which you tried and faced this issue? Also which imagestream you used (for minishift we currently use imagestream based on centos).

**Comment by johnfosborneiii** [comment] 2017-01-03 22:06
After I run minishift start I login as developer/developer through the OpenShift Console. I then click on My Project -> Add to Project -> PHP 5.6 latest builder image and I put in the following for the GitHub Repository https://github.com/VeerMuchandi/ab-deploy -> Create. It builds and deploys fine, but the container that gets deployed immediately exits and restarts in a loop. Each time the log throws the error message above. This code repository works fine with other instances of OCP. I have also tried other PHP code bases and those do not work either. All of the other builder images / templates seem to work fine for me.

**Comment by hferentschik** [comment] 2017-01-04 10:29
@johnfosborneiii, I cannot reproduce this. I followed your steps and used the PHP 5.6 builder image with the sources from https://github.com/VeerMuchandi/ab-deploy. The app built just fine. When I then accessed the URL of the app - http://test-myproject.192.168.99.100.xip.io/ I got:

     I am VERSION 2 
     My Pod IP is : 172.17.0.5

I believe this is the expected behavior. Can you reproduce this starting from scratch? 

Last but not least, in case you can re-produce this, I don't believe it is an Minishift issue. It would most likely be an issue with the s2i image or the image stream imported via _cluster up_. minishift currently does not change any default imagestreams, templates, etc. It purely delegates provisioning of OpenShift to 'oc cluster up'. Have you checked the OpenShift issue tracker? 

I am going to close this issue, but feel  free to add additional information or resolution of the problem.

**Closed by hferentschik** 2017-01-04 10:29 UTC
Labels: bug
