### ISSUE TITLE
Pods unable to write to persistent volumes 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#856] opened 2017-05-03 11:37 UTC
Pods which make a persistent volume claim, cannot write to their assigned persistent volume.

Internally we rely on the 100 persistent volumes created by _cluster up_. In our case we set _host-pv_dir_ to _/var/lib/minishift/openshift.local.pv_. After provisioning is complete the created persistent volume directories have the following permissions:

    $ minishift ssh -- "sudo ls -la /var/lib/minishift/openshift.local.pv"
    drwxrwx---    2 root     root          4096 May  3 11:31 pv0001
    ...

When a persistent volume claim is made, the pod then cannot write to this directory (tested with MariaDB, MongoDB, Jenkins, etc).

One can get around this problem by running the following command after Minishfift started:

    $ minishift ssh -- "sudo chmod -R o+rwx /var/lib/minishift/openshift.local.pv/pv*"

Not sure what the proper permissions should be, but this works.

See also https://issues.jboss.org/projects/CDK/issues/CDK-120

**Comment by hferentschik** [comment] 2017-05-03 11:40
Not sure whether this is a 'cluster up' issue only or whether there is something else we should do on the Minishift side when using _host-pv_dir_. 

Not sure how to work around this for now either, since the persistent volumes are created in the background. We cannot just issue a _chmod_ command after _cluster up_ returns.

**Comment by hferentschik** [comment] 2017-05-03 11:42
@csrwng any insight on this? Is this a 'cluster up' issue or is there something we are missing or should be doing on the Minishift side?

Also, any idea on how we could at least temporarily work around this?

**Comment by budhrg** [comment] 2017-05-03 14:41
I was trying `oc cluster up` to see if it issue with it or not but seems like my setup is having some issue.
Keep getting message even setting the insecure registry in  `/etc/sysconfig/docker`
```
$ oc cluster up --host-pv-dir /var/lib/minishift/openshift.local.pv
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... 
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0 image ... OK
-- Checking Docker daemon configuration ... FAIL
   Error: did not detect an --insecure-registry argument on the Docker daemon
   Solution:

     Ensure that the Docker daemon is running with the following argument:
     	--insecure-registry 172.30.0.0/16

```

**Comment by csrwng** [comment] 2017-05-03 17:16
@hferentschik I'm not sure what's going on. We specifically don't make the directories world writeable. However, because the default user group is 0, then usually pods can write to those directories. I will test locally with v1.5.0 and see if I can reproduce. Is it happening with any pod/image?

**Comment by csrwng** [comment] 2017-05-03 17:33
I cannot reproduce with 'oc cluster up' v1.5.0 running directly on my Mac, will try with minishift 1.0.

**Comment by csrwng** [comment] 2017-05-03 17:51
Trying a new install of minishift, I get this error starting up... is there a way to get around it?
```
Starting local OpenShift cluster using 'xhyve' hypervisor...
Error starting the cluster:  Error attempting to download and cache oc: Cannot get the OpenShift release version v1.5.0: GET https://api.github.com/repos/openshift/origin/releases/tags/v1.5.0: 403 API rate limit exceeded for x.x.x.x (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 34m2.8156134s
```

**Comment by hferentschik** [comment] 2017-05-03 17:55
> Error starting the cluster:  Error attempting to download and cache oc: Cannot get the OpenShift release version v1.5.0: GET https://api.github.com/repos/openshift/origin/releases/tags/v1.5.0: 403 API rate limit exceeded for x.x.x.x (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 34m2.8156134s

My guess is you are somewhere in a network where several people download Minishift right now (which is good :-)). GitHub has this rate limit based on IP. Provided enough people are on the same LAN, all of them will be seen from the outside as the same IP.

**Comment by hferentschik** [comment] 2017-05-03 18:26
@budhrg The message is expected. You do need to specify the insecure registry. So depending on what docker daemon you are running you need to make sure the insecure registry is configured. I am using docker-machine in which case I need to specify  --engine-insecure-registry:

docker-machine create --driver virtualbox --engine-insecure-registry 172.30.0.0/16 cluster

**Comment by hferentschik** [comment] 2017-05-03 18:53
> We specifically don't make the directories world writeable.

Really? I am a bit surprised.

> However, because the default user group is 0,

What do you mean with "default user group is 0"? So per default OpenShift expect an image to run as root (user id 0), right? Are you saying that even if the user where to specify a different user id via the _USER_ directive, the use group would still be 0 and it should still work (based on group permissions)? 

What if users configure _anyuid_:

    $ oc adm policy add-scc-to-group anyuid system:authenticated

We are trying to push this as a default for Minishift, allowing the user to run many of the popular images out there which would otherwise not run on OpenShift. Would you not latest in this case need other file permissions on these persistent volume directories?

I think there might be a major problem with the persistent volumes provided by cluster up.

> Is it happening with any pod/image?

Any from the default templates which makes a persistent volume claim.

**Comment by hferentschik** [comment] 2017-05-03 18:57
@csrwng, for what its worth,  I seem to be seeing the same issue when using _cluster up_ directly on a docker-machine provisioned VM:

    $ oc cluster up --host-pv-dir /mnt/sda1/pv

The persistence volume directories get created ok, but even though in the web console I can see that a volume is assigned, no data ever appears. 

I tried with Mariadb Persistent  as well as  Mongodb Persistent,

**Comment by hferentschik** [comment] 2017-05-03 19:13
Looking at https://developers.redhat.com/blog/2017/04/07/adding-persistent-storage-to-the-container-development-kit-3-0/ (referenced in CDK-120), this seems to be the better approach (in terms of setup and permissions for the hostfolder persistent volumes. 

Maybe we need to re-visit the idea of creating persistent volumes via an add-on again. The rub there is that some of the requires commands might be ISO dependent.

**Comment by LalatenduMohanty** [comment] 2017-05-03 21:56
@hferentschik @csrwng Minishift code might be responsible for this as we create the directories with sudo ( I had written the code but I do not remember why I used sudo) where as `cluster up` does not use sudo to create the directories. 

[1] https://github.com/minishift/minishift/blob/master/pkg/minishift/clusterup/dockerhost.go#L33
[2] https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/host/host.go#L19-L23

**Comment by LalatenduMohanty** [comment] 2017-05-03 22:00
@hferentschik ahh I did not see your comment https://github.com/minishift/minishift/issues/856#issuecomment-299003447 before. I would still findout if we really need sudo to create these directories in Minishift

**Comment by LalatenduMohanty** [comment] 2017-05-03 22:32
> I would still findout if we really need sudo to create these directories in Minishift

We need sudo to create these directories  as `host.RunSSHCommand` runs as an user.  I guess the directories need access permission so that the docker process in the VM should be able to write in these directories.

**Comment by hferentschik** [comment] 2017-05-04 07:57
>  I guess the directories need access permission

The directories we create are the smaller problem. The actual pvxxxx directories are still created by _cluster up_. I am looking at a different approach.

**Comment by agajdosi** [comment] 2017-05-04 08:28
@csrwng Quick solution is to manually download oc binary and place it into ~/.minishift/cache/oc/v1.5.0/. Then minishift will skip the download.

**Comment by hferentschik** [comment] 2017-05-04 10:49
@csrwng, I'd like to create a few 'cluser up' issues, related to this. Is there a label or something I should apply or just add them to https://github.com/openshift/origin/issues? How does one filter _cluster up_ issues.

Here is what I am thinking atm:
* Persistent volume creation should not occur in the background. This is really unexpected imo and makes it really hard to know when OpenShift is fully provisioned. I'd rather have less persistent volumes instead. IMO 10 would be plenty in which case there should be no need to create the directories in the background 
* Have an option do skip the creation. Users might want to setup different persistent volumes, maybe even a different type. Within Minishift I can also use add-ons to create the volumes. I have the code ready for this. However, since the _cluster up_ persistent volumes get created regardless, I would need to delete this persistence volumes first 
* Potentially have an option to specify the number of persistent volumes to be created
* Now my favorite one, use a hostPath persistent volume provisioner. This would solve pretty much all problems. The provisioner would dynamically create directories and there is no need to have a fixed pre-existing count. Have you looked into this before?

**Comment by csrwng** [comment] 2017-05-04 13:45
@hferentschik I have no objection to the changes proposed. Simply creating issues with cluster up in the subject should be redirected appropriately. I will definitely take a look at these as soon as I get back. 

The reason that hostpath dynamic provisioning didn't work for us is that it doesn't set the right SELinux context (as it exists today in Kube).

**Comment by csrwng** [comment] 2017-05-04 13:47
It would be nice if kube would allow invoking an external dynamic provisioner, which is something else that maybe we should look at.

**Comment by hferentschik** [comment] 2017-05-04 15:05
> Simply creating issues with cluster up in the subject should be redirected appropriately.

Ok, will do

>  I will definitely take a look at these as soon as I get back.

Thanks

**Comment by hferentschik** [comment] 2017-05-04 15:10
> The reason that hostpath dynamic provisioning didn't work for us is that it doesn't set the right SELinux context (as it exists today in Kube).

So there is a built-in one already. I was under the impression one needs to provide the provisioner as described here - https://dzone.com/articles/dynamically-provisioning-hostpath-based-volumes-on

So I was thinking we could create a new repo which creates the image as described at the dzone article. This way we would have control what this provisioner does as well. Maybe I'm wrong.

> It would be nice if kube would allow invoking an external dynamic provisioner,

what's a "external dynamic provisioner" and how does it differ from the approach from the article?

**Comment by hferentschik** [comment] 2017-05-04 19:18
*  Persistent volume creation should not occur in the background - https://github.com/openshift/origin/issues/14060
* Have an option do skip the creation - https://github.com/openshift/origin/issues/14061
* Implement hostPath provisioner - https://github.com/openshift/origin/issues/14062

@csrwng here we go :-)

**Comment by hferentschik** [comment] 2017-05-04 19:40
> I cannot reproduce with 'oc cluster up' v1.5.0 running directly on my Mac, will try with minishift 1.0.

How do you use Docker? Docker for Mac? I am using docker-machine and when I create a new machine and run plain 'cluster up' (not even specifying a custom directory), I don't get the DB pod to start. I am also using oc 1.5.0.

**Comment by hferentschik** [comment] 2017-05-04 19:48
So looking at the running MariaDB pod, using the patch from pull request #859, I see the following permissions for _/var/lib/mysql/data_:

     drwxrwxrwx  6 root  root  4096 May  4 19:30 data

This is pretty much what I would expect. The user running the db process is the mysql user with the user id 27. Extract from _/etc/passwd_:

    root:x:0:0:root:/root:/bin/bash
    mysql:x:27:27:MySQL Server:/var/lib/mysql:/sbin/nologin

So root has as expected the user id 0 and mysql 27. Looking at this I fully understand why I needed to make the directory world writable. How can it even work any other way?

BTW, the used image is _mariadb-101-centos7_ - https://hub.docker.com/r/centos/mariadb-101-centos7/

**Comment by hferentschik** [comment] 2017-05-04 19:50
@praveenkumar when you run _cluster up_ on a native Linux Docker daemon, what permissions are you ending up with for _/var/lib/mysql/data_?

**Comment by LalatenduMohanty** [comment] 2017-05-04 20:21
@hferentschik I am able to run MariaDB on Minishift 1.0.0 without any issue.  Here is the screenshots. 

<img width="632" alt="screen shot 2017-05-04 at 4 18 29 pm" src="https://cloud.githubusercontent.com/assets/3125299/25723342/a1ce06c6-30e5-11e7-9da1-65a74b997e4b.png">
<img width="1278" alt="screen shot 2017-05-04 at 4 18 51 pm" src="https://cloud.githubusercontent.com/assets/3125299/25723345/a46bc918-30e5-11e7-93fc-6e0e3ef438d4.png">

**Comment by praveenkumar** [comment] 2017-05-05 04:47
>when you run cluster up on a native Linux Docker daemon, what permissions are you ending up with for /var/lib/mysql/data?

```
$ ./oc rsh mariadb-1-cccnk
sh-4.2$ ls -l /var/lib/mysql/
total 0
drwxrwx---. 6 root       root 241 May  5 03:56 data
srwxrwxrwx. 1 1000040000 root   0 May  5 03:56 mysql.sock
sh-4.2$ cat /etc/passwd
[..]
root:x:0:0:root:/root:/bin/bash
mysql:x:27:27:MySQL Server:/var/lib/mysql:/sbin/nologin
```

**Comment by hferentschik** [comment] 2017-05-05 07:31
> I am able to run MariaDB on Minishift 1.0.0 on OS X without any issue. 

And you are sure you are using 1.0.0? Which ISO are you using?

I can reproduce this at will. I can also show that the moment I change the permissions the pod comes up. I see the exact same behaviour as described in CDK-120.

Maybe to start with checking who sees the problem. @praveenkumar, @budhrg, @amitkrout, @gbraad - can you test master out of the box and start "MariaDB persistent"

**Comment by hferentschik** [comment] 2017-05-05 08:35
@praveenkumar 

    drwxrwx---. 6 root       root 241 May  5 03:56 data

So how does this even work? Owner and group are root. How can _mysql_ user write to this directory? I take it you checked that the underlying persistent volume directory contains the database files?

**Comment by budhrg** [comment] 2017-05-05 09:22
I am also able to deploy MariaDB persistent with binary compiled from master branch. 
Note, I just did
```
$ git fetch upstream
$ git rebase upstream/master master
$ make
$ minishift start

## Deploy MariaDB Persistent from UI
```
![screenshot from 2017-05-05 14-50-40](https://cloud.githubusercontent.com/assets/1132451/25740028/54eacb42-31a2-11e7-893a-dff9a76dad94.png)

**Comment by hferentschik** [comment] 2017-05-05 09:27
> I am also able to deploy MariaDB persistent with binary compiled from master branch.

Which OS and driver?

**Comment by budhrg** [comment] 2017-05-05 09:35
> Which OS and driver?

Linux with KVM. 

Also, dancer + mysql persistent storage is working fine.
![screenshot from 2017-05-05 15-05-12](https://cloud.githubusercontent.com/assets/1132451/25740476/51ac2a82-31a4-11e7-8f26-ef8c80089b5c.png)

**Comment by gbraad** [comment] 2017-05-05 10:26
| Reporter | ISO Variant | Working | Hypervisor |
| --------- | ------------- | --------- | ------------ |
|    |    |    |    |

**Comment by hferentschik** [comment] 2017-05-05 12:24
@csrwng maybe you can help me out and explain to me how this is even working. So assuming I stick with the permissions as created per default by _cluster up_,  I end up with:

    drwxrwx---. 6 root       root 241 May  5 03:56 data

for _/var/lib/mysql/data_. So how can the mysql process even write data to this directory, assuming it runs as _mysql_ user?

**Comment by csrwng** [comment] 2017-05-05 12:48
@hferentschik the reason it works is that it doesn't run as the mysql user. Normally openshift will assign a random user to the pod whose group is 0. Now, it's a different story if you have anyuid scc enabled.

**Comment by gbraad** [comment] 2017-05-05 12:53
yes, it seems `anyuid` is enabled when it fails

**Comment by csrwng** [comment] 2017-05-05 12:54
@gbraad is that default for minishift?

**Comment by hferentschik** [comment] 2017-05-05 12:54
>  the reason it works is that it doesn't run as the mysql user. Normally openshift will assign a random user to the pod whose group is 0.

Got you. In fact we were just discussing that. IMO this is super confusing, especially since it is not transparent at all (looking at the pod for example). 

> Now, it's a different story if you have anyuid scc enabled.

Turns out, I had the Minishift anyuid add-on enabled - https://github.com/minishift/minishift/blob/master/addons/anyuid/anyuid.addon, so that was the reason it was failing for me.

For many people it is very important to be able to run with _anyuid_. It is an important feature of Minishift. For these users who enable _anyuid_, persistent volumes won't work unless we adjust the permissions. 

@csrwng what are your concerns to make the persistent volumes world writable? This way they can be used out of the box w/ or w/o anyuid.

**Comment by gbraad** [comment] 2017-05-05 12:56
@csrwng No, I just got told this was the case for CDK... It was just something I thought of when hardy posted the permissions again... it would be different if the container can escalate privilege to root (when anyuid) is used.

**Comment by csrwng** [comment] 2017-05-05 13:00
@hferentschik you can read some of the discussion in this issue: https://github.com/openshift/origin/issues/13496

One of the use cases for cluster up is running directly on your linux box, and it's likely not a good thing to make any directory on your linux box world writeable without you explicitly allowing it. The case of minishift is different because it's self-contained and less likely to be exposed to the outside world. Maybe we should detect what permissions to use by default based on either an argument, env var, or other.

**Comment by hferentschik** [comment] 2017-05-05 13:03
I really dislike the magic behind this. For all one knows and sees poking around in the db pod, it should not work, but still it does. There must be heaps of people running into this :-(

Either way, several options:

* _cluster up_ creates the persistent volumes world writeable to cater for anyuid (I think this makes sense regardless, but it might not help right now for the upcoming CDK release)
* We apply the patch #859 and effectively change the directory permissions in all cases (potential downside is additional startup times, since we need to wait until all persistent volume directories are created)
* We modify #859, and extract the commands into the anyuid add-on. In this case the permissions only get changed when the anyuid add-on is installed and enabled
* Leave things as is and make it a documentation issue

**Comment by csrwng** [comment] 2017-05-05 13:06
@hferentschik this will likely be the default in a production openshift environment though (not having anyuid). It may be misleading for someone to develop their app locally relying on the anyuid scc and then discovering that it won't run on a cloud deployment.

**Comment by hferentschik** [comment] 2017-05-05 13:06
> One of the use cases for cluster up is running directly on your linux box, and it's likely not a good thing to make any directory on your linux box world writeable without you explicitly allowing it

Not sure, these are very specific directories. Personally I would not mind, especially since running w/ anyuid is important to me.

> Maybe we should detect what permissions to use by default based on either an argument, env var, or other.

If changing the permissions per default is not an option, then some sort of config should work

**Comment by budhrg** [comment] 2017-05-05 13:07
> We modify #859, and extract the commands into the anyuid add-on. In this case the permissions only get changed when the anyuid add-on is installed and enabled

My vote goes to this one. If we enable anyuid, let's add the solution to its side-effects too.

**Comment by gbraad** [comment] 2017-05-05 13:11
I believe enabling `anyuid` is bad practice, and shouldn't be considered unless there is no other way. this is not an add-on to enable by default. but yes, if enabled, we might have to do something with the permissions and in this case the earlier suggestions seems the most viable option without causing too much collateral damage

**Comment by hferentschik** [comment] 2017-05-05 13:20
@gbraad I switched sides on this multiple times and atm are somewhere caught in the middle. For the CDK we got explicitly asked to enable anyuid. People want to try any off image with OpenShift and hit this problem directly. The fear is that they walk away. Before we enabled anyuid silently, not at least there is some feedback via the _anyuid_ addon application (which we should improve btw). Using add-ons it became more transparent, but it is of course still questionable on whether we should enable it per default. 

I think the idea is, if a user does not get the image to run from the beginning, he might just walk away. Of he, however, gets it running and is able to evaluate things, he has more invested. By the time he then wants to push to an environment where anyuid is not enabled, he has either learned enough to understand what's going or he needs to figure it out then. At this stage he won't as easily walk away soon.

@gbraad check openshift/origin#13496, this is actually exactly our issue and the discussion here is very similar.

**Comment by hferentschik** [comment] 2017-05-05 13:23
> My vote goes to this one. If we enable anyuid, let's add the solution to its side-effects too.

@budhrg @csrwng, there is a rub with pulling this into the add-on. In the add-on we can deal with the default location of the persistent volumes. If someone uses the _host-pv-dir_ option, the add-on approach will fail. The way the patch is applied now, it will work regardless.

**Comment by gbraad** [comment] 2017-05-05 13:36
@hferentschik will check. I am also not convinced yet, but more towards accepting non-root usage. especially due to OpenShift Online working this way...

**Comment by gbraad** [comment] 2017-05-05 13:37
@hferentschik I do not like to patch that much. I know why we do it this way, but it is something that needs a lifecycle and consideration of removal (when a fix is available).

**Comment by stevekuznetsov** [comment] 2017-05-05 13:44
> specially due to OpenShift Online working this way...

@gbraad I'm not sure any of the Online clusters are using the `AnyUID` security context constraint by default. Which ones are you seeing that on?

**Comment by gbraad** [comment] 2017-05-05 13:46
@stevekuznetsov I referred to "non-root" usage (especially OSO working this way)

**Comment by stevekuznetsov** [comment] 2017-05-05 13:47
@gbraad oh, sorry - I read your comment the opposite of what you meant!

**Comment by hferentschik** [comment] 2017-05-05 14:30
>  I do not like to patch that much.

Not me either. :-)

**Comment by hferentschik** [comment] 2017-05-05 14:33
After some more contemplating, I think that pull request #859 is the best path forward for now. Using add-ons, we would not be able to handle the _host-pv-dir_ option properly and by making it part of start.go, it will be easier to remove once @csrwng implements https://github.com/openshift/origin/issues/14076 ;-)

**Comment by gbraad** [comment] 2017-05-05 14:36
@hferentschik agree, but we are responsible for setting `--host-pv-dir` anyways.

**Comment by hferentschik** [comment] 2017-05-05 14:47
> but we are responsible for setting --host-pv-dir anyways.

It's an option you can change yourself. We just provide a default which suits our ISO. You can also use this options to get your persistent volumes out to the host.

**Comment by jorgemoralespou** [comment] 2017-05-06 07:37
@hferentschik even though we have anyuid active by default in the wrapper, I'm starting to think that developers should be aware of the constraint and relieve it on demand (I agree with @gbraad). I'm thinking that maybe making the existence easier for this can help by introducing an additional command:
"oc-cluster allow-root <project|sa>"

This will prevent them from but understanding does as they move their applications to other environments while also provides an easy way to circumvent.

Not optimal though.

**Comment by hferentschik** [comment] 2017-05-06 19:15
>  I'm thinking that maybe making the existence easier for this can help by introducing an additional command

For the pull request related to the issue, I added some echo statements to the anyuid add-on which add much more transparency imo. I am hoping this helps a bit. 

I am not disagreeing @jorgemoralespou or @gbraad, I also feel it is partly dangerous to enable it per default. However, I myself ran in fact multiple times into  the anyuid issue. Unfortunately, interpreting the underlying issue is hard (maybe OpenShift could do something there) and if I have existing images you will have to make modifications first to get them to run. How you do this in imo not at all highlighted and easy to find. 

From a CDK point of view we have enabled anyuid since CDK 2.x and for quite some time in CDK 3.x. I feel making a last minute change like this is not such a good idea either.

**Comment by jorgemoralespou** [comment] 2017-05-06 19:39
@hferentschik on the other hand having anyuid assigned to
system:authenticated means that every user will have it, and it's much more
difficult to remove that permission for a specific application.
I think this should be enabled per namespace at most, but better or service
account since eventually these Allison's will not run in a clustered/secure
environment.
Maybe we should ask the openshift UI/CLI should provide better feedback,
although it already provided some.

**Comment by jorgemoralespou** [comment] 2017-05-06 19:41
In any case one can disable the anyuid add-on. Then we would still require
easier experience to allow anyuid or user/namespace.

**Comment by gbraad** [comment] 2017-05-07 03:51
The information on how to run an image with a non-root user is captured in the topic: https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines "Support Arbitrary User IDs". Using `anyuid` is as bad as `setenforce 0` to me. It is also not an unknown, and is actually something we need to enforce... just like this answer explains well: http://stackoverflow.com/questions/37723401/how-do-you-run-an-openshift-docker-container-as-something-besides-root The containers fail with a clear error message that root usage is not allowed. What else could we do?

Note: this is related to using Docker as the container runtime. What about CRI-o ?

**Comment by LalatenduMohanty** [comment] 2017-05-08 06:56
@hferentschik @gbraad I think we should rethink about  enabling anyuid in CDK by default. 

We need to solve two issues.
1.  We need to enable anyuid scc to help users/developers get started with OpenShift. In the process we should educate developers that this is not something they will get in OpenShift Online or in a proper OpenShift setup. 

2. Enable use of Minishift as staging setup for a proper OpenShift setup i.e. application developed on Minishift should be able to deployed on OpenShift online or similar.  

I am not sure at this moment how to handle this two use case (specially the second point), but this is something we need to fix.

**Comment by gbraad** [comment] 2017-05-08 07:13
@LalatenduMohanty at the moment it feels like these two are not mutually exclusive. If we choose 1, we have issues with 2... and the other way around, unless we find a proper way to indicate to the user what is happening. At the moment I am missing a needed output, such as:

    -- Setting anyuid to allow root usage for containers

or whatever. At the moment it is happing automagically, and this leads to more confusion (as can be seen in this issue). As @GrahamDumpleton mentions in comment: https://github.com/openshift/origin/issues/13496#issuecomment-299622659 we have to deal with a "StackOverflow generation" where people are not spending time to learn something/fix the actually issue.

Ideally, we could have something to automate by layering `nss_wrapper` and a `su - user -c $CMD` on top of the image ;-) *dreaming*

**Comment by gbraad** [comment] 2017-05-08 07:15
However, why not at least restrict to `myproject`?

```
$ oc adm policy add-scc-to-user anyuid -z default -n myproject
```

or at least some other project that is more clear in naming it allows root: `myproject-anyuid` ? WDYT?

**Comment by hferentschik** [comment] 2017-05-08 07:27
> At the moment I am missing a needed output, such as:

I think especially with the updated pull request, the message it quite clear with pointers on where to find more information.

**Comment by hferentschik** [comment] 2017-05-08 08:07
> The containers fail with a clear error message that root usage is not allowed.

How is this error message clear? IMO it does not at all help to resolve the issue. And it is not only about running as root, containers also fail when running as non root, but not set up to be able to run under a random uid. Not running as root I get and this is also a recommendation for containers in general, but OpenShift goes a step further.

**Comment by hferentschik** [comment] 2017-05-08 08:16
> Using anyuid is as bad as setenforce 0 to me

Not so sure, I get the additional security you get by assigning a from a range of pre-allocated uid, but it also makes it then hard to reason about the system. Even though I knew about this, I still was initially confused on why  MariaDB was not working. If you connect to a running pod and check permissions and processes, you actually wonder how this works at all. It works because of this - https://github.com/CentOS/CentOS-Dockerfiles/blob/master/mariadb/centos7/fix-permissions.sh - which is imo neither transparent nor easy to understand.

**Comment by GrahamDumpleton** [comment] 2017-05-08 08:28
And that ``fix-permissions`` script is duplicated in various images and done differently. For a discussion of ``fix-permissions`` and various problems, worth reading:

* https://github.com/sclorg/s2i-base-container/issues/112
* https://github.com/sclorg/s2i-python-container/issues/178

**Comment by gbraad** [comment] 2017-05-08 08:50
@hferentschik the report about output is pre-patch/pre-hange (as this let to the current late discovery of the root cause)

**Comment by budhrg** [comment] 2017-05-09 09:39
Resolved via https://github.com/minishift/minishift/pull/859

**Closed by budhrg** 2017-05-09 09:39 UTC
Labels: kind/bug, priority/critical

**Comment by gbraad** [comment] 2017-10-24 14:50
Please, also have a look at https://github.com/openshift/origin/pull/16631 as this is the proposed solution from OpenShift. With a marker file we can prevent the creation of the PVs.
