### ISSUE TITLE
admin-user addon fails if admin user exists on apply

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1919] opened 2018-01-18 10:20 UTC
### General information

  * Minishift version: 1.11
  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. minishift start
  2. minishift login -u admin -p admin
  3. minishift addon apply admin-user
  4. ERROR
![image](https://user-images.githubusercontent.com/78350/35092976-3f8bd128-fc41-11e7-90a2-7584f37bc689.png)

### Expected
Addon applied succesfully

### Actual
Addon is not applied

### Qualification
The addons need to be idempotent, so there needs to be a feature when writing addons that ignores a failure on a command error. I think I already requested this.

e.g.

```
oc create user admin --full-name=admin
```
Will fail on error

```
!oc create user admin --full-name=admin
```

Will not fail on error, and continue.

cc/  @LalatenduMohanty @hferentschik

**Comment by praveenkumar** [comment] 2018-01-19 08:33
#1130

**Comment by elyscape** [comment] 2018-01-30 23:24
Another related issue is that `minishift addon remove admin-user` doesn't fully work. It removes the User object but not the Identity object that is created if you log in as that user, resulting in the following:
```shellsession
scapeless:~ elyscape$ minishift addons apply admin-user
-- Applying addon 'admin-user':..

scapeless:~ elyscape$ oc get user admin
NAME      UID                                    FULL NAME   IDENTITIES
admin     df65bdfe-060c-11e8-9aad-8e64ce944971   admin       
scapeless:~ elyscape$ oc login -u admin
Authentication required for https://192.168.64.9:8443 (openshift)
Username: admin
Password: 
Login successful.

scapeless:~ elyscape$ oc get user admin
NAME      UID                                    FULL NAME   IDENTITIES
admin     df65bdfe-060c-11e8-9aad-8e64ce944971   admin       anypassword:admin
scapeless:~ elyscape$ oc get identity anypassword:admin
NAME                IDP NAME      IDP USER NAME   USER NAME   USER UID
anypassword:admin   anypassword   admin           admin       df65bdfe-060c-11e8-9aad-8e64ce944971
scapeless:~ elyscape$ minishift addons remove admin-user
-- Removing addon 'admin-user':.
admin user deleted

scapeless:~ elyscape$ minishift addons apply admin-user
-- Applying addon 'admin-user':..

scapeless:~ elyscape$ oc login -u admin
Authentication required for https://192.168.64.9:8443 (openshift)
Username: admin
Password: 
error: The server was unable to respond - verify you have provided the correct host and port and that the server is currently running.
scapeless:~ elyscape$ oc login -u system:admin
Logged into "https://192.168.64.9:8443" as "system:admin" using existing credentials.

scapeless:~ elyscape$ oc get user admin
NAME      UID                                    FULL NAME   IDENTITIES
admin     f75bd703-060c-11e8-9aad-8e64ce944971   admin       
scapeless:~ elyscape$ oc get identity anypassword:admin
NAME                IDP NAME      IDP USER NAME   USER NAME   USER UID
anypassword:admin   anypassword   admin           admin       df65bdfe-060c-11e8-9aad-8e64ce944971
```
This can be dealt with by adding `oc delete identity anypassword:admin` to the remove script.

**Comment by LalatenduMohanty** [comment] 2018-03-06 18:54
@jorgemoralespou This is duplicate of https://github.com/minishift/minishift/issues/1130.  So I am planning to close this one.

**Comment by LalatenduMohanty** [comment] 2018-03-06 19:05
@elyscape  You have again executed the `minishift addon apply` command after running the `remove` command, hence you are seeing this I think.  I could not reproduce the issue

```
$ minishift addon apply admin-user
-- Applying addon 'admin-user':..

$ minishift addon remove admin-user
-- Removing addon 'admin-user':.
admin user deleted

$ oc login -u admin
Authentication required for https://192.168.64.6:8443 (openshift)
Username: admin
Password:
error: Internal error occurred: unexpected response: 500 - verify you have provided the correct host and port and that the server is currently running.
Error from server (InternalError): Internal error occurred: unexpected response: 500
```

**Comment by elyscape** [comment] 2018-03-06 19:09
Right, the steps to reproduce are:
1. Apply the addon
2. Log in as admin
3. Remove the addon
4. Apply the addon again
5. Try to log in as asmin

**Comment by LalatenduMohanty** [comment] 2018-03-07 21:36
@elyscape Can you please create a new issue for it? The issue you are reporting is is a different than this issue.

**Closed** 2018-03-21 13:00 UTC
Labels: component/addons, kind/feature, priority/minor
