### ISSUE TITLE
Checking requested OpenShift version fails when offline

### ISSUE THREAD

**Issue by ppalaga** [minishift/minishift#2144] opened 2018-03-18 11:43 UTC
### General information

  * Minishift version: v1.14.0+1ec5877
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

The general expectation here is, that minishift should be able to start offline, once all the bits were cached during previous successful starts when the internet connection was on.

(1) With internet connection available

    minishift start 

Expected: minishift starts cleanly

    minishift stop

(2) Diconnect from the internet

    minishift start 

Expected: minishift starts into a functional state, maybe with some warnings
Actual:

```
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.1' is valid ... FAIL
   v3.7.1 is not a valid OpenShift version
```

**Comment by ppalaga** [comment] 2018-03-18 11:56
This seems to be a regression between 1.13.1 and 1.14.0. 

1.13.1 works as expected. Some startup tasks fail, but the VM starts into a usable state:

```
$ minishift version
minishift v1.13.1+75352e5
$ minishift start
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM ............... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 22% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.7.1
-- Checking 'oc' support for startup flags ... 
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.7.1 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.71:8443


```

**Comment by budhrg** [comment] 2018-03-18 14:46
> This seems to be a regression between 1.13.1 and 1.14.0.

I won't say it is a regression as this pre-flight check of validating requested OpenShift version is using openshift origin release to see the request version is valid or not.

This we might need to disable during offline mode.

**Comment by anjannath** [comment] 2018-03-18 16:54
Yup, offline mode or once we have the requested `oc` version cached we should disable this check.

**Comment by praveenkumar** [comment] 2018-03-19 09:51
We have a PR #2149 in place to handle it, I am closing this issue because it duplicate to what @gbraad filled #2102 .

**Closed by praveenkumar** 2018-03-19 09:51 UTC

**Comment by ppalaga** [comment] 2018-03-19 10:43
@praveenkumar great, thanks for the info.
