### ISSUE TITLE
Allow "--openshift-version latest" for testing unreleased version of openshift

### ISSUE THREAD

**Issue by thomasmckay** [minishift/minishift#1274] opened 2017-08-16 15:36 UTC
As an integration tester, I want to run the latest unreleased builds of openshift.
My use case is that I'm developing and testing external tool integration with openshift and would like the ability to confirm/find issues prior to release candidates. Being able to use "latest" would be very helpful.

**Comment by gbraad** [comment] 2017-08-17 00:42
This is something that could be enabled as part of our experimental features. It wouldn't have to take much effort, so I think this can be slipped in soon...

**Comment by gbraad** [comment] 2017-08-17 05:40
After a little bit of looking into this issue:

There are two things we need, the origin container and the client. While the origin container can be tagged as [latest](https://hub.docker.com/r/openshift/origin/tags/), this does not happen for the client. The client only knows a [latest release](https://github.com/openshift/origin/releases/latest).

What would you expect to happen?

**Comment by praveenkumar** [comment] 2017-08-17 06:01
> There are two things we need, the origin container and the client. While the origin container can be tagged as latest, this does not happen for the client. The client only knows a latest release.

Right, we got same request some time back and as you mentioned here what should we possible use for the client binary. Should it be whatever latest (alpha/beta/released) or one which we ship as default latest released version. 

I am not sure about if this is a priority issue for us atm. we can discuss around it.

**Comment by gbraad** [comment] 2017-08-17 06:30
> I am not sure about if this is a priority issue for us atm. we can discuss around it.

it is certainly not a priority at the moment, but functionality we should definitely provide. But what if I want to use my own built `oc` OpenShift client? What if I want to use my own built origin container? A lot of permutations are available. And I think we should investigate what each of this options would entail.

However, the aforementioned issue is actually one of the easier problems... but likely will need an additional flag to specify the client to use for deployment.

**Comment by gbraad** [comment] 2017-08-17 06:31
Added tags for feedback from OP, and for additional investigation

**Comment by thomasmckay** [comment] 2017-08-17 11:52
As the user, I run 'oc' from the host running the VM, not directly on the VM. In the case of recently running 3.6.0-rc0, I installed 'oc' of that version locally.
In general I agree this could be an advanced option. Perhaps specifying 'latest' should still print out a help message with warning. To actually run 'latest' perhaps an additional flag is needed like --voiding-warranty ;)

**Comment by jorgemoralespou** [comment] 2017-08-18 12:03
I might have requested this before, as this is something I also find very useful and use quite often with "oc cluster up".

In case of "oc cluster up", the binary is already present on your box, and you can run with "--images=latest" that will pull down the openshift images from dockerhub tagged as latest.

What I would do here, to support this feature, since it is mostly for developers:

```
MINISHIFT_ENABLE_EXPERIMENTAL=on minishift start --extra-clusterup-flags=--version=latest
```

This should use the oc client for the VM, currently "v3.6.0", and the start oc cluster up with the "--images=latest" so that the images get pulled from the internet. 

Also, these images should not be cached, as you would most likely want the latest images every time you create such a cluster.

It almost work currently:

```
MINISHIFT_ENABLE_EXPERIMENTAL=on minishift start --extra-clusterup-flags=--version=latest
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% OK
-- Importing cached images ...
   Importing openshift/origin-docker-registry:v3.6.0 [49.7s]
   Importing openshift/origin-haproxy-router:v3.6.0 [35.8s]
   Importing openshift/origin:v3.6.0 [29.1s]
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
-- Extra `oc` cluster up flags (experimental) ...
   '--version=latest'
Starting OpenShift using openshift/origin:latest ...
Pulling image openshift/origin:latest
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 52% complete
Pulled 3/4 layers, 84% complete
Pulled 3/4 layers, 93% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Applying addon 'admin-user':..

 [developer@192.168.99.100:8443/myproject]
[jmorales:~] $ minishift ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec
docker@minishift:~$ docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-deployer          latest              f4c3c40561ac        10 hours ago        1.057 GB
openshift/origin                   latest              c42a8b7581bf        10 hours ago        1.057 GB
openshift/origin-pod               latest              9aa16bc45f6c        10 hours ago        213.2 MB
openshift/origin-docker-registry   v3.6.0              ec456625b2a0        2 weeks ago         1.062 GB
openshift/origin-haproxy-router    v3.6.0              75e805233369        2 weeks ago         995.3 MB
openshift/origin                   v3.6.0              25e1f260f8ae        2 weeks ago         974.3 MB
```

**Comment by gbraad** [comment] 2017-08-21 16:37
@jorgemoralespou @thomasmckay 
Although I added a more direct option: `MINISHIFT_ENABLE_EXPERIMENTAL=on minishift start --clusterup-version=latest` to achieve what `--extra-clusterup-flags=--version=latest` does, I am not sure if this is an approach we want to take.

**Comment by thomasmckay** [comment] 2017-08-21 16:49
Would it be bad to just use ```MINISHIFT_ENABLE_EXPERIMENTAL=on minishift start --openshift-version latest``` for simpler usage? Is the ```--clusterup-version``` useful with ```--openshift-version``` or are they mutually exclusive?

**Comment by gbraad** [comment] 2017-08-21 17:19
In short:
  * `--openshift-version` is the version of `oc` to be used, while
  * `--clusterup-version` tells `oc cluster up` which container images to pull

as you can see, this is related to the earlier concern:

> What would you expect to happen? We will deploy and run `oc cluster up` using the 'latest' oc version (3.6.0 as of now), or we use the 'latest' (as the top most, v3.7.0-alpha.0).

The `oc` client does not have a concept of `latest`, so this is why I asked... what do you expect it would do?

**Comment by jorgemoralespou** [comment] 2017-08-21 17:50
Can you paste a link to the binary from CI so we can test this? The feature
is fine as it is, I think for now. Now could always replace the oc in the
.minishift folder if he wanted to also test the latest oc client, keeping
in mind this is an advanced developer feature.

**Comment by gbraad** [comment] 2017-08-22 07:10
http://artifacts.ci.centos.org/minishift/minishift/pr/1288

**Comment by jorgemoralespou** [comment] 2017-08-22 12:22
@gbraad I see a small glitch in how things should work, not sure if because I have image-cache enabled.

When starting with image-cache I get:
```
MINISHIFT_ENABLE_EXPERIMENTAL=on ./minishift-1274 start --clusterup-version=latest
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% OK
-- Importing cached images ...
   Importing openshift/origin-docker-registry:v3.6.0 [1m37.3s]
   Importing openshift/origin-haproxy-router:v3.6.0 [36.2s]
   Importing openshift/origin:v3.6.0 [30.7s]
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
version  version=latest
Starting OpenShift using openshift/origin:latest ...
Pulling image openshift/origin:latest
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 55% complete
Pulled 2/4 layers, 72% complete
Pulled 3/4 layers, 84% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Applying addon 'admin-user':..
```

Then I ssh into minishift and list the images available:
```
docker@minishift:~$ docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-deployer          latest              5e33c0e2fff0        2 hours ago         1.057 GB
openshift/origin-docker-registry   latest              1cf04f377705        2 hours ago         1.146 GB
openshift/origin-haproxy-router    latest              6ee245a457aa        2 hours ago         1.078 GB
openshift/origin                   latest              a6cd17dc10be        2 hours ago         1.057 GB
openshift/origin-pod               latest              e4c22abd7d50        2 hours ago         213.2 MB
openshift/origin-docker-registry   v3.6.0              ec456625b2a0        2 weeks ago         1.062 GB
openshift/origin-haproxy-router    v3.6.0              75e805233369        2 weeks ago         995.3 MB
openshift/origin                   v3.6.0              25e1f260f8ae        2 weeks ago         974.3 MB
```

I think that the v3.6.0 images should not be there.

**Comment by jorgemoralespou** [comment] 2017-08-22 12:28
@gbraad Disabled image caching and it's working as expected.

```
minishift config view
- cpus                 : 2
- image-caching        : false
- memory               : 8192
- vm-driver            : virtualbox
 [developer@192.168.99.100:8443/myproject]
[jmorales:~/Downloads] $ MINISHIFT_ENABLE_EXPERIMENTAL=on ./minishift-1274 start --clusterup-version=latest
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   host-volumes-dir ... OK
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
version  version=latest
Starting OpenShift using openshift/origin:latest ...
Pulling image openshift/origin:latest
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 56% complete
Pulled 2/4 layers, 74% complete
Pulled 3/4 layers, 88% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Applying addon 'admin-user':..


[jmorales:~/Downloads] $ minishift ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec

docker@minishift:~$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-deployer   latest              5e33c0e2fff0        2 hours ago         1.057 GB
openshift/origin            latest              a6cd17dc10be        2 hours ago         1.057 GB
openshift/origin-pod        latest              e4c22abd7d50        2 hours ago         213.2 MB
```

**Comment by hferentschik** [comment] 2017-08-22 12:29
@jorgemoralespou this is due to image caching enabled. These two things play in this case not together. It will work, but the import of the image is basically not needed in this case. As you see the images gets imported, but then not used. This is due to the fact that the import is based on the OpenShift version specified. It does not take a tag into consideration.

**Comment by gbraad** [comment] 2017-08-22 12:39
This is why a possible flag will help, as we can force caching to be
disabled in that case.
But this feels much like side-effects we do not want...

Either fix the caching code? but based on what?
or force the caching to be turned off... but under which condition?

**Comment by jorgemoralespou** [comment] 2017-08-22 13:51
I would think that the caching should be on the OpenShift version of the
images that will be run and not of the client being used.
This would not be the expected behavior and consistent behavior.

**Comment by gbraad** [comment] 2017-08-22 14:02
At the moment we do not make such a distinguishment.
We only know the `--openshift-version` (which is the client, AND the
deployed container version)

**Comment by jorgemoralespou** [comment] 2017-08-22 14:23
The deployed container version is what should be cached, if it's different
from the OpenShift client version.

**Comment by hferentschik** [comment] 2017-08-22 14:34
> I would think that the caching should be on the OpenShift version of the images that will be run and not of the client being used.

Sure, except that you are using some experimental feature. We only expose  the '--openshift-version' flag. And as long as you use this options, things will align. 
I am not sure whether it is worth changing too much code for experimental features.

> This would not be the expected behavior and consistent behavior.

Once you officially expose OpenShift version + OpenShift image tag, yes.

**Comment by jorgemoralespou** [comment] 2017-08-22 15:01
@hferentschik well, depends on whether you'll be formalizing this into an actual parameter or not.

Have you given a thought on formalizing this parameter or the "client" version and the "images" version?

**Comment by gbraad** [comment] 2017-08-28 08:41
The team voted on #1288 against adding an additional flag to allow direct use, as the current `--extra-clusterup-flags` already provides an option for doing this.

Closing this issue...

**Closed** 2017-08-30 11:45 UTC
Labels: kind/feature, priority/major, status/needs-investigation
