### ISSUE TITLE
Install Minishift on AWS ec2 

### ISSUE THREAD

**Issue by santosh3702** [minishift/minishift#2421] opened 2018-05-30 08:58 UTC
### General information

  * Minishift version: 1.18.0
 I want to install Minishift on AWS ec2 instance OS : Red Hat Enterprise Linux 7.5 (HVM),  Ubuntu Server 16.04 LTS (HVM) , Instance type: t2.micro 
  
I am trying to install on aws ec2 but i didn't any detail steps in openshift website , is it possible to install Minishift on AWS ec2.

**Comment by LalatenduMohanty** [comment] 2018-05-30 10:42
@santosh3702 At this point it is not possible with Minishift v1.18.0 because "minishift start" creates a Linux VM to provision OpenShift in it.  it is only possible if you have nested virtualization enabled in the Instance you are using for Minishift. However we are working on #392 which will allow you to re-use a VM to provision Minishift without creating a new VM.

**Comment by LalatenduMohanty** [comment] 2018-05-30 10:42
@santosh3702 I am inclined to mark it duplicate of #392, WDYT?

**Comment by praveenkumar** [comment] 2018-06-28 05:55
@santosh3702 We now have a way to use minishift (v1.19.0) and provision existing VM https://docs.openshift.org/latest/minishift/using/experimental-features.html#run-against-an-existing-machine can you try that and let us know if that work and then close this issue?

**Comment by santosh3702** [comment] 2018-06-28 10:02
So minishift can install on AWS right ,

**Comment by anjannath** [comment] 2018-06-28 10:08
It is not specific to AWS, minishift can now provision OpenShift on any
remote machine.
You just need to provide the Ip address and the ssh key to connect to the
machine.

Please go through the documentation that @praveenkumar pointed to in the
previous comment.

**Comment by santosh3702** [comment] 2018-06-28 10:13
Sure I will follow the steps

**Comment by anjannath** [comment] 2018-07-11 06:12
@santosh3702 Were you able to start minishfit on your aws instance?

**Comment by mackenza** [comment] 2018-07-17 15:52
I just tried against EC2 and was not successful... 
```
Starting to provision the remote machine ..... FAIL E0717 11:41:34.058044     165 start.go:416] Error starting the VM: Error creating the VM. Error creating machine: Error detecting OS: OS type not recognized. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error detecting OS: OS type not recognized
```
In the installing on existing machine instructions (btw the link that @praveenkumar posted above seems to have been moved to https://docs.openshift.org/latest/minishift/using/run-against-an-existing-machine.html), it says `CentOS7/RHEL7/Fedora(>26) are the suggested Linux distributions for this feature.`. I am using Amazon Linux 2 AMI. Is the above a suggestion or a requirement? I don't want to blow up my EC2 instance if the OS isn't the issue.

Any assistance would be helpful.

**Comment by LalatenduMohanty** [comment] 2018-08-23 06:32
@mackenza  We have never tested Amazon Linux 2 AMI. We will look in to it. But I would highly recommend you to  use CentOS or Fedora to get started.

**Comment by gbraad** [comment] 2018-08-23 06:36
this will fail with the generic driver, as Amazon's AWS Linux is not a 'real' RHEL-derivative. At least, it is not indicated as such from the os-release. Therefore the provisioner will not work (as there is no default).

**Comment by praveenkumar** [comment] 2018-08-23 08:05
Created https://github.com/machine-drivers/machine/issues/7 once it is added to machine repo it will be resolved.

@LalatenduMohanty should we close this or have it open to track?

**Comment by budhram** [comment] 2018-09-25 09:36
@LalatenduMohanty Please have a look.

**Comment by LalatenduMohanty** [comment] 2018-09-25 09:39
We can close this as the issue is https://github.com/machine-drivers/machine/issues/7

**Closed by LalatenduMohanty** 2018-09-25 09:39 UTC
Labels: component/generic-driver, kind/feature, priority/major
