### ISSUE TITLE
Trying the oc annotate command with minishift deployment?

### ISSUE THREAD

**Issue by anshulbehl** [minishift/minishift#1985] opened 2018-02-06 15:44 UTC
### General information
Due to somewhat slow backend of my application it was required to annotate the route to application with haproxy timeout using the commands provided in

https://docs.openshift.org/latest/install_config/configuring_routing.html

While doing this it was difficult to get hold of the haproxy hostname as the above link uses openshift origin as reference and not minishift.
Since minishift is running locally on IP http://192.168.64.2:8443, I tried to hit the timeout endpoint using the same URL(192.168.64.2:8443/timeout) which responses in 

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot \"get\" on \"/timeout\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

Which seems about right and now I tried to replace the command:

```
~ oc annotate route myroute --overwrite haproxy.router.openshift.io/timeout=2s
with
~ oc annotate route myroute --overwrite 192.168.64.2:8443/timeout=2s
```

which resulted in:
```
The Route "myrouter" is invalid: metadata.annotations: Invalid value: "192.168.64.2:8443/timeout": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

There are two issues which I want to highlight,
1. minishift documentation should also explain the annotate command or how to find the hostname of haproxy in an active minishift deployment
2. oc utility should be able to take hostname:port format as part of annotate command.

I would also like to hear about any possible solutions that you think I can try, one thing that comes to mind is reverse proxying the hostname:port to a URL  and then using the same url in the annotate command but it looks a bit cumbersome.

```
  * Minishift version: -----> minishift v1.8.0+6455fc3
  * OS: Linux / macOS / Windows -----> macOS
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox -----> xhyve
```

### Expected
it should be easy to find the hostname of haproxy on a minishift deployment
oc annotate utility should take hostname:port for setting the timeout for haproxy
### Actual
Not able to find the hostname haproxy is running on
Cannot use hostname:port format in oc annotate utility

### Logs

Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Plugin server listening at address 127.0.0.1:61894
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
The 'minishift' VM is already running.

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.

Please consider posting this on http://gist.github.com/ and post the link in the issue.

@LalatenduMohanty @praveenkumar

**Comment by jorgemoralespou** [comment] 2018-02-06 19:43
@anshulbehl 
You don't need to change the annotation if you want to change the timeout for the router

haproxy.router.openshift.io/timeout=5s

2) oc annotate issues belong to openshift/origin repo. And what you're requesting is something that will not be accepted, as your assumption of how the annotation works was incorrect.

You should close this issue.

**Comment by anshulbehl** [comment] 2018-02-06 20:58
@jorgemoralespou 
Quoting https://docs.openshift.org/latest/install_config/configuring_routing.html
After installing OpenShift Origin and deploying a router, you can configure the default timeouts for an existing route when you have services in need of a low timeout, as required for Service Level Availability (SLA) purposes, or a high timeout, for cases with a slow back end.

As documented the command specifically changes the haproxy timeout for the route specified and hence the understanding seems valid.
Also referenced https://bugzilla.redhat.com/show_bug.cgi?id=1361024
>>>oc annotate issues belong to openshift/origin repo. And what you're requesting is something >>>that will not be accepted, as your assumption of how the annotation works was incorrect.

Ack on above, but it would be good if minishift can also document the similar steps to annotate the route on a minishift deployment.

**Comment by praveenkumar** [comment] 2018-02-07 10:46
After discussing with @anshulbehl  in person, it mostly looks like the issue from openshift/origin side not from minishift because here we don't control it. @anshulbehl can you please close this issue and open to https://github.com/openshift/origin/issues ?

> but it would be good if minishift can also document the similar steps to annotate the route on a minishift deployment.

Since minishift always going to have port information for console side so not much can be done on this front.

**Comment by jorgemoralespou** [comment] 2018-02-07 20:22
@anshulbehl yes, you can configure the timeout for a route in the router,
but that's OpenShift and nothing to do with minishift which just provides
the ability to run OpenShift in a VM.
I don't really know what issue you want to open on OpenShift, since what
you were trying to do is not valid, and hence not an issue.
@praveenkumar do you understand what is the issue that should be opened on
the OpenShift side?

**Comment by praveenkumar** [comment] 2018-02-08 05:12
> do you understand what is the issue that should be opened on the OpenShift side?

@jorgemoralespou what @anshulbehl want to allow port info also as part of annotation key which currently not available, I am not sure if it is by design or some improvement can be done from Openshift side to accommodate this use case. If it is by design then we can't do much and he needs to use an endpoint which supported by Openshift.

**Comment by jorgemoralespou** [comment] 2018-02-08 06:55
@praveenkumar,
It is by design. But I don't understand why would he want such annotation.

**Comment by praveenkumar** [comment] 2018-02-12 04:42
> It is by design. 

Thanks, @jorgemoralespou for confirming. 

> But I don't understand why would he want such annotation.

He just wants to do something which is not supported by design so I am closing this issue now. @anshulbehl if you still think there is some improvement we can do from the minishift side, please comment and will reopen it.

**Closed by praveenkumar** 2018-02-12 04:42 UTC
