### ISSUE TITLE
Question: issue with Hyper-V administrateur preflight check

### ISSUE THREAD

**Issue by itscaro** [minishift/minishift#1987] opened 2018-02-07 10:50 UTC
I'm using Windows 10 17.03 with user on domain. The user is added to Hyper-V Admin group.

Preflight check if user is in the role Hyper-V Admin fails

https://github.com/minishift/minishift/blob/f9ccd57cfef7af081a4a3289948af6d5eed45443/cmd/minishift/cmd/start_preflight.go#L377

This call gives: `The trust relationship between the primary domain and the trusted domain failed.`

What is failing here?

Thank you

**Comment by gbraad** [comment] 2018-02-07 10:53
This was implemented as part of #1541, but fails when a user is part of a domain: duplicate of #1882.

**Comment by gbraad** [comment] 2018-02-07 10:54
@anjannath maybe we should make this WARN by default.

@itscaro please try to start after setting:
```
PS> minishift config set warn-check-hyperv-driver true
```

**Comment by gbraad** [comment] 2018-02-07 10:57
Please continue discussion on #1882

**Closed** 2018-02-07 10:57 UTC
Labels: resolution/duplicate
