### ISSUE TITLE
--service-catalog should no longer be considered experimental

### ISSUE THREAD

**Issue by eriknelson** [minishift/minishift#2017] opened 2018-02-12 16:32 UTC
### Expected
The `--service-catalog` should not require `export MINISHIFT_ENABLE_EXPERIMENTAL=y`.

### Actual
The `--service-catalog` requires `export MINISHIFT_ENABLE_EXPERIMENTAL=y`.

I was demoing catalog features with minishift, and it seems a number of catalog folks expected this to no longer be an experimental feature.  It still is behind this gate, I would propose to remove this requirement, since the catalog is now beta level.

CC: @pmorie

**Comment by gbraad** [comment] 2018-02-13 01:07
This is due to `oc cluster up` also still classifying it as such: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#installing-the-service-catalog

Duplicate of #1908

**Closed by gbraad** 2018-02-13 01:07 UTC
