### ISSUE TITLE
Password can not be entered when console/terminal lacks PTY support

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1653] opened 2017-11-03 07:52 UTC
**Steps to Reproduce**
- Open minishift project in IDEA IntelliJ / Eclipse
- Add Run configuration with `--iso-url` pointed to RHEL iso
- Click on Run button (Shift + F10)
- In the 'Console View', enter subscription username

See Devstudio issue as well https://issues.jboss.org/browse/JBIDE-25260

### With CMD / Powershell behavior

Password prompt message appear again on pressing enter.
**Expected**: Should repeat asking of username/password saying invalid credentials.

![password_prompt_enter](https://user-images.githubusercontent.com/1132451/32367217-6780d334-c0a7-11e7-99e9-2881d83b40a9.PNG)

**Comment by budhrg** [comment] 2017-11-03 07:52
I am also able to reproduce same with Git Bash (Unsupported shell) in Windows 10.

**Comment by budhrg** [comment] 2017-11-03 09:29
Latest finding is that I am able to still reproduce with spinning wheel progress bar for registration https://github.com/minishift/minishift/commit/0e75c4ece2ec0154700cd8827a648aaf2d454965

**Comment by gbraad** [comment] 2017-11-05 11:30
You mentioned this was not reproducible on the current DevSuite GA and CDK 3.1-GA? Maybe this was tested with a development branch of DevSuite (console plugin)?

Anyways, it seems that https://github.com/minishift/minishift/commit/0b524595ae6d17ab62f10f1c6326c5449170bfac#diff-a685a6d5ca4e6adc776533a278e72732R79 is answered automatically with an empty string, due to which the `for`-loop get retriggered. This can only happen when the code https://github.com/minishift/minishift/blob/a9fc054fca4820cb9e249b71e6c28b01a7b123f8/pkg/util/input.go#L37 does not get a valid filedescriptor. This is needed to be prevent nothing to be printed (as the ssh/crypto) solution has issues on Windows IIRC.

**Comment by gbraad** [comment] 2017-11-05 12:13
https://github.com/golang/go/issues/21009

**Comment by gbraad** [comment] 2017-11-05 16:16
Maybe making use of https://github.com/golang/crypto/blob/master/ssh/terminal/terminal.go (`NewTerminal`.`ReadPassword("...")` would be possible instead? Not sure how this behaves...

**Comment by budhrg** [comment] 2017-11-06 06:21
I noticed a weird behavior here. I added debug lines and noticed following behavior
in IntelliJ IDE : 
![screenshot from 2017-11-06 11-48-24](https://user-images.githubusercontent.com/1132451/32427852-b0e77260-c2e8-11e7-821c-a3ed18de914e.png)

The **weird behavior** is that the control execution is not holding itself for user's input.
But, from actual terminal/shell, execution hold for user's input:
```
$ minishift start
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .............................. OK
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: bgurung@redhat.com
After username line....
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Registration in progress .. FAIL [4s]
   [...]   
```

**Comment by gbraad** [comment] 2017-11-06 06:24
I am not sure if this is true. It rather looks like an issue with the debugger, as the execution pas not passed on in the executable. Add `fmt.PrintLn` to the code to confirm.

**Comment by budhrg** [comment] 2017-11-06 06:30
> golang/go#21009 ReadPassword not working when there is no PTY support. For IntelliJ this can be turned on.

Golang related issue - https://youtrack.jetbrains.com/issue/GO-4271

**Comment by gbraad** [comment] 2017-11-06 06:35
Seems I forgot to post it here. A golang issues related to this is: https://github.com/golang/go/issues/21009

It mentions to enable it as follows: https://youtrack.jetbrains.com/issue/PY-19938 by setting the registry paramater: `run.processes.with.pty`

**Comment by gbraad** [comment] 2017-11-06 09:51
That things work in the DevSuite GA, is weird for sure
However, as you said it didn't work for you either, I tried git-bash. But this does not work at all for me. the VM start perfectly, but the powershell.exe calls all fail to perform the requested action
this means that even though the VM has an IP address, it fails (as it can not get the IP address for the interface). if people wanna use git-bash for this, I would recommend the bash for windows option instead

**Comment by gbraad** [comment] 2017-11-06 09:57
Since we want to hide (prevent echoing) to the console, there is at the moment not much we can do. I would suggest to discuss alternative solutions on the side of CDK (such as a popup to populate the environment variables).

**Comment by gbraad** [comment] 2017-11-06 13:42
I think we can move on and close this: https://issues.jboss.org/browse/JBIDE-25260?focusedCommentId=13486086&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13486086

**Comment by budhrg** [comment] 2017-11-06 16:55
Closing this issue as we can't do much from minishift implementation point of view.

**Comment by robstryker** [comment] 2017-11-16 18:22
@budhrg  Hey can you explain to me why exactly there's no way for you to fix this?  What exactly is causing the presence of a \n to ruin everything? Is there no way to filter the \n off? Does the presence of the \n mean the go code will never read another line of input because golang can never move past the \n? 

I'm lacking a complete understanding here of why this behaves this way.

**Comment by budhrg** [comment] 2017-11-17 10:14
@robstryker , It is mostly an IDE issue rather than Go issue. See https://github.com/golang/go/issues/21009#issuecomment-315352712. 

IDE issue here https://youtrack.jetbrains.com/issue/GO-4271

Even, as mentioned in the ticket, I tried to use `pty` from registry but didn't work for me.

Will try one more time later and follow up with IntelliJ guys.

**Comment by gbraad** [comment] 2017-11-17 10:41
@robstryker We need PTY support, as in this way we can prevent the characters to be echoed to the console. it has nothing to do with `\n` as a character, but a non-existent descriptor to read input.

**Comment by robstryker** [comment] 2017-11-20 17:55
@gbraad  Would it be possible to detect that you don't currently HAVE pty support? Once you detect that, you can prevent the problematic call attempting to read in from a non-existent descriptor? Maybe then you could just error out with a simple "Provided credentials are invalid. Shutting down CDK" etc or something different?

My point is, there must be other solutions than simply closing this and taking no action.

**Comment by budhrg** [comment] 2017-11-28 15:43
Reopening as we need to investigate if we can detect pty support from minishift side as mentioned by @robstryker above.

**Comment by robstryker** [comment] 2017-12-05 14:34
I would just like to note that JBossTools considers a cdk functioning with no PTY to be a major use case. We used to use the terminal view (which did have PTY), but were told this was unnecessary after some previous changes and flags being passed in. 

Even just detecting that there's no PTY and erroring-out instead of getting stuck in a loop is better than what we have here.

**Comment by hferentschik** [comment] 2017-12-12 10:56
Have you guys tried replacing:

```Go
terminal.ReadPassword(int(os.Stdin.Fd()))
```

with 

```Go
terminal.ReadPassword(syscall.Stdin)
```

It might not make a difference, but it is more concise.

**Comment by hferentschik** [comment] 2017-12-12 11:04
We could also try to wrap the _terminal.ReadPassword_ call into a _terminal.IsTerminal_ call. If we are not dealing with a terminal we would just read in the default way from stdin. It means the password would be echoed, but it would most likely bypass the problem. I guess it would be up to @robstryker and the DevStudio team whether they would prefer that.

**Comment by hferentschik** [comment] 2017-12-12 11:15
Last but not least, we could also make the retry configurable (either explicitly or implicitly). The DevStudio integration would use a 0 retry. This way, the user gets an error and is forced to go back to the proper dialog to verify the credentials. It seems reasonable that there is only one place for the user to provide these credentials.

**Comment by robstryker** [comment] 2017-12-12 16:28
It might be nice to just do if( Terminal.isTerminal() )  { // current behavior } else { 'Your credentials are incorrect. Your terminal is not a PTY Terminal. Retries are disabled". }

**Comment by gbraad** [comment] 2017-12-19 16:38
> terminal.ReadPassword(syscall.Stdin)

Is not possible, as the function on Windows expects an `int`. This was done specifically. I think this is a glitch in the language.

**Closed** 2017-12-20 08:46 UTC
Labels: kind/bug, priority/major, status/needs-investigation
