### ISSUE TITLE
Service url is not reachable in minishift setup

### ISSUE THREAD

**Issue by ilterpehlivan** [minishift/minishift#79] opened 2016-09-09 15:15 UTC
Hi,

I am trying to deploy one of the Karaf rest example from the quickstarts into my local minishift environment. I deployed it and service up and running succesfully. 
However i can not access to service url, here is the outputs

Pod:
[eiltpeh@localhost blueprint]$ oc get pods
NAME                              READY     STATUS    RESTARTS   AGE
exposecontroller-1-au4i4          1/1       Running   1          23h
fabric8-docker-registry-1-6kpgp   1/1       Running   2          23h
fabric8-forge-1-xmdbx             1/1       Running   1          23h
fabric8-q1anx                     1/1       Running   2          23h
gogs-1-p1gjr                      1/1       Running   1          23h
jenkins-1-xdkhq                   1/1       Running   1          23h
karaf-camel-rest-sql-1-ldwbe      1/1       Running   0          12m
mysql-4-9vps0                     1/1       Running   2          23h
nexus-1-aoiyd                     1/1       Running   9          23h
router-1-dcv6f                    2/2       Running   4          23h

Routes:
[eiltpeh@localhost blueprint]$ oc get routes
NAME                      HOST/PORT                                            PATH      SERVICE  
karaf-camel-rest-sql      karaf-camel-rest-sql-default.192.168.99.100.xip.io             karaf-camel-rest-sql  
mysql                     mysql.xip.io                                                   mysql  
router                    router.xip.io                                                  router                  

[eiltpeh@localhost blueprint]$ curl http://karaf-camel-rest-sql-default.192.168.99.100.xip.io
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

[eiltpeh@localhost blueprint]$ curl http://karaf-camel-rest-sql-default.192.168.99.100.xip.io/camel-rest-sql/books
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

Minishift service IP:
[eiltpeh@localhost blueprint]$ minishift service karaf-camel-rest-sql --url
http://192.168.99.100:32449
[eiltpeh@localhost blueprint]$ curl http://192.168.99.100:32449
curl: (7) Failed connect to 192.168.99.100:32449; Connection refused

Kubernetes Port:
[eiltpeh@localhost blueprint]$ kubectl get service karaf-camel-rest-sql --output='jsonpath="{.spec.ports[0].NodePort}"'
"32449"[eiltpeh@localhost blueprint]$

I disabled firewall, ipv6 yet it is still not working
Could you please help ?

Thanks

**Comment by jimmidyson** [comment] 2016-09-12 11:59
What version of minishift are you running?

**Comment by jimmidyson** [comment] 2016-09-12 12:35
Also what VM driver and OS are you using?

**Comment by ilterpehlivan** [comment] 2016-09-12 12:45
Hi jimmi
I am running on windows 7 with minishift 0.6 version
I am using Virtualbox as driver
I gave a try in my Vmware with centos and i also observed this in there too.
Is hyperv working for windows btw i could not make it work with --vm-driver=hyperv option ?

Thanks

**Comment by jimmidyson** [comment] 2016-09-12 12:57
That looks like there are no service endpoints. Are you sure the pod is properly started? What does `oc get pods` show? How about `oc get endpoints karaf-camel-rest-sql`?

**Comment by ilterpehlivan** [comment] 2016-09-12 17:50
THe pod is working fine since i can be able to see the camel router is working from the logs

2016-09-12 17:47:52,607 | INFO  | #1 - timer://foo | generateOrder-route              | 75 - org.apache.camel.camel-core - 2.17.3 | Inserted new order 59
2016-09-12 17:47:53,068 | INFO  | ssed%20=%20false | processOrder-route               | 75 - org.apache.camel.camel-core - 2.17.3 | Processed order id 59 item ActiveMQ of 7 copies of ActiveMQ in Action
2016-09-12 17:48:02,610 | INFO  | #1 - timer://foo | generateOrder-route              | 75 - org.apache.camel.camel-core - 2.17.3 | Inserted new order 60
2016-09-12 17:48:02,647 | INFO  | ssed%20=%20false | processOrder-route               | 75 - org.apache.camel.camel-core - 2.17.3 | Processed order id 60 item Camel of 4 copies of Camel in Action

POD
karaf-camel-rest-sql-1-ji7sl      1/1       Running   0          4m

$ oc get endpoints karaf-camel-rest-sql
NAME                   ENDPOINTS         AGE
karaf-camel-rest-sql   172.17.0.5:8181   6m

Route:
karaf-camel-rest-sql      karaf-camel-rest-sql-default.192.168.99.100.xip.io             karaf-camel-rest-sql

**Comment by hferentschik** [comment] 2016-12-19 10:53
@ilterpehlivan, any chance you could try this with the latest version of minishift to verify whether this is still an issue? This would help us a lot. Thanks.

**Comment by budhrg** [comment] 2017-01-17 08:23
@ilterpehlivan Could you confirm with latest version of minishift? 
We are not able to reproduce it now.

**Comment by budhrg** [comment] 2017-01-30 06:15
@ilterpehlivan 

Based on what you are trying to achieve here 
```
[eiltpeh@localhost blueprint]$ curl http://karaf-camel-rest-sql-default.192.168.99.100.xip.io
```

With minishift version `v1.0.0-beta.1+`, you can achieve same as shown below:
```
$ oc get pods
NAME                READY     STATUS      RESTARTS   AGE
nodejs-ex-1-btptw   1/1       Running     0          5m
nodejs-ex-1-build   0/1       Completed   0          8m

$ oc expose svc/nodejs-ex
route "nodejs-ex" exposed

$ oc get routes
NAME        HOST/PORT                              PATH      SERVICES    PORT       TERMINATION
nodejs-ex   nodejs-ex-demo.192.168.42.243.xip.io             nodejs-ex   8080-tcp   

$ curl -I nodejs-ex-demo.192.168.42.243.xip.io      
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 40382
ETag: W/"9dbe-1JmfkBUY/av+bFVWtUNjJg"
Date: Mon, 30 Jan 2017 06:10:55 GMT
Set-Cookie: b243d23b7f3de7be6767d61e5564cca5=e21e8069f53753bdc22a8bd1ecd71710; path=/; HttpOnly
Cache-control: private
```

About, `minishift service <service-name> --url`, it seems at the moment it is broken post `v1.0.0-beta.1`.

I am closing this issue and tracking `service` command changes in issue https://github.com/minishift/minishift/issues/342

**Closed by budhrg** 2017-01-30 06:15 UTC
Labels: kind/bug, priority/major, status/needs-info
