### ISSUE TITLE
Minikube ISO nightly test failed in timeout 

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1880] opened 2018-01-03 08:48 UTC
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

Link to the failure; https://ci.centos.org/job/minishift-nightly-minikube/14/consoleFull

### Actual

```
00:13:45       | datagrid65-basic | datagrid-app | /             | Welcome to the JBoss Data Grid Server |
02:00:58 Killed by signal 15.
02:00:58 + rtn_code=124
02:00:58 + [[ 124 -eq 124 ]]
02:00:58 + echo 'BUILD TIMEOUT'
02:00:58 BUILD TIMEOUT
02:00:58 + cico node done f9328031
```

**Comment by agajdosi** [comment] 2018-01-03 09:01
The timeout is caused by #1703. However the actual reason why the rollout sometimes fails is uknown to me. It might be the fact that we are hitting the RAM limit on CentOS, we use the same value as with b2d I believe, which is 2GB.

**Comment by praveenkumar** [comment] 2018-01-12 11:17
https://github.com/minishift/minishift/pull/1864 this is something we should try once.

**Comment by budhrg** [comment] 2018-01-12 11:22
Duplicate of https://github.com/minishift/minishift/issues/1857

**Closed by budhrg** 2018-01-12 11:22 UTC
Labels: component/integration-test, kind/bug, priority/major, status/needs-investigation
