### ISSUE TITLE
Create a fabric8 add-on

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#1034] opened 2017-06-16 10:35 UTC
lets create an addon so its easy to install fabric8 into minishift from the command line.

We're getting close to a repeatable install on minishift; so I should be able to submit a PR for a first spike at an addon next week.

Is there a way to specify a parameter to an addon? e.g. I'd like the fabric8 addon to use the latest release of fabric8 but it might be nice to let a user override which version to use via the minishift CLI?

**Comment by hferentschik** [comment] 2017-06-16 12:08
Duplicate of issue #860 

> lets create an addon so its easy to install fabric8 into minishift from the command line.

+1

> We're getting close to a repeatable install on minishift; so I should be able to submit a PR for a first spike at an add-on next week.

That would be awesome. Let me know whether I can help. I currently have a bit of slack.

**Comment by jstrachan** [comment] 2017-06-16 13:57
@hferentschik ah great thanks. I should have a first cut of the addon later today, fingers crossed, just polishing the bash ;)

is an addon able to run minishift commands to reconfigure minishift? e.g. stuff like this:
```
minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'
```
also is there a way to test a new addon file on a current build of minishift?

**Comment by budhrg** [comment] 2017-06-16 14:02
@jstrachan These [commands](https://docs.openshift.org/latest/minishift/using/addons.html#addon-commands) are available to be run through the `*.addon` file. You might be interested in `openshift` command for your `config set --patch` use case.

> also is there a way to test a new addon file on a current build of minishift?

We have now [`minishift addons apply`](https://docs.openshift.org/latest/minishift/command-ref/minishift_addons_apply.html) command to test new addon file.

Let us know if still need any assistance.

**Comment by hferentschik** [comment] 2017-06-16 14:03
> is an addon able to run minishift commands to reconfigure minishift? 

yes, see also https://docs.openshift.org/latest/minishift/using/addons.html#addon-commands

**Comment by hferentschik** [comment] 2017-06-16 14:03
> also is there a way to test a new addon file on a current build of minishift?

See @budhrg response

**Comment by jstrachan** [comment] 2017-06-16 14:08
@budhrg @hferentschik thanks! I tried to find docs on addons and failed; I was looking in the 'Developing Minishift" section https://docs.openshift.org/latest/minishift/developing/index.html and didn't see anything. Now I know to check the using section too :)

**Comment by hferentschik** [comment] 2017-06-16 14:10
>  I was looking in the 'Developing Minishift" section

Doh. To be fair, I find this confusing as well. I think this topic name is ambiguous. I'd prefer "Contributing to Minishift". I think it would make it clearer from the outright what to expect in this sub section.

**Comment by budhrg** [comment] 2017-06-16 14:10
> Now I know to check the using section too :)

Great :) :+1:

**Comment by budhrg** [comment] 2017-06-16 14:11
+1 for "Contributing to Minishift" in-place of "Developing Minishift"

**Comment by jstrachan** [comment] 2017-06-16 14:46
BTW @budhrg @hferentschik do you have any good ideas on how I can fetch the latest version from maven central to find the version for fabric8 to install in the addon? 

In the bash script I'm using the lovely combination of `curl`, `cut` and `grep` ;)
https://github.com/fabric8io/fabric8-platform/blob/master/install.sh#L14

I guess one option is every time we release fabric8 we do a PR on minishift and then minishift just installs whatever version number that gets backed into the minishift binary; but I was hoping to be able to upgrade fabric8 a little faster. Another option could be to create some web service that provides a canonical URL that the addon can use; the downside is running something like that at scale so that it always works. Unfortunately github doc projects don't support redirect :(

I wonder if we could host the addon inside the fabric8 repo (so we can keep it updated as we do new releases) then have a way to download the latest addon file from a URL in github as folks install it?

**Comment by jstrachan** [comment] 2017-06-16 14:49
I guess I could use `ssh` to invoke the curl / grep / cut thing; but I can't output those results to an environment variable that I can use in the rest of the addon file right?

**Comment by hferentschik** [comment] 2017-06-16 14:54
> I guess I could use ssh to invoke the curl / grep / cut thing; but I can't output those results to an environment variable that I can use in the rest of the addon file right?

Right, there is a feature request to allow custom variables to be provided to the add-ons. The idea is to either provide them via the command line or setting them by using (a yet to be implemented) add-on command. 

Right now there is no easy way of doing what you are after.

**Comment by hferentschik** [comment] 2017-06-16 14:57
> I wonder if we could host the addon inside the fabric8 repo (so we can keep it updated as we do new releases) then have a way in minishift to download the latest addon file from a URL in github as folks install it?

That's a possibility. For now one would have to download the add-on first though and then install it from disk. However, it is on our todo list to allow an URL as add-on location. We could add this to our next sprint. We have several contributors at the moment who are interested in adding/providing add-ons. In most case it would make more sense if this add-ons live in their corresponding repo and users can just provide an URL. Also frees us to a certain degree from maintaining the add-ons ;-)

**Comment by hferentschik** [comment] 2017-06-16 15:00
Ok, re-opening this issue and closing #860 instead. Seems the action is taking place here :-)

**Comment by hferentschik** [comment] 2017-06-16 15:04
So the issue I was referring to was #635. So we would be looking at something like:

    $ minishift addon install http://fabric8.io/minishift/addon/latest

**Comment by budhrg** [comment] 2017-06-16 15:05
> So the issue I was referring to was #635. So we would be looking at something like:

I was searching it :) . Thanks for putting it here.

**Comment by hferentschik** [comment] 2017-06-19 20:34
Please have a look at https://github.com/minishift/minishift/issues/635#issuecomment-309565251.
I tried to think the http location through a bit and I think the URL would need to point to an archive of sorts (zip, tar). Would that work for you?

**Comment by rawlingsj** [comment] 2017-06-19 21:31
I wonder if github releases might be useful too as they support  `latest` in the URL? It might make it easier for folks to create their own addons too.  

for example:
```
minishift addon install https://github.com/fabric8io/fabric8-resources/releases/latest
```
Creating zip / tar can be done although sometimes it's nice to take a quick look (on github for example) at the script / yaml you're installing first?

**Comment by jstrachan** [comment] 2017-06-19 21:42
I've made the release process update a canonical file we can just refer to - kinda like the 'latest' on GitHub releases but without needing tar balls or redirects 
https://github.com/fabric8io/fabric8-resources/blob/master/fabric8-system-openshift.yml

**Comment by rawlingsj** [comment] 2017-06-19 21:44
That's nice.

**Comment by hferentschik** [comment] 2017-06-20 09:37
> I've made the release process update a canonical file we can just refer to - kinda like the 'latest' on GitHub releases but without needing tar balls or redirects
https://github.com/fabric8io/fabric8-resources/blob/master/fabric8-system-openshift.yml

Not quite sure I follow. As Minishift add-on you need a *.addon file as well as any additional resources, e.g. JSON and YAML files. Somehow we need to download the whole add-on "bundle".

**Comment by jstrachan** [comment] 2017-06-20 09:44
@hferentschik my comment above referred to how to access the latest fabric8 release YAML from inside the `fabric8.addon` without doing any magic bash commands

**Comment by jstrachan** [comment] 2017-06-20 09:48
here's a first spike at a `fabric8.addon`
https://gist.github.com/jstrachan/4ddcf5b0cf64d485d2a917e3df89078f#file-addon-sh

I suspect its a little way from being usable mind you ;) 

One thing I'm not sure is how to port this command to work inside an addon:
https://gist.github.com/jstrachan/4ddcf5b0cf64d485d2a917e3df89078f#file-addon-sh-L12-L21

i.e. we want to embed a simple blob of YAML we can `oc create` using some variable interpolation. 

I noticed that the xpass addon includes local files:
https://github.com/minishift/minishift/tree/master/addons/xpaas

are the variables interpolated before the files get passed to the `oc create` command?

Also can we refer to environment variables from inside the addon? Would like to let the user pass in the github client ID + secret via environment variables if possible: 
https://gist.github.com/jstrachan/4ddcf5b0cf64d485d2a917e3df89078f#file-addon-sh-L8

**Comment by jstrachan** [comment] 2017-06-20 10:27
aha - I could use an openshift template! :) lemme just do that!

**Comment by jstrachan** [comment] 2017-06-20 10:54
here's my latest attempt at an addon:
https://gist.github.com/jstrachan/0d9bb130ffbb4f2f64316fb20d8f6daf

I'm stuck on 2 parts. enabling CORS via something like this:
```
minishift openshift config set --patch '{"corsAllowedOrigins": [".*"]}'
```
being able to run `oc process .... | oc apply -f -` so that we can process a template, substitute parameters using interpolation like these lines:
* https://gist.github.com/jstrachan/0d9bb130ffbb4f2f64316fb20d8f6daf#file-fabric8-addon-sh-L9
* https://gist.github.com/jstrachan/0d9bb130ffbb4f2f64316fb20d8f6daf#file-fabric8-addon-sh-L13

any idea?

**Comment by jorgemoralespou** [comment] 2017-06-20 11:13
@hferentschik Agree with @jstrachan on the first point. That's one of the requirements we missed to discuss when talking about addons.

This is how I do:
- On addon, if it requires a restart, I mark it to be restarted after the addons has been applied.
https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/plugins.d/pipelines.local.plugin#L33

- This just sets a flag, that will instruct the main process to restart when finished
https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L85-L88

- A restart will happen if marked
https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L1080

- This is how a restart happens for "oc cluster"
https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L90-L97

**Comment by jstrachan** [comment] 2017-06-20 11:14
BTW @jorgemoralespou just helped me out on twitter, I can use `oc new-app --template=bar --param=foo` instead of `oc process .... | oc apply -f -`

**Comment by jstrachan** [comment] 2017-06-20 13:11
here's my first spike https://github.com/minishift/minishift/pull/1043

its close.

current pending issues are:
* routing-suffix does not seem to work? Any ideas why [these expressions](https://github.com/jstrachan/minishift/blob/91814cf1403e5721931dd7ffc06cc74f7e44b8ff/addons/fabric8/fabric8.addon#L30) don't get evaluated? 
* does not enable CORS
* does not pass in the github OAuth client ID or secret (e.g. from env vars?)

**Comment by gbraad** [comment] 2017-06-26 05:38
@jstrachan CORS enablement has been mentioned in https://github.com/minishift/minishift/issues/1047#issuecomment-309847261

**Comment by hferentschik** [comment] 2017-08-07 10:10
I am going to close this issue in favour of https://github.com/minishift/minishift-addons/issues/4.

We created a dedicated repository for collecting community contributed add-ons. Let's add this add-on there.

**Closed by hferentschik** 2017-08-07 10:10 UTC
Labels: component/addons, kind/task, priority/major
