### ISSUE TITLE
"minishift start --public-hostname mycluster" causes minishift console inaccessible

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#838] opened 2017-04-27 12:06 UTC
Enviornment : 

```
os - OS X
hypervisor - xhyve
Minishift rc2
iso - minishift-b2d.iso(v1.0.2)
```

Steps to reproduce : 
```
1. Use minishift rc2 binary
2. Run command  "minishift start --public-hostname mycluster"
3. Open web console (minishift console)
4. The url https://mycluster:8443/console/ throws "Server not found"
```
```
$ minishift start --public-hostname mycluster
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MB / 40.00 MB [==========================================================================================================================================================================] 100.00% 0s
Downloading OpenShift binary 'oc' version 'v1.5.0-rc.0'
 18.93 MB / 18.93 MB [==========================================================================================================================================================================] 100.00% 0s
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0-rc.0 image ... 
   Pulling image openshift/origin:v1.5.0-rc.0
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 85% complete
   Pulled 2/3 layers, 95% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.64.2 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://mycluster:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

$ minishift console
Opening the OpenShift Web console in the default browser...
$ minishift status
Running
$ curl -I https://mycluster:8443/console/
curl: (6) Could not resolve host: mycluster
```

**Comment by praveenkumar** [comment] 2017-04-28 03:33
@amitkrout This is not a bug `--public-hostname` is something which is accessible publicly and here you put `mycluster` which is not accessible publicly. This worked as expected, I am closing this now.

**Closed by praveenkumar** 2017-04-28 03:33 UTC

**Comment by ylacaute** [comment] 2017-09-01 15:42
@praveenkumar 
Hi, what we should understand with your message ? The option **--public-hostname** ask for a hostname. So when we start minishift with a particular hostname, we can see in logs :

**The server is accessible via web console at:
    https://myhost:8443**

But this is not true. What we should expect with the option then ? And what we can do in order to be accessible ? 

We tryed to build set up an apache proxy in front of minishift but this seems not possible : after the redirction to /console, some JS scripts seems to be loaded aysnch doing new http request with an hardcoded ip (of the vm), we suppose your scripts should use "window.location.origin" instead, we maybe have be no problem to create this apache proxy.

Thanks for your help.

**Comment by chilcano** [comment] 2017-09-21 11:14
I've used `$ minishift start --public-hostname myhost` and had to add `myhost` to `/etc/hosts`, in this way i can connect to web console `https://myhost:8443/console` without problems and redirections because the generated TLS/SSL certificate had 2 new entries with `myhost` and the ip address in the `SubjectAltName` attribute.

Now, I would like to set a proper minishift's VM hostname instead using the `--profile` value. 
Seems `--public-hostname` is not used to set the minishift's VM hostname.

Any idea?.
