### ISSUE TITLE
minishift start not  working on HyperV with B2D ISO

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2347] opened 2018-04-28 04:24 UTC
### General information

  * Minishift version: 
  * OS: Windows
  * Hypervisor : Hyper-V

### Steps to reproduce

  1. Run `minishift start` in Windows 10 with HyperV setup

### Actual
```
PS C:\Users\lmohanty\Downloads\minishift-1.16.1-windows-amd64\minishift-1.16.1-windows-amd64> .\minishift.exe start
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'external' ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ........................................................................................................................................ FAIL E0428 03:11:45.806730    7744 start.go:369] Error starting the VM: Error creating the VM. Error creating machine: Error detecting OS: OS type not recognized. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error detecting OS: OS type not recognized
```

However it runs fine with `CenTOS` ISO on the same setup

```
.\minishift.exe start --iso-url centos
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'external' ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.9.0/minishift-centos7.iso'
 326.00 MiB / 326.00 MiB [======================================================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ................................................................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'openshift/origin:v3.9.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.9.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.9.0' . CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
Pulling image openshift/origin:v3.9.0
Pulled 0/4 layers, 4% complete
Pulled 1/4 layers, 30% complete
Pulled 2/4 layers, 51% complete
Pulled 3/4 layers, 80% complete
Pulled 3/4 layers, 98% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
Using nsenter mounter for OpenShift volumes
Using 192.168.2.3 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.2.3:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Exporting of OpenShift images is occuring in background process with pid 4216.
```
### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by LalatenduMohanty** [comment] 2018-04-28 07:04
Ironically when ever I am running with `> .\minishift.exe start --show-libmachine-logs -v5` it is working fine. I will give it few more iterations of `minishift start` and then see what happens.

**Comment by amitkrout** [comment] 2018-04-30 07:29
@LalatenduMohanty I don't see any problem in minishift start with default b2d iso + hyperv + minishift-1.16.1.

**Comment by gbraad** [comment] 2018-04-30 07:49
me neither

**Comment by gbraad** [comment] 2018-05-02 03:45
any update ?

**Comment by gbraad** [comment] 2018-05-03 04:30
please describe your setup

**Comment by anjannath** [comment] 2018-05-22 09:00
Working for me in win10, @LalatenduMohanty Were you able to start it?

**Comment by praveenkumar** [comment] 2018-05-25 07:04
Closing this looks like some issue with the machine which @LalatenduMohanty is having? We can reopen if continue to reproduce.

**Closed by praveenkumar** 2018-05-25 07:04 UTC
Labels: kind/bug, os/windows, status/needs-info
