### ISSUE TITLE
Add an option to disable the internet check

### ISSUE THREAD

**Issue by svenstaro** [minishift/minishift#2244] opened 2018-04-05 13:54 UTC
Recently a check in start_preflight.go was introduced that uses CheckInternetConnectivity to check whether github.com is reachable. This is  a problem if you're relying on a proxy because then you'll have to wait for the check to fail in order to be able to continue.

I think it should be possible to disable this check via command line flag.

**Comment by praveenkumar** [comment] 2018-04-06 04:03
@svenstaro As of now, we have an option to skip some of the test using config set command. Are you getting issue this network connectivity check failed because of a proxy environment and then minishift not allow you to continue or it just test taking some time to fail and then continue ?

```
$ minishift config set skip-check-openshift-release true
```

**Comment by gbraad** [comment] 2018-04-07 13:59
Duplicate of #1628

Sorry to be picky. Can we close this issue instead as invalid, as the skip is available, it was a warning by design for this purpose and it is documented.

**Closed** 2018-04-07 14:00 UTC
Labels: resolution/invalid
