### ISSUE TITLE
Dynamically generate the list of command references in the layout.erb file

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#809] opened 2017-04-23 06:14 UTC
Dynamically generate the layout content for command references [here](https://github.com/minishift/minishift/blob/master/docs/source/layouts/layout.erb#L133-L205).

Right now, unable to get the command reference for `minishift openshift registry`.

**Comment by hferentschik** [comment] 2017-04-23 13:30
This is a duplicate of #721

**Closed by hferentschik** 2017-04-23 13:30 UTC
Labels: component/build, kind/task, priority/minor
