### ISSUE TITLE
Problems spinning up OpenShift when Minishift instance changed IP address (Hyper-V)

### ISSUE THREAD

**Issue by thesteve0** [minishift/minishift#593] opened 2017-03-23 02:52 UTC
#I provisioned this machine at home last night.
```
PS C:\Users\steve> minishift start --memory 12048 --cpus 3 --vm-driver hyperv --openshift-version v1.5.0-rc.0

and it came up fine.

Tonight I am behind a hotel wifi and when I go to start the machine again I get

PS C:\Users\steve> minishift start --memory 12048 --cpus 3 --vm-driver hyperv --openshift-version v1.5.0-rc.0
Starting local OpenShift cluster using 'hyperv' hypervisor...
Provisioning OpenShift via 'C:\Users\steve\.minishift\cache\oc\v1.5.0-rc.0\oc.exe [cluster up --use-existing-config --host-config-dir /var/lib/minishift/opens
hift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 172.20.15.217.nip
.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0-rc.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 172.20.15.217 as the server IP
-- Starting OpenShift container ... FAIL
   Error: Docker run error rc=2
   Details:
     Image: openshift/origin:v1.5.0-rc.0
     Entrypoint: [/bin/bash]
     Command: [-c for name in 172.20.15.217 minishift; do ls /var/lib/origin/openshift.local.config/node-$name &> /dev/null && echo $name && break; done]

E0322 22:49:26.859689    2424 start.go:364] Error starting the cluster:  exit status 1
```

Not sure how to debug and I am only here for a couple of hours. I have noticed Hyper-V internet problems on hotel networks. Happened to me in Brno as well. We should do some sort of testing on wifi that has a "sign in" portal.

**Comment by thesteve0** [comment] 2017-03-23 03:06
More diagnosis:
 
![image](https://cloud.githubusercontent.com/assets/1404099/24230195/1afc4e6c-0f54-11e7-8e1a-ef50b3f483bb.png)

So this is definitely a hyper-V

Ok other people hit against this:

https://www.credera.com/blog/technology-insights/microsoft-solutions/using-your-windows-8-wireless-connection-inside-hyper-v/

Will try and report back

**Comment by thesteve0** [comment] 2017-03-23 03:32
So I don't have a sharing option on my wifi adapter or the bridged network it is a part of. I will spend some time researching a bit

**Comment by budhrg** [comment] 2017-03-23 04:09
@thesteve0 

> I provisioned this machine at home last night.
PS C:\Users\steve> minishift start --memory 12048 --cpus 3 --vm-driver hyperv --openshift-version v1.5.0-rc.0

When you provisioned it with hyperv, you used Virtual Switch (say switch1) mapped to your home network.

> Tonight I am behind a hotel wifi and when I go to start the machine again I get

At this point, you are in different network but the switch you were using `switch1` is mapped to your home network. Please confirm this.

One other issue we found yesterday is that if we have multiple switches then the very *1st switch* is got selected during VM creation. Now, if this *1st switch* doesn't map to network interface card/adapter which has internet then, there will be issues in provisioning as you experience.


As a thumb rule for HyperV at the moment:
- Check in the HyperV Manager, the first switch is always connected to  network interface card/adapter with internet available

**Comment by thesteve0** [comment] 2017-03-23 04:17
I have an external wlan that is attached to my wireless network. 

I am on that same switch right now which is supposed to talk to my wireless card. This only happens on Hotel networks. 

Yeah I know to change it when I upgrade or make a new VM. I am attached to the same one I was last night which is talking over wireless

**Comment by budhrg** [comment] 2017-03-23 04:24
@thesteve0 

Then, it might be due to flaky network connections at Hotel. 

> We should do some sort of testing on wifi that has a "sign in" portal.

This seems to interesting testing. 

> It would be great if we could doc a solution for this.

It might be difficult for us to reproduce this issue at our end. Any particular steps we need to go through to hit this issue?

**Comment by thesteve0** [comment] 2017-03-23 04:35
Nope network is working like a champ on my host os - nice and fast with little to no latency. 

I think it is take your minishift on a windows 10 laptop with hyper-v to some place that makes you sign into a portal to get on wifi and you should hit it.

**Comment by gbraad** [comment] 2017-03-23 08:41
I analyzed the issue and it is exactly the same problem as described in #343. According to the info in thois issue, this should be resolved in version 1.6.

**Comment by LalatenduMohanty** [comment] 2017-03-23 12:55
@thesteve0 Going to close this as this is a duplicate of #343. Let us know if you differ. We can continue the discussion on #343.

**Closed by LalatenduMohanty** 2017-03-23 12:55 UTC
Labels: kind/bug, priority/major, resolution/duplicate

**Comment by thesteve0** [comment] 2017-03-23 13:02
No it's not a duplicate. This is specific to being behind a WiFi portal. I
have no problem with changing ips

**Comment by budhrg** [comment] 2017-03-23 14:30
@thesteve0 , I hit this issue with exact error logs in Fedora 24. It seems to duplicate of #343 

```
$ minishift start --vm-driver virtualbox    
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Provisioning OpenShift via '/home/budhram/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.99.100.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.4.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.99.100 as the server IP
-- Starting OpenShift container ... FAIL
   Error: Docker run error rc=2
   Details:
     Image: openshift/origin:v1.4.1
     Entrypoint: [/bin/bash]
     Command: [-c for name in 192.168.99.100 minishift; do ls /var/lib/origin/openshift.local.config/node-$name &> /dev/null && echo $name && break; done]
E0323 19:57:04.569304   12743 start.go:379] Error starting the cluster:  exit status 1
```

I had minishift instance stopped with IP `192.168.99.101` but when I start again, then it is taking `192.168.99.100` and failing.
