### ISSUE TITLE
Web Console not displaying, OS X, --vm-driver vmwarefusion, 1.0.0-beta.4

### ISSUE THREAD

**Issue by starksm64** [minishift/minishift#498] opened 2017-03-02 01:45 UTC
I have started a mini shift cluster using the vmwarefusion driver on OS X 10.11.6. I'm using the 1.0.0-beta.4 build download.
[tmp 572]$ minishift version
Minishift version: 1.0.0-beta.4

while I am able to start the cluster and deploy apps, I am unable to view the web console. When I login, I see:

> An error has occurred
> 
> Unable to load details about the server. If the problem continues, please contact your system administrator.

![webconsolescreen](https://cloud.githubusercontent.com/assets/332210/23489156/bf47288a-fea5-11e6-9f94-aba39c39eaaa.png)

Where would I look for more information about why the web console is not displaying?

**Comment by budhrg** [comment] 2017-03-02 06:40
@starksm64 , We haven't tested vmwarefusion driver well enough yet. 

By any means, you are using Safari to open web console? You might want to look this issue https://github.com/minishift/minishift/issues/199.

We will try to first reproduce it at our end.

**Comment by starksm64** [comment] 2017-03-02 06:46
Yes, I was using Safari. I have tried opening the console in Chrome and I am able to login and see the web console as expected.

**Comment by praveenkumar** [comment] 2017-03-02 06:49
@starksm64 right, I can confirm in safari we get same issue and `minishift console` use default browser driver which is safari for mac. We will try to find out why this is not handled properly in safari. 

Thanks for trying out minishift on a different vm-driver 👍

**Comment by budhrg** [comment] 2017-03-02 07:10
I think we can close this issue as it is duplicate of #199

**Comment by praveenkumar** [comment] 2017-03-02 07:46
I agree, closing this because of duplicate of #199

**Closed by praveenkumar** 2017-03-02 07:46 UTC
Labels: os/darwin

**Comment by galderz** [comment] 2017-04-05 11:56
I've just encountered this issue too with OSX + Safari. It works fine with Chrome. Any ideas/workarounds?

**Comment by hferentschik** [comment] 2017-04-05 13:20
the issues are the self signed certificates. Safari does not handle them well.
