### ISSUE TITLE
Extra progress bar during minishift start

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#989] opened 2017-06-05 14:19 UTC
Hi,

I am not able to remember whether we are allowing progress bars during `minishift start`. Anyone experiencing same?

```
 mss
Starting local OpenShift cluster using 'kvm' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sDownloading OpenShift binary 'oc' version 'v1.5.1'
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... 
   Pulling image openshift/origin:v1.5.1
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Pulled 0/3 layers, 3% complete
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Pulled 0/3 layers, 45% complete
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Pulled 1/3 layers, 65% complete
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Pulled 2/3 layers, 90% complete
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Pulled 3/3 layers, 100% complete
   Extracting
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Image pull complete
-- Checking Docker daemon configuration ... OK
 19.96 MiB / 19.96 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s
   Using Docker shared volumes for OpenShift volumes
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s
   Using 192.168.42.203 as the server IP
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s
   Creating initial OpenShift configuration
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Starting OpenShift using container 'origin'
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   Waiting for API server to start listening
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s   OpenShift server started
 19.96 MiB / 19.96 MiB [==========================================================================================================================] 100.00% 0s 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0sOK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.203:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

 40.00 MiB / 40.00 MiB [==========================================================================================================================] 100.00% 0s
```

**Comment by gbraad** [comment] 2017-06-05 14:26
if you resize your terminal you can end up having the same problem.. user problem I call this. Should we address this? (The user did get the feedback to his action, just not what he expected to see)

**Comment by jorgemoralespou** [comment] 2017-06-05 14:29
@here all these progress bars suck. :-(

**Comment by LalatenduMohanty** [comment] 2017-06-05 14:29
I am seeing 
```
$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [===============================================================================================================================================================================] 100.00% 0s
 40.00 MiB / 40.00 MiB [===============================================================================================================================================================================] 100.00% 0sDownloading OpenShift binary 'oc' version 'v1.5.1'
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... 
   Pulling image openshift/origin:v1.5.1
 40.00 MiB / 40.00 MiB [===============================================================================================================================================================================] 100.00% 0s   Pulled 0/3 layers, 3% complete
 40.00 MiB / 40.00 MiB [===============================================================================================================================================================================] 100.00% 0s   Pulled 1/3 layers, 47% complete
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s   Pulled 2/3 layers, 90% complete
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s   Pulled 3/3 layers, 100% complete
   Extracting
 40.00 MiB / 40.00 MiB [===============================================================================================================================================================================] 100.00% 0s   Image pull complete
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s-- Checking Docker daemon configuration ... OK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s
   Using Docker shared volumes for OpenShift volumes
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s
   Using 192.168.42.211 as the server IP
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s
   Creating initial OpenShift configuration
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s   Starting OpenShift using container 'origin'
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s   Waiting for API server to start listening
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s   OpenShift server started
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s-- Adding default OAuthClient redirect URIs ... OK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0sOK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.211:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

 19.96 MiB / 19.96 MiB [===============================================================================================================================================================================] 100.00% 0s
```

**Comment by gbraad** [comment] 2017-06-05 14:35
currently testing in a different way (godog), so... you see this during normal usage now with master? If so, this is a blocker... right?

**Comment by budhrg** [comment] 2017-06-05 14:36
> you see this during normal usage now with master

Yes, blocker

**Comment by jorgemoralespou** [comment] 2017-06-05 14:48
@gbraad yeah, I downloaded a release on friday to get "addons apply" functionality, and it's no good

**Comment by LalatenduMohanty** [comment] 2017-06-05 18:13
It seems https://github.com/minishift/minishift/commit/bc3fb3e1a53c6ef4aa3fcdb876ce53a7f159f4f3 is the bad commit. 

On master, revert the commit and then see if you can reproduce it. 
```
$ git revert bc3fb3e1a53c6ef4aa3fcdb876ce53a7f159f4f3
```

**Comment by hferentschik** [comment] 2017-06-05 18:19
I don't see this issue at all on OS X. @LalatenduMohanty, not sure about this commit you are pointing out. It am not sure why this should be causing this issue.

**Comment by LalatenduMohanty** [comment] 2017-06-05 18:35
@hferentschik I am seeing this on OS X as well. The issue is with fresh installs
```
$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0s
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0sDownloading OpenShift binary 'oc' version 'v1.5.1'
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0s
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0s-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... 
   Pulling image openshift/origin:v1.5.1
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s   Pulled 0/3 layers, 3% complete
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s   Pulled 1/3 layers, 83% complete
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0s   Pulled 2/3 layers, 89% complete
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0s   Pulled 3/3 layers, 100% complete
   Extracting
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s   Image pull complete
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0sOK
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0sOK
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s
   Using Docker shared volumes for OpenShift volumes
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0sOK
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s
   Using 192.168.64.7 as the server IP
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s
   Creating initial OpenShift configuration
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s   Starting OpenShift using container 'origin'
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0s   Waiting for API server to start listening
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s   OpenShift server started
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0sOK
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0sOK
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0sOK
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0sOK
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0sOK
-- Login to server ... OK
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0sOK
-- Removing temporary directory ... OK
 40.00 MiB / 40.00 MiB [====================================================================================================================================================================] 100.00% 0s
 18.94 MiB / 18.94 MiB [====================================================================================================================================================================] 100.00% 0s^C
```

**Comment by LalatenduMohanty** [comment] 2017-06-05 18:37
I am not sure why the said commit is an issue. Thats something we need to find out.

**Comment by hferentschik** [comment] 2017-06-05 18:37
Turns out the issue only occurs when our code makes use of the progress bar, aka it needs to download the ISO or oc. Most likely it is related to the update to cheggaaa in the commit @LalatenduMohanty pointed out. Either the latest version of cheggaaa has a bug or it requires some additional pulldown information.

**Comment by hferentschik** [comment] 2017-06-05 18:38
> I am not sure why the said commit is an issue. Thats something we need to find out.

Because _ cheggaaa_ got updated as well.

**Comment by LalatenduMohanty** [comment] 2017-06-05 18:48
@hferentschik You are right, after I used the older version of `cheggaaa`  the issue got fixed. 

```{r}
$ git diff
diff --git a/glide.lock b/glide.lock
index a02c90f5..45c24867 100644
--- a/glide.lock
+++ b/glide.lock
@@ -175,7 +175,7 @@ imports:
   - internal/urlfetch
   - urlfetch
 - name: gopkg.in/cheggaaa/pb.v1
-  version: f6ccf2184de4dd34495277e38dc19b6e7fbe0ea2
+  version: b6229822fa186496fcbf34111237e7a9693c6971
 - name: gopkg.in/yaml.v2
   version: cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b
 testImports: []
```

**Comment by hferentschik** [comment] 2017-06-05 18:52
@LalatenduMohanty I am working on a patch. cheggaaa did not have a pinned version, hence we ran into this issue during the last upgrade.

**Comment by LalatenduMohanty** [comment] 2017-06-05 18:56
@hferentschik ok, I was interested to fix this issue, hence was working towards fixing it.

**Comment by hferentschik** [comment] 2017-06-05 19:03
cheggaaa did not have a pinned version which was introducing the issue as side effect of the docker-machine upgrade. Pull request #991 will pin cheggaaa to the last known working version.

Moving forward, I'd like to replace cheggaaa once we get a chance to work on some ux gloss.

**Comment by gbraad** [comment] 2017-06-06 01:48
we will have to manually merge, as CircleCI is not triggered

**Comment by gbraad** [comment] 2017-06-06 02:49
Merged

**Closed by gbraad** 2017-06-06 02:49 UTC
Labels: kind/bug, priority/blocker
