### ISSUE TITLE
oc login system:admin prompting for password

### ISSUE THREAD

**Issue by thomasmckay** [minishift/minishift#2442] opened 2018-06-08 12:17 UTC
### General information

https://github.com/minishift/minishift/pull/2422

After _minishift start_ against a centos7 vm, _oc login system:admin_ is prompting for a password.

Logs seemed to be without error, including this:
```
About to run SSH command:
/var/lib/minishift/bin/oc login -u system:admin
SSH cmd err, output: <nil>: Logged into "https://192.168.123.240:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "myproject".
```

**Comment by LalatenduMohanty** [comment] 2018-06-11 08:03
@thomasmckay It seems to be a duplicate of #2107. I guess you had `admin-user` add-on enabled right?

**Comment by thomasmckay** [comment] 2018-06-11 13:30
@LalatenduMohanty - Yes, I _minishift addon apply admin-user_ after _minishift start_ and can then use the _admin_ user as a workaround. My issue appears to be same as 2107.

**Comment by praveenkumar** [comment] 2018-06-13 13:10
After doing some debugging looks like we can't make this behaviour back again since now cluster up happen inside the vm and `system:admin` user created with it along the certs (something like below), there is currently no way we take that outside and update the current config file until we again put a logic to parse and update which might not work in longer term since `~/.kube/config` does contain lot of different type of cofiguration as per provider (like openshift, kubernetes, GKE, azure ...etc.)

I am thinking to make `admin-user` addon as part of post clusterup so that it will be always there without the addon and then depreicate the `admin-user` addon after 1-2 releases.

@minishift/minishift-dev comments/Suggestions?

**Comment by gbraad** [comment] 2018-06-14 09:00
Not completely following the reason why this can't work. what is missing compared to before?

**Comment by LalatenduMohanty** [comment] 2018-06-14 10:03
> what is missing compared to before?

The issue is we did not have to anything extra to make `oc login -u system:admin` work as `oc` binary was on the host and it was implicitly doing all teh changes in ~/.kube (we were using cluster up on remote docker daemon).  But now we run `oc cluster up` in the VM itself s we need explicitly do changes in kube config to make this work. 

@praveenkumar  the issue is that in the output of `minishift start` we say `oc login -u system:admin` will work.  So either we change the output of `minishift start` by removing ` oc login -u system:admin` and saying ` oc login -u admin -p admin` or we need code changes to make sure ` oc login -u system:admin` works. 

```
$ minishift start
-- Starting profile 'minishift'
-- Check if depereccated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .............. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'openshift/origin:v3.9.0' ......... OK
   Importing 'openshift/origin-docker-registry:v3.9.0' .. OK
   Importing 'openshift/origin-haproxy-router:v3.9.0' .. OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Copying oc binary from the OpenShift container image to VM . OK
-- Starting OpenShift cluster ...................................
Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.64.2 as the host IP
Using 192.168.64.2 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.2:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
```

**Comment by LalatenduMohanty** [comment] 2018-06-14 10:17
Personally I think we need to do code changes to make `oc login -u system:admin` work.

**Comment by gbraad** [comment] 2018-06-14 10:29
I'd rather change the message first.

Changes , as improvement, can follow later

**Comment by praveenkumar** [comment] 2018-06-19 07:41
I spend some more time today and there is no way as of now to merge the kubeconfig file on fly. Kubernetes/Openshift uses `KUBECONFIG` env variable to look up and that variable does have a capability to merge, but again this is run by the user.

- https://stackoverflow.com/questions/46184125/one-line-kubectl-command-to-merge-config-file-with-kube-config
- https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#append-home-kube-config-to-your-kubeconfig-environment-variable

I am not thinking to modify the output message from the `oc cluster up` and display what user should used for login as administrator.

@minishift/minishift-dev wdyt?

**Comment by alexellis** [comment] 2018-06-21 14:08
I'm completely stuck setting up minishift because of this breaking change. Could anyone point me in the right direction to get this command working on minishift? I also get prompted for a password.

```
$ minishift version
minishift v1.19.0+1750702
```

**Comment by alexellis** [comment] 2018-06-21 14:10
```
oc login https://192.168.99.102:8443  -u system:admin
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Authentication required for https://192.168.99.102:8443 (openshift)
Username: system:admin
Password: 
```

I can't get past this - following example by @mhausenblas from the OpenShift blog. https://blog.openshift.com/openfaas-on-openshift/

If I leave off the IP I get a different error:

```
oc login -u system:admin
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

error: couldn't get https://104.198.175.52:443/.well-known/oauth-authorization-server: unexpected response status 403
```

**Comment by LalatenduMohanty** [comment] 2018-06-21 14:57
@alexellis Please check the workaround https://github.com/minishift/minishift/issues/2107#issuecomment-396160071 and we are trying to fix the issue asap.

**Comment by LalatenduMohanty** [comment] 2018-06-21 14:58
Closing this issue as a duplicate of https://github.com/minishift/minishift/issues/2107

**Closed by LalatenduMohanty** 2018-06-21 14:58 UTC
Labels: kind/bug, priority/major
