### ISSUE TITLE
Build fail due to Asset not initialized

### ISSUE THREAD

**Issue by praveenkumar** [MiniShift/minishift#149] opened 2016-11-07 12:13 UTC
If I try to do `go build` on minishift it failed with below error. I was able to find the root cause of this issue and will send a PR which success the compilation.

```
$ go build github.com/jimmidyson/minishift/
# github.com/jimmidyson/minishift/pkg/minikube/cluster
src/github.com/jimmidyson/minishift/pkg/minikube/cluster/openshift_caching.go:42: undefined: Asset
```

**Comment by jimmidyson** [comment] 2016-11-07 12:16
Dupe of #148

**Closed by jimmidyson** 2016-11-07 12:16 UTC
