### ISSUE TITLE
Minikube ISO provisioning breaks the permissions for *.pem

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#2098] opened 2018-03-08 09:09 UTC
Not sure what causes this, but the error is as follows:

```
-- Starting Minishift VM .................................... FAIL E0308 07:02:31.205081  230055 start.go:369] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Copying ca.pem to machine dir failed: open /home/gbraad/.minishift/ca.pem: permission denied. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Copying ca.pem to machine dir failed: open /home/gbraad/.minishift/ca.pem: permission denied
```

When looking at the permissions:
```
-r----x--x. 1 gbraad gbraad 1038 Mar  7 08:56 /home/gbraad/.minishift/ca.pem
```

after `rm -f ~/.minishift/*pem` the permissions on restart look as follows:
```
-rw-rw-r--. 1 gbraad gbraad 1038 Mar  8 08:13 /home/gbraad/.minishift/ca.pem
```

At the moment not sure why this happens, as this is encountered after doing:

```
minishift start --iso-url centos
minishift delete --force
minishift start --iso-url minikube
minishift delete --force
minishift start --iso-url centos
```

which is unlikely to be the cause... something did a `chmod`, and failed...

**Comment by LalatenduMohanty** [comment] 2018-03-08 09:14
@gbraad Is it reproducible ?

**Comment by gbraad** [comment] 2018-03-08 13:03
Consistent after the permission are wrong. Just wonder what changed the permission. Need to look at the utils in the provisioner and check if we are consistent.

**Comment by gbraad** [comment] 2018-03-09 01:29
```
$ minishift start --iso-url centos
$ minishift delete --force
$ minishift start --iso-url minikube
...
-- Starting Minishift VM ..................f............... OK
-- Checking for IP address ... OK
... 
$ minishift delete --force
Deleting the Minishift VM...
Minishift VM deleted.
$ minishift start --iso-url centos
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.1' is valid ... OK
-- Checking if requested OpenShift version 'v3.7.1' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    1 GB
   vCPUs :    1
   Disk size: 5 GB
-- Starting Minishift VM ...................................... FAIL E0309 01:10:31.747456   42461 start.go:369] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Copying ca.pem to machine dir failed: open /home/gbraad/.minishift/ca.pem: permission denied. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Copying ca.pem to machine dir failed: open /home/gbraad/.minishift/ca.pem: permission denied
$ 
```

**Comment by gbraad** [comment] 2018-03-09 01:30
@minishift/minishift-dev reproducible

**Comment by gbraad** [comment] 2018-03-09 01:35
```
-r----x--x. 1 gbraad gbraad 1038 Mar  9 00:58 /home/gbraad/.minishift/ca.pem
```

**Comment by gbraad** [comment] 2018-03-09 01:54
```
$ minishift start --iso-url centos
-- Starting Minishift VM ....................................................... OK
...
$ ls -al ~/.minishift/ca.pem
-rw-rw-r--. 1 gbraad gbraad 1038 Mar  9 01:46 /home/gbraad/.minishift/ca.pem
$ minishift delete --force
Deleting the Minishift VM...
Minishift VM deleted.
$ minishift start --iso-url minikube
-- Starting Minishift VM ................................. OK
...
$ ls -al ~/.minishift/ca.pem                                                                                                                                                                                                                                    130 
-r----x--x. 1 gbraad gbraad 1038 Mar  9 01:52 /home/gbraad/.minishift/ca.pem

**Comment by gbraad** [comment] 2018-03-09 02:12
Definetely in the minikube provisioning code:

```
$ rm -rf ~/.minishift/*.pem       
$ minishift start --iso-url minikube
-- Starting Minishift VM .................................. OK
...
$ ls -al ~/.minishift/ca.pem 
-r----x--x. 1 gbraad gbraad 1038 Mar  9 02:09 /home/gbraad/.minishift/ca.pem
```

**Comment by gbraad** [comment] 2018-03-09 02:32
```
set auth options {CertDir:/home/gbraad/.minishift CaCertPath:/home/gbraad/.minishift/certs/ca.pem CaPrivateKeyPath:/home/gbraad/.minishift/certs/ca-key.pem CaCertRemotePath:/etc/docker/ca.p
em ServerCertPath:/home/gbraad/.minishift/machines/server.pem ServerKeyPath:/home/gbraad/.minishift/machines/server-key.pem ClientKeyPath:/home/gbraad/.minishift/certs/key.pem ServerCertRem
otePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:/home/gbraad/.minishift/certs/cert.pem ServerCertSANs:[] StorePath:/home/gbraad/.minishift}
setting up certificates
(minishift) Calling .GetMachineName
(minishift) Calling .GetIP
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.169
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:3e:94:e6
generating server cert: /home/gbraad/.minishift/machines/server.pem ca-key=/home/gbraad/.minishift/certs/ca.pem private-key=/home/gbraad/.minishift/certs/ca-key.pem org=gbraad.minishift san=[192.168.42.169 localhost]
```

https://github.com/minishift/minishift/blob/master/pkg/minishift/provisioner/buildroot_provisioner.go#L94

**Comment by gbraad** [comment] 2018-03-09 02:46
It does not modify the content:

```
$ minishift start --iso-url centos  
$ ls -al ~/.minishift/ca.pem 
-rw-rw-r--. 1 gbraad gbraad 1038 Mar  9 02:39 /home/gbraad/.minishift/ca.pem
$ sha1sum ~/.minishift/ca.pem 
372a2f5496e65c05b2867d09ea1a4615083f8c51  /home/gbraad/.minishift/ca.pem
$ minishift start --iso-url minikube
$ ls -al ~/.minishift/ca.pem
-r----x--x. 1 gbraad gbraad 1038 Mar  9 02:44 /home/gbraad/.minishift/ca.pem
$ sha1sum ~/.minishift/ca.pem      
372a2f5496e65c05b2867d09ea1a4615083f8c51  /home/gbraad/.minishift/ca.pem
```

**Comment by gbraad** [comment] 2018-03-09 03:25
using
```
minishift delete --force; rm -rf ~/.minishift/*.pem; minishift start --iso-url centos; minishift delete --force; minishift start --iso-url minikube
```
and bisecting with some `panic("")` I see it happens in:

```
 196         for src, dst := range hostCerts {
 197                 f, err := assets.NewFileAsset(src, filepath.Dir(dst), filepath.Base(dst), "0777")
 198                 if err != nil {
 199                         return errors.Wrapf(err, "open cert file: '%s'", src)
 200                 }       
 201                 if err := assets.CopyFileLocal(f); err != nil {
 202                         return errors.Wrapf(err, "transferring file: '%+v'", f)
 203                 }       
 204         }       
 205         
 206         // The Host IP is always added to the certificate's SANs list
 207         hosts := append(authOptions.ServerCertSANs, ip, "localhost")
 208         log.Debugf("generating server cert: %s ca-key=%s private-key=%s org=%s san=%s",
 209                 authOptions.ServerCertPath,
 210                 authOptions.CaCertPath,
 211                 authOptions.CaPrivateKeyPath,
 212                 org,
 213                 hosts,
 214         )     
```

**Comment by gbraad** [comment] 2018-03-09 04:11
From what it looks like, doing this

https://github.com/minishift/minishift/blob/2b3e3a210089bf748730daf8fdd71ec44dde3bcc/pkg/minishift/provisioner/utils.go#L201

causes the change in permissions

**Comment by LalatenduMohanty** [comment] 2018-04-04 11:39
Closing this issue as it is duplicate of #2063

**Comment by LalatenduMohanty** [comment] 2018-04-04 11:51
Reopening it as it is slightly different issue than #2063

**Closed** 2018-04-11 10:36 UTC
Labels: kind/bug, priority/major
