### ISSUE TITLE
Error starting minishift in windows

### ISSUE THREAD

**Issue by GolanTrevize10** [minishift/minishift#745] opened 2017-04-12 13:38 UTC
Hi, I'm trying to start minishift 1.0.0rc1 using virtualbox 5.1.18 in Windows. When I run minishift start for the first time I get this error:
```

Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0412 15:19:43.506075   17164 start.go:164] Error starting the VM: Error creatin
g the VM. Error creating machine: Error in driver during machine creation: open
/.minishift/cache/iso/minishift-b2d.iso: The system cannot find the path specifi
ed.. Retrying.
E0412 15:19:43.891575   17164 start.go:164] Error starting the VM: Error getting
 the state for host: machine does not exist. Retrying.
E0412 15:19:44.232575   17164 start.go:164] Error starting the VM: Error getting
 the state for host: machine does not exist. Retrying.
E0412 15:19:44.234075   17164 start.go:170] Error starting the VM:  Error creati
ng the VM. Error creating machine: Error in driver during machine creation: open
 /.minishift/cache/iso/minishift-b2d.iso: The system cannot find the path specif
ied.
Error getting the state for host: machine does not exist
Error getting the state for host: machine does not exist
```

The .minishift directory doesn't exist anywhere in my computer. I'm running it from my %USERPROFILE% drive. 

If I try to run it again I get a different output. But if I run minishift delete I get again the first one.

```

Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0412 15:19:57.917575   14216 start.go:164] Error starting the VM: Error getting
 the state for host: machine does not exist. Retrying.
E0412 15:19:58.272075   14216 start.go:164] Error starting the VM: Error getting
 the state for host: machine does not exist. Retrying.
E0412 15:19:58.617075   14216 start.go:164] Error starting the VM: Error getting
 the state for host: machine does not exist. Retrying.
E0412 15:19:58.618575   14216 start.go:170] Error starting the VM:  Error gettin
g the state for host: machine does not exist
Error getting the state for host: machine does not exist
Error getting the state for host: machine does not exist
```

**Comment by LalatenduMohanty** [comment] 2017-04-12 14:13
@GolanTrevize10 Can you please provide the exact commands you executed? Also please let us know which version of Windows you are using?

**Comment by GolanTrevize10** [comment] 2017-04-12 20:24
I'm running minishift start --vm-driver=virtualbox
Using Windows 7.
It looks like it is a proxy problem because I was trying behind my company proxy but if I try with direct connection to internet it works. How can I define my proxy configuration? Setting http_proxy doesn't seem to work

**Comment by LalatenduMohanty** [comment] 2017-04-13 05:59
@GolanTrevize10 Minishift supports proxy. Please check `minishift start --help` usage and you can see --http-proxy and --htps-proxy . Please use the use the flag which is relevant to you and let us know if it fixes the issue you are seeing.

```
Usage:
  minishift start [flags]

Flags:

      --http-proxy string               HTTP proxy for virtual machine (In the format of http://<username>:<password>@<proxy_host>:<proxy_port>)
      --https-proxy string              HTTPS proxy for virtual machine (In the format of https://<username>:<password>@<proxy_host>:<proxy_port>)
```

**Comment by GolanTrevize10** [comment] 2017-04-13 09:00
@LalatenduMohanty  Same error. I think those proxy flags are not used when downloading initial iso, as stated in issue  #718

**Comment by LalatenduMohanty** [comment] 2017-04-13 09:04
@GolanTrevize10 Right. It is duplicate of #718. I am going to close this and we can track this in #718

**Closed by LalatenduMohanty** 2017-04-13 09:04 UTC
Labels: kind/bug, priority/major, resolution/duplicate
