### ISSUE TITLE
Unable to access postgres route

### ISSUE THREAD

**Issue by magick93** [minishift/minishift#504] opened 2017-03-02 18:16 UTC
Hello

I'm trying to access a postgres service.
I've installed https://github.com/sclorg/postgresql-container/tree/master/9.5, and apparently if I set the `POSTGRESQL_ADMIN_PASSWORD` env var, then pg will allow remote connections. I did that but it seems pg is not listening.

I also tried to telnet to the route, and port 5432, but got:
`telnet: Unable to connect to remote host: Connection refused
`

**Comment by hferentschik** [comment] 2017-03-02 18:29
@magick93 - can you provide some more info. How did you install this image? Can you provide the steps to reproduce. I would think that you don't expose the service port.

**Comment by magick93** [comment] 2017-03-02 18:37
Steps to reproduce

1. `minishift start`
2. login to web console as developer
3. In myproject click on `Add to project`
4. Click on `Data Stores`
5. Click on `Select` on `PostgreSQL (Ephemeral)`
6. Customize or go with defaults and click `Create`
7. Then go to deployment config for the newly created data store
8. Click on `Environment` and click on `Add environment variable`
9. Add `POSTGRESQL_ADMIN_PASSWORD` and give any value
10. Create a route by going `Applications` > `Routes` > `Create Route`
11. Name new route `postgresql`. Go with defaults. Ports cannot be changed - only option is `5432 -> 5432`
12. Attempt to connect to postgres either with telnet or pgadmin.

**Comment by jorgemoralespou** [comment] 2017-03-02 22:47
You will most likely not be able to use a route for postgresql. Routes are
for http/https (or ssl over SNI), as in secure traffic SNI is required to
do the mapping from requested url to service.
If you want to test from your localhost, there is 2 easy options:

- port forwarding, where you open forward your localhost:5432 to the
pod:5432. Look into oc port-forward -h examples
- nodePort. This is a special type of service that opens a port (usually
withiin a predefined range) that will be able to route to your service.
That port will be open on the minishift ip. Look for nodePort in the
openshift documentation.

There's a 3rd option, which is more complex, and requires you to add an
additional IP to the VM, so I will not describe it.

Hope this helps.

**Comment by hferentschik** [comment] 2017-03-03 09:07
@magick93 can you try this and verify whether this works for you? If you want to temporary access the db, I guess port forward is easiest. If you are more looking for how to set this up in a more permanent way, I'd say take a look at the NodePort feature.

**Comment by hferentschik** [comment] 2017-05-11 18:59
Closing this issue, since there was no more feedback.

**Closed by hferentschik** 2017-05-11 18:59 UTC
Labels: kind/question, priority/major, status/needs-info
