### ISSUE TITLE
minishift oc command line keeps switching to developer user

### ISSUE THREAD

**Issue by starksm64** [minishift/minishift#1944] opened 2018-01-25 21:38 UTC
### General information

  * Minishift version: v1.12.0+daa0943
  * OS: macOS 10.13.2
  * Hypervisor: VirtualBox

[wildfly-swarm-service-broker 1272]$ type oc
oc is hashed (/Users/starksm/.minishift/cache/oc/v3.7.1/darwin/oc)
[wildfly-swarm-service-broker 1273]$ oc version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62

After switching between projects using the oc command line, I get into a state where oc projects no longer shows all of the projects and fails to show the resources that do exist in the project I'm in. It looks like this is because it keeps switching to the developer user rather than the admin user I was logged in as.

### Steps to reproduce

  1. clone https://github.com/starksm64/wildfly-swarm-service-broker.git
  2. cd wildfly-swarm-service-broker
  3. Follow the steps in the README.md to setup, start minishift and deploy the openshift/jwt-service-broker-template.yml
  4. Run oc projects to see the list of projects. It should show:
[wildfly-swarm-service-broker 1229]$ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    * jwt-service-broker
    kube-public
    kube-service-catalog
    kube-system
    myproject - My Project
    openshift
    openshift-infra
    openshift-node
    openshift-template-service-broker

5. Change to the openshift-template-service-broker

### Expected
I should be able to see all of the projects 

[wildfly-swarm-service-broker 1229]$ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    jwt-service-broker
    kube-public
    kube-service-catalog
    kube-system
    myproject - My Project
    openshift
    openshift-infra
    openshift-node
  * openshift-template-service-broker

### Actual

On changing projects, I keep getting put back to the developer user with myproject selected, and I cannot view the resources of the project I am trying to switch to.

[wildfly-swarm-service-broker 1260]$ oc project jwt-service-broker
Now using project "myproject" from context named "jwt-service-broker" on server "https://192.168.99.100:8443".
[wildfly-swarm-service-broker 1261]$ oc whoami
developer
[wildfly-swarm-service-broker 1262]$ oc login $(minishift ip):8443 -u admin -p admin
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    jwt-service-broker
    kube-public
    kube-service-catalog
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-template-service-broker

Using project "myproject".
[wildfly-swarm-service-broker 1263]$ oc whoami
admin
[wildfly-swarm-service-broker 1264]$ oc project jwt-service-broker
Already on project "myproject" on server "https://192.168.99.100:8443".
[wildfly-swarm-service-broker 1265]$ oc projects
You have one project on this server: "My Project (myproject)".

Using project "myproject" from context named "jwt-service-broker" on server "https://192.168.99.100:8443".
[wildfly-swarm-service-broker 1266]$ oc whoami
developer
[wildfly-swarm-service-broker 1267]$ oc login $(minishift ip):8443 -u admin -p admin
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    jwt-service-broker
    kube-public
    kube-service-catalog
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-template-service-broker

Using project "myproject".
[wildfly-swarm-service-broker 1268]$ oc whoami
admin
[wildfly-swarm-service-broker 1269]$ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    jwt-service-broker
    kube-public
    kube-service-catalog
    kube-system
  * myproject - My Project
    openshift
    openshift-infra
    openshift-node
    openshift-template-service-broker

Using project "myproject" on server "https://192.168.99.100:8443".
[wildfly-swarm-service-broker 1270]$ oc project jwt-service-broker
Already on project "myproject" on server "https://192.168.99.100:8443".
[wildfly-swarm-service-broker 1271]$ oc whoami
developer

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment] 2018-01-29 04:03
@starksm64 I didn't try the `wildfly-swarm-service-broker` but did some experiment around it and not able to reproduce it.

```
$ oc login https://192.168.64.86:8443
Authentication required for https://192.168.64.86:8443 (openshift)
Username: developer
Password: 
Login successful.

You have one project on this server: "myproject"

Using project "myproject".

 $ oc new-project test --as system:admin
Now using project "test" on server "https://192.168.64.86:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
 
$ oc projects
You have one project on this server: "My Project (myproject)".

09:23 $ oc login
Authentication required for https://192.168.64.86:8443 (openshift)
Username: admin
Password: 
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
    myproject
    openshift
    openshift-infra
  * test

Using project "test".

09:23 $ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
    myproject - My Project
    openshift
    openshift-infra
  * test

Using project "test" on server "https://192.168.64.86:8443".

$ oc project myproject
Now using project "myproject" on server "https://192.168.64.86:8443".
 
$ oc whoami
admin
 
$ oc project test
Now using project "test" on server "https://192.168.64.86:8443".

$ oc whoami
admin
```

**Comment by LalatenduMohanty** [comment] 2018-03-01 08:15
Duplicate of #1966.

**Comment by LalatenduMohanty** [comment] 2018-03-01 08:16
@starksm64 Even if this is created before #1966 , #1966 has more discussions and information, so I will suggest closing this issue and tracking it in #1966

**Closed** 2018-03-01 08:18 UTC
Labels: kind/bug, priority/major
