### ISSUE TITLE
Update Xpaas addon

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2879] opened 2018-10-10 15:24 UTC
### General information

Recently there were 2 commits to xpaas, which we should include into xpaas addon:
- https://github.com/openshift/openshift-ansible/commit/f369cf5074bb27d8569b5fe59e974b12430fb351
- https://github.com/openshift/openshift-ansible/commit/55454dd89b0e704ac91abceb6e3936404f0199ad

**Comment by anjannath** [comment] 2018-10-11 07:19
@agajdosi Also there is #2876

**Comment by LalatenduMohanty** [comment] 2018-11-15 09:23
@agajdosi I think this is duplicate of https://github.com/minishift/minishift/issues/2483

**Closed** 2018-11-15 09:24 UTC
Labels: component/addons, kind/task, priority/major
