### ISSUE TITLE
minishift status returns "Does Not Exist" when launched from a terminal without admin right and minishift start was launched from a terminal with admin rights

### ISSUE THREAD

**Issue by apupier** [minishift/minishift#1361] opened 2017-09-11 13:07 UTC
'minishift setup-cdk' requires admin privilege
if using 'minishift start' in the same terminal with admin privileges,
then if launched in a terminal without admin rights, 'minishift status' will return "Does Not Exist"

**Comment by apupier** [comment] 2017-09-11 13:09
@budhrg I think that it was the issue that we encountered during our call

**Comment by LalatenduMohanty** [comment] 2017-09-11 13:26
@apupier you should not need admin privilege for running setup-cdk. Are you getting any error when you run it as an user?  The issue you are facing i.e. ` 'minishift status' will return "Does Not Exist"` should be gone if you run setup-cdk without admin previlage. 

Also it is an CDK issue so we will move it to CDK Jira https://issues.jboss.org/projects/CDK/issues/.

**Comment by apupier** [comment] 2017-09-11 13:29
my bad, it is 'minishift start' which requires admin right

otherwise there is:

> C:\Users\Aurelien Pupier>minishift start
> Starting local OpenShift cluster using 'hyperv' hypervisor...
> E0911 15:28:20.827670   14712 start.go:282] Error starting the VM: Error creating the VM. Error with pre-create check: "Hyper-v commands have to be run as an Administrator". Retrying.
> E0911 15:28:23.485364   14712 start.go:282] Error starting the VM: Error creating the VM. Error with pre-create check: "Hyper-v commands have to be run as an Administrator". Retrying.
> E0911 15:28:26.142630   14712 start.go:282] Error starting the VM: Error creating the VM. Error with pre-create check: "Hyper-v commands have to be run as an Administrator". Retrying.
> Error starting the VM: Error creating the VM. Error with pre-create check: "Hyper-v commands have to be run as an Administrator"
> Error creating the VM. Error with pre-create check: "Hyper-v commands have to be run as an Administrator"
> Error creating the VM. Error with pre-create check: "Hyper-v commands have to be run as an Administrator"

**Comment by gbraad** [comment] 2017-09-11 13:33
Are you sure thr user is allowed to use HyperV? The user needs to be part of the HyperV adminstrators group

**Comment by budhrg** [comment] 2017-09-11 13:33
@apupier , I doubt you ran `minishift setup-cdk` with admin rights.

When we did last time in the call, it was fine AFAIR. 
Could you retry again?

**Comment by apupier** [comment] 2017-09-11 13:38
> Are you sure thr user is allowed to use HyperV? The user needs to be part of the HyperV adminstrators group

the user is not part of Hyper-V admin group as it is the default behavior.

**Comment by gbraad** [comment] 2017-09-11 13:38
https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-driver-plugins.html#insufficient-privileges

**Comment by budhrg** [comment] 2017-09-11 13:41
@apupier https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-driver-plugins.html#insufficient-privileges

User need to be part of admin group.

**Comment by gbraad** [comment] 2017-09-11 13:42
> the user is not part of Hyper-V admin group

Please correct the permissions, as this is necessary to create VMs inside Hyper-V manager

**Comment by apupier** [comment] 2017-09-11 13:45
> the user is not part of Hyper-V admin group
> Please correct the permissions, as this is necessary to create VMs inside Hyper-V manager

this is not necessary, we can also just launch the terminal in admin mode which is even what lead to think to be the correct solution with the error message when it is not the case:

> Error creating the VM. Error with pre-create check: "Hyper-v commands have to be run as an Administrator"

**Comment by apupier** [comment] 2017-09-11 13:50
several things can be improved relatively easily I think:
- when "Does not Run", add a message to explain that you need to launch with the admin mode (or to be in the Hyper-v administrator?)
- when 'minishift start', isntead of "have to be run as an Administrator", something like "have to be run by an Hyper-V administrator. See XXX to configure it"

**Comment by gbraad** [comment] 2017-09-11 13:51
This message comes from the cmdlets from PowerShell and are abstracted by submachine. We can not change these messages

**Comment by gbraad** [comment] 2017-09-11 13:53
It is necessary for the user to be part of the HyperV administrators group as this is the saferopyioncanrunning or having to use administrator. In most caes domain policies forbids users to be part of the local administrator group

**Comment by gbraad** [comment] 2017-09-11 13:55
We can change the pre flightcheck to check if the user is part of the TV admin group,but for this we need a PowerShell abstraction. Part of #1316 ?

**Comment by gbraad** [comment] 2017-09-11 13:56
Duplicate of #356

**Comment by gbraad** [comment] 2017-09-11 13:59
@budhrg can you check if the installer deals with the permissions? Maybe a different preinstalled it from who uses it?

**Comment by gbraad** [comment] 2017-09-12 08:04
I added #1368. Perhaps it is possible to also check for group membership. WDYT?

**Comment by gbraad** [comment] 2017-09-12 11:52
The group membership check with https://github.com/minishift/minishift/issues/1368#issuecomment-328812218 takes 10+ secs and is therefore not usable.

**Comment by gbraad** [comment] 2017-09-13 06:11
Using `@([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Hyper-V Administrators")` to check the permissions works

**Comment by gbraad** [comment] 2017-09-13 07:52
Rephrased the installation of the driver plugin with #1373

**Comment by budhrg** [comment] 2017-09-13 10:50
Resolved via https://github.com/minishift/minishift/pull/1373 with documentation fix.

**Closed by budhrg** 2017-09-13 10:50 UTC
Labels: component/documentation, kind/bug, os/windows, priority/major

**Comment by LalatenduMohanty** [comment] 2017-09-13 10:58
https://github.com/minishift/minishift/issues/1368 will also help to address this issue.
