### ISSUE TITLE
Spike to get Che running on Minishift

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1264] opened 2017-08-14 08:05 UTC
Getting Che running on Minishift can be achieved in different ways:

  * Re-use the Docker environment
  * Running on OpenShift
    * Templates

More info: https://lists.minishift.io/archives/list/minishift@lists.minishift.io/thread/WM4D7ENYJSF6DM5TOY2LJJD2XCQBP3IZ/

**Comment by gbraad** [comment] 2017-08-14 08:22
More information will be collected here over time.

**Comment by budhrg** [comment] 2017-08-14 09:44
The instruction to run che on Fedora 25 works like charm for me
```
$ docker run -p 8080:8080 \
       --name che \
       -v /var/run/docker.sock:/var/run/docker.sock \
       -v /var/chedata:/data:Z -e CHE_HOST=<machine-ip> -e CHE_DOCKER_IP_EXTERNAL=<machine-ip> \
       -e CHE_DOCKER_SERVER__EVALUATION__STRATEGY=docker-local --security-opt label:disable \
       rhche/che-server  # eclipse/che-server
```

**Comment by gbraad** [comment] 2017-08-14 09:56
Using `rhche/che-server` is likely to succeed, as it has been modified. At that time I still experienced issues with `eclipse/che-server`. But running on the docker environment directly is probably not our aim, however it shows the configuration is possible to host Che.

BTW, what were your settings for the VM?

**Comment by amisevsk** [comment] 2017-08-14 17:27
Comment from the Che side: We currently use minishift for Che development on a regular basis. You might be interested in [the repo](https://github.com/redhat-developer/rh-che). The image we deploy has a few extra additions, such as keycloak support, but you should be able to run a build of Che built off the current `openshift-connector-wip` branch.

**Comment by gbraad** [comment] 2017-08-15 00:04
```
$ SCRIPT_URL=https://raw.githubusercontent.com/redhat-developer/rh-che/master/dev-scripts/openshift_deploy.sh
$ curl -fsSL ${SCRIPT_URL} -o deploy-che.sh && sh deploy-che.sh
```

**Comment by l0rd** [comment] 2017-09-13 09:48
To run upstream eclispe che on minishift: https://www.eclipse.org/che/docs/setup/openshift/index.html#deploy-che-on-minishift

And we are currently making it much easier [here](https://github.com/eclipse/che/issues/6097) (I am working on that issue this week).

**Comment by gbraad** [comment] 2017-09-13 10:00
@l0rd would it be possible to see if we can create an addon for Minishift?

  * https://github.com/minishift/minishift/blob/master/docs/source/using/addons.adoc

This way we can make it part of https://github.com/minishift/minishift-addons

**Comment by budhrg** [comment] 2017-09-13 10:02
> This way we can make it part of https://github.com/minishift/minishift-addons

+1 for addon

**Comment by l0rd** [comment] 2017-09-13 10:50
@gbraad @budhrg I will look at that. I've added the related extra-step to https://github.com/eclipse/che/issues/6097

**Comment by gbraad** [comment] 2017-09-13 10:55
If help is needed, let us know... we are in #minishift on freenode.

**Comment by budhrg** [comment] 2017-09-13 11:02
@l0rd  I tried following steps as mentioned in  https://www.eclipse.org/che/docs/setup/openshift/index.html#deploy-che-on-minishift

```
DEPLOY_SCRIPT_URL=https://raw.githubusercontent.com/eclipse/che/master/dockerfiles/cli/scripts/openshift/deploy_che.sh
WAIT_SCRIPT_URL=https://raw.githubusercontent.com/eclipse/che/master/dockerfiles/cli/scripts/openshift/wait_until_che_is_available.sh
STACKS_SCRIPT_URL=https://raw.githubusercontent.com/eclipse/che/master/dockerfiles/cli/scripts/openshift/replace_stacks.sh
curl -fsSL ${DEPLOY_SCRIPT_URL} -o ./get-che.sh
curl -fsSL ${WAIT_SCRIPT_URL} -o ./wait-che.sh
curl -fsSL ${STACKS_SCRIPT_URL} -o ./stacks-che.sh
bash ./get-che.sh && bash ./wait-che.sh && bash ./stacks-che.sh
```

and che deployed successfully, but getting some error in creating workspace.
![screenshot from 2017-09-13 16-25-06](https://user-images.githubusercontent.com/1132451/30374043-1b426222-98a1-11e7-9e4e-8f5a506b49e9.png)
![screenshot from 2017-09-13 16-31-21](https://user-images.githubusercontent.com/1132451/30374044-1b4301be-98a1-11e7-9464-663b2dd68d15.png)

Any idea?

**Comment by budhrg** [comment] 2017-09-13 11:09
Clicking on `Run` button second time did the trick
![screenshot from 2017-09-13 16-38-55](https://user-images.githubusercontent.com/1132451/30374305-1b17649a-98a2-11e7-9322-a856cac59e3b.png)

**Comment by l0rd** [comment] 2017-09-13 11:10
You probably just hit this issue
https://github.com/openshiftio/openshift.io/issues/798

**Comment by budhrg** [comment] 2017-09-13 11:13
@l0rd , I am having `registry.devshift.net/che/vertx` in recipe location. I looks like Vert.X example

**Comment by l0rd** [comment] 2017-09-13 11:21
Ok so that's not the same issue. Maybe workspace creation timed out because
the pull of the image took too long. Can you find any evidence of that in
the logs of che-server pod and openshift events? If so we should create an
issue to make the error message more clear.

**Comment by budhrg** [comment] 2017-09-13 12:00
logs from che build

https://drive.google.com/file/d/0B92iOOnPFHczNjZRZmxSNExTdGs/view?usp=sharing

**Comment by budhrg** [comment] 2017-09-22 10:00
Another issue, while reattempting today

![screenshot from 2017-09-22 15-26-21](https://user-images.githubusercontent.com/1132451/30739301-71d04e6e-9faa-11e7-806b-0edafb149fde.png)

Also, `che-server` image is from nightly

```
$ oc status
In project eclipse-che on server https://192.168.42.137:8443

svc/che-debug (all nodes):31533 -> http-debug
  dc/che deploys docker.io/eclipse/che-server:nightly 
    deployment #1 deployed 12 minutes ago - 1 pod

http://che-eclipse-che.192.168.42.137.nip.io (svc/che-host)
  dc/che deploys docker.io/eclipse/che-server:nightly 
    deployment #1 deployed 12 minutes ago - 1 pod

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
``` 

So might be exactly same as last time.

**Comment by l0rd** [comment] 2017-09-22 10:10
@budhrg Have you ran script `replace_stacks.sh`?

**Comment by budhrg** [comment] 2017-09-22 10:18
> @budhrg Have you ran script replace_stacks.sh?

You mean ` ./stacks-che.sh` right? Yes.

**Comment by gbraad** [comment] 2017-09-22 10:18
@l0rd did you have a look at the addon option for Che on Minishift?

**Comment by budhrg** [comment] 2017-09-22 10:20
https://github.com/eclipse/che/commit/942254eacf4d544fa354cd87ce849a267fa7cf4f seems to be added before 3 days.

**Comment by l0rd** [comment] 2017-09-22 10:32
@budhrg we have made different changes to the stacks so that might be a regression. What the stack that's not starting? `registry.devshift.net/che/vertx`?

@gbraad no but I would be happy to do that. Ideally I should first complete the previous tasks in https://github.com/eclipse/che/issues/6097. Let's say next week or the one right after but let me know if you think it's something that need to be done urgently and I will look at it earlier.

**Comment by budhrg** [comment] 2017-09-22 10:33
> `registry.devshift.net/che/vertx` 

@l0rd , Yes. the default `CentOS Nodejs` stack seems working fine to me.

**Comment by budhrg** [comment] 2017-09-22 10:49
@l0rd ,

Though the workspace for stack `CentOS Nodejs` created successfully, on creating new project via sample `web-nodejs-sample`, I am getting followin error on running it

```
cd && scl enable rh-nodejs4 'node app/app.js'preview:http://${server.port.8080}
Unable to open /etc/scl/conf/rh-nodejs4!
```

Any idea? 

Note: I still need to go through basic working of che.

**Comment by LalatenduMohanty** [comment] 2017-09-22 10:52
> Let's say next week or the one right after but let me know if you think it's something that need to be done urgently and I will look at it earlier.

@l0rd  Thank you. We are actually targeting the next release of upstream Minishift  i.e. v1.7.0 on 9th September 2017.   We should be able to help you for creating an add-on for Minishift. I will start a mail thread for discussing some more details.

**Comment by gbraad** [comment] 2017-09-22 12:10
@budhrg those issues look more like a not up-to-date example...

@LalatenduMohanty @l0rd, although we could go ahead with a single script to run, it would be great to have it wrapped as an addon

**Comment by l0rd** [comment] 2017-09-22 17:30
@budhrg yeah I think you have found a couple of issues in image `centos-nodejs` (cc @dharmit). Sorry about that but the centos-nodejs image hasn't been tested yet really. vert.x and spring-boot should be the stable ones.   

I cannot reproduce your vert.x stack issue though. You may use different image version for che-server. Here is the digest of the image I am using (it correspond to the current latest images pushed to the Docker Hub):
 
```
sha256:e63c1154375c34afbfe52e34a31ebbaef475974a395ffbac6dcaf3a15d3ae3ee"
```
Once the pod is started I've used command `oc get po/<pod-id> -o json | jq .status.containerStatuses[].imageID` to retrieve the imageID that contains the digest.

And by the way I think that you should try it with a stable release instead of nightly. To do so you can run:
```
export CHE_IMAGE_TAG=5.18.0-centos
```
right before executing the scripts to deploy Che.

**Comment by budhrg** [comment] 2017-09-23 15:08
> export CHE_IMAGE_TAG=5.18.0-centos

Thanks for the info @l0rd , I will try with it.

**Comment by LalatenduMohanty** [comment] 2017-10-05 20:24
Created https://github.com/minishift/minishift-addons/issues/42 to track the add-on creation for Che.

**Comment by LalatenduMohanty** [comment] 2017-10-05 20:25
@budhrg Should we close the issue now?

**Comment by budhrg** [comment] 2017-10-07 14:50
Yes @LalatenduMohanty , most of the investigation is done and it's fine to close it now.

**Closed by budhrg** 2017-10-07 14:50 UTC
Labels: component/addons, kind/task, priority/major
