### ISSUE TITLE
Openshift cannot pull the image from the internal registry

### ISSUE THREAD

**Issue by surajssd** [minishift/minishift#1615] opened 2017-10-25 07:01 UTC
**Type of issue**

/kind bug

**Steps to reproduce**

```console
$ eval $(minishift docker-env)
$ oc login -u developer -p developer
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    myproject
  * ticker

Using project "ticker".


$ oc new-project proj
Now using project "proj" on server "https://192.168.42.2:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.


$ docker pull centos/httpd
Using default tag: latest
latest: Pulling from centos/httpd
d9aaf4d82f24: Pull complete 
17695ed7ebda: Pull complete 
603fea4e6d47: Pull complete 
1923be8fd3f1: Pull complete 
Digest: sha256:79eacf66ec2d0eb930b0693dc524c729ea6fa04cb6ca825c0479231e85dc18f8
Status: Downloaded newer image for centos/httpd:latest


$ docker tag centos/httpd docker-registry-default.192.168.42.2.nip.io:443/proj/myhttpd
$ docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.42.2.nip.io:443
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded

$ docker push docker-registry-default.192.168.42.2.nip.io:443/proj/myhttpd
The push refers to a repository [docker-registry-default.192.168.42.2.nip.io:443/proj/myhttpd]
ffdbc94377b2: Pushed 
95847010d10a: Pushed 
2a9e8fbc6354: Pushed 
cf516324493c: Pushed 
latest: digest: sha256:17d46753675e6014df5170d44ff5c748e19ab053afb7be00c79ed99c4b3e0831 size: 1155


$ oc run web --image docker-registry-default.192.168.42.2.nip.io:443/proj/myhttpd
deploymentconfig "web" created

$ oc get pods
NAME           READY     STATUS             RESTARTS   AGE
web-1-8g06l    0/1       ImagePullBackOff   0          4m
web-1-deploy   1/1       Running            0          4m

$ oc get events
LASTSEEN   FIRSTSEEN   COUNT     NAME           KIND                    SUBOBJECT                     TYPE      REASON              SOURCE                        MESSAGE
33s        33s         1         web-1-8g06l    Pod                                                   Normal    Scheduled           default-scheduler             Successfully assigned web-1-8g06l to localhost
17s        32s         2         web-1-8g06l    Pod                     spec.containers{web}          Normal    Pulling             kubelet, localhost            pulling image "docker-registry-default.192.168.42.2.nip.io:443/proj/myhttpd"
16s        32s         2         web-1-8g06l    Pod                     spec.containers{web}          Warning   Failed              kubelet, localhost            Failed to pull image "docker-registry-default.192.168.42.2.nip.io:443/proj/myhttpd": rpc error: code = 2 desc = Error: image proj/myhttpd:latest not found
6s         32s         4         web-1-8g06l    Pod                                                   Warning   FailedSync          kubelet, localhost            Error syncing pod
6s         31s         2         web-1-8g06l    Pod                     spec.containers{web}          Normal    BackOff             kubelet, localhost            Back-off pulling image "docker-registry-default.192.168.42.2.nip.io:443/proj/myhttpd"
35s        35s         1         web-1-deploy   Pod                                                   Normal    Scheduled           default-scheduler             Successfully assigned web-1-deploy to localhost
34s        34s         1         web-1-deploy   Pod                     spec.containers{deployment}   Normal    Pulled              kubelet, localhost            Container image "openshift/origin-deployer:v3.6.0" already present on machine
33s        33s         1         web-1-deploy   Pod                     spec.containers{deployment}   Normal    Created             kubelet, localhost            Created container
33s        33s         1         web-1-deploy   Pod                     spec.containers{deployment}   Normal    Started             kubelet, localhost            Started container
33s        33s         1         web-1          ReplicationController                                 Normal    SuccessfulCreate    replication-controller        Created pod: web-1-8g06l
35s        35s         1         web            DeploymentConfig                                      Normal    DeploymentCreated   deploymentconfig-controller   Created new replication controller "web-1" for version 1
```

**Other info**

Minishift start logs

```console
$ minishift start --cpus 4 --memory 6144 
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    6 GB
   vCPUs :    4
   Disk size: 20 GB
-- Starting Minishift VM ....................................................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
 3.92 MiB / 34.72 MiB [=================>--------------------------------------------------------------------------------------------------------------------------------------]  11.28% 8m52s 34.72 MiB / 34.72 MiB [==========================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.6.0 checksums ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 54% complete
Pulled 3/4 layers, 90% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.2:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Waiting for persistent volumes to be created ... OK

-- Applying addon 'admin-user':..

-- Applying addon 'anyuid':.
 Add-on 'anyuid' changed the default security context constraints to allow pods to run as any user.
 Per default OpenShift runs containers using an arbitrarily assigned user ID.
 Refer to https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#security-context-constraints and
 https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines for more information.

-- Applying addon 'registry-route':........
Add-on 'registry-route' created docker-registry route. Please run following commands to login to the OpenShift docker registry:
$ eval $(minishift docker-env)
$ docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.42.2.nip.io:443
```

versions:

```console
$ minishift version
minishift v1.7.0+1549135

$ oc version
oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.2:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

**Comment by amitkrout** [comment] 2017-11-08 05:27
#1318

**Comment by amitkrout** [comment] 2017-11-08 10:14
I am able to reproduce it on minishift 1.8.0 with busybox
Steps:
```
1. docker login -u developer -p $(oc whoami -t) docker-registry-default.$(./minishift ip).nip.io:443
2. docker pull busybox
3. docker tag docker.io/busybox docker-registry-default.$(./minishift ip).nip.io:443/myproject/busybox:latest
4. docker push docker-registry-default.$(./minishift ip).nip.io:443/myproject/busybox:latest
5. oc new-app --image-stream=busybox --name=busybox
6. Open minishift console to see the failure 
```

I can see the the image is pulled from "Pulling repository    172.30.1.1:5000/myproject/busybox"
```
$ ./minishift version
minishift v1.8.0+6455fc3

$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.163:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
$
```

**Comment by praveenkumar** [comment] 2017-11-08 12:22
Did try to find what causing this issue but need some more debugging. Below is what I found when experimenting same. Looks like openshift not able to pull the image from internal exposed registry but `docker pull` does works as expected.

```
17:38 $ oc get pods
NAME           READY     STATUS             RESTARTS   AGE
web-1-7xtxd    0/1       ImagePullBackOff   0          3m
web-1-deploy   1/1       Running            0          3m

17:39 $ oc describe pod web-1-7xtxd
Name:			web-1-7xtxd
Namespace:		myproject
Security Policy:	restricted
Node:			localhost/192.168.64.26
Start Time:		Wed, 08 Nov 2017 17:35:54 +0530
Labels:			deployment=web-1
			deploymentconfig=web
			run=web
Annotations:		kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"myproject","name":"web-1","uid":"298a2758-c47d-11e7-9d8c-befd96875f00"...
			openshift.io/deployment-config.latest-version=1
			openshift.io/deployment-config.name=web
			openshift.io/deployment.name=web-1
			openshift.io/scc=restricted
Status:			Pending
IP:			172.17.0.3
Controllers:		ReplicationController/web-1
Containers:
  web:
    Container ID:	
    Image:		docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd
    Image ID:		
    Port:		
    State:		Waiting
      Reason:		ImagePullBackOff
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tkrks (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-tkrks:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-tkrks
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  3m		3m		1	default-scheduler				Normal		Scheduled	Successfully assigned web-1-7xtxd to localhost
  3m		2m		4	kubelet, localhost	spec.containers{web}	Normal		Pulling		pulling image "docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd"
  3m		2m		4	kubelet, localhost	spec.containers{web}	Warning		Failed		Failed to pull image "docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd": rpc error: code = 2 desc = Error: image myproject/myhttpd:latest not found
  3m		1m		6	kubelet, localhost	spec.containers{web}	Normal		BackOff		Back-off pulling image "docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd"
  3m		1m		11	kubelet, localhost				Warning		FailedSync	Error syncing pod

17:39 $ docker images
REPOSITORY                                                           TAG                 IMAGE ID            CREATED             SIZE
docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd   latest              dbfc2cbe2971        4 weeks ago         255MB
centos/httpd                                                         latest              dbfc2cbe2971        4 weeks ago         255MB
openshift/origin-deployer                                            v3.6.0              ad03ec44312c        3 months ago        974MB
openshift/origin-docker-registry                                     v3.6.0              ec456625b2a0        3 months ago        1.06GB
openshift/origin-haproxy-router                                      v3.6.0              75e805233369        3 months ago        995MB
openshift/origin                                                     v3.6.0              25e1f260f8ae        3 months ago        974MB
openshift/origin-pod                                                 v3.6.0              fb52c4c8f037        3 months ago        213MB

17:42 $ docker rmi dbfc2cbe2971 --force
Untagged: docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd:latest
Untagged: docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd@sha256:79eacf66ec2d0eb930b0693dc524c729ea6fa04cb6ca825c0479231e85dc18f8
Untagged: docker.io/centos/httpd:latest
Untagged: docker.io/centos/httpd@sha256:79eacf66ec2d0eb930b0693dc524c729ea6fa04cb6ca825c0479231e85dc18f8
Deleted: sha256:dbfc2cbe297168639680dc9512abffe62ef805ff4c38ed9982bec2be0ee51c09
Deleted: sha256:6d33de7388d6834ca967613b0c29c5074607e2c3c886542348bcec208ebd18b6
Deleted: sha256:536ab0bf734773b4941b35e700f589ea970cca7e0cff3cff54a9cbc172919cff
Deleted: sha256:4567d8f4c80a032313be99b619a78f5f198cc5234dedb97616f42df2c526b25b
Deleted: sha256:cf516324493c00941ac20020801553e87ed24c564fb3f269409ad138945948d4

17:42 $ docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-deployer          v3.6.0              ad03ec44312c        3 months ago        974MB
openshift/origin-docker-registry   v3.6.0              ec456625b2a0        3 months ago        1.06GB
openshift/origin-haproxy-router    v3.6.0              75e805233369        3 months ago        995MB
openshift/origin                   v3.6.0              25e1f260f8ae        3 months ago        974MB
openshift/origin-pod               v3.6.0              fb52c4c8f037        3 months ago        213MB

17:42 $ docker pull docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd
Using default tag: latest
Trying to pull repository docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd ... 
latest: Pulling from docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd
d9aaf4d82f24: Pull complete 
17695ed7ebda: Pull complete 
603fea4e6d47: Pull complete 
1923be8fd3f1: Pull complete 
Digest: sha256:79eacf66ec2d0eb930b0693dc524c729ea6fa04cb6ca825c0479231e85dc18f8

17:42 $ docker images
REPOSITORY                                                           TAG                 IMAGE ID            CREATED             SIZE
docker-registry-default.192.168.64.26.nip.io:443/myproject/myhttpd   latest              dbfc2cbe2971        4 weeks ago         255MB
openshift/origin-deployer                                            v3.6.0              ad03ec44312c        3 months ago        974MB
openshift/origin-docker-registry                                     v3.6.0              ec456625b2a0        3 months ago        1.06GB
openshift/origin-haproxy-router                                      v3.6.0              75e805233369        3 months ago        995MB
openshift/origin                                                     v3.6.0              25e1f260f8ae        3 months ago        974MB
openshift/origin-pod                                                 v3.6.0              fb52c4c8f037        3 months ago        213MB
```

**Comment by praveenkumar** [comment] 2017-11-08 12:50
More debugging and looks like it not the issue the way we are looking it, check also https://github.com/openshift/origin/issues/7327 so below is what @surajssd should do before specifying the image with the exposed registry. I would prefer to close this issue if @surajssd agree on explained answer.

```
✔ ~/work/github/go_practice/bin 
18:04 $ oc get is
No resources found.

18:05 $ docker push docker-registry-default.192.168.64.26.nip.io/test/myhttpd
The push refers to a repository [docker-registry-default.192.168.64.26.nip.io/test/myhttpd]
ffdbc94377b2: Pushed 
95847010d10a: Pushed 
2a9e8fbc6354: Pushed 
cf516324493c: Pushed 
latest: digest: sha256:79eacf66ec2d0eb930b0693dc524c729ea6fa04cb6ca825c0479231e85dc18f8 size: 1155

18:05 $ oc get is
NAME      DOCKER REPO                    TAGS      UPDATED
myhttpd   172.30.1.1:5000/test/myhttpd   latest    4 seconds ago

18:09 $ oc run web1 --image 172.30.1.1:5000/test/myhttpd 
deploymentconfig "web1" created

18:17 $ oc get pods
NAME            READY     STATUS              RESTARTS   AGE
web1-1-deploy   1/1       Running             0          5s
web1-1-kdsc2    0/1       ContainerCreating   0          1s

$ oc describe pod web1-1-kdsc2
[...]
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  17s		17s		1	default-scheduler				Normal		Scheduled	Successfully assigned web1-1-kdsc2 to localhost
  15s		12s		2	kubelet, localhost	spec.containers{web1}	Normal		Pulling		pulling image "172.30.1.1:5000/test/myhttpd@sha256:79eacf66ec2d0eb930b0693dc524c729ea6fa04cb6ca825c0479231e85dc18f8"
  14s		12s		2	kubelet, localhost	spec.containers{web1}	Normal		Pulled		Successfully pulled image "172.30.1.1:5000/test/myhttpd@sha256:79eacf66ec2d0eb930b0693dc524c729ea6fa04cb6ca825c0479231e85dc18f8"
  13s		11s		2	kubelet, localhost	spec.containers{web1}	Normal		Created		Created container
  13s		11s		2	kubelet, localhost	spec.containers{web1}	Normal		Started		Started container
```

**Comment by amitkrout** [comment] 2017-11-08 15:20
@praveenkumar i did the same as you mentioned above however deployment went unsuccessful (verified in minishift cosole). Would you please have look and comment if i am doing anything wrong

```
$ docker push docker-registry-default.$(./minishift ip).nip.io:443/myproject/busybox:latest
The push refers to a repository [docker-registry-default.192.168.42.75.nip.io:443/myproject/busybox]
0271b8eebde3: Pushed 
latest: digest: sha256:91ef6c1c52b166be02645b8efee30d1ee65362024f7da41c404681561734c465 size: 527

$ oc get is
NAME      DOCKER REPO                         TAGS      UPDATED
busybox   172.30.1.1:5000/myproject/busybox   latest    2 seconds ago

$ oc run test --image 172.30.1.1:5000/myproject/busybox
deploymentconfig "test" created

$ oc get pods
NAME            READY     STATUS             RESTARTS   AGE
test-1-deploy   1/1       Running            0          4m
test-1-s8v43    0/1       CrashLoopBackOff   5          4m
  
$ oc get pods
NAME            READY     STATUS    RESTARTS   AGE
test-1-deploy   0/1       Error     0          10m

$ oc describe pod test-1-deploy
[...]
Status:			Failed
IP:			172.17.0.2
Controllers:		<none>
Containers:
  deployment:
    Container ID:	docker://4c7a849c436c294f86e2e7aca6e8366f528d77fa6c3e4c4dfad5e07683256f51
    Image:		openshift/origin-deployer:v3.6.0
    Image ID:		docker-pullable://docker.io/openshift/origin-deployer@sha256:f23d1894be193be43de8b98ee6e30ce7f34ff235cdc4425fb609159f8f1ef2e0
    Port:		
    State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Wed, 08 Nov 2017 20:18:47 +0530
      Finished:		Wed, 08 Nov 2017 20:28:48 +0530
    Ready:		False
    Restart Count:	0
    Environment:
      KUBERNETES_MASTER:	https://127.0.0.1:8443
      OPENSHIFT_MASTER:		https://127.0.0.1:8443
      BEARER_TOKEN_FILE:	/var/run/secrets/kubernetes.io/serviceaccount/token
      [...]
      OPENSHIFT_DEPLOYMENT_NAME:	test-1
      OPENSHIFT_DEPLOYMENT_NAMESPACE:	myproject
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from deployer-token-86vq3 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  deployer-token-86vq3:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deployer-token-86vq3
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  10m		10m		1	default-scheduler					Normal		Scheduled	Successfully assigned test-1-deploy to localhost
  10m		10m		1	kubelet, localhost	spec.containers{deployment}	Normal		Pulled		Container image "openshift/origin-deployer:v3.6.0" already present on machine
  10m		10m		1	kubelet, localhost	spec.containers{deployment}	Normal		Created		Created container
  10m		10m		1	kubelet, localhost	spec.containers{deployment}	Normal		Started		Started container
$
```

**Comment by surajssd** [comment] 2017-11-14 05:47
Now I am facing other issue with the cluster setup,

So I had my minishift running without any addons enabled, I enabled the registry expose addon, restarted the machine and I see the registry is not exposed, there is no openshift route created!

**Comment by amitkrout** [comment] 2017-11-14 06:18
@surajssd This is not the right way to enable the addons. I would recommend execute the command ```.\minishift addons apply registry-route``` if minishift is up and running.

**Comment by surajssd** [comment] 2017-11-14 06:48
@amitkrout thanks for the input, this helped!

@praveenkumar also what you suggested works for me! The only problem is somehow using one name to push image and using other to push image seems little counter-intuitive! 

Isn't there any other way to use the registry's exposed route?

**Comment by praveenkumar** [comment] 2017-11-14 09:29
@surajssd I am not sure cc @jorgemoralespou

**Comment by praveenkumar** [comment] 2017-11-21 06:18
@surajssd Have you got any explanation around your issue yet?

**Comment by surajssd** [comment] 2017-11-21 07:12
@praveenkumar what do you mean by "explanation" ?

**Comment by mjudeikis** [comment] 2017-12-07 12:57
I think oc cluster up ir minishft threats exposed registry as an external one. If you do `oc get is` and use internal registry url `oc run web --image=5000/myproject/myhttpd` this might work. I will raise separate issue to track this (if this will be a case)

**Comment by mjudeikis** [comment] 2017-12-07 16:46
@praveenkumar. I this is kinda expected behavior.
Idea is that registry ,from openshift point of view, is an external registry. It's being treated as one. And by default it requires authentication. I don't think it's valid point to implement this for `oc cluster up` as registry expose was not implemented there too. It sounds more as minishift feature. 

The solution would be:
1. `docker login -u developer -p `oc whoami -t` docker-registry-default.127.0.0.1.nip.io`
2. `oc secrets new internal-reg .dockerconfigjson=/root/.docker/config.json` #or alternatilvy pull flag based secret creation syntax `oc secrets new-dockercfg myseret --docker-email=test --docker-password=$(oc whoami -t) --docker-username=admin --docker-server=docker-registry-default.127.0.0.1.nip.io` 
3. `oc secrets link default internal-reg`
or add it to deployment configs. 
This will enable DC to pull images using this secret from exposed registry.

But because it's per project basis you might want to think how to do this... 

At the same time as soon as you push image into registry `is` is being created, and if you use internal `is` reference, pull should be handled using default secrets.

`oc run web --image=172.30.1.1:5000/myproject/myhttpd`

**Comment by praveenkumar** [comment] 2017-12-11 09:26
@surajssd does @mjudeikis explanation make sense to you now?

**Comment by surajssd** [comment] 2017-12-11 13:37
@praveenkumar i think yes I understand all that, if minishift get's the instruction of those steps right so that user finds it usable then I am good anyway.

**Comment by praveenkumar** [comment] 2017-12-13 10:30
@surajssd Thanks, I added documentation label to it and will add some docs to make aware to the user when they hit this kind of situation.

**Comment by LalatenduMohanty** [comment] 2018-01-04 12:32
Resolved via #1884

**Closed by LalatenduMohanty** 2018-01-04 12:32 UTC
Labels: component/documentation, kind/bug, priority/critical

**Comment by deepikathimmegowda** [comment] 2018-11-01 10:54
Hi.. i am also facing the same issue too. i m using v3.11 okd.io

i had pushed my local image to openshift docker-registry then facing the below error while pulling that particular image
Failed to pull image "172.30.1.1:5000/play-image-project-2/play-app-image-stream-2@sha256:832d243aea1926e705c0f32fd3c5c1876eea3edbc93599276dbb75190eaed77c": rpc error: code = Unknown desc = Error response from daemon: Get http://172.30.1.1:5000/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)


to verify i tried to deploy the Image: openshift/jenkins. i get same error even with this image
Failed to pull image "172.30.1.1:5000/openshift/jenkins@sha256:fc4b06ab71503abcf50fe104f4c7e3434bcc61d3d3dc02d26870b794b9aa63f1": rpc error: code = Unknown desc = Error response from daemon: Get http://172.30.1.1:5000/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

I presume it could be issue with this okd.io version to pull images from docker-registry?

**Comment by deepikathimmegowda** [comment] 2018-11-08 16:22
@anjannath  : i tried to deploy Jenkins image from webconsole. 
add to project -> browse catalog -> Jenkins (Ephemeral)

This itself errors out when i try to deploy a project  with Jenkins (Ephemeral) image

**Comment by XuHaoIgeneral** [comment] 2019-08-30 07:34
> @praveenkumar. I this is kinda expected behavior.
> Idea is that registry ,from openshift point of view, is an external registry. It's being treated as one. And by default it requires authentication. I don't think it's valid point to implement this for `oc cluster up` as registry expose was not implemented there too. It sounds more as minishift feature.
> 
> The solution would be:
> 
> 1. `docker login -u developer -p `oc whoami -t` docker-registry-default.127.0.0.1.nip.io`
> 2. `oc secrets new internal-reg .dockerconfigjson=/root/.docker/config.json` #or alternatilvy pull flag based secret creation syntax `oc secrets new-dockercfg myseret --docker-email=test --docker-password=$(oc whoami -t) --docker-username=admin --docker-server=docker-registry-default.127.0.0.1.nip.io`
> 3. `oc secrets link default internal-reg`
>    or add it to deployment configs.
>    This will enable DC to pull images using this secret from exposed registry.
> 
> But because it's per project basis you might want to think how to do this...
> 
> At the same time as soon as you push image into registry `is` is being created, and if you use internal `is` reference, pull should be handled using default secrets.
> 
> `oc run web --image=172.30.1.1:5000/myproject/myhttpd`

Thanks!  sometimes We use pod to create pod. it's a die

**Comment by tineo** [comment] 2020-02-27 21:03
> @anjannath : i tried to deploy Jenkins image from webconsole.
> add to project -> browse catalog -> Jenkins (Ephemeral)
> 
> This itself errors out when i try to deploy a project with Jenkins (Ephemeral) image

I have the same problem maybe it could be the url in localhost 127.0.0.1
