### ISSUE TITLE
Failing builds due to unresolvable glide.sh

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#571] opened 2017-03-20 04:32 UTC
While building on CI the following errors occur:

CentOS-CI: Connection to 172.19.3.110 closed. during the compilation (when glide needs to be installed)
Travis-CI: The command "GLIDE_TAG=$(curl -s https://glide.sh/version)" failed and exited

The domain http://glide.sh is not available: https://github.com/Masterminds/glide/issues/784

This can ofcourse always occur, but maybe it is better to rely on only larger operated services during a build process/install procedure.

Since we are using the releases, why not pin the GLIDE_TAG? This will result in a more predictable outcome anyways.

Analysis:
  * centos-ci: tagged version using releases
  * travis-ci: tagged version using releases
  * appveyor: go get
  * circl-ci: go get

I believe we should have a preferred way for all platforms, and preferably pinned to a version.

Note:
On Fedora I have been using the packaged versions anyways, Golang is 1.7.5 and Glide is also recent enough. In this case: 
```
$ dnf install -y golang glide
```
Will suffice to perform a build. However, packaged versions for CentOS are available after enabling epel-release, but they are slightly older (but in my opinion workable enough). Anyways, if the version is pinned to a specified version, or to the packaged version, the outcome is more predictable.

**Comment by praveenkumar** [comment] 2017-03-20 05:13
I would say we should use same approach for glide installation (go get), whatever CI we are using, this way we are sure that our all CI have same version because if we use rpm/deb package for centos/travis CI then might be we don't get what master have and hit inconsistent results.

**Comment by gbraad** [comment] 2017-03-20 07:16
agree. I also believe the go get method seems to be the better approach.

**Comment by hferentschik** [comment] 2017-03-20 08:03
> I would say we should use same approach for glide installation (go get), whatever CI we are using

+1

**Comment by hferentschik** [comment] 2017-03-20 08:22
Merged via pull request #572

**Comment by gbraad** [comment] 2017-03-20 08:24
will prepare another PR for the `go get` method of installation

**Comment by hferentschik** [comment] 2017-03-20 08:32
>will prepare another PR for the go get method of installation

The problems with 'go get'  is that it will always fetch HEAD. This is actually not optimal, since we are exposing us of getting non reproducible builds. Setting a fixed version of Glide is imo the better approach.  

I would like to align Glide setup approaches across our CI setups, but preferably in a way we've done here - with a explicitly set Glide version.

Windows still needs some special treatment though, since there we are running into a problems where we exceed the maximum path length.

**Comment by gbraad** [comment] 2017-03-20 09:31
Any method will work for me. I prefer version pinned myself to, so I will look into this later. Installing on Windows should not be that much of a problem.

**Comment by hferentschik** [comment] 2017-04-24 14:31
It's only Circle CI left which does not download a fixed version. In the other CI systems we use wget now to download, extract and use a binary release of Glide. We should align Circle CI.

**Comment by praveenkumar** [comment] 2017-04-26 13:27
I assigned it to myself and will soon address it.

**Comment by hferentschik** [comment] 2017-04-26 18:47
> I assigned it to myself and will soon address it.

+1, thanks.

**Comment by hferentschik** [comment] 2017-04-27 08:50
Merged via pull request #832 (updates Circle CI)

**Closed by hferentschik** 2017-04-27 08:50 UTC
Labels: component/build, kind/task, priority/major
