### ISSUE TITLE
Error: Error: No such image: openshift/origin:v3.7.1

### ISSUE THREAD

**Issue by mtttcgcg** [minishift/minishift#2279] opened 2018-04-13 16:14 UTC
Hi all, I had minishift working great about a month ago, but when I tried it again yesterday, it won't start anymore, even with a minishift delete and another go. Have tried adding 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/19497375/38745858-a8d68190-3efa-11e8-87f8-6b6761f816d3.png">, 
<img width="202" alt="image" src="https://user-images.githubusercontent.com/19497375/38745864-aeb92a9a-3efa-11e8-80c0-c83d4243ea09.png"> (which was not a known option), deleting the .minishift directory and trying again, and with --iso-url. All have the same error.

Any ideas?

### General information

  * Minishift version: 1.13.1
  * OS:  Windows
  * Hypervisor: Hyper-V 

### Steps to reproduce

  1. set HYPERV_VIRTUAL_SWITCH=External4Minikube (this is a hyper-V switch with the external button clicked)
  2.  minishift start 
 
  

### Expected
Minishift should start up without error

### Actual
-- Checking for available ports ... FAIL
   Error: Cannot get TCP port information from Kubernetes host
   Caused By:
     Error: cannot create container using image openshift/origin:v3.7.1
     Caused By:
       Error: Error: No such image: openshift/origin:v3.7.1
Error during 'cluster up' execution: Error starting the cluster.

### Logs

https://gist.github.com/mtttcgcg/7604934f491f5072544a0169c34e6617

**Comment by praveenkumar** [comment] 2018-04-16 06:04
This looks like issue with your DNS resolver, it might be happen if you are behind a VPN, Please add your comment to #2037.

Closing this as this is duplicate of existing issue.

**Closed by praveenkumar** 2018-04-16 06:04 UTC

**Comment by mtttcgcg** [comment] 2018-04-16 15:37
Hmmm. I upgraded to minishift 1.15.1 and now --network-nameserver works. So I'm pointing it directly at my DNS server but it has the same error. I am not on VPN.
