### ISSUE TITLE
C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by manjrem** [minishift/minishift#3033] opened 2018-11-26 20:49 UTC
### General information

  * Minishift version: minishift v1.27.0+707887e
  * OS:  Windows 10
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. download minishift
  2. minishift config set vm-driver virtualbox
  3. minishift.exe start  --show-libmachine-logs -v5

### Logs

(minishift) DBG | Waiting for VM "minishift" to power on...
(minishift) DBG | VM "minishift" has been successfully started.
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | Checking vm logs: C:\Users\mmanjrek\.minishift\machines\minishift\minishift\Logs\VBox.log
(minishift) DBG | Getting to WaitForSSH function...
(minishift) DBG | Using SSH client type: external
(minishift) DBG | &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\mmanjrek\.minishift\machines\minishift\id_rsa -p 1790] C:\Program Files (x86)\Gow\bin\ssh.bat <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
(minishift) DBG | SSH cmd err, output: exit status 1: 'C:\Program' is not recognized as an internal or external command,
(minishift) DBG | operable program or batch file.
(minishift) DBG |
(minishift) DBG | Error getting ssh command 'exit 0' : ssh command error:
(minishift) DBG | command : exit 0
(minishift) DBG | err     : exit status 1
(minishift) DBG | output  : 'C:\Program' is not recognized as an internal or external command,
(minishift) DBG | operable program or batch file.
(minishift) DBG |

**Comment by budhram** [comment] 2018-11-27 05:07
@manjrem You are using external client being provided by `Gow`.
See below:
```
(minishift) DBG | Using SSH client type: external
(minishift) DBG | &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\mmanjrek.minishift\machines\minishift\id_rsa -p 1790] 
C:\Program Files (x86)\Gow\bin\ssh.bat }   <-------------------- Notice this line
```

Check either:
1. Removing `Gow` folder and make sure no other such client is being used
2. Remove `C:\Program Files (x86)\Gow\bin` from Environment Variable `PATH`

**Comment by anjannath** [comment] 2018-11-27 08:22
Duplicate of #1354

**Comment by gbraad** [comment] 2018-11-27 11:03
WONTFIX

this is an issue with how Gow wraps `plink`. There is not much we can do about this, as the script itself is faulty, and it is an awful hack anyways as `plink` is not really comptaible with `ssh` as command. The solution is to prevent the use of Gow by uninstalling, removing from path, or perhaps by implementing to force the native ssh implementation #2570.

**Comment by gbraad** [comment] 2018-11-27 11:05
I suggest to do both: #2570 and #1354 

  * #2570 as a workaround to force native client
  * #1354 to document this as a 'known issue'

**Closed** 2018-11-27 11:07 UTC
Labels: kind/bug, os/windows, priority/minor, resolution/wontfix
