### ISSUE TITLE
Unable to Start minishift version: 1.0.0-rc.1 with virtualbox

### ISSUE THREAD

**Issue by darryl1309** [minishift/minishift#702] opened 2017-04-07 05:05 UTC
Hi guys,
I keep getting an error when i execute the command below:
```
./minishift.exe start --vm-driver=virtualbox
```

I have deleted everything it generated and tried starting it again but issue still persists.

### Output
```
Starting local OpenShift cluster using 'virtualbox' hypervisor...
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     To create a new Docker machine to run OpenShift, run this command again with
     the --create-machine argument. This will create a Docker machine named
     'openshift'.

     To use a different machine name, specify the --machine-name=NAME argument.

     If you wish to use an existing Docker machine, enable it before running this
     command by executing:

        docker-machine env

     where NAME is the name of your Docker machine.

   Caused By:
     Error: Get https://192.168.99.101:2376/_ping: net/http: TLS handshake timeout
E0407 11:35:50.934594    5264 start.go:410] Error starting the cluster.
```

**Comment by budhrg** [comment] 2017-04-07 05:08
@darryl1309 , could you let us know which version you are using ? `minishift version` ?

**Comment by darryl1309** [comment] 2017-04-07 05:11
Minishift version: 1.0.0-rc.1

**Comment by darryl1309** [comment] 2017-04-07 05:12
The first time i downloaded it. These are the logs:

$ minishift start --vm-driver virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MB / 40.00 MB  100.00% 0sssss5s
 19.05 MB / 19.05 MB  100.00% 0ssss3s
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     To create a new Docker machine to run OpenShift, run this command again with
     the --create-machine argument. This will create a Docker machine named
     'openshift'.

     To use a different machine name, specify the --machine-name=NAME argument.

     If you wish to use an existing Docker machine, enable it before running this
     command by executing:

        docker-machine env

     where NAME is the name of your Docker machine.

   Caused By:
     Error: Get https://192.168.99.101:2376/_ping: net/http: TLS handshake timeout
E0407 10:47:53.316351    8912 start.go:410] Error starting the cluster.

**Comment by darryl1309** [comment] 2017-04-07 05:14
I have set my envirament variable path as 
- C:\Users\<username>\Minishift
since the minishift.exe is located there

**Comment by budhrg** [comment] 2017-04-07 05:30
@darryl1309 ,  could you please provide the output of 
```
minishift.exe start --vm-driver virtualbox -v 5 --showlibmachine-logs
```

That would really help us to debug. Though we have similar issue here https://issues.jboss.org/browse/CDK-104

**Comment by LalatenduMohanty** [comment] 2017-04-07 06:10
@darryl1309 I think because of something your setup has gone bad. It would be helpful if we can reproduce this. Please provide the logs as @budhrg  suggested.

**Comment by thesteve0** [comment] 2017-04-08 19:16
We are also seeing TLS handshake issues on Mac as well 

https://bugzilla.redhat.com/show_bug.cgi?id=1435261

Can you please add notes to this as well as this may not be a minishift issue

**Comment by darryl1309** [comment] 2017-04-10 07:28
I used powershell and cmd it worked there. Using bash and cygwin terminal triggers this error.

**Comment by ryanj** [comment] 2017-04-10 17:09
Seeing this error at the end of my `minishift start` command output (with virtualbox):
```-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... FAIL
   Error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
E0410 10:06:38.058557   10931 start.go:410] Error starting the cluster.```

**Comment by jorgemoralespou** [comment] 2017-04-10 17:37
@ryanj That's because you're on a blacklist of users for our tooling ;-)

Can you give more details of your OS that you're using? Also, did you have minishift working before with any version? Can you paste the full logs?

````
minishift start --vm-driver virtualbox -v 5 --showlibmachine-logs
````

**Comment by ryanj** [comment] 2017-04-10 18:43
@jorgemoralespou ;-)

Earlier in the day I had tried running  `minishift start` on an OSX machine (defaulting to the `xhyve` driver).  I [hit an issue with the xhyve driver](https://github.com/minishift/minishift/issues/482#issuecomment-293013864), so I tried again with `--vm-driver=virtualbox`.  This almost worked, aside from the cert issues.

I gave it another try and was able to get `minishift start --vm-driver=virtualbox` to work successfully (on OSX) after running `minikube delete && minishift delete`.

**Comment by revandarth** [comment] 2017-04-19 06:21
I am here with same error. 
`C:\WINDOWS\system32>minishift start --vm-driver="virtualbox"
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MB / 40.00 MB [=============================================] 100.00% 0s
E0418 23:05:11.138735   12660 start.go:164] Error starting the VM: Error creating the VM. Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
 19.05 MB / 19.05 MB [=============================================] 100.00% 0s
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     To create a new Docker machine to run OpenShift, run this command again with
     the --create-machine argument. This will create a Docker machine named
     'openshift'.

     To use a different machine name, specify the --machine-name=NAME argument.

     If you wish to use an existing Docker machine, enable it before running this
     command by executing:

        docker-machine env

     where NAME is the name of your Docker machine.

   Caused By:
     Error: Get https://192.168.99.100:2376/_ping: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0418 23:06:17.675200   12660 start.go:410] Error starting the cluster.`

**Comment by HaakonL** [comment] 2017-04-20 19:22
Similar error here as well, first time I install minishift today, rc.2, and my docker install is a week old. Windows 10 Pro.


C:\Program Files\minishift>minishift start
Starting local OpenShift cluster using 'hyperv' hypervisor...
                                                                                                                                                                                                                                                                                                                                                                                                                                         -- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot obtain a Docker client
   Solution:

     To create a new Docker machine to run OpenShift, run this command again with
     the --create-machine argument. This will create a Docker machine named
     'openshift'.

     To use a different machine name, specify the --machine-name=NAME argument.

     If you wish to use an existing Docker machine, enable it before running this
     command by executing:

        docker-machine env

     where NAME is the name of your Docker machine.

   Caused By:
     Error: invalid endpoint
Error starting the cluster.

**Comment by praveenkumar** [comment] 2017-04-27 07:58
I am not sure why `minishift` depend on host docker client because it suppose to make use of what we have in the issue. We do need to dig it bit more and see what's causing this issue.

**Comment by tdussmann** [comment] 2017-05-17 13:46
> I used powershell and cmd it worked there. Using bash and cygwin terminal triggers this error.

Similar for me, I tried to use cygwin terminal, as the image download timed out with cmd.exe due to the proxy settings not being applied (?!), which worked flawlessly from the cygwin terminal, except that this error then happens. 
So now that the iso has been downloaded when called from cygwin, I was able to start successfully from cmd.exe without this error happening...

**Comment by praveenkumar** [comment] 2017-05-31 11:41
@tdussmann this is something we recently pushed to upstream it mostly around proxy env when those are part of default bash environment variable then we can see same error. I am closing this issue if you face again, we will reopen.

**Closed by praveenkumar** 2017-05-31 11:41 UTC
Labels: kind/bug, priority/major

**Comment by Ganitagya** [comment] 2017-08-04 10:24
Hi @jorgemoralespou ,

I was trying to start minishift using the below command:
``` minishift --alsologtostderr --show-libmachine-logs start --iso-url file://C:/Users/abcd/ISO_Images/minishift-b2d-iso/build/minishift-b2d.iso```

And I am getting the below error:
```-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... FAIL
   Error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Error during 'cluster up' execution: Error starting the cluster.
```

The full logs are here: [minishift_logs](https://gist.github.com/Ganitagya/8595e02c52926cc9ebedfc7edb4299c8)

can you please help ?

**Comment by gbraad** [comment] 2017-08-04 10:34
@Ganitagya 

Can you please file a new issue. This has been closed, and might be unrelated. Also, try not to at-reply to a person, as this would exclude others to look at it.

**Comment by Ganitagya** [comment] 2017-08-04 10:36
sure

**Comment by gbraad** [comment] 2017-08-04 10:38
@Ganitagya after you have done so, I will remove the entry here... as they are unrelated ;-).

**Comment by Ganitagya** [comment] 2017-08-04 10:53
I have done it.
Opened it [here](https://github.com/minishift/minishift/issues/1226)
