### ISSUE TITLE
Unable to build and deploy PHP sample  project 

### ISSUE THREAD

**Issue by darryl1309** [minishift/minishift#763] opened 2017-04-18 06:26 UTC
hi guys,
i have problems when building at minishift i've used the sample projects from the console itself to check if it is working however it is always at pending status. Please refer to the screenshots below

**git project used**
https://github.com/openshift/cakephp-ex.git

**oc status:**
![buildproblem](https://cloud.githubusercontent.com/assets/26946315/25117045/cc232a3c-2442-11e7-8089-0f072908fc0a.PNG)

**console status:**
![image](https://cloud.githubusercontent.com/assets/26946315/25117080/ee0cd56c-2442-11e7-80e1-00715fb73153.png)

**Comment by agajdosi** [comment] 2017-04-18 06:36
Hi @darryl1309, thank you for reporting this. It seems your issue can be related to #723. Are you using Boot2docker image or CentOS?

**Comment by darryl1309** [comment] 2017-04-18 06:47
I believe it is Boot2docker and i'm starting it via virtualbox.
the console is accessible and I logged in using system,admin and developer users but deployments are always pending. Is there a proxy config for the console? Because I've only set my proxy at my terminal.

![image](https://cloud.githubusercontent.com/assets/26946315/25117600/6345ffa0-2445-11e7-9524-ac4e52c98553.png)

**Comment by darryl1309** [comment] 2017-04-18 06:58
Hi,
I've ssh'ed  minishift and checked the status but the minishift command doesn't work.

![image](https://cloud.githubusercontent.com/assets/26946315/25118053/291c2fb4-2447-11e7-8725-e806c8c87a54.png)

when i exit the ssh there is an error shown after

![image](https://cloud.githubusercontent.com/assets/26946315/25118106/657d3412-2447-11e7-8c5b-32c02046c00c.png)

**Comment by LalatenduMohanty** [comment] 2017-04-18 07:24
@darryl1309 Can you please put the steps to reproduce the issue and the version of minishift you are using?

**Comment by darryl1309** [comment] 2017-04-18 08:33
Hi guys,

kindly see document on how i set it up, maybe it was my setup.

[Minishift Setup.docx](https://github.com/minishift/minishift/files/927845/Minishift.Setup.docx)

Steps on how I added a project.

1. add project

![image](https://cloud.githubusercontent.com/assets/26946315/25121452/52505b14-2454-11e7-9079-27d9d5882f93.png)

2. Select php
![image](https://cloud.githubusercontent.com/assets/26946315/25121479/69937c2a-2454-11e7-997b-03b49a77ef43.png)

3. select php version

![image](https://cloud.githubusercontent.com/assets/26946315/25121505/80f4313e-2454-11e7-9436-
127bfdf77fd5.png)

4. create project
![image](https://cloud.githubusercontent.com/assets/26946315/25121551/a4f44ede-2454-11e7-94a6-3b19b0e8959b.png)

**Comment by praveenkumar** [comment] 2017-04-18 09:12
@darryl1309 Looks like in your case build is not completed on time and due that deployment failed. I did try same on windows-10 and everything works as expected. 

Can you please put the builds logs you can get those https://cloud.githubusercontent.com/assets/26946315/25117080/ee0cd56c-2442-11e7-80e1-00715fb73153.png (see here a option `view logs`) ?

I got below as per build logs.
```
Cloning "https://github.com/openshift/cakephp-ex.git" ...
	Commit:	6f2ebfbeaaaae3b1771aaa36d5beec5b2898c82d (Merge pull request #61 from bparees/sc_metadata)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Wed Feb 15 16:28:08 2017 -0500
---> Installing application source...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
Found 'composer.json', installing dependencies using composer.phar...

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 26  298k   26 81669    0     0  50582      0  0:00:06  0:00:01  0:00:05 50569
100  298k  100  298k    0     0   169k      0  0:00:01  0:00:01 --:--:--  169k
All settings correct for using Composer
Downloading...

Composer (version 1.4.1) successfully installed to: /opt/app-root/src/composer.phar
Use it: php composer.phar

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 10 installs, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (1.5.6): Downloading (100%)
  - Installing cakephp/cakephp-codesniffer (1.0.2): Downloading (100%)
  - Installing phpunit/php-token-stream (1.2.2): Downloading (100%)
  - Installing symfony/yaml (v2.8.16): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (1.2.3): Downloading (100%)
  - Installing phpunit/php-timer (1.0.8): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.2): Downloading (100%)
  - Installing phpunit/php-code-coverage (1.2.18): Downloading (100%)
  - Installing phpunit/phpunit (3.7.38): Downloading (100%)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating optimized autoload files

Pushing image 172.30.1.1:5000/myproject/testphp:latest ...
Pushed 0/9 layers, 1% complete
Pushed 1/9 layers, 12% complete
Pushed 2/9 layers, 24% complete
Pushed 3/9 layers, 35% complete
Pushed 4/9 layers, 49% complete
Pushed 5/9 layers, 58% complete
Pushed 6/9 layers, 72% complete
Pushed 7/9 layers, 88% complete
Pushed 8/9 layers, 100% complete
Pushed 9/9 layers, 100% complete
Push successful
```

**Comment by darryl1309** [comment] 2017-04-18 09:18
Hi guys,

that is actually one of my main problem logs doesn't show. It is stuck at loading log and pending status. 

![image](https://cloud.githubusercontent.com/assets/26946315/25123382/bb53c898-245a-11e7-99b5-f9d1a612cdd8.png)

**Comment by darryl1309** [comment] 2017-04-18 09:20
This might be a network problem, however i am able to clone the git project directly but not through minishift, that is why I thought there is a proxy configuration at minishift.

**Comment by praveenkumar** [comment] 2017-04-18 09:26
@darryl1309 if you are behind proxy then you can use minishift proxy options https://docs.openshift.org/latest/minishift/using/managing-minishift.html#http-s-proxies

**Comment by darryl1309** [comment] 2017-04-18 09:35
I've started it but there is a warning and logs still don't show.

![image](https://cloud.githubusercontent.com/assets/26946315/25124078/2f33e016-245d-11e7-894e-139257a705e2.png)

![image](https://cloud.githubusercontent.com/assets/26946315/25124121/54ad6f9c-245d-11e7-979a-b9f52464db1e.png)

**Comment by praveenkumar** [comment] 2017-04-18 10:14
@darryl1309 Can you ssh to that minishift VM using `minishift ssh` and then try to do `docker pull busybox` and see if that works?

**Comment by darryl1309** [comment] 2017-04-19 02:03
Yep it is the proxy problem.

![image](https://cloud.githubusercontent.com/assets/26946315/25159650/d70e02ea-24e3-11e7-9d9b-7d29846f77bc.png)

I only exported the proxy at my terminal and i'm able to clone from git. It seems like minishift proxy is different from the terminal proxy. I used the command below to start minishift:
_minishift start --vm-driver virtualbox --http-proxy http://YOURPROXY:PORT --https-proxy https://YOURPROXY:PORT_

**Comment by praveenkumar** [comment] 2017-04-19 03:25
> minishift start --vm-driver virtualbox --http-proxy http://YOURPROXY:PORT --https-proxy https://YOURPROXY:PORT

@darryl1309 if you have only http-proxy then you don't need to put https-proxy or vice versa. Also once you use these param to start minishift then after VM is up (with/without error) you can ssh to it and check shell env which  should have proxy env set same like you did from terminal check with `env` command.

**Comment by darryl1309** [comment] 2017-04-19 06:14
Hi,
should there be a proxy setting at the env lists? Because mine only shows below:

![image](https://cloud.githubusercontent.com/assets/26946315/25165689/50d7e016-250a-11e7-9938-7552b42d6ec7.png)

**Comment by darryl1309** [comment] 2017-04-19 06:23
Hi guys, 
I've set the proxy after minishift ssh 
![image](https://cloud.githubusercontent.com/assets/26946315/25165965/938e1370-250b-11e7-9e13-87ec283f4aa8.png)

Build is still stuck at pending status and loading logs
![image](https://cloud.githubusercontent.com/assets/26946315/25165978/a49462dc-250b-11e7-8f25-a4a010dcebc5.png)

**Comment by praveenkumar** [comment] 2017-04-19 06:54
@darryl1309 Problem is if you set proxy using shell it is not set for openshift container so `minishift start --http-proxy=<>` should work. Check the below and it worked for me.

Please join `#minishift` channel on freenode and we can have conversation there if still didn't work.

```
# ./minishift start --http-proxy http://fedora:fedora123@10.70.49.109:3128 --show-libmachine-logs
...
 OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.209:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

$ ./minishift ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec

docker@minishift:~$ env
SSH_CLIENT=192.168.42.1 48698 22
MAIL=/var/mail/docker
USER=docker
SHLVL=1
HOME=/home/docker
SSH_TTY=/dev/pts/0
PAGER=less -EM
PS1=\u@\h:\w\$ 
ENV=/home/docker/.ashrc
BACKUP=1
LOGNAME=docker
http_proxy=http://fedora:fedora123@10.70.49.109:3128  => set by default as part of minishift start
TERM=xterm-256color
PATH=/home/docker/.local/bin:/usr/local/sbin:/usr/local/bin:/apps/bin:/usr/sbin:/usr/bin:/sbin:/bin
G_FILENAME_ENCODING=iso8859-1
LANG=C
MANPAGER=less -isR
SHELL=/bin/sh
FLWM_TITLEBAR_COLOR=58:7D:AA
PWD=/home/docker
SSH_CONNECTION=192.168.42.1 48698 192.168.42.209 22
EDITOR=vi
```

**Comment by praveenkumar** [comment] 2017-05-30 10:37
@darryl1309 have your issue is resolved?

**Comment by praveenkumar** [comment] 2017-05-31 07:26
@darryl1309 I am going to close this issue let me know if you still have same problem and will reopen.

**Closed by praveenkumar** 2017-05-31 07:26 UTC
Labels: kind/bug, priority/major
