### ISSUE TITLE
Unset all DOCKER_* variables as part of initial setup of minishift

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#298] opened 2017-01-16 10:09 UTC
Currently if we already have docker env set on the same shell session where we are running `minishift start <options>` it fails  because minishift consume those available variable to do the initial check for docker daemon configuration and failed with below error.

```
Checking Docker daemon configuration ... FAIL
   Error: Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
E0113 12:49:08.408930    2148 start.go:246] Error starting 'cluster up':  exit status 1
```

Another improvement should be done in same direction #252

**Comment by praveenkumar** [comment] 2017-01-30 08:53
@LalatenduMohanty Have a look to https://github.com/minishift/minishift/blob/master/cmd/minikube/cmd/env.go#L158-L197 it have complete logic around this.

**Comment by LalatenduMohanty** [comment] 2017-01-31 08:11
I am not able to reproduce the issue now. I was able to reproduce it once when I assigned this to me but can not anymore. Looking in to what has changed.

**Comment by LalatenduMohanty** [comment] 2017-01-31 13:55
Still not able to reproduce. Took a boot2docker ISO version of 1.12.2 and created the docker env with the version. But minishift starts fine. 
```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.24 (downgraded from 1.25)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.2
 API version:  1.24 (minimum version )
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Lalatendus-MacBook-Pro:1.12.2 lmohanty$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.0/minishift-b2d.iso'
 40.00 MB / 40.00 MB [======================================================================================================================================================================] 100.00% 0s
 21.34 MB / 21.34 MB [======================================================================================================================================================================] 100.00% 0s
Provisioning OpenShift via '/Users/lmohanty/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... 
   Pulling image openshift/origin:v1.4.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 59% complete
   Pulled 2/3 layers, 88% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.64.7 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.64.7:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

```

**Comment by hferentschik** [comment] 2017-01-31 14:21
I can go both ways, unset the variables for good measure or just move on.

**Comment by LalatenduMohanty** [comment] 2017-02-06 10:25
As per the current code i.e. https://github.com/minishift/minishift/blob/master/cmd/minikube/cmd/start.go#L151-L154 and https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster.go#L319-L344 we are explicitly setting environment variables for docker daemon for the `cluster up` . Also https://github.com/minishift/minishift/pull/340 improved the code with respect to docker environment API version. So it seems the code does the right thing, hence closing it. Lets re-open it if we reproduce it.

**Closed by LalatenduMohanty** 2017-02-06 10:25 UTC
Labels: kind/bug, priority/major
