### ISSUE TITLE
Unable to restart Minishift due to Docker failing to start

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#561] opened 2017-03-17 03:46 UTC
**Steps to reproduce**
````
$ minishift start --show-libmachine-logs --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso
```
After this, Minishift has successfully deployed OpenShift

Now trying to restart Minishift with
```
$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.
$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
```
will cause it to hang... 

On closer inspection, it seems Docker does not start:

```
$ minishift start --show-libmachine-logs
Starting local OpenShift cluster using 'kvm' hypervisor...
Waiting for SSH to be available...
Detecting the provisioner...
Error getting SSH command to check if the daemon is running: Something went wrong running an SSH command!
command : sudo docker version
err     : exit status 1
output  : Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: read unix @->/var/run/docker.sock: read: connection reset by peer


Error getting SSH command to check if the daemon is running: Something went wrong running an SSH command!
command : sudo docker version
err     : exit status 1
output  : Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?


Error getting SSH command to check if the daemon is running: Something went wrong running an SSH command!
command : sudo docker version
err     : exit status 1
output  : Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?


Error getting SSH command to check if the daemon is running: Something went wrong running an SSH command!
command : sudo docker version
err     : exit status 1
output  : Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?


^C
```

```
$ minishift ssh
$ sudo systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
$ sudo journalctl -u docker
Mar 16 23:40:41 minishift systemd[1]: Starting Docker Application Container Engine...
Mar 16 23:40:41 minishift docker[11037]: time="2017-03-16T23:40:41.813917014-04:00" level=info msg="libcontainerd: new containerd process, pid: 11050"
Mar 16 23:40:42 minishift docker[11037]: time="2017-03-16T23:40:42.898595323-04:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for p
Mar 16 23:40:42 minishift docker[11037]: time="2017-03-16T23:40:42.940468054-04:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it
Mar 16 23:40:43 minishift docker[11037]: time="2017-03-16T23:40:43.100043506-04:00" level=fatal msg="Error starting daemon: layer does not exist"
Mar 16 23:40:43 minishift systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Mar 16 23:40:43 minishift systemd[1]: Failed to start Docker Application Container Engine.
Mar 16 23:40:43 minishift systemd[1]: Unit docker.service entered failed state.
Mar 16 23:40:43 minishift systemd[1]: docker.service failed.
```

**Comment by gbraad** [comment] 2017-03-17 05:28
Not observed with Minishift beta-4 and CentOS rc-2

**Comment by LalatenduMohanty** [comment] 2017-03-17 05:36
```
$ minishift start --show-libmachine-logs --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso
Starting local OpenShift cluster using 'kvm' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso'
 335.00 MB / 335.00 MB [===============================================================================================================================================================================] 100.00% 0s
Running pre-create checks...
Creating machine...
(minishift) Downloading /home/lmohanty/.minishift/cache/boot2docker.iso from file:///home/lmohanty/.minishift/cache/iso/minishift-centos7.iso...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with minishift...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
Provisioning OpenShift via '/home/lmohanty/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.131.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... 
   Pulling image openshift/origin:v1.4.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 57% complete
   Pulled 2/3 layers, 70% complete
   Pulled 2/3 layers, 95% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.131 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.131:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin


[lmohanty@LalatenduM-laptop ~]$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.

[lmohanty@LalatenduM-laptop ~]$ minishift start --show-libmachine-logs --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso
Starting local OpenShift cluster using 'kvm' hypervisor...
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Provisioning OpenShift via '/home/lmohanty/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.131.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.4.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.131 as the server IP
-- Starting OpenShift container ... 
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.131:8443

   To login as administrator:
       oc login -u system:admin

``

**Comment by gbraad** [comment] 2017-03-17 06:11
Retried with master and rc3. Not repoducible

**Comment by gbraad** [comment] 2017-03-17 07:01
Correction... it happens again... consistently.

  1. `minishift delete`
  2. `minishift start --show-libmachine-logs --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso`
  3. `minishift stop`
  4. `minishift start --show-libmachine-logs`

**Comment by LalatenduMohanty** [comment] 2017-03-17 07:16
I still can not reproduce this . Fedora 25 updated, KVM, minishift latest built from master

```
$ minishift start --show-libmachine-logs --iso-url file:///home/lmohanty/Downloads/minishift-centos7.iso 
Starting local OpenShift cluster using 'kvm' hypervisor...
Running pre-create checks...
Creating machine...
(minishift) Downloading /home/lmohanty/.minishift/cache/boot2docker.iso from file:///home/lmohanty/Downloads/minishift-centos7.iso...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with minishift...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
Provisioning OpenShift via '/home/lmohanty/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.113.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... 
   Pulling image openshift/origin:v1.4.1
   Pulled 0/3 layers, 3% complete
   Pulled 0/3 layers, 8% complete
   Pulled 0/3 layers, 13% complete
   Pulled 0/3 layers, 18% complete
   Pulled 0/3 layers, 22% complete
   Pulled 0/3 layers, 26% complete
   Pulled 0/3 layers, 32% complete
   Pulled 0/3 layers, 37% complete
   Pulled 0/3 layers, 41% complete
   Pulled 0/3 layers, 45% complete
   Pulled 0/3 layers, 49% complete
   Pulled 0/3 layers, 54% complete
   Pulled 0/3 layers, 57% complete
   Pulled 1/3 layers, 66% complete
   Pulled 1/3 layers, 68% complete
   Pulled 1/3 layers, 70% complete
   Pulled 1/3 layers, 73% complete
   Pulled 1/3 layers, 74% complete
   Pulled 1/3 layers, 77% complete
   Pulled 1/3 layers, 80% complete
   Pulled 1/3 layers, 82% complete
   Pulled 2/3 layers, 86% complete
   Pulled 2/3 layers, 87% complete
   Pulled 2/3 layers, 88% complete
   Pulled 2/3 layers, 89% complete
   Pulled 2/3 layers, 90% complete
   Pulled 2/3 layers, 91% complete
   Pulled 2/3 layers, 93% complete
   Pulled 2/3 layers, 94% complete
   Pulled 2/3 layers, 95% complete
   Pulled 2/3 layers, 97% complete
   Pulled 2/3 layers, 98% complete
   Pulled 2/3 layers, 99% complete
   Pulled 2/3 layers, 100% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.113 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.113:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

[lmohanty@LalatenduM-laptop ~]$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.

$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
Provisioning OpenShift via '/home/lmohanty/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.113.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.4.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.113 as the server IP
-- Starting OpenShift container ... 
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.113:8443

   To login as administrator:
       oc login -u system:admin

$ minishift version
Minishift version: 1.0.0-beta.5

$ minishift ssh
Last login: Fri Mar 17 03:09:04 2017 from 192.168.42.1
[docker@minishift ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

VARIANT="minishift"
VARIANT_VERSION="1.0.0-rc.3"
BUILD_ID="d08c1b0-13032017171452-local"
[docker@minishift ~]$ exit
logout
[lmohanty@LalatenduM-laptop ~]$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.
[lmohanty@LalatenduM-laptop ~]$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
Provisioning OpenShift via '/home/lmohanty/.minishift/cache/oc/v1.4.1/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.113.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.4.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.113 as the server IP
-- Starting OpenShift container ... 
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.113:8443

   To login as administrator:
       oc login -u system:admin

```

**Comment by gbraad** [comment] 2017-03-17 07:33
It is about 50/50 chance...

In some cases doing the start, stop, start cycle will work. maybe even for 2 times in a row...

**Comment by gbraad** [comment] 2017-03-17 07:37
```
Mar 17 03:35:43 minishift systemd[1]: Starting Docker Application Container Engine...
Mar 17 03:35:43 minishift docker[10414]: time="2017-03-17T03:35:43.686323385-04:00" level=info msg="libcontainerd: new containerd process, pid: 10425"
Mar 17 03:35:44 minishift docker[10414]: time="2017-03-17T03:35:44.809065831-04:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use  `man docker` to refer to dm.thinpooldev section."
Mar 17 03:35:44 minishift docker[10414]: time="2017-03-17T03:35:44.827447201-04:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
Mar 17 03:35:44 minishift docker[10414]: time="2017-03-17T03:35:44.987843437-04:00" level=fatal msg="Error starting daemon: layer does not exist"
Mar 17 03:35:44 minishift systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Mar 17 03:35:44 minishift systemd[1]: Failed to start Docker Application Container Engine.
Mar 17 03:35:44 minishift systemd[1]: Unit docker.service entered failed state.
Mar 17 03:35:44 minishift systemd[1]: docker.service failed.
```

**Comment by gbraad** [comment] 2017-03-17 07:40
```
/usr/bin/docker daemon -H tcp://0.0.0.0:2376                        -H unix:///var/run/docker.sock                        --selinux-enabled                        --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current                        --default-runtime=docker-runc                        --storage-driver devicemapper                        --tlsverify --tlscacert /etc/docker/ca.pem                        --tlscert /etc/docker/server.pem                        --tlskey /etc/docker/server-key.pem
sudo /usr/bin/docker daemon -H tcp://0.0.0.0:2376                        -H unix:///var/run/docker.sock                        --selinux-enabled                        --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current                        --default-runtime=docker-runc                        --storage-driver devicemapper                        --tlsverify --tlscacert /etc/docker/ca.pem                        --tlscert /etc/docker/server.pem                        --tlskey /etc/docker/server-key.pem
INFO[0000] libcontainerd: new containerd process, pid: 10518
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
WARN[0001] devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section.
WARN[0001] devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored.
FATA[0001] Error starting daemon: layer does not exist
```

**Comment by gbraad** [comment] 2017-03-17 07:46
Able to resolve with `sudo rm -rf /var/lib/docker`, which means that the filesystem/images were corrupted.

**Comment by agajdosi** [comment] 2017-03-17 10:55
@LalatenduMohanty @gbraad I am not able to reproduce this issue with beta5 on Fedora 24 with kvm vm-provider. Did 6 runs of which 6 passed.

**Comment by gbraad** [comment] 2017-03-17 11:08
have this occurring on three different remote environments... will keep an eye on it...

**Comment by praveenkumar** [comment] 2017-05-31 10:45
@gbraad as per discussion on this issue I am going to close it and it you hit again then will reopen.

**Closed by praveenkumar** 2017-05-31 10:45 UTC
Labels: kind/bug, priority/major
