### ISSUE TITLE
application redeployment is getting failed for OpenShift v3.7/minishift v1.7.0+1549135

### ISSUE THREAD

**Issue by hrishin** [minishift/minishift#1821] opened 2017-12-11 05:33 UTC
### General information
In redeploying scenario on OpenShift v3.7/minishift v1.7.0 may be Deployment/DeploymentConfig is not happening correctly.
Its unable to pull the images from OpenShift internal registry as pod status keeps shuffling between ErrImagePull/ImagePullBackOff for a long time before pod comes up.Tough looks like imagestream build happening correctly.

  * Minishift version: minishift v1.7.0+1549135
  * OS: Linux Fedora 25
  * Hypervisor: KVM 

https://github.com/openshift/origin/issues/17705

### Steps to reproduce
1.deploy the application     ( Got successful )
2. redeploy the same application either with some change/without any change.

### Expected
Keep throwing ErrImagePull/ImagePullBackOff

### Actual
Application pod should come up in one go

**Comment by gbraad** [comment] 2017-12-11 06:28
Since you use OpenShift v3.7 (with m 1.7.0), you must have specified start parameters. Can you provide all the information you used? Do you also have a possible example location?

Also, it is suggested to use a newer version of Minishift if possible. Run `minishift update`.

**Comment by gbraad** [comment] 2017-12-11 06:30
In the issue at OpenShift's tracker, I can also see you do not use client correctly. Please do:

```
$ eval $(minishift oc-env)
$ oc   # this is the same client as used for the deployment
```

**Comment by hrishin** [comment] 2017-12-11 07:49
@gbraad let's try it.

**Comment by LalatenduMohanty** [comment] 2017-12-12 19:57
@hrishin Are you still seeing the issue with latest Minishift?

**Comment by hrishin** [comment] 2017-12-18 05:39
@LalatenduMohanty let me confirm the issue ASAP.

**Comment by piyush1594** [comment] 2017-12-18 07:25
hi @hrishin @LalatenduMohanty 

I am still facing this issue. I am using minishift version `minishift v1.10.0+10461c6` and openshift version `v3.7.0`. I did the above step `eval $(minishift oc-env)` too. Attaching the screenshot of openshift console also.

![screenshot from 2017-12-18 12-45-31](https://user-images.githubusercontent.com/19270240/34094250-67ec9dc6-e3f2-11e7-955e-c68382535f2f.png)

**Comment by hrishin** [comment] 2017-12-21 05:19
@LalatenduMohanty @gbraad any updates on this issue?

**Comment by gbraad** [comment] 2017-12-21 05:46
At the moment we experience issues with using v3.7.0, as can be seen from #1776

**Comment by LalatenduMohanty** [comment] 2017-12-21 07:44
@hrishin @piyush1594 Can you please provide me exact steps to reproduce?

**Comment by gbraad** [comment] 2017-12-21 08:32
@hrishin can you provide full instructions, from beginning to end? This means, include the `minishift start` and possible environment variables you set

**Comment by mc-meta** [comment] 2017-12-24 19:19
This resembles somewhat the issue we are experiencing on OO/minishift 3.7.0 when dc objects reference relative images:

met [05:49pm]  ~/git/minishift-demo-fortune/s06/app-fortune> grep image: fortune-dc.yaml
          image: badluck/quote:latest
          image: badluck/db:latest
met [05:49pm]  ~/git/minishift-demo-fortune/s06/app-fortune> oc apply -f fortune-dc.yaml
deploymentconfig "fortune" configured
met [05:50pm]  ~/git/minishift-demo-fortune/s06/app-fortune> oc get events |grep -i pull
15s        28s         2         fortune-24-6v7rr    Pod                     spec.containers{db}           Normal    Pulling                 {kubelet mid1-s101orig-4.buongiorno.com}    pulling image "badluck/db:latest"
13s        26s         2         fortune-24-6v7rr    Pod                     spec.containers{db}           Warning   Failed                  {kubelet mid1-s101orig-4.buongiorno.com}    Failed to pull image "badluck/db:latest": rpc error: code = 2 desc = Error: image badluck/db:latest not found
13s        26s         2         fortune-24-6v7rr    Pod                     spec.containers{db}           Warning   Failed                  {kubelet mid1-s101orig-4.buongiorno.com}    Error: ErrImagePull
26s        26s         1         fortune-24-6v7rr    Pod                     spec.containers{quote}        Normal    Pulling                 {kubelet mid1-s101orig-4.buongiorno.com}    pulling image "badluck/quote:latest"
21s        21s         1         fortune-24-6v7rr    Pod                     spec.containers{quote}        Warning   Failed                  {kubelet mid1-s101orig-4.buongiorno.com}    Failed to pull image "badluck/quote:latest": rpc error: code = 2 desc = Error: image badluck/quote:latest not found
21s        21s         1         fortune-24-6v7rr    Pod                     spec.containers{quote}        Warning   Failed                  {kubelet mid1-s101orig-4.buongiorno.com}    Error: ErrImagePull
12s        20s         3         fortune-24-6v7rr    Pod                     spec.containers{db}           Normal    BackOff                 {kubelet mid1-s101orig-4.buongiorno.com}    Back-off pulling image "badluck/db:latest"
 
and at some point deployment is rolled back.  The same works when image references are absolute, e.g.:

met [07:11pm]  ~/git/minishift-demo-fortune/s06/app-fortune> grep image: fortune-dc.yaml
          image: docker-registry.default.svc:5000/badluck/quote:latest
          image: docker-registry.default.svc:5000/badluck/db:latest
met [07:11pm]  ~/git/minishift-demo-fortune/s06/app-fortune> oc apply -f fortune-dc.yaml
deploymentconfig "fortune" configured

met [07:14pm]  ~/git/minishift-demo-fortune/s06/app-fortune> oc get events |grep -i pull|tail -n 4

2m         2m          1         fortune-26-wwgfj    Pod                     spec.containers{db}           Normal    Pulling                          {kubelet mid1-s101orig-5.buongiorno.com}    pulling image "docker-registry.default.svc:5000/badluck/db:latest"
1m         1m          1         fortune-26-wwgfj    Pod                     spec.containers{db}           Normal    Pulled                           {kubelet mid1-s101orig-5.buongiorno.com}    Successfully pulled image "docker-registry.default.svc:5000/badluck/db:latest"
1m         1m          1         fortune-26-wwgfj    Pod                     spec.containers{quote}        Normal    Pulling                          {kubelet mid1-s101orig-5.buongiorno.com}    pulling image "docker-registry.default.svc:5000/badluck/quote:latest"
1m         1m          1         fortune-26-wwgfj    Pod                     spec.containers{quote}        Normal    Pulled                           {kubelet mid1-s101orig-5.buongiorno.com}    Successfully pulled image "docker-registry.default.svc:5000/badluck/quote:latest"


From our tests, 'oc apply' works with relative images during initial dc creation, but fails at update attempts. AFAICT 'oc apply' creation/updates with relative images are working fine with 3.6.x (tested on mini-shift). 

HTH,

-m

**Comment by cunningt** [comment] 2018-02-16 11:46
I'm seeing this issue using fabric8:deploy and openshift v3.7.0 on minishift v1.13.0+ee338c6.    Is there a workaround here (different version of oc to use, different steps I can take to push the image once I've built it using fabric8:build, remove the application and then reinstall)?

**Comment by piyush1594** [comment] 2018-02-16 11:52
Hey @cunningt 

We have introduced a workaround for that, you can check the [issue](https://github.com/fabric8io/fabric8-maven-plugin/issues/1130)

FMP 3.5.35 has been released yesterday with this workaround.

You should hit for Openshift 3.7.x
`mvn -Dfabric8.openshift.trimImageInContainerSpec=true fabric8:deploy`

It should ideally work. Let us know if you face some issue.

Thanks

**Comment by cunningt** [comment] 2018-02-16 13:50
Thanks @piyush1594 - upgrading my FMP version and using the trimInContainerSpec env variable worked!

**Comment by piyush1594** [comment] 2018-03-23 09:59
@LalatenduMohanty @anjannath @hrishin I think we can close this issue.

**Comment by budhrg** [comment] 2018-03-23 10:31
@hrishin WDYT ? Can we close this issue?

**Comment by piyush1594** [comment] 2018-03-26 15:02
Hey, @budhrg  

This was the issue which was not related to minishift but because of OpenShift. We figured this and already fixed in FMP [FMP Issue](https://github.com/fabric8io/fabric8-maven-plugin/issues/1130) which has been fixed by [FMP FIX](https://github.com/fabric8io/fabric8-maven-plugin/pull/1176)

This was related to this issue in OpenShift [Issue](https://github.com/openshift/origin/issues/18406) which has been fixed here [Fix](https://github.com/openshift/origin/pull/18524)

I have already mentioned the workaround to get this working using FMP in above comments [here](https://github.com/minishift/minishift/issues/1821#issuecomment-366216280)

I think we are good to close this issue.

Thanks

**Comment by gbraad** [comment] 2018-03-27 00:51
Closing

**Closed by gbraad** 2018-03-27 00:51 UTC
Labels: kind/bug, priority/major, status/needs-info
