### ISSUE TITLE
Cannot run EAP template based application - wrong user is used to run server

### ISSUE THREAD

**Issue by mlabuda** [minishift/minishift#156] opened 2016-11-23 11:51 UTC
I tried to run EAP 6.4 based application on minishifit. At first I set up router, then I uploaded templates (I have tried from adb-utils repo as well as from MW repo https://github.com/jboss-openshift/application-templates together with secrets). Applications other than EAP, e.g. nodejs or php based are working. Problem is with EAP.

Description of a problem:
- After build of an application (build pod is completed) there is an application pod and deployment pod.
- Deployment pod has ready status 1/1 and is in state Running
- Application pod has ready status 0/1 and is in state Running
- After timeout period of deployment pod, deployment fails and there is no application running.

After remote access to the application pod and looking for cause, there is following log in readiness-error https://paste.fedoraproject.org/482978/14792997/

When I looked closer at processed I found out that it run under a different user than it should. Also remote access to pod logged me as user:
uid=1000040000 gid=0(root) groups=0(root),1000040000

When I use this against different OpenShift instance, it log me in as:
uid=185(jboss) gid=185(jboss) groups=185(jboss)

Not sure whether this is just a misconfiguration or minishift bug @LalatenduMohanty  point me to file an issue here.

**Comment by jimmidyson** [comment] 2016-11-23 12:11
By default, OpenShift runs pods as an arbitrary uid, hence the `1000040000` you saw above. You can allow pods to run as defined uids, but that requires editing the SCCs & is not recommended. This doesn't look like a bug to me, but environmental difference, with minishift showing correct default behaviour.

**Comment by jimmidyson** [comment] 2016-11-23 12:15
See https://docs.openshift.org/latest/creating_images/guidelines.html#use-uid for more details.

**Comment by LalatenduMohanty** [comment] 2016-11-23 12:15
@mlabuda Are you able to run EAP on existing CDK?

**Comment by mlabuda** [comment] 2016-11-23 12:45
@LalatenduMohanty yeah, I was comparing minishift to CDK. Basically I am trying to have minishift set up as CDK is. In CDK it runs with jboss user, but in minishift with the 1000040000. So It is probably misconfiguration. I will try to set correct SCC to be able to accomplish it and let you know whether it fixed the issue.

**Comment by jimmidyson** [comment] 2016-11-23 12:57
I strongly feel that the CDK/minishift should use the default SCC & not allow RunAsAny by default. Otherwise you get developers writing stuff against minishift, deploying to proper cluster & hitting issues with permissions only then - the earlier you hit a problem, the easier it is to fix normally.

**Comment by LalatenduMohanty** [comment] 2016-11-23 13:00
> strongly feel that the CDK/minishift should use the default SCC & not allow RunAsAny by default. Otherwise you get developers writing stuff against minishift, deploying to proper cluster & hitting issues with permissions only then - the earlier you hit a problem, the easier it is to fix normally.

+1.

**Comment by jimmidyson** [comment] 2016-11-23 13:30
@tnozicka @praveenkumar Is this anything you're aware of? Some of the images in https://github.com/projectatomic/adb-utils/blob/master/services/openshift/templates/common/jboss-image-streams.json require to `RunAsAny` being set. In CDK this appears to be done by adding `system:authenticated` group to `anyuid` SCC. It makes much more sense for the EAP images to properly support OpenShift requirements to run as arbitrary uids as detailed in https://docs.openshift.org/latest/creating_images/guidelines.html#use-uid.

**Comment by jimmidyson** [comment] 2016-11-23 13:47
@bparees Is this something you're aware of? EAP images failing to run as arbitrary uid?

**Comment by bparees** [comment] 2016-11-23 14:30
No, the xpaas images support running as arbitrary uids as far as i know.  @knrc would be the one to ask/investigate this.

**Comment by jimmidyson** [comment] 2016-11-23 14:53
@mlabuda Can you share the logs from the EAP pod, as well as some simple repro steps please?

**Comment by tnozicka** [comment] 2016-11-23 15:00
I believe the default policy is correct; we should have defaults as close to production as possible. Especially if **all production** clusters will force random uid for security reasons.

If this is truly a bug in EAP than it should be fixed there. But from the short log it isn't clear.

From my experience with EAP 7 it worked ok with `oc cluster up` which should have the SCC set correctly.

**Comment by jimmidyson** [comment] 2016-11-23 15:08
Agreed. I think there's something else going on here. As I said before, if @mlabuda can provide repro steps then I can try to track down what the actual issue is.

**Comment by mlabuda** [comment] 2016-11-23 15:16
Steps to reproduce. For step 3 and 4 I used tooling (e.g. template param for hostname is not set this way via oc binary, but for the cause of problem and steps to reproduce it does not play a role):
**1. ASSERT:** Have minishift downloaded and started. Have oc binary. (minishift used v0.9.0, oc version v1.2.1)
**2. EXEC:** Log in as admin via oc and set up router:
_oc adm policy add-scc-to-user hostnetwork -z router
oc adm router_
**3. EXEC:** Set template and image stream for EAP.
_oc create -f https://raw.githubusercontent.com/projectatomic/adb-utils/master/services/openshift/templates/cdk/image-streams-rhel7.json -n openshift
oc create -f https://raw.githubusercontent.com/projectatomic/adb-utils/master/services/openshift/templates/common/eap64-basic-s2i.json -n openshift_
**4. EXEC:** Create a new application based on EAP template and wait until build completes and there is a deployment pod and an application pod.
_oc new-app --template=eap64-basic-s2i_

**5. RESULT:** Deployment pod has ready status 1/1 and is in state Running. Application pod has ready status 0/1 and is in state Running. Deployment timeouts. If you log into application pod, EAP is already started. If I try to run readiness script manually, it hangs there. Running part of script results into an error in readiness-error log file /tmp/readiness-error:
https://paste.fedoraproject.org/482978/14792997/

You can also observer than rsh to an application pod on minishift is done as 1000040000 user but on CDK as jboss user.

**Comment by jimmidyson** [comment] 2016-11-23 16:28
Reproduced - had to add `oc create -f https://raw.githubusercontent.com/projectatomic/adb-utils/master/services/openshift/templates/common/jboss-image-streams.json -n openshift` to step 3.

**Comment by jimmidyson** [comment] 2016-11-23 17:14
Confirmed as working with `oc cluster up`. Something weird with filesystem permissions.

On `oc cluster`:

    sh-4.2$ ls -l /home/jboss/       
    total 0
    drwxr-xr-x. 5 jboss jboss 101 Nov 23 12:07 source

On `minishift`:

    sh-4.2$ ls -l /home/jboss/
    ls: cannot access /home/jboss/source: Permission denied
    total 0
    d????????? ? ? ? ?            ? source

**Comment by jimmidyson** [comment] 2016-11-23 17:15
Wondering if this is an aufs issue?

**Comment by jimmidyson** [comment] 2016-11-23 20:46
It gets even weirder... Do a:

```bash
eval $(minishift docker-env)
docker ps | grep eap
docker exec -it -u root <container_id> bash
ls -l /home/jboss/
exit
```

Notice how the pod has either already or shortly after exiting the shell become ready...

**Comment by praveenkumar** [comment] 2016-11-24 03:23
@jimmidyson @mlabuda if it is aufs issue, I can test it on centos.iso once which we created recently and let you folks know if I hit to same issue.

**Comment by mlabuda** [comment] 2016-11-24 08:43
@jimmidyson you are right with the image stream, sorry. I had a wrong value in clipboard. Updated steps to reproduce. @praveenkumar that would be great. At least we can exclude one possible cause.

**Comment by mlabuda** [comment] 2016-12-08 09:30
Guys, any update on this one?

**Comment by hferentschik** [comment] 2016-12-16 15:56
@mlabuda Could you try with the latest release of Minishift - 1.0.0-beta.1. It is based on _cluster up_ and I just went through the steps to replicate and got an working app under http://eap-app-myproject.192.168.99.140.xip.io/index.jsf. 

If it works, I think we can resolve this as "out of date"

**Comment by mlabuda** [comment] 2016-12-19 09:08
Yes, we can resolve this. It is working on minishift 1.0.0-beta.1 release.

**Comment by hferentschik** [comment] 2016-12-19 09:26
Closing this issue, since it is out of date as of minishift 1.0.0-beta.1

**Closed by hferentschik** 2016-12-19 09:26 UTC
Labels: bug, out-of-date
