### ISSUE TITLE
Local DNS solution to reliably access applications and services in an offline situation

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1774] opened 2017-11-30 10:01 UTC
Currently we are using nip.io/xip.io to provide an alternative to DNS, but this causes issues when in a completely disconnected situation. We have to investigate what is possible to provide a local DNS solution.

**Comment by LalatenduMohanty** [comment] 2017-11-30 21:02
We did similar work for CDK 2.x in https://github.com/vagrant-landrush/landrush for the same purpose. We wanted a local DNS solution which will work on Windows, macOS and Linux and landrush works on all of them.

**Comment by hferentschik** [comment] 2017-11-30 21:04
This is a duplicate of issue #201. AS @LalatenduMohanty, we know what to do and how to do it. With Minishift it becomes even a bit easier now. Basically a lot can be taken from Landrush.

**Closed** 2017-11-30 21:05 UTC
Labels: kind/feature, priority/major

**Comment by gbraad** [comment] 2018-01-24 17:52
We do not need landrush, as during the f2f we have worked on a PoC.
