### ISSUE TITLE
Minishift Web Console - Access from remote machine

### ISSUE THREAD

**Issue by Mach7ne** [minishift/minishift#3356] opened 2019-10-07 13:31 UTC
### General information

  * Minishift version: v1.34
  * OS: Linux 
  * Hypervisor: KVM 

Hello
Guys, comming here with an issue, was looking around but did not found any solution, maybe You can advise/help?

I have deployed bare metal server with basic rhel and minishift. Cluster is started.

Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+7618f0a-307)
DiskUsage:  15% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 1.682 GB (used by oc binary, ISO or cached images)

I only have bash shell on that server, no GUI and can't access web console from that server.
Also all is working with **oc** command, however I would like to also have access to web console.
Is there any way I could access web console url from remote machine that is on same lan?

**Comment by gbraad** [comment] 2019-10-07 14:03
Duplicate of https://github.com/minishift/minishift/issues/1287

**Closed by gbraad** 2019-10-07 14:03 UTC
