### ISSUE TITLE
minishift fails in second run and sometimes in first run

### ISSUE THREAD

**Issue by onderson** [minishift/minishift#3224] opened 2019-03-28 22:08 UTC
### General information

  * Minishift version: 1.33
  * OS: Linux Ubuntu 18.04
  * Hypervisor: KVM 

### Steps to reproduce

  1. minishift start
  2. minishift stop
  3. minishift start

### Expected
success
success
success

### Actual
1- (this does not always happen. It sometimes starts after doing clean restart)
and this is the error i see 

`minishift forbidden: User \"system:anonymous\" cannot get path \"/console\": no RBAC policy matched`

when i've tried to start webconsole even if this error happens as below;

E0328 13:49:20.267915    4523 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 84% complete
Pulled 5/6 layers, 87% complete
Pulled 5/6 layers, 90% complete
Pulled 5/6 layers, 93% complete
Pulled 5/6 layers, 94% complete
Pulled 5/6 layers, 96% complete
Pulled 5/6 layers, 98% complete
Pulled 5/6 layers, 100% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.42.67 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0328 13:53:23.423795    4523 config.go:40] Running "create-master-config"
I0328 13:53:26.101743    4523 config.go:46] Running "create-node-config"
I0328 13:53:27.362741    4523 flags.go:30] Running "create-kubelet-flags"
I0328 13:53:27.946474    4523 run_kubelet.go:49] Running "start-kubelet"
I0328 13:53:28.248224    4523 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0328 13:58:28.258069    4523 run_self_hosted.go:571] API server error: Get https://192.168.42.67:8443/healthz?timeout=32s: dial tcp 192.168.42.67:8443: connect: connection refused ()
Error: timed out waiting for the condition

Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --http-proxy ...............--https-proxy ..................... --image 'openshift/origin-${component}:v3.11.0' --no-proxy 192.168.42.0/24 --public-hostname 192.168.42.67 --routing-suffix 192.168.42.67.nip.io --base-dir /var/lib/minishift/base
err     : exit status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0328 13:49:15.469620    4523 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0328 13:49:20.267915    4523 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 84% complete
Pulled 5/6 layers, 87% complete
Pulled 5/6 layers, 90% complete
Pulled 5/6 layers, 93% complete
Pulled 5/6 layers, 94% complete
Pulled 5/6 layers, 96% complete
Pulled 5/6 layers, 98% complete
Pulled 5/6 layers, 100% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.42.67 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0328 13:53:23.423795    4523 config.go:40] Running "create-master-config"
I0328 13:53:26.101743    4523 config.go:46] Running "create-node-config"
I0328 13:53:27.362741    4523 flags.go:30] Running "create-kubelet-flags"
I0328 13:53:27.946474    4523 run_kubelet.go:49] Running "start-kubelet"
I0328 13:53:28.248224    4523 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0328 13:58:28.258069    4523 run_self_hosted.go:571] API server error: Get https://192.168.42.67:8443/healthz?timeout=32s: dial tcp 192.168.42.67:8443: connect: connection refused ()
Error: timed out waiting for the condition

2- success
3-
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:43877
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Calling .Start
(minishift) DBG | Starting VM minishift
...(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.67
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:ad:ca:45
.(minishift) Calling .GetConfigRaw
-- Setting proxy information ... (minishift) Calling .GetIP
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) Calling .DriverName
(minishift) DBG | IP address: 192.168.42.67
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:ad:ca:45
(minishift) Calling .GetIP
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.67
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:ad:ca:45
(minishift) Calling .GetSSHHostname
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.67
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:ad:ca:45
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) Calling .GetSSHKeyPath
(minishift) DBG | AK: resolvestorepath: /home/onders/.minishift
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/onders/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.42.67 -o IdentitiesOnly=yes -i /home/onders/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
export HTTP_PROXY=http://127.0.0.1:3128 http_proxy=http://127.0.0.1:3128 HTTPS_PROXY=http://127.0.0.1:3128 https_proxy=http://127.0.0.1:3128 NO_PROXY=localhost,127.0.0.1,172.30.1.1,localhost,127.0.0.1,192.168.42.67,192.168.42.1 no_proxy=localhost,127.0.0.1,172.30.1.1,localhost,127.0.0.1,192.168.42.67,192.168.42.1
....SSH cmd err, output: exit status 255: 
FAIL
 FAIL E0328 19:18:28.610975   25976 start.go:494] Error starting the VM: Error setting proxy to VM: ssh command error:
command : export HTTP_PROXY=http://127.0.0.1:3128 http_proxy=http://127.0.0.1:3128 HTTPS_PROXY=http://127.0.0.1:3128 https_proxy=http://127.0.0.1:3128 NO_PROXY=localhost,127.0.0.1,172.30.1.1,localhost,127.0.0.1,192.168.42.67,192.168.42.1 no_proxy=localhost,127.0.0.1,172.30.1.1,localhost,127.0.0.1,192.168.42.67,192.168.42.1
err     : exit status 255
output  : . Retrying.
Error starting the VM: Error setting proxy to VM: ssh command error:
command : export HTTP_PROXY=http://127.0.0.1:3128 http_proxy=http://127.0.0.1:3128 HTTPS_PROXY=http://127.0.0.1:3128 https_proxy=http://127.0.0.1:3128 NO_PROXY=localhost,127.0.0.1,172.30.1.1,localhost,127.0.0.1,192.168.42.67,192.168.42.1 no_proxy=localhost,127.0.0.1,172.30.1.1,localhost,127.0.0.1,192.168.42.67,192.168.42.1
err     : exit status 255
output  :

**Comment by onderson** [comment] 2019-03-29 08:57
Tested again while not being on VPN. This did not happen and console is coming up in the first start but if i stop with 

`minishift stop`
and in the next run when i do

`minishift start`

the error happens again regardless of being or not on VPN.

**Comment by gbraad** [comment] 2019-04-01 02:30
This has been recorded several times and is likely an issue with the actual `oc cluster up`.
We haven't been able to pinpoint the reason... it seems network, like pulling speed or a timeout during the setup of the components just taking slightly longer than expected.

**Comment by gbraad** [comment] 2019-04-01 02:32
Duplicate of #3217

**Closed by gbraad** 2019-04-01 02:32 UTC

**Comment by onderson** [comment] 2019-04-01 06:19
@gbraad , i have got two issues here.
1st one is the error i got during first start of minishift
and 
2nd one is the error i got during the second start of minishift. 

which one is the duplicate of #3127?

and should we log another issue for the other one which is not duplicate?
