### ISSUE TITLE
"docker-env" parameter is not supported by config set

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#728] opened 2017-04-10 15:21 UTC
When we start minishift, it is possible to define the parameters to be used to customize the docker daemon

```
Usage:
  minishift start [flags]

Flags:
      --docker-env stringArray          Environment variables to pass to the Docker daemon. Use the format <key>=<value>.
```

Unfortunately, we can't specify them using config set

```
minishift config set docker-env [storage-driver=devicemapper]
Cannot find property name docker-env
```

It should be great to align the parameters supported by the command `start` with `config`

**Comment by hferentschik** [comment] 2017-04-10 15:44
This is really a duplicate of #687. Going to close it.

**Closed by hferentschik** 2017-04-10 15:44 UTC
Labels: kind/feature, priority/major
