### ISSUE TITLE
Fails to escape password with special characters

### ISSUE THREAD

**Issue by rhoads-zach** [minishift/minishift#878] opened 2017-05-10 20:47 UTC
When attempting to use a developer account with a special character in the password, minishift fails to escape it correctly during setup:

```
$./minishift --vm-driver=virtualbox --username=user@example.com --password="fakePWthat-has-)-in-it" start
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Registering machine using subscription-manager
E0510 14:37:54.600570   11169 start.go:176] Error starting the VM: Error registering the VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username=user@example.com --password fakePWthat-has-)-in-it
err     : exit status 1
output  : bash: -c: line 0: syntax error near unexpected token `)'
```

Using MINISHIFT_PASSWORD has same effect.

Intentionally escaping yields a double escape:
```
$./minishift --vm-driver=virtualbox --username=user@example.com --password="fakePWthat-has-\)-in-it" start
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Registering machine using subscription-manager
E0510 14:37:54.600570   11169 start.go:176] Error starting the VM: Error registering the VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username=user@example.com --password fakePWthat-has-\\)-in-it
err     : exit status 1
output  : bash: -c: line 0: syntax error near unexpected token `)'
```

**Comment by budhrg** [comment] 2017-05-11 07:08
@praveenkumar , probably this is one of edge case which got missed.

**Comment by budhrg** [comment] 2017-05-11 08:14
I am also able to reproduce this issue.

**Comment by praveenkumar** [comment] 2017-05-11 10:04
@budhram can you try to put that password in single quote string instead double quote and see if that still case because I think with single quote it should escape those.

**Comment by hferentschik** [comment] 2017-05-11 12:16
> can you try to put that password in single quote string instead double quote and see if that still case because I think with single quote it should escape those.

+1

@rhoads-zach, can you put your password into single quotes? Does this work? Using double quotes will still enable interpolation in your shell.

**Comment by gbraad** [comment] 2017-05-15 07:23
Maybe to add: Allow a user to specify the password from input, just like hostfolders does

**Comment by budhrg** [comment] 2017-05-15 09:59
> Maybe to add: Allow a user to specify the password from input, just like hostfolders does

@gbraad That should be feature :smile:

**Comment by rhoads-zach** [comment] 2017-05-15 14:50
@hferentschik just retried with single quotes and it has the same issue

**Comment by budhrg** [comment] 2017-05-22 05:52
Resolved via https://github.com/minishift/minishift/pull/914

**Closed by budhrg** 2017-05-22 05:52 UTC
Labels: kind/bug, priority/major
