### ISSUE TITLE
'oc' command not using same IP as minishift's profile server

### ISSUE THREAD

**Issue by klauern** [minishift/minishift#2765] opened 2018-09-05 19:23 UTC
### General information
When using Minishift to start an OpenShift Cluster with a specific profile, the `oc` binary isn't using the same IP address as the profile is set, even when using `docker-env` and `oc-env` commands.

  * Minishift version: 1.23.0
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1. `minishift profile test`
  2.  `minishift config set cpus 8` # plus Memory to 8GB, network-nameserver to 1.1.1.1
  3. `minishift start`
  4. `& minishift oc-env | Invoke-Expression`
  5. `& minishift docker-env | Invoke-Expression`
  6. `oc status`

### Expected

I'd get a status about the OpenShift Environment

### Actual

Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Logs

```sh
C:\Users\klauer
λ  minishift oc-env
$Env:PATH = "C:\Users\klauer\.minishift\cache\oc\v3.10.0\windows;$Env:PATH"
# Run this command to configure your shell:
# & minishift oc-env | Invoke-Expression
C:\Users\klauer
λ  & minishift oc-env | Invoke-Expression
C:\Users\klauer
λ  minishift docker-env
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://172.18.79.98:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\klauer\.minishift\profiles\mattermost\certs"
# Run this command to configure your shell:
# & minishift docker-env | Invoke-Expression
C:\Users\klauer
λ  & minishift docker-env | Invoke-Expression
C:\Users\klauer
λ  oc status
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Unable to connect to the server: dial tcp 172.18.79.102:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
C:\Users\klauer
λ
```

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by klauern** [comment] 2018-09-05 19:36
In addition, here's the config vars.  I had to put in the `network-parameter` setting because of an issue that @gbraad mentioned in #2663 

```
C:\Users\klauer
λ  minishift config view
- cpus                               : 4
- image-caching                      : true
- memory                             : 8GB
- network-nameserver                 : [1.1.1.1]
```

**Comment by praveenkumar** [comment] 2018-09-06 04:55
@klauern Are you behind the proxy, if yes then make sure VM ip (in your case 172.18.79.102) should be added to your `no_proxy` / `NO_PROXY` environment variable.

**Comment by klauern** [comment] 2018-09-06 11:48
@praveenkumar This was done on my personal computer, which is not behind a proxy at all.

**Comment by praveenkumar** [comment] 2018-09-06 13:13
@amitkrout @agajdosi can you reproduce this on windows system?

**Comment by amitkrout** [comment] 2018-09-07 07:00
@praveenkumar I am unable to reproduce this. 
```
PS C:\minishift-1.23.0-windows-amd64> .\minishift.exe profile set test
Profile 'test' set as active profile.
PS C:\minishift-1.23.0-windows-amd64> .\minishift.exe config set network-nameserver 1.1.1.1
PS C:\minishift-1.23.0-windows-amd64> .\minishift.exe start
-- Starting profile 'test'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'myswitch' ... OK
[...]
The server is accessible via web console at:
    https://10.40.143.225:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Exporting of OpenShift images is occuring in background process with pid 3256.

PS C:\minishift-1.23.0-windows-amd64> & .\minishift oc-env | Invoke-Expression
PS C:\minishift-1.23.0-windows-amd64> & .\minishift docker-env | Invoke-Expression
PS C:\minishift-1.23.0-windows-amd64> .\minishift.exe config view
- network-nameserver                 : [1.1.1.1]
PS C:\minishift-1.23.0-windows-amd64> oc status
In project My Project (myproject) on server https://10.40.143.225:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.
```

**Comment by praveenkumar** [comment] 2018-09-11 03:41
@klauern Are you still facing this issue? if yes can you provide the no_proxy/NO_PROXY, http_proxy/HTTP_PROXY and https_proxy/HTTPS_PROXYdetails here?

**Comment by klauern** [comment] 2018-09-13 17:53
I am not facing this issue anymore, but I'm not sure what fixed it.  I've removed almost all of my networking devices, bridges, switches, etc., and am only using the "Default Switch" that comes OOTB with Hyper-V enabled, and my WiFi connection.  I think that by not giving it any choices on devices, subnets, etc., to provision IP's, seems to prevent it from breaking.

**Comment by praveenkumar** [comment] 2018-09-14 05:26
@klauern thanks for the confirmation, mostly it was due to some network device. Closing this issue now.

**Closed** 2018-09-14 05:27 UTC
