### ISSUE TITLE
config view needs a trailing line feed

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#756] opened 2017-04-14 19:07 UTC
ovpn-120-36:minishift-1.0.0-rc.1-darwin-amd64 burr$ ./minishift config view
- cpus                 : 2
- disk-size            : 20g
- iso-url              : file:///Users/burr/.minishift/cache/iso/minishift-rhel7.iso
- memory               : 6000
- vm-driver            : virtualboxovpn-120-36:minishift-1.0.0-rc.1-darwin-amd64 burr$

**Comment by budhrg** [comment] 2017-04-15 05:30
This has been fixed in latest master now.

####  Minishift Master
```
$ minishift config view                     
- vm-driver            : kvm

$
```

####  Minishift RC 1
```
$ ./minishift-rc1 config view
- vm-driver            : kvm[budhram@dhcp35-83 minishift]$
```

@burrsutter , could you try the latest master build from here http://artifacts.ci.centos.org/minishift/minishift/master/93/darwin-amd64/minishift

and let us know if the issue still exists or not?

Thanks

**Comment by LalatenduMohanty** [comment] 2017-04-17 11:08
This is duplicate of #724

**Comment by LalatenduMohanty** [comment] 2017-04-17 11:10
@burrsutter as @budhrg mentioned it is duplicate of #724 and already fixed in master and should be available in next release if you want a released Minishift. I am going to close this. However please re-open if the issue is not fixed for you.

**Closed by LalatenduMohanty** 2017-04-17 11:10 UTC
Labels: kind/bug, priority/minor, resolution/duplicate
