### ISSUE TITLE
How to get rid of to set up every time "oc" environment after "minishift start"

### ISSUE THREAD

**Issue by anaresh7777** [minishift/minishift#2780] opened 2018-09-07 10:15 UTC
Is there a way to not every time to set up "oc" environment(val $(minishift oc-env)) after "minishift start"?. This problem I had with the previous versions of minishift but I am facing this issue after upgrading to latest minishift 1.23.0.

**Comment by praveenkumar** [comment] 2018-09-07 11:57
@anaresh7777 can you paste exact command you tried and the error message you are getting which will help us to find a root cause around it.

**Comment by anaresh7777** [comment] 2018-09-07 15:49
I can start minishift successfully. but when I run "oc config view" command. I am getting " oc: command not found". I can run "oc" commands without any issues when I set-up oc environment "eval $(minishift oc-env)". So, do I need to set-up oc environment every start of minishift or is there any other way to use oc commands after minishift start without setting-up oc environment every time?
I mean, I want to use like following:
1. minishift start
2. oc config view (But now I am getting oc: command not found)

**Comment by anaresh7777** [comment] 2018-09-10 09:06
@praveenkumar Thanks for the information. It's cleared.

**Comment by praveenkumar** [comment] 2018-09-10 15:40
@anaresh7777 ack, closing this now.

**Closed by praveenkumar** 2018-09-10 15:40 UTC
