### ISSUE TITLE
docker images not cached

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#1734] opened 2017-11-22 09:05 UTC
The image-cache parameter has been set for my profile but no images are stored under `~/.minishift/cache/images` or `./minishift/profiles/istio-demo/cacje/images`

```
minishift config view --profile istio-demo
- cpus                 : 2
- image-caching        : true
- memory               : 3GB
- openshift-version    : v3.7.0-rc.0
- vm-driver            : xhyve

minishift start --profile istio-demo
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    3 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ......................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.7.0-rc.0
-- Checking `oc` support for startup flags ...
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   version ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.7.0-rc.0 ...
Pulling image openshift/origin:v3.7.0-rc.0
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 46% complete
Pulled 1/4 layers, 68% complete
Pulled 2/4 layers, 80% complete
Pulled 3/4 layers, 88% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.22:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Applying addon 'admin-user':..

-- Exporting of OpenShift images is occuring in background process with pid 73158.
```

But folders are empty

```
lr ~/.minishift/cache/images
/Users/dabou/.minishift/cache/images
 lr ~/.minishift/profiles/istio-demo/cache/images
/Users/dabou/.minishift/profiles/istio-demo/cache/images
```

**Comment by gbraad** [comment] 2017-11-22 09:35
which version of minishift are you using?

**Comment by gbraad** [comment] 2017-11-22 09:37
Duplicate of #1666

**Closed by gbraad** 2017-11-22 09:37 UTC
