### ISSUE TITLE
OpenShift Config Patch does not work as expected

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#2569] opened 2018-07-08 07:22 UTC
### General information

  * Minishift version: `v1.19.0+1750702`
  * OS: Linux / macOS / Windows:  macOS
  * Hypervisor: xhyve 

### Steps to reproduce

  1.  Run minishift openshift config set --patch '{
  "oauthConfig": {
    "identityProviders": [
      {
        "challenge": "true",
        "login": "true",
        "mappingMethod": "claim",
        "name": "htpasswd",
        "provider": {
          "apiVersion": "v1",
          "kind": "HTPasswdPasswordIdentityProvider",
          "file": "/var/lib/minishift/openshift.local.config/master/users.htpasswd"
        }
      }
    ]
  }
}'

### Expected
The Patch should be applied correctly and the minishift OpenShift to be restarted successfully 

### Actual
Minishift patch fails to update and the its rolled back successfully .

If we do the same command via oc ex config patch , I see the patch getting correctly updated:

```minishift openshift config view | oc ex config patch  --patch='{"oauthConfig": {"identityProviders": [ {"challenge": true,"login": true,"mappingMethod": "claim","name": "htpasswd","provider": {"apiVersion": "v1","kind": "HTPasswdPasswordIdentityProvider","file": "/var/lib/minishift/openshift.local.config/master/users.htpasswd"}}]}}' -```

**Comment by praveenkumar** [comment] 2018-07-09 07:52
@kameshsampath I tried below and now everything works as expected. We will try to have an addon soon which will resolve it soon.

```
# On the CentOS VM
$ sudo yum install httpd-tools
$ htpasswd -c /var/lib/minishift/openshift.local.config/master/users.htpasswd developer

# Exit from the VM
$ minishift openshift config set --patch '{"oauthConfig": {"identityProviders": [ {"challenge": true,"login": true,"mappingMethod": "add","name": "htpasswd","provider": {"apiVersion": "v1","kind": "HTPasswdPasswordIdentityProvider","file": "users.htpasswd"}}]}}'
```

the problem which you had in your patch config is the path of the file it assumes the file should be in `/var/lib/minishift/openshift.local.config/master/` and also doesn't need absolute path.

**Comment by kameshsampath** [comment] 2018-07-09 08:48
> the problem which you had in your patch config is the path of the file it assumes the file should be in /var/lib/minishift/openshift.local.config/master/ and also doesn't need absolute path.
is this minishift restriction because of persistence, IIRC OpenShift allows me to have that file anywhere as long as I have right permissions for it.

anyways thanks for the analysis and I wish the error message should be bit more clearer as I dont see any info in the logs, I did had a doubt regarding filepath. 

Worth checking with OpenShift guys ?

**Comment by anjannath** [comment] 2018-07-10 09:57
@praveenkumar Can we close this? as this was not a bug in the command but because the package was not present..
/cc @kameshsampath

**Comment by praveenkumar** [comment] 2018-07-10 13:32
Yes, close this, @kameshsampath any objection?

**Closed** 2018-07-11 06:09 UTC
Labels: kind/bug, priority/major
