### ISSUE TITLE
Running minishift delete followed by minishift start leaves invalid entries in .kube/config

### ISSUE THREAD

**Issue by ceridwen** [minishift/minishift#1915] opened 2018-01-16 21:20 UTC
### General information

  * Minishift version: v1.11.0+4459917
  * OS: Mac OS X 10.12.6
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Start a minishift cluster.
  2. Run `oc login system:admin`
  3. Run `minishift delete`.

### Expected

The minishift entries are cleaned up, so that if I need to e.g. change minishift versions, I don't keep adding more and more cruft into my .kube/config.

### Actual

I have users and corresponding contexts `- name: system:admin/127-0-0-1:8443`, `- name: system:admin/192-168-99-105:8443`, `- name: developer/192-168-99-105:8443`, and two clusters under  `server: https://127.0.0.1:8443` and `server: https://192.168.99.105:8443` left over.

**Comment by gbraad** [comment] 2018-01-17 02:24
Just like minikube, we do not touch any config file in `~\.kube\config` when it concerns the delete. This has been discussed before to implement, but unable to find the issue.

**Comment by ceridwen** [comment] 2018-01-17 21:02
I looked, and I couldn't find any previous discussion either.  The difference between minikube and minishift here is that minikube creates one entry each in clusters/contexts/users, and when you do minikube delete followed by minikube start, there's still only one entry each.  With minishift, every delete-start cycle results in more and more entries building up in .kube/config.  Maybe it's start that needs to be changed, but at the moment if you need to change minishift versions for testing like I do, switching requires a lot of manual cleanup.

**Comment by LalatenduMohanty** [comment] 2018-03-06 18:01
The issue is with the `oc` binary, check https://github.com/openshift/origin/issues/18645

**Comment by praveenkumar** [comment] 2018-06-04 05:46
This is not something we can do but how `oc` actually behave so I am in favor to close this issue.

**Closed by praveenkumar** 2018-06-04 05:46 UTC
Labels: kind/bug, priority/minor
