### ISSUE TITLE
Metrics don't work due to permission issue for cassandra pod

### ISSUE THREAD

**Issue by VeerMuchandi** [minishift/minishift#802] opened 2017-04-21 14:15 UTC
I am using  Mac OS Sierra 10.12.4

$ minishift version
Minishift version: 1.0.0-rc.2
CDK Version: 3.0.0-20042017

See the pastebin here. It seems to have issue with persistent volume claim. 
https://pastebin.com/kF56yEuh

**Comment by LalatenduMohanty** [comment] 2017-04-21 14:21
Thanks for the issue report. We will try to reproduce and if it is a issue only with CDK then we will move it to CDK Jira i.e. https://issues.jboss.org/projects/CDK/i

**Comment by VeerMuchandi** [comment] 2017-04-21 16:52
I verified this issue is on CDK only

**Comment by LalatenduMohanty** [comment] 2017-04-24 06:56
@VeerMuchandi  Opened https://issues.jboss.org/browse/CDK-118  as it is a CDK specific issue and closing this.

**Comment by hferentschik** [comment] 2017-04-24 09:13
@LalatenduMohanty I don't think this is CDK specific. I did a quick check, and cannot get metrics to work with any of the rc versions, nor with master. I have to revert back to beta5 and then it works. 

It might indeed be related to enabling persistent volumes (but have not looked any deeper). I recommend re-opening and also increasing the priority, since this a quite big issue.

**Comment by budhrg** [comment] 2017-04-24 09:16
> I did a quick check, and cannot get metrics to work with any of the rc versions, nor with master. I have to revert back to beta5 and then it works.

@hferentschik , Did you test in Mac? as for Fedora 25 (Linux) it was working for me and @LalatenduMohanty .

**Comment by hferentschik** [comment] 2017-04-24 09:42
> Did you test in Mac? as for Fedora 25 (Linux) it was working for me and

I am on Mac, but I have a hard time seeing how this is related. How do you verify that Hawkular is up? I can see some Metrics related pods as well, but I still cannot access Hawkular. When I access 'https://metrics-openshift-infra.192.168.99.100.nip.io/hawkular/metrics' using a rc version or master, I get: "Application is not available" (and some additional info).

If I run, however, `minishift start --metrics --openshift-version v1.4.1`,  I can access Hawkular. So, I can actually use master, but I have to provision an earlier version of OpenShift.

**Comment by praveenkumar** [comment] 2017-04-24 11:49
It fails for `cassandra` pod and below is the logs from the exited pod looks like permission issue.

```
$ docker logs 7e143b75e0cf
The MAX_HEAP_SIZE envar is not set. Basing the MAX_HEAP_SIZE on the available memory limit for the pod (4144390144).
The memory limit is between 2 and 4GB. Setting max_heap_size to 1GB.
The MAX_HEAP_SIZE has been set to 1024M
THE HEAP_NEWSIZE envar is not set. Setting to 200M based on the CPU_LIMIT of 2000. [100M per CPU core]
About to generate seeds
Trying to access the Seed list [try #1]
Trying to access the Seed list [try #2]
Trying to access the Seed list [try #3]
Setting seeds to be hawkular-cassandra-1-k6wn3
cat: /etc/ld.so.conf.d/*.conf: No such file or directory
getopt: invalid option -- 'R'
OpenJDK 64-Bit Server VM warning: Cannot open file /opt/apache-cassandra/logs/gc.log due to No such file or directory
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.deserializeLargeSubset (Lorg/apache/cassandra/io/util/DataInputPlus;Lorg/apache/cassandra/db/Columns;I)Lorg/apache/cassandra/db/Columns;
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.serializeLargeSubset (Ljava/util/Collection;ILorg/apache/cassandra/db/Columns;ILorg/apache/cassandra/io/util/DataOutputPlus;)V
CompilerOracle: dontinline org/apache/cassandra/db/Columns$Serializer.serializeLargeSubsetSize (Ljava/util/Collection;ILorg/apache/cassandra/db/Columns;I)I
CompilerOracle: dontinline org/apache/cassandra/db/transform/BaseIterator.tryGetMoreContents ()Z
CompilerOracle: dontinline org/apache/cassandra/db/transform/StoppingTransformation.stop ()V
CompilerOracle: dontinline org/apache/cassandra/db/transform/StoppingTransformation.stopInPartition ()V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.doFlush (I)V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.writeExcessSlow ()V
CompilerOracle: dontinline org/apache/cassandra/io/util/BufferedDataOutputStreamPlus.writeSlow (JI)V
CompilerOracle: dontinline org/apache/cassandra/io/util/RebufferingInputStream.readPrimitiveSlowly (I)J
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.selectBoundary (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;II)I
CompilerOracle: inline org/apache/cassandra/utils/AsymmetricOrdering.strictnessOfLessThan (Lorg/apache/cassandra/utils/AsymmetricOrdering/Op;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/vint/VIntCoding.encodeVInt (JI)[B
INFO  [main] 2017-04-24 11:44:54,434 YamlConfigurationLoader.java:85 - Configuration location: file:/opt/apache-cassandra-3.0.9-1/conf/cassandra.yaml
INFO  [main] 2017-04-24 11:44:54,549 Config.java:446 - Node configuration:[allocate_tokens_for_keyspace=null; authenticator=AllowAllAuthenticator; authorizer=AllowAllAuthorizer; auto_bootstrap=true; auto_snapshot=true; batch_size_fail_threshold_in_kb=50; batch_size_warn_threshold_in_kb=5; batchlog_replay_throttle_in_kb=1024; broadcast_address=null; broadcast_rpc_address=null; buffer_pool_use_heap_if_exhausted=true; cas_contention_timeout_in_ms=1000; client_encryption_options=<REDACTED>; cluster_name=hawkular-metrics; column_index_size_in_kb=64; commit_failure_policy=stop; commitlog_compression=LZ4Compressor; commitlog_directory=/cassandra_data/commitlog; commitlog_max_compression_buffers_in_pool=3; commitlog_periodic_queue_size=-1; commitlog_segment_size_in_mb=32; commitlog_sync=periodic; commitlog_sync_batch_window_in_ms=null; commitlog_sync_period_in_ms=10000; commitlog_total_space_in_mb=null; compaction_large_partition_warning_threshold_mb=100; compaction_throughput_mb_per_sec=16; concurrent_compactors=null; concurrent_counter_writes=32; concurrent_materialized_view_writes=32; concurrent_reads=32; concurrent_replicates=null; concurrent_writes=32; counter_cache_keys_to_save=2147483647; counter_cache_save_period=7200; counter_cache_size_in_mb=null; counter_write_request_timeout_in_ms=5000; cross_node_timeout=false; data_file_directories=[Ljava.lang.String;@482cd91f; disk_access_mode=auto; disk_failure_policy=stop; disk_optimization_estimate_percentile=0.95; disk_optimization_page_cross_chance=0.1; disk_optimization_strategy=ssd; dynamic_snitch=true; dynamic_snitch_badness_threshold=0.1; dynamic_snitch_reset_interval_in_ms=600000; dynamic_snitch_update_interval_in_ms=100; enable_scripted_user_defined_functions=false; enable_user_defined_functions=false; enable_user_defined_functions_threads=true; encryption_options=null; endpoint_snitch=SimpleSnitch; file_cache_size_in_mb=512; gc_log_threshold_in_ms=200; gc_warn_threshold_in_ms=1000; hinted_handoff_disabled_datacenters=[]; hinted_handoff_enabled=true; hinted_handoff_throttle_in_kb=1024; hints_compression=null; hints_directory=null; hints_flush_period_in_ms=10000; incremental_backups=false; index_interval=null; index_summary_capacity_in_mb=null; index_summary_resize_interval_in_minutes=60; initial_token=null; inter_dc_stream_throughput_outbound_megabits_per_sec=200; inter_dc_tcp_nodelay=false; internode_authenticator=null; internode_compression=all; internode_recv_buff_size_in_bytes=null; internode_send_buff_size_in_bytes=null; key_cache_keys_to_save=2147483647; key_cache_save_period=14400; key_cache_size_in_mb=null; listen_address=hawkular-cassandra-1-k6wn3; listen_interface=null; listen_interface_prefer_ipv6=false; listen_on_broadcast_address=false; max_hint_window_in_ms=10800000; max_hints_delivery_threads=2; max_hints_file_size_in_mb=128; max_mutation_size_in_kb=null; max_streaming_retries=3; max_value_size_in_mb=256; memtable_allocation_type=heap_buffers; memtable_cleanup_threshold=null; memtable_flush_writers=null; memtable_heap_space_in_mb=null; memtable_offheap_space_in_mb=null; min_free_space_per_drive_in_mb=50; native_transport_max_concurrent_connections=-1; native_transport_max_concurrent_connections_per_ip=-1; native_transport_max_frame_size_in_mb=256; native_transport_max_threads=128; native_transport_port=9042; native_transport_port_ssl=null; num_tokens=256; otc_coalescing_strategy=TIMEHORIZON; otc_coalescing_window_us=200; partitioner=org.apache.cassandra.dht.Murmur3Partitioner; permissions_cache_max_entries=1000; permissions_update_interval_in_ms=-1; permissions_validity_in_ms=2000; phi_convict_threshold=8.0; range_request_timeout_in_ms=10000; read_request_timeout_in_ms=5000; request_scheduler=org.apache.cassandra.scheduler.NoScheduler; request_scheduler_id=null; request_scheduler_options=null; request_timeout_in_ms=10000; role_manager=CassandraRoleManager; roles_cache_max_entries=1000; roles_update_interval_in_ms=-1; roles_validity_in_ms=2000; row_cache_class_name=org.apache.cassandra.cache.OHCProvider; row_cache_keys_to_save=2147483647; row_cache_save_period=0; row_cache_size_in_mb=0; rpc_address=hawkular-cassandra-1-k6wn3; rpc_interface=null; rpc_interface_prefer_ipv6=false; rpc_keepalive=true; rpc_listen_backlog=50; rpc_max_threads=2147483647; rpc_min_threads=16; rpc_port=9160; rpc_recv_buff_size_in_bytes=null; rpc_send_buff_size_in_bytes=null; rpc_server_type=sync; saved_caches_directory=null; seed_provider=org.apache.cassandra.locator.SimpleSeedProvider{seeds=hawkular-cassandra-1-k6wn3}; server_encryption_options=<REDACTED>; snapshot_before_compaction=false; ssl_storage_port=7001; sstable_preemptive_open_interval_in_mb=50; start_native_transport=true; start_rpc=false; storage_port=7000; stream_throughput_outbound_megabits_per_sec=200; streaming_socket_timeout_in_ms=86400000; thrift_framed_transport_size_in_mb=15; thrift_max_message_length_in_mb=16; tombstone_failure_threshold=100000; tombstone_warn_threshold=1000; tracetype_query_ttl=86400; tracetype_repair_ttl=604800; trickle_fsync=false; trickle_fsync_interval_in_kb=10240; truncate_request_timeout_in_ms=60000; unlogged_batch_across_partitions_warn_threshold=10; user_defined_function_fail_timeout=1500; user_defined_function_warn_timeout=500; user_function_timeout_policy=die; windows_timer_interval=1; write_request_timeout_in_ms=2000]
INFO  [main] 2017-04-24 11:44:54,551 DatabaseDescriptor.java:311 - DiskAccessMode 'auto' determined to be mmap, indexAccessMode is mmap
INFO  [main] 2017-04-24 11:44:54,693 DatabaseDescriptor.java:418 - Global memtable on-heap threshold is enabled at 251MB
INFO  [main] 2017-04-24 11:44:54,693 DatabaseDescriptor.java:422 - Global memtable off-heap threshold is enabled at 251MB
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Unable to check disk space available to /cassandra_data/commitlog. Perhaps the Cassandra user does not have the necessary permissions
org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to /cassandra_data/commitlog. Perhaps the Cassandra user does not have the necessary permissions
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:538)
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:119)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:543)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:696)
ERROR [main] 2017-04-24 11:44:54,714 CassandraDaemon.java:709 - Exception encountered during startup
org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to /cassandra_data/commitlog. Perhaps the Cassandra user does not have the necessary permissions
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:538) ~[apache-cassandra-3.0.9-1.jar:3.0.9-1]
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:119) ~[apache-cassandra-3.0.9-1.jar:3.0.9-1]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:543) [apache-cassandra-3.0.9-1.jar:3.0.9-1]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:696) [apache-cassandra-3.0.9-1.jar:3.0.9-1]
Caused by: java.nio.file.AccessDeniedException: /cassandra_data/commitlog
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_111]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_111]
	at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:57) ~[na:1.8.0_111]
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:64) ~[na:1.8.0_111]
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44) ~[na:1.8.0_111]
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51) ~[na:1.8.0_111]
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39) ~[na:1.8.0_111]
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368) ~[na:1.8.0_111]
	at java.nio.file.Files.getFileStore(Files.java:1461) ~[na:1.8.0_111]
	at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:747) ~[apache-cassandra-3.0.9-1.jar:3.0.9-1]
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:528) ~[apache-cassandra-3.0.9-1.jar:3.0.9-1]
	... 3 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /cassandra_data/commitlog
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:57)
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:64)
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
	at java.nio.file.Files.getFileStore(Files.java:1461)
	at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:747)
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:528)
```

**Comment by hferentschik** [comment] 2017-04-24 14:21
> It fails for cassandra pod and below is the logs from the exited pod looks like permission issue.

@praveenkumar good digging.  I take it, this is not a Mac issue then, right? Do you mind updating the title of the issue?

**Comment by hferentschik** [comment] 2017-04-24 14:22
@praveenkumar next question of course is why this is happening. 1.4.1 seems to work fine, but 1.5.x fails. Is it something we do or is it an issue with _cluster up_ or OpenShift?

**Comment by hferentschik** [comment] 2017-04-24 14:26
@praveenkumar, this seems to be inline what I have been seeing. One pod kept restarting all the time. I had no time yet to look into it, but cassandra pod?

@csrwng Any idea what could cause Metrics deployment failure with OpenShift 1.5.x?

**Comment by csrwng** [comment] 2017-04-24 14:28
@hferentschik not sure, will take a look

**Comment by budhrg** [comment] 2017-04-25 04:28
Same behavior with Windows 10.

**Comment by budhrg** [comment] 2017-04-25 05:24
I am experiencing same behavior with `v1.4.1` too.

**Comment by hferentschik** [comment] 2017-04-25 08:04
@budhrg It is not enough to look in the OpenShift Console. This warning can be there, even so Hawkular is up and running. You need to access Hawkulkar.

**Comment by budhrg** [comment] 2017-04-25 10:12
> This warning can be there, even so Hawkular is up and running. You need to access Hawkulkar.

Don't know what happen but it seems it is working fine with 1.4.1 now. Might be timing thing here.

But 1.5.0-rc.0 is not working as I commented before.

**Comment by LalatenduMohanty** [comment] 2017-04-26 07:25
This sounds like a regression with "cluster up" or Minishift. Hence increased the priority. We should cross check `cluster up` in 1.5 and file an issue in Origin repo if we see the same issue.

**Comment by hferentschik** [comment] 2017-04-26 09:28
For what it's worth,  I tried with pure _cluster up_ using _oc_ version 1.5.0 and I am seeing the same problem. Hawkular never really fully comes up. 

@csrwng any update on this?

**Comment by hferentschik** [comment] 2017-04-26 09:30
I don't think we can do much in terms of the release. The only alternative seems to be to provision OpenShift 1.4.1 (using _oc_ 1.5.0) as baseline. However, this feels wrong.

I suggest to use 1.5.0 as baseline. People needing metrics can always explicitly provision 1.4.1. Not nice, but I think it is the better option atm.

Thoughts?

**Comment by budhrg** [comment] 2017-04-26 09:53
> I suggest to use 1.5.0 as baseline. People needing metrics can always explicitly provision 1.4.1. Not nice, but I think it is the better option atm.

Sounds good to me. Are we documenting anywhere for it ?

**Comment by csrwng** [comment] 2017-04-26 15:30
@hferentschik @budhrg I've hit this problem with regular cluster up on v1.5.0. What I see is that there's a timeout pulling an image from dockerhub:
```
Error: error pulling image configuration: Get https://registry-1.docker.io/v2/openshift/origin/blobs/sha256:4f46cd210abb0c11d28190c02b95e000f0375ea3019005ea4a2bf186d7f7d02d: net/http: TLS handshake timeout
```
This happened for some of the images. If you pre-pull the images, things work ok. I believe this is a new problem with docker hub.

**Comment by csrwng** [comment] 2017-04-26 16:22
I've tested with minishift version 1.0.0-rc.2 and was able to get metrics working... with some manual tweaking. So it looks like the hawkular-cassandra image is the last one to be pulled (likely slower due to the issue I mentioned with docker hub above). So by the time it finishes downloading the hawkular-metrics pod has given up trying to connect to it. After the hawkular-cassandra pod started, I manually deleted the hawkular-metrics pod to let the replication controller recreate it. At that point it came up and everything was happy.

One possible fix would be to pre-pull these images, (or at least start the pre-pull asynchronously when you get the --metrics flag).

**Comment by budhrg** [comment] 2017-04-28 05:23
> One possible fix would be to pre-pull these images, (or at least start the pre-pull asynchronously when you get the --metrics flag).

This seems to somehow related to https://github.com/minishift/minishift/issues/143.

**Comment by hferentschik** [comment] 2017-04-28 07:22
@csrwng, 

> One possible fix would be to pre-pull these images, (or at least start the pre-pull asynchronously when you get the --metrics flag).

Are you suggesting this as a fix on the Minishift side or in _cluster up_? It really should be fixed in the latter, right?

**Comment by csrwng** [comment] 2017-04-28 13:35
@hferentschik yes one way to fix it would be to have cluster up start a background process to pull images, but in my opinion that's not ideal. We'd only be gaining a few seconds before the metrics deployer creates its pod.

I may have asked this before, but is there a technical reason to not include images in the iso that minishift pulls down?

**Comment by hferentschik** [comment] 2017-04-28 13:45
>  yes one way to fix it would be to have cluster up start a background process to pull images, but in my opinion that's not ideal. 

why not? After all the issues also exist in pure _cluster up_. Not sure about what you mean exactly with "We'd only be gaining a few seconds before the metrics deployer creates its pod", but for me it's about getting metrics up and running consistently when the --metrics flag is specified. Maybe this is not even an issue in _cluster up_, but OpenShift directly. Surely it should not be required to re-pull images.  

> I may have asked this before, but is there a technical reason to not include images in the iso that minishift pulls down?

Size is a big argument, especially since metrics is an optional feature. Also, Minishift allows you to provision different versions of OpenShift. So at best we could include a default which might get out of date quickly.

**Comment by csrwng** [comment] 2017-04-28 13:49
> Not sure about what you mean exactly with "We'd only be gaining a few seconds before the metrics deployer creates its pod",

What I mean is that if we begin pulling the image asynchronously on startup, it's not guaranteed that we won't run into this problem again because the metrics deployer pod will try to start running metrics pods shortly after startup and images will likely not be ready by then.

Maybe the real solution would be to change the way that the metrics deployer works and not create any pods until images have been pulled down.

**Comment by csrwng** [comment] 2017-04-28 13:53
> Size is a big argument, especially since metrics is an optional feature. Also, Minishift allows you to provision different versions of OpenShift. So at best we could include a default which might get out of date quickly.

Would it be possible to pull a different iso based on your options? I can see this being useful particularly in the case where you want to work completely offline

**Comment by hferentschik** [comment] 2017-04-28 13:54
> Maybe the real solution would be to change the way that the metrics deployer works and not create any pods until images have been pulled down

That sounds reasonable. As a user I expect the metrics deployer to do the right thing. Having to know and deal with order and timings of image pull seems wrong.

**Comment by csrwng** [comment] 2017-04-28 13:56
@jcantrill ^^

**Comment by jcantrill** [comment] 2017-04-28 14:40
I defer to @mwringe

**Comment by jorgemoralespou** [comment] 2017-04-28 18:57
@csrwng I also think that regarding metrics and logging this is a big issue in both cluster up and minishift, and a solution should be provided. Changing from a deployer pod to a job could give some benefit in how the orchestrated deployment can be done, but not sure if there will be more ways to deploy these soon (with ansible apps through the service broker).

**Comment by LalatenduMohanty** [comment] 2017-10-28 18:19
This is a still an issue. Hence re-opening.

**Comment by hferentschik** [comment] 2017-10-30 08:50
Given that metrics are going to change, we can imo close this issue. Nothing we can do from our side anyways.

**Comment by LalatenduMohanty** [comment] 2017-10-30 09:02
@hferentschik I have also heard the rumors. Do you have more information or pointers for the new implementation for metrics?

**Comment by jcantrill** [comment] 2017-10-30 16:27
* https://github.com/openshift/origin/tree/master/examples/prometheus
* https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_prometheus

**Closed** 2017-10-31 08:31 UTC
Labels: kind/bug, priority/critical

**Comment by ldipotetjob** [comment] 2018-02-23 11:09
I have the same problem when i try to deploy an image of Cassandra.
OpenJDK 64-Bit Server VM warning: Cannot open file /var/log/cassandra/gc.log due to Permission denied.
And a lot of people have the same problem without any clear solution.
I am thinking seriously in change of PaaS. It is just a Cassandra installation !!.

**Comment by ldipotetjob** [comment] 2018-02-23 11:18
This is what Red hat say:
[https://access.redhat.com/solutions/2929691
: Solutions in progress

**Comment by mwringe** [comment] 2018-02-23 14:35
@jsanda can you take a look?

**Comment by abhaynayak24** [comment] 2018-06-05 09:17
Is there any way to export the data in cassandra to an excel file?
