### ISSUE TITLE
Error starting VM on RHEL + DevSuite

### ISSUE THREAD

**Issue by cdrage** [minishift/minishift#1467] opened 2017-09-29 16:09 UTC
Following these exact instructions resulted in this error when first starting minishift: https://developers.redhat.com/products/devsuite/hello-world/#fndtn-rhel

```sh
[rhel@rhel ~]$ minishift start
Starting local OpenShift cluster using 'kvm' hypervisor...
E0929 12:07:42.633966    1691 start.go:282] Error starting the VM: dial tcp: missing address. Retrying.
E0929 12:07:42.656182    1691 start.go:282] Error starting the VM: dial tcp: missing address. Retrying.
E0929 12:07:42.679701    1691 start.go:282] Error starting the VM: dial tcp: missing address. Retrying.
Error starting the VM: dial tcp: missing address
dial tcp: missing address
dial tcp: missing address
```

I can confirm that I've also installed KVM...

**Comment by cdrage** [comment] 2017-09-29 16:11
Ahhhh, looks I have to update: https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.1/html-single/getting_started_guide/index which is down-stream from Minishift. My mistake! Ended up being a KVM hypervisor problem..

However, is there a way for this error to be updated / more useful information?

**Comment by gbraad** [comment] 2017-10-02 03:45
Please provide error logs with `minishift --show-libmachine-logs -v5`.
Never seen this `missing address` before...

**Comment by cdrage** [comment] 2017-10-02 13:10
@gbraad See above comment, it was because KVM had not yet been set-up.

To reproduce: Setup a clean RHEL image, install https://developers.redhat.com/products/devsuite/hello-world/#fndtn-rhel and try to bring it up after setting up the CDK.

**Comment by gbraad** [comment] 2017-10-02 15:05
So the problem is resolved?
In minishift I worked on #485 which provides startup checks to see if requirements arr net. This will also be available in the next release of CDK.

**Comment by cdrage** [comment] 2017-10-02 15:26
@gbraad I believe minishift should check to see if libvirt / kvm is installed, so no :-1:

**Comment by gbraad** [comment] 2017-10-03 01:39
It does ...

https://github.com/minishift/minishift/blob/d549fb33d7157b1358906e879aa4cc2e795bfcba/cmd/minishift/cmd/start_preflight.go#L224

Closing, as this been resolved. If the problem persists or is insufficient please open a new issue. If issues with CDK, please open a Jira issue.

**Closed by gbraad** 2017-10-03 01:39 UTC

**Comment by cdrage** [comment] 2017-10-03 13:42
Hey @gbraad 

This issue is *not* resolved, I ask for you to please re-open this issue.

As per my previous comments, even with the attached code:

https://github.com/minishift/minishift/blob/d549fb33d7157b1358906e879aa4cc2e795bfcba/cmd/minishift/cmd/start_preflight.go#L224

`docker-machine-driver-kvm` is the only thing that is being checked.

docker-machine-driver-kvm is installed by default via `rh-devsuite`. I have no issues with that. 

The issue is that libvirt / kvm is *not* being checked. Checking to see if libvirt is installed or if the libvirtd daemon is running would be ideal. Or even if `virsh` is available.


Ping @LalatenduMohanty @praveenkumar

**Comment by cdrage** [comment] 2017-10-03 14:10
Also, we check HyperV in a suitable way (https://github.com/minishift/minishift/blob/d549fb33d7157b1358906e879aa4cc2e795bfcba/cmd/minishift/cmd/start_preflight.go#L257). Ideally it would be nice to have this added to xhyve + kvm checks, rather than simply checking to see if the driver is installed (which technically, is NOT checking to see if xhyve + kvm is installed).

**Comment by gbraad** [comment] 2017-10-03 15:20
#1472 was opened

**Comment by cdrage** [comment] 2017-10-03 15:48
Thanks for giving the issue (https://github.com/minishift/minishift/issues/1472). Closing without context confused me since you just linked start_preflight.go and that's it.

I'm good now :+1:

**Comment by gbraad** [comment] 2017-10-03 15:49
Whoops... my apologies. I had written a closing comment with the new issue ID... seems on reposting I forgot to include it. Anyways, the check is merged
