### ISSUE TITLE
che feature step reports runtime error 

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2974] opened 2018-11-05 09:09 UTC
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. make integration GODOG_OPTS="-tags addon-che"
  2. 
  3. 
  4. 

### Expected
Should not through any runtime error

### Actual
Error is coming from - https://github.com/minishift/minishift/blob/master/test/integration/features/addons/addon-che.feature#L28

```
When user tries to get the stacks information # che-steps.go:43 -> *CheRunner./che.weTryToGetTheStacksInformation
02:03:25     runtime error: invalid memory address or nil pointer dereference
02:03:25 runtime.call64
02:03:25 	/usr/lib/golang/src/runtime/asm_amd64.s:574
02:03:25 runtime.gopanic
02:03:25 	/usr/lib/golang/src/runtime/panic.go:502
02:03:25 runtime.panicmem
02:03:25 	/usr/lib/golang/src/runtime/panic.go:63
02:03:25 runtime.sigpanic
02:03:25 	/usr/lib/golang/src/runtime/signal_unix.go:388
02:03:25 github.com/minishift/minishift/test/integration/che.doRequest
02:03:25 	github.com/minishift/minishift/test/integration/che/cheAPI.go:201
02:03:25 github.com/minishift/minishift/test/integration/che.(*CheAPI).GetStackInformation
02:03:25 	github.com/minishift/minishift/test/integration/che/cheAPI.go:486
02:03:25 github.com/minishift/minishift/test/integration/che.(*CheRunner).weTryToGetTheStacksInformation
02:03:25 	github.com/minishift/minishift/test/integration/che/che.go:70
02:03:25 github.com/minishift/minishift/test/integration/che.(*CheRunner).(github.com/minishift/minishift/test/integration/che.weTryToGetTheStacksInformation)-fm
02:03:25 	github.com/minishift/minishift/test/integration/che/che-steps.go:43
02:03:25 runtime.call32
02:03:25 	/usr/lib/golang/src/runtime/asm_amd64.s:573
02:03:25 reflect.Value.call
02:03:25 	/usr/lib/golang/src/reflect/value.go:447
02:03:25 reflect.Value.Call
02:03:25 	/usr/lib/golang/src/reflect/value.go:308
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.(*StepDef).run
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/stepdef.go:201
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.(*Suite).runStep
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/suite.go:303
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.(*Suite).runSteps
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/suite.go:388
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.(*Suite).runScenario
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/suite.go:597
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.(*Suite).runFeature
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/suite.go:566
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.(*Suite).run
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/suite.go:220
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.(*runner).run
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/run.go:76
02:03:25 github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog.RunWithOptions
02:03:25 	github.com/minishift/minishift/vendor/github.com/DATA-DOG/godog/run.go:167
02:03:25 github.com/minishift/minishift/test/integration.TestMain
02:03:25 	github.com/minishift/minishift/test/integration/integration_test.go:35
02:03:25 main.main
02:03:25 	_testmain.go:38
02:03:25 runtime.main
02:03:25 	/usr/lib/golang/src/runtime/proc.go:198
02:03:25 runtime.goexit
02:03:25 	/usr/lib/golang/src/runtime/asm_amd64.s:2361
```

Details - https://ci.centos.org/job/minishift-nightly-centos/330/console

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by amitkrout** [comment] 2018-11-05 09:12
Locally i am not able to reproduce this on macOS+xhyve

**Comment by praveenkumar** [comment] 2018-11-05 10:19
@amitkrout is it coming from the CI?

**Comment by amitkrout** [comment] 2018-11-05 10:40
@praveenkumar yes

**Comment by agajdosi** [comment] 2018-11-05 12:20
The error is reported on line 201 in cheAPI.go, which is the return of doRequest() func: https://github.com/minishift/minishift/blob/master/test/integration/che/cheAPI.go#L201. Looking onto the function I have found there is an http request which is not closed directly or via `defer` in the code: https://github.com/minishift/minishift/blob/master/test/integration/che/cheAPI.go#L191. Looks like this could be the problem.

**Comment by agajdosi** [comment] 2018-11-05 14:48
@amitkrout @praveenkumar As this issue is intermittent and hard to reproduce I suggest to implement fix for the above hypothesis ^ in separate issue and then wait if this issue comes back in next month or not. If you agree, I am going to create the issue and upload fix with `defer res.Body.Close() ` asap. WDYT?

**Comment by agajdosi** [comment] 2018-11-05 17:15
Resolving the unclosed response in separate issue: https://github.com/minishift/minishift/issues/2978. Lets see if that fixes the problem.

**Comment by agajdosi** [comment] 2018-11-14 08:34
Today the error appeared again, however was in combination with wrong start (timeout start issue) - https://ci.centos.org/job/minishift-nightly-centos/339/consoleFull. Waiting whether the error appears again with clean start.

**Comment by agajdosi** [comment] 2019-03-04 09:10
Recently this issue appears only in combination with failed Minishift start of failed Che app rollout. The failure is then expected. Thus I am closing this issue. If we observe the failure after successful start and deployment of Che again the we can reopen this.

**Closed by agajdosi** 2019-03-04 09:10 UTC
Labels: component/integration-test, kind/bug, priority/major
