### ISSUE TITLE
Minishift: Checking for existing OpenShift container ... FAIL

### ISSUE THREAD

**Issue by garyyang6** [minishift/minishift#1627] opened 2017-10-26 22:53 UTC
Cannot start minishift at CentOS 7.  Below is the log. Can someone help.

```
minishift start --https-proxy https://myproxy..com:9000 --http-proxy http://myproxy.com:9000 --vm-driver=virtualbox
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM .............. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   host-pv-dir ... OK
   host-volumes-dir ... OK
   http-proxy ... OK
   https-proxy ... OK
   no-proxy ... OK
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... 
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... FAIL
   Error: unexpected error while checking OpenShift container state
   Caused By:
     Error: An error occurred trying to connect: Get https://192.168.42.64:2376/v1.24/containers/origin/json: remote error: tls: bad certificate
Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by gbraad** [comment] 2017-10-27 03:38
Please, when filing an issue, state your steps to reproduce, what is expected and the actual outcome.

Currently, the test you refer to
```
-- Checking HTTP connectivity from the VM ...
Retrieving http://minishift.io/index.html ... FAIL
```
does not support proxy settings, and therefore FAILs, but does not error the execution to continue. This is already recorded in another task and will be fixed.

Closing this issue

**Comment by gbraad** [comment] 2017-10-27 03:44
Closed the wrong issue... Slightly confused about the issues you filed. Earlier you filed: #1625. Will ask a related question there.

But the error you get is how it tries to communicate with docker in the VM. Somehow it concludes it can't communicate... I am wondering if this is due to the proxy you are also using.

Can you `minishift ssh` to open the VM and try `docker ps` ?

**Comment by garyyang6** [comment] 2017-10-27 16:45
I am able to minishift ssh to open VM and run docker ps.
minishift ssh
oot2Docker version 1.12.6, build HEAD : 5ab2289 - Wed Jan 11 03:20:40 UTC 2017
Docker version 1.12.6, build 78d1802
docker@minishift:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Does it mean the minishift is running? If it does, can I ignore those errors? What problems I may have when I use minishif?  What is the minishift URL? I cannot figure out from console.

**Comment by gbraad** [comment] 2017-10-27 17:06
This is to make sure Docker runs inside the VM. can you retry the whole process, but doing:

```
$ minishift delete --force
$ minishift start --https-proxy https://myproxy..com:9000 --http-proxy http://myproxy.com:9000 --vm-driver=virtualbox --show-libmachine-logs -v5
```

and provide the logs here.

**Comment by garyyang6** [comment] 2017-10-27 18:04
Something I cannot explain.

I unpluged my laptop's ethernet cable to make my laptop not behind proxy. Reset proxy settings to none. Restarted docker and minishit. I am able to start minishit successfully. Since you asked me to "minishift delete --force" and provide log to you. I plugged in the ethernet cable and make my laptop behind corporate proxy. Restart docker and minishit. But, this time I started minishit successfully without any error.  I have no idea how I made it work. Below is the log. By the way, I would like to learn of how to use minishift to develop and deploy. Do you have any docs in PDF format? I am not good at reading docs online.  Thanks.

minishift start --https-proxy https://myproxy.com:9000 --http-proxy http://myproxy.com:9000 --vm-driver=virtualbox
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ..................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 11% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   http-proxy ... OK
   https-proxy ... OK
   no-proxy ... OK
   routing-suffix ... OK
   host-config-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

**Comment by gbraad** [comment] 2017-11-01 06:01
Might have been something in the configuration of the previous Minishift run. We have an outstanding issue when it concerns restart OpenShift in a different environment/IP settings.

But docs... eh well... we have them published in the Git archive. So if you download these, you have the docs of Minishift, but you actually need OpenShift documentation if it concerns development. Look for the Free e-books about OpenShift on http://openshift.org, http://openshift.com and/or http://developer.redhat.com/.

Closing the issue

**Closed by gbraad** 2017-11-01 06:01 UTC
