### ISSUE TITLE
Incorrect url returned for https routes by `minishift openshift service list`

### ISSUE THREAD

**Issue by pjos** [minishift/minishift#2091] opened 2018-03-06 19:27 UTC
### General information

  * Minishift version: v1.14.0+1ec5877
  * OS: Linux (CentOS 7)
  * Hypervisor: KVM

### Steps to reproduce

  1. Start minishift  `minishift start`
  2. Apply registry-route addon to expose a route to internal registry.
```
$ minishift addons apply registry-route
-- Applying addon 'registry-route':........
Add-on 'registry-route' created docker-registry route. Please run following commands to login to the OpenShift docker registry:
$ eval $(minishift docker-env)
$ eval $(minishift oc-env)
$ docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.42.87.nip.io:443
```
  3.  `oc login -u system:admin`
  4.  Check created route for the internal registry, note the ***edge*** termination.
```$ oc get route -n default
NAME              HOST/PORT                                      PATH      SERVICES          PORT       TERMINATION   WILDCARD
docker-registry   docker-registry-default.192.168.42.87.nip.io             docker-registry   5000-tcp   edge          None
```
  5.  Now use `minishift openshift service list -n default`, you get ***http*** instead of ***https***
```
$ minishift openshift service list -n default                                                                                                                  
|-----------|-----------------|----------|-----------------------------------------------------|--------|
| NAMESPACE |      NAME       | NODEPORT |                      ROUTE-URL                      | WEIGHT |
|-----------|-----------------|----------|-----------------------------------------------------|--------|
| default   | kubernetes      |          |                                                     |        |
|           | router          |          |                                                     |        |
|           | docker-registry |          | http://docker-registry-default.192.168.42.87.nip.io |        |
|-----------|-----------------|----------|-----------------------------------------------------|--------|
```

### Expected
Expected `ROUTE-URL`  should begin with secured  _***https***_://

### Actual
All `ROUTE-URL` returned seems to be constructed with a leading plain  _***http***_://

### Logs
N/A

**Comment by anjannath** [comment] 2018-03-07 06:52
This is a duplicate of #1564  
@pjos i am close this issue, we can discuss this in #1564

**Closed by anjannath** 2018-03-07 06:52 UTC
Labels: resolution/duplicate
