### ISSUE TITLE
Interactively ask for username and password during registration

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#938] opened 2017-05-22 08:46 UTC
If a user doesn't use `MINISHIFT_USERNAME` and `MINISHIFT_PASSWORD` as environment variable + they don't want to use username/password flag then there should be an interactive shell which ask user about `username and password`

**Comment by LalatenduMohanty** [comment] 2017-05-22 08:54
CDK issue  https://issues.jboss.org/browse/cdk-110

**Comment by gbraad** [comment] 2017-05-22 09:15
Note: current implementation for password input does not echo the input with `*`. This is due the implementations that were available did not work as expected for a Windows console.

**Comment by rctrh** [comment] 2017-05-23 17:48
A sub-case that I think should be also covered - If the user specifies --username but doesn't specify password, then the user should be prompted for the password, or minimally an error should be generated since registration won't succeed with only a username.

**Comment by hferentschik** [comment] 2017-06-15 18:14
Resolved via pull request #1014

**Closed by hferentschik** 2017-06-15 18:14 UTC
Labels: kind/bug, priority/major

**Comment by shuawest** [comment] 2017-08-21 01:04
I just installed CDK 3.1.0-1. While using the environment variable method of install I say my username and password printed in plain text. 

```
- Command "sudo -E subscription-manager register --auto-attach --username jowest@redhat.com --password 'notmyrealpassword' " took 35.9s
```

When you use the prompt model the same happens.  

```
Red Hat Developers or Red Hat Subscription Management (RHSM) username: jowest@redhat.com
Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
| Command "sudo -E subscription-manager register --auto-attach --username jowest@redhat.com --password 'notmyrealpassword' " took 17s
```

The expected behavior is that is the password is stored in a more secure way, and never shows up in plain text in an log file, or console output. 

This issue should be reopened.

**Comment by gbraad** [comment] 2017-08-21 03:28
@shuawest Can you provide more information about your start command?

I guess you used `--show-libmachine-logs -v5`, and if so, there is no way for us to prevent this behaviour, unless we start messing with the way `libmachine` handles this. This is because we use an SSH connection to do the subscription command, and libmachine abstracts all these calls and allow debug logging. The same would be for all the ssh connections that might contain a password, such as hostfolders.

**Comment by shuawest** [comment] 2017-08-21 13:58
> Can you provide more information about your minishift start command or configuration?

The logging level was set to 4. 

```
minishift config set cpus 2
minishift config set disk-size 30G
minishift config set memory 8192
minishift config set vm-driver virtualbox
minishift config set server-loglevel 4
minishift start -v 4
```

**Comment by gbraad** [comment] 2017-08-21 14:02
It therefore worked as expected. Newer version will not log this at
loglevel 2 or larger anymore, anyways. But as mentioned,
--show-libmachine-logs will still log them as plaintext when specified.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
