### ISSUE TITLE
Cannot start minishift again after stopping it

### ISSUE THREAD

**Issue by psrna** [minishift/minishift#153] opened 2016-11-17 19:32 UTC
**First start is ok:**

```
[hudson@psrna-virt ~]$ ./minishift status
E1117 14:11:29.827445    9442 update.go:76] GET https://api.github.com/repos/jimmidyson/minishift/releases/latest: 403 API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 15m37.172546344s
Does Not Exist
[hudson@psrna-virt ~]$ ./minishift start
E1117 14:11:35.299299    9459 update.go:76] GET https://api.github.com/repos/jimmidyson/minishift/releases/latest: 403 API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 15m31.700691782s
Starting local OpenShift cluster...
Downloading ISO
 36.00 MB / 36.00 MB [==================================================================================================================================================================] 100.00% 0s
oc is now configured to use the cluster.
Run this command to use the cluster: 
oc login --username=admin --password=admin
```

**Then I stop minishift:**

```
[hudson@psrna-virt ~]$ ./minishift stop
E1117 14:13:04.644492    9714 update.go:76] GET https://api.github.com/repos/jimmidyson/minishift/releases/latest: 403 API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 14m2.355498265s
Stopping local OpenShift cluster...
Machine stopped.
```

**Next start will fail:**

```
[hudson@psrna-virt ~]$ ./minishift start
E1117 14:13:09.506328    9769 update.go:76] GET https://api.github.com/repos/jimmidyson/minishift/releases/latest: 403 API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 13m57.493664368s
Starting local OpenShift cluster...
E1117 14:16:35.742269    9769 start.go:92] Error starting host: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1117 14:19:39.742390    9769 start.go:92] Error starting host: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
```

**here is a debug log:**

```
E1117 14:22:38.631322   10206 update.go:76] GET https://api.github.com/repos/jimmidyson/minishift/releases/latest: 403 API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 4m28.368669528s
Starting local OpenShift cluster...
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:55454
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
Waiting for SSH to be available...
Getting to WaitForSSH function...
(minishift) Calling .GetSSHHostname
(minishift) DBG | GetIP called for minishift
(minishift) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases
(minishift) DBG | IP address: 192.168.42.103
(minishift) DBG | Unable to locate IP address for MAC 52:54:00:51:a5:f7
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) DBG | AK: resolvestorepath: /home/hudson/.minishift
(minishift) DBG | AK: resolvestorepath: /home/hudson/.minishift
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/hudson/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.42.103 -o IdentitiesOnly=yes -i /home/hudson/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  : 
```

**Comment by budhrg** [comment] 2016-11-28 14:35
Duplicate of issue https://github.com/minishift/minishift/issues/106

**Comment by mlabuda** [comment] 2016-11-30 09:46
budhrg I don't think this is a duplicate of the one you are pointing to. Error output looks different to me.

**Comment by LalatenduMohanty** [comment] 2016-12-14 12:02
As discussed with @psrna he found the issue on RHEL7 +libvirt and KVM

**Comment by hferentschik** [comment] 2016-12-19 09:18
I am not able to re-produce this. I tried (in a loop) on OS X with VirtualBox and xhyve. Could it be that this is a variation of the issue described in #179 where parameters don't match between CLI calls?

**Comment by hferentschik** [comment] 2016-12-19 09:18
Can anyone post a command sequence to re-produce this issue, otherwise I think we can close it.

**Comment by LalatenduMohanty** [comment] 2016-12-26 14:56
I am getting an intermittent issue on Fedora 23 with KVM. I am using minishift compiled from master commit:9f871ac6984a8ed522a71522f17c1357617b37b7

Steps to reproduce

* $ ./minishift start --iso-url http://cdk-builds.usersys.redhat.com/builds/.minishift/temp-lala/minishift-rhel.iso --username lmohanty@redhat.com --password *********
* ./minishift stop or ./minishift delete
* $ ./minishift start --iso-url http://cdk-builds.usersys.redhat.com/builds/.minishift/temp-lala/minishift-rhel.iso --username lmohanty@redhat.com --password *************

```
$ ./minishift start --iso-url http://cdk-builds.usersys.redhat.com/builds/.minishift/temp-lala/minishift-rhel.iso --username lmohanty@redhat.com --password ***********                                                            
Starting local OpenShift cluster...
Downloading ISO
 333.00 MB / 333.00 MB [============================================================================================================================================================================================================================================] 100.00% 0s
E1226 18:52:27.140588   28835 start.go:131] Error starting machine: Error creating. Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1226 18:55:28.015393   28835 start.go:131] Error starting machine: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1226 18:58:28.888064   28835 start.go:131] Error starting machine: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1226 18:58:28.888120   28835 start.go:137] Error starting machine:  Error creating. Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

* $ rm -rf ~/.minishift
* $ sudo systemctl start libvirtd

#Using boot2docker ISO does not help also
* $ minishift start
```
[lmohanty@dhcp35-203 linux-amd64]$ ./minishift start
Starting local OpenShift cluster...
Downloading ISO
 36.00 MB / 36.00 MB [==============================================================================================================================================================================================================================================] 100.00% 0s
E1226 20:16:12.260861   29660 start.go:131] Error starting machine: Error creating. Error creating machine: Error in driver during machine creation: [Code-9] [Domain-20] operation failed: domain 'minishift' already exists with uuid 67d05ba3-d80e-49ea-8622-269a27dd94df. Retrying.
E1226 20:19:13.127968   29660 start.go:131] Error starting machine: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1226 20:22:13.992766   29660 start.go:131] Error starting machine: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E1226 20:22:13.992828   29660 start.go:137] Error starting machine:  Error creating. Error creating machine: Error in driver during machine creation: [Code-9] [Domain-20] operation failed: domain 'minishift' already exists with uuid 67d05ba3-d80e-49ea-8622-269a27dd94df
Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by LalatenduMohanty** [comment] 2016-12-26 16:29
Somehow the setup started working for the boot2docker ISO. I have executed start and stop in a loop till I hit the github  403 API rate limit. 
@psrna can you please try again with the latest release and see if you are seeing this issue.

**Comment by praveenkumar** [comment] 2016-12-29 03:06
@LalatenduMohanty Please use `--show-libmachine-logs --v=5` for detail debugs logs which will help us look what went wrong.

**Comment by hferentschik** [comment] 2017-01-09 11:26
I think we can resolve this one, right. There is the rate limit issue, but that is probably unrelated. Other than that I cannot re-produce this.

**Comment by LalatenduMohanty** [comment] 2017-01-10 09:42
@hferentschik I am also in the opinion that we can close this and if it reproduced bt @psrna , he will reopen it.

**Closed** 2017-01-10 20:26 UTC
Labels: bug, cannot-reproduce, major
