### ISSUE TITLE
Insecure registry settings not applied when present in persistent config

### ISSUE THREAD

**Issue by kniels5** [minishift/minishift#2873] opened 2018-10-09 15:22 UTC
### General information

  * Minishift version: v1.24.0+8a904
  * OS: macOS
  * Hypervisor: VirtualBox (centos)

#### Insecure via Minishift Config
  1.  Added insecure-registry setting to minishift config, e.g.
`              {
    "insecure-registry": [
        "172.30.0.0/16",
        "nexus-proxy-nexus-persistent.192.168.99.100.nip.io",
        "nexus-internal-nexus-persistent.192.168.99.100.nip.io"
    ],
    "vm-driver": "virtualbox"
}`

  2. minishift stop, minishift start
  3. validated the insecure settings were added to /etc/sysconfig/docker

      `OPTIONS="--selinux-enabled --log-driver=journald -H tcp://0.0.0.0:2376 -H 
 unix:///var/run/docker.sock --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem --tlskey=/etc/docker/server-key.pem --tlsverify"`

The insecure settings were not applied (docker info also did not show registries being added)

#### Insecure via Minishift start

1. started minishift with command line arguments

`minishift start --insecure-registry 172.30.0.0/16 --insecure-registry nexus-proxy-nexus-persistent.192.168.99.100.nip.io:443`

2. validated the insecure settings were added to /etc/sysconfig/docker

   `OPTIONS="--selinux-enabled --log-driver=journald -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem --tlskey=/etc/docker/server-key.pem --tlsverify"`

Output of Docker Info for both:
```
[docker@minishift ~]$ docker info
Containers: 65
 Running: 33
 Paused: 0
 Stopped: 32
Images: 14
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: e9c345b3f906d5dc5e8100b05ce37073a811c74a (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-862.6.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 3.858 GiB
Name: minishift
ID: ZV2F:DKNV:2JGP:O54K:U6XV:R7QF:DUG4:QFN7:K723:LYF7:N6KY:NIIT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

**Comment by agajdosi** [comment] 2018-10-10 08:51
Hi @kniels5, thank you for the report. I have tried this issue with minishift v1.24.0+8a904d0 on Linux and I am not able to reproduce it. In my case the insecure-registries defined in config are applied just fine, docker info shows them correctly.
 
Did you reuse the machine? I mean you had running Minishift, then you applied the config settings and restarted the Minishift? This might be the catch, not sure if this is supported, I am testing this scenario now so will update here soon.

**Comment by agajdosi** [comment] 2018-10-10 10:38
It is reproducible if I follow this scenario:
1. start minishift
2. set insecure-registries into config
3. stop minishift
4. start minishift
5. minishift ssh -- docker info -> registries are not set

I am not sure whether this is not expected, pinging @praveenkumar, @LalatenduMohanty.

**Comment by praveenkumar** [comment] 2018-10-10 11:01
@agajdosi @kniels5  Provisioner only runs the first time of the start and if you have a stop VM and then put anything which a provisioner run (here our minishift one which keeps that insecure registry info) it will not apply so this is expected behavior.

**Comment by praveenkumar** [comment] 2018-10-10 12:07
I did below and I don't see any issue here.

```
$ ./minishift delete
You are deleting the Minishift VM: 'minishift'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Minishift VM deleted.

$ ./minishift config view
- insecure-registry                  : [foo.bar.com]

$ ./minishift start --no-provision
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.10.0' is supported ... SKIP
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ................ OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK

$ ./minishift ssh -- docker info
[...]
Experimental: false
Insecure Registries:
 foo.bar.com   ==> This is present here.
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

```

**Comment by agajdosi** [comment] 2018-10-10 12:11
@praveenkumar I have the same results, works if config set before first start. We can close this as this behaviour is expected.

@kniels5 To have the configuration applied please delete the Minishift instance and start a new one. That way you will get the insecure registries applied. Please let us know if that works for you, so we can close this.

**Comment by kniels5** [comment] 2018-10-10 13:54
Hmmmm, my use case here is running artifactory, nexus on minishift, which means I would have to provision VM, start openshift and deploy these applications, i.e. I dont have the routes to my docker repos at the time of a first provision.

Wondering the rational behind only applying certain settings on first start/provision? 

At minimum the documentation should state which things are only applied during initial provisioning.

**Comment by praveenkumar** [comment] 2018-10-15 04:42
@kniels5 there is a hack way if you really need to append the insecure registry after the start but that setting will be not persist after reboot.

```
$ minishift ssh
$ sudo vi /etc/systemd/system/docker.service.d/10-machine.conf 
edit this file and append the insecure registry info at the end of it each one should be separated by `--insecure-registry` flag.
$ cat /etc/systemd/system/docker.service.d/10-machine.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd-current -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock            --selinux-enabled            --log-driver=journald            --signature-verification=false            --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current            --default-runtime=docker-runc            --exec-opt native.cgroupdriver=systemd            --userland-proxy-path=/usr/libexec/docker/docker-proxy-current            --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem            --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem            --label provider=xhyve --insecure-registry 172.30.0.0/16 --insecure-registry foo.bar.com

$ docker stop origin
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
$ docker info
$ docker start origin
```

**Closed** 2018-10-25 10:29 UTC
Labels: kind/bug, priority/major, resolution/wontfix
