### ISSUE TITLE
Ability to Copy Profile Config

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#1842] opened 2017-12-13 16:37 UTC
it will be great to have a support of copying profile config, that will help in creating identical profiles. I have just thought about config, but will be great if we can copy what other possible resources

e.g. minishift profile copy <src> <target>

**Comment by LalatenduMohanty** [comment] 2017-12-13 18:59
Duplicate of #1649.

**Closed by LalatenduMohanty** 2017-12-13 18:59 UTC
