### ISSUE TITLE
'addon install' can only install the default addons even if an addon is part of minishift binary

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#771] opened 2017-04-18 17:59 UTC
User can not install any addon which is part of minishift binary (i.e. minishift complied with the addon  part of the source code of MInishift just using the minishift binary i.e. without the source for the addon. Refer https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/addon/addon_install.go#L59-L91

```
$ minishift addons install eap-templates
Add-on installation failed with the error: The source of a addon needs to be a directory. 'eap-templates' is not
```

**Comment by hferentschik** [comment] 2017-04-18 18:05
This is by design. Either you have the add-on on the filesystem and point to it or you run `minishift addons install --defaults`.

**Comment by LalatenduMohanty** [comment] 2017-04-18 18:15
@hferentschik I changed it to a feature request. We should add this feature so that users can add the addon which is part of the minishift binary. Also we are embedding all addons available in the addons directory to the minishift binary.

**Comment by LalatenduMohanty** [comment] 2017-04-18 18:18
Should it be another flag i.e. 

```
Usage:
  minishift addons install [SOURCE] [flags]

Flags:
      --addon addon-name   Install addon which is available in minishift 
```

**Comment by praveenkumar** [comment] 2017-04-19 03:28
@hferentschik @LalatenduMohanty why don't we put all addons which are part of minishift binary as `default` so user can install it but have choice to enable which ever they think good for their usecase?

**Comment by budhrg** [comment] 2017-04-19 03:52
Agree with @praveenkumar  here.

On next level, we can do that with #639  to give better user experience to user.

**Comment by LalatenduMohanty** [comment] 2017-04-19 05:24
@praveenkumar @budhrg works for me.  I do not see any benefit  in making some addon part of minishift binary but the user can not use it at all.

**Comment by praveenkumar** [comment] 2017-05-31 11:57
@LalatenduMohanty @hferentschik so what is our take if we all agree that all the addons which are part of our repo should be `default` then I think this issue we can close.

**Comment by budhrg** [comment] 2017-05-31 15:40
Yes +1 for closing it. Also, for automatic installation of addons we have #639 . Rest of the addons need to be  manually installed.

**Closed** 2017-06-27 20:07 UTC
Labels: kind/feature, priority/major
