### ISSUE TITLE
Minishift running in Docker container

### ISSUE THREAD

**Issue by rhuss** [minishift/minishift#31] opened 2016-07-20 06:19 UTC
Just a crazy idea: Would it be possible to let minishift run within a Docker container ? Or is this completely off since this doesn't require to setup an external Docker daemon (maybe there are already other solutions for this, too).

The benefits would be:
- Extended functionality like adding a registry by setting env vars, starting gofabric8 etc. could be easily provided by the Docker image or a sub-image.
- Can be easily used in integration tests e.g. by fabric8-maven-plugin
- Even easier installation when a Docker daemon is already present.

As I said, this could be completely off-focus of minishift, at their could be already alternatives which provides this in a better way.

**Comment by jimmidyson** [comment] 2016-07-20 08:25
It's not crazy... we do have some plans to support native Docker in minikube & this will inherit from there. The only problem I see is having a inconsistent environment (e.g. Docker version, config, OS versions, etc) makes support harder.

**Comment by praveenkumar** [comment] 2017-05-31 07:37
@hferentschik I think we also discussed something similar but not making it as docker images. If you think this is still relevant then let's add some milestone to it.

**Comment by hferentschik** [comment] 2017-05-31 08:38
Actually I think this is a duplicate of #392. TBH, I am a bit sceptical still about this. We can close this as a duplicate and carry on with #392 which is "scheduled" for a milestone. This needs to be further discussed and thought through though.

**Closed by hferentschik** 2017-05-31 08:38 UTC
Labels: kind/feature, priority/major

**Comment by zoobab** [comment] 2019-11-06 14:19
Well minikube without virtualization and inside docker, just with the option ```--vm-driver=none```.

Minishift seems to have banned that feature.

But I don't see any technical reason why it could not work.
