### ISSUE TITLE
 Error attempting to get plugin server address for RPC upon start using xhyve/macOS

### ISSUE THREAD

**Issue by jkirklan** [minishift/minishift#1708] opened 2017-11-16 15:24 UTC
I am on a mac running High Sierra.   

I try to start minishift and receive the following error:

```
Error deleting the Minishift VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
```

I run `minishift start --vm-driver xhyve --show-libmachine-logs -v 5` and get the following error:
```
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
```

minishift is also exceptionally slow.  Other operations such as `minishift delete` also give the same RPC error.

**Comment by gbraad** [comment] 2017-11-16 15:30
This is a problem with the communication between xhyve and the xhyve-driver. Can you explain more about how you have set it all up?

**Comment by gbraad** [comment] 2017-11-16 15:33
The first error makes no sense in the flow, as it mentions a delete.

would it be possible to do `rm -rf ~/.minishift/machines/` and reboot... and then retry (sorry about the reboot, but it is better to clear the state of the driver as much as possible).

**Comment by jkirklan** [comment] 2017-11-16 15:50
Sorry, the first error was accidentally copied from a delete.  I meant to copy:

Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

**Comment by gbraad** [comment] 2017-11-16 15:52
Have you been able to use minishift before, or does minikube work?
Please provide me the steps that were used to install the driver.

**Comment by jkirklan** [comment] 2017-11-16 15:52
xhyve is installed via brew.  I have the following packages installed:

docker-machine-driver-xhyve
xhyve

I then did the chmod/chowns in the docs. 

Just to give more info:
oc version
oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
    options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
    inet 127.0.0.1 netmask 0xff000000
    inet6 ::1 prefixlen 128
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
    nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC0: flags=0<> mtu 0
XHC20: flags=0<> mtu 0
XHC1: flags=0<> mtu 0
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether ac:de:48:00:11:22
    inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x7
    nd6 options=201<PERFORMNUD,DAD>
    media: autoselect
    status: active
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether f4:0f:24:20:67:12
    inet6 fe80::8f8:e664:6a1b:a8e0%en0 prefixlen 64 secured scopeid 0x8
    inet 192.168.7.29 netmask 0xffffff00 broadcast 192.168.7.255
    nd6 options=201<PERFORMNUD,DAD>
    media: autoselect
    status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
    ether 06:0f:24:20:67:12
    media: autoselect
    status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
    ether 2a:d3:cd:71:66:da
    inet6 fe80::28d3:cdff:fe71:66da%awdl0 prefixlen 64 scopeid 0xa
    nd6 options=201<PERFORMNUD,DAD>
    media: autoselect
    status: active
en4: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=60<TSO4,TSO6>
    ether 26:00:45:b0:64:05
    media: autoselect <full-duplex>
    status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=60<TSO4,TSO6>
    ether 26:00:45:b0:64:04
    media: autoselect <full-duplex>
    status: inactive
en3: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=60<TSO4,TSO6>
    ether 26:00:45:b0:64:01
    media: autoselect <full-duplex>
    status: inactive
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=60<TSO4,TSO6>
    ether 26:00:45:b0:64:00
    media: autoselect <full-duplex>
    status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    options=63<RXCSUM,TXCSUM,TSO4,TSO6>
    ether 26:00:45:b0:64:00
    Configuration:
        id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
        maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
        root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
        ipfilter disabled flags 0x2
    member: en1 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 14 priority 0 path cost 0
    member: en2 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 12 priority 0 path cost 0
    member: en3 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 13 priority 0 path cost 0
    member: en4 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 11 priority 0 path cost 0
    nd6 options=201<PERFORMNUD,DAD>
    media: <unknown type>
    status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
    options=6403<RXCSUM,TXCSUM,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
    inet6 fe80::e408:6457:ac6e:be92%utun0 prefixlen 64 scopeid 0x10
    inet6 fd88:c1bf:1695:574:e408:6457:ac6e:be92 prefixlen 64
    nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
    options=6403<RXCSUM,TXCSUM,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
    inet6 fe80::4b83:b914:8943:82b1%utun1 prefixlen 64 scopeid 0x11
    nd6 options=201<PERFORMNUD,DAD>

**Comment by jkirklan** [comment] 2017-11-16 15:53
I was using minishift 1.01 fine.  Uninstalled it and installed the CDK.

**Comment by jkirklan** [comment] 2017-11-16 15:54
I did a minishift delete and rebooted before and it didn't do anything.  Is that sufficient or does that not clear the machines dir?

**Comment by gbraad** [comment] 2017-11-16 15:55
In that case, please remove the `.minishift` folder to be sure;

```
$ rm -rf ~/.minishift
```

and reboot the machine and retry. the driver can be finicky when an older config is found.

**Comment by jkirklan** [comment] 2017-11-16 15:56
minishift version
minishift v1.7.0+204ce19
CDK v3.2.0-1

**Comment by jkirklan** [comment] 2017-11-16 16:08
Ok I did that and rebooted:

$ minishift setup-cdk
Setting up CDK 3 on host using '/Users/jkirklan/.minishift' as Minishift's home directory
Copying minishift-rhel7.iso to '/Users/jkirklan/.minishift/cache/iso/minishift-rhel7.iso'
Copying oc to '/Users/jkirklan/.minishift/cache/oc/v3.6.173.0.21/oc'
Creating configuration file '/Users/jkirklan/.minishift/config/config.json'
Creating marker file '/Users/jkirklan/.minishift/cdk'
Default add-ons anyuid, admin-user, xpaas, registry-route, che installed
Default add-ons anyuid, admin-user, xpaas enabled
CDK 3 setup complete.

$ minishift start --vm-driver xhyve --show-libmachine-logs -v 5
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
.... FAIL E1116 11:04:26.186984     716 start.go:356] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
.Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

**Comment by jkirklan** [comment] 2017-11-16 16:17
No vpn running.  I do have the Red Hat VPN installed but not up.

**Comment by jkirklan** [comment] 2017-11-16 17:47
Still having the same issue.  None of the above addressed

**Comment by hferentschik** [comment] 2017-11-16 19:17
I somehow seem to remember that the shave driver needs to be re-compiled with OS X version upgrades. @praveenkumar might know more. Since it seems that you already upgraded to High Sierra the problem might lie there. 

Did you use Minishift before an upgrade to High Sierra? Was it working then?

**Comment by jkirklan** [comment] 2017-11-16 23:33
Yes I used it before the upgrade and it worked fine.

**Comment by gbraad** [comment] 2017-11-17 00:13
please try to force a reinstall of the driver with brew. The xhyve driver needs to be compiled against the hypervisor.kit, and likely this is the reason why it might fail now, as it might not be able to access/link correctly.

**Comment by jkirklan** [comment] 2017-11-17 01:48
It failed again after those steps:
$ minishift start --vm-driver xhyve --show-libmachine-logs -v 5
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
.... FAIL .E1116 20:45:47.530405    3997 start.go:356] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

**Comment by gbraad** [comment] 2017-11-17 03:29
Can you explain what 'those steps' are?

**Comment by praveenkumar** [comment] 2017-11-17 06:23
I also recently upgraded to High Sierra and not able to reproduce issue which you are having right now. Below are the details about my setup and you can try to compare if something mismatch.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

$ brew info docker-machine-driver-xhyve
docker-machine-driver-xhyve: stable 0.3.3, HEAD
Docker Machine driver for xhyve
https://github.com/zchee/docker-machine-driver-xhyve
/usr/local/Cellar/docker-machine-driver-xhyve/0.3.3 (3 files, 10.2MB) *
  Poured from bottle on 2017-08-30 at 12:30:48
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-xhyve.rb
==> Dependencies
Build: go ✘, ocaml ✘, opam ✘
Required: libev ✔
Recommended: docker-machine ✔
==> Requirements
Build: git ✔
Required: macOS >= 10.10 ✔
==> Options
--without-docker-machine
	Build without docker-machine support
--without-qcow2
	Do not support qcow2 disk image format
--HEAD
	Install HEAD version
==> Caveats
This driver requires superuser privileges to access the hypervisor. To
enable, execute
    sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    sudo chmod u+s /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

$ brew info xhyve
xhyve: stable 0.2.0, HEAD
xhyve, lightweight macOS virtualization solution based on FreeBSD's bhyve
https://github.com/mist64/xhyve
/usr/local/Cellar/xhyve/HEAD-1f1dbe3 (3 files, 225.6KB) *
  Built from source on 2016-09-20 at 12:06:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/xhyve.rb
==> Requirements
Required: macOS >= 10.10 ✔
```

**Comment by jkirklan** [comment] 2017-11-17 16:26
I uninstalled xhyve, ran minishift delete, rm -rf ~/.minishift, check that there were no minishift processes running, reinstalled xhyve and the other required packages. I then ran setup-cdk. After that I ran minshift start and got the error above.  Interestingly I went to my RHEL 7.4 system and tried to install and got the same behavior.

**Comment by jkirklan** [comment] 2017-11-17 16:28
My High Sierra output from those commands follows:

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

$ brew info xhyve
xhyve: stable 0.2.0 (bottled), HEAD
xhyve, lightweight macOS virtualization solution based on FreeBSD's bhyve
https://github.com/mist64/xhyve
/usr/local/Cellar/xhyve/0.2.0 (10 files, 11.2MB) *
  Poured from bottle on 2017-11-16 at 20:39:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/xhyve.rb
==> Requirements
Required: macOS >= 10.10 ✔

$ brew info docker-machine-driver-xhyve
docker-machine-driver-xhyve: stable 0.3.3 (bottled), HEAD
Docker Machine driver for xhyve
https://github.com/zchee/docker-machine-driver-xhyve
/usr/local/Cellar/docker-machine-driver-xhyve/0.3.3 (3 files, 10.5MB) *
  Poured from bottle on 2017-11-16 at 20:39:18
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-xhyve.rb
==> Dependencies
Build: go ✔, ocaml ✔, opam ✔
Required: libev ✔
Recommended: docker-machine ✔
==> Requirements
Build: git ✔
Required: macOS >= 10.10 ✔
==> Options
--without-docker-machine
	Build without docker-machine support
--without-qcow2
	Do not support qcow2 disk image format
--HEAD
	Install HEAD version
==> Caveats
This driver requires superuser privileges to access the hypervisor. To
enable, execute
    sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    sudo chmod u+s /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

**Comment by gbraad** [comment] 2017-11-18 11:59
I am not following "my RHEL 7.4 system and tried to install and got the
same behavior". This is unrelated to this issue.

Which steps were taken to remove and reinstall xhyve and the driver plugin?

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by jkirklan** [comment] 2017-11-19 00:31
The RHEL comment was an aside.  Sorry to confuse you.  To uninstall and reinstall xhyve I ran:

```
$ brew uninstall xhyve docker-machine-driver-xhyve
$ brew install xhyve docker-machine-driver-xhyve
$ minishift delete
$ rm -rf .minishift
```

**Comment by praveenkumar** [comment] 2017-11-20 09:21
@jkirklan Can you execute following commands as see if that works for you?

```
$ brew uninstall xhyve docker-machine-driver-xhyve
$ sudo curl -L  https://github.com/zchee/docker-machine-driver-xhyve/releases/download/v0.3.3/docker-machine-driver-xhyve -o /usr/local/bin/docker-machine-driver-xhyve
$ sudo chown root:wheel /usr/local/bin/docker-machine-driver-xhyve
$ sudo chmod u+s,+x /usr/local/bin/docker-machine-driver-xhyve
```

**Comment by praveenkumar** [comment] 2018-01-18 10:11
@jkirklan I am closing this issue now, please reopen if you still facing same.

**Closed by praveenkumar** 2018-01-18 10:11 UTC
Labels: os/darwin, priority/major, status/needs-info

**Comment by jkirklan** [comment] 2018-02-06 16:27
Sorry I missed this comment.  I ran the commands you gave me and have the same result.  It looks like it could be a network communication issue.  Is it possible it is talking to the wrong network?

**Comment by jkirklan** [comment] 2018-02-12 18:42
For those that care, I figured it out. After a month of trying.  I turned the firewall off on macos and the install proceeded.

**Comment by gbraad** [comment] 2018-02-12 19:07
Can you indicate how to turn off the firewall?

**Comment by jkirklan** [comment] 2018-02-12 20:47
I thought it fixed it but it didn't.. the issue continues.  I have the same issue on both my macs

**Comment by gbraad** [comment] 2018-02-12 22:00
Can you indicate which versions of macOS you have?
What is installed on the machine(s)?

**Comment by jkirklan** [comment] 2018-02-13 00:04
Macos - 10.13.1
$ docker-machine version
docker-machine version 0.13.0, build 9ba6da9

$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:20:09 2018
  OS/Arch:	linux/amd64
  Experimental:	false

$ oc version
oc v3.7.14
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

$ brew info xhyve
xhyve: stable 0.2.0 (bottled), HEAD
xhyve, lightweight macOS virtualization solution based on FreeBSD's bhyve
https://github.com/mist64/xhyve
/usr/local/Cellar/xhyve/0.2.0 (10 files, 11.2MB) *
  Poured from bottle on 2018-02-12 at 16:07:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/xhyve.rb
==> Requirements
Required: macOS >= 10.10 ✔
==> Options
--HEAD
	Install HEAD version

$ brew info docker-machine-driver-xhyve
docker-machine-driver-xhyve: stable 0.3.3 (bottled), HEAD
Docker Machine driver for xhyve
https://github.com/zchee/docker-machine-driver-xhyve
/usr/local/Cellar/docker-machine-driver-xhyve/0.3.3 (3 files, 10.5MB) *
  Poured from bottle on 2018-02-12 at 15:10:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-xhyve.rb
==> Dependencies
Build: go ✘, ocaml ✘, opam ✘
Required: libev ✔
Recommended: docker-machine ✔
==> Requirements
Required: macOS >= 10.10 ✔
==> Options
--without-docker-machine
	Build without docker-machine support
--without-qcow2
	Do not support qcow2 disk image format
--HEAD
	Install HEAD version
$ ll /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
-r-sr-xr-x  1 root  wheel    11M Jun 28  2017 /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

**Comment by jkirklan** [comment] 2018-02-13 00:05
$ minishift start --vm-driver xhyve --show-libmachine-logs -v5 2>&1
-- minishift version: v1.11.0+d7f374a
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
.... FAIL E0212 19:04:58.747280   13526 start.go:368] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
..Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

**Comment by gbraad** [comment] 2018-02-13 00:34
I am currently unable to reproduce this, since I am away from my desk for
another week. I'll ask Praveen to also have a look. However, have you tried
to use docker-machine with the xhyve driver? or minikube?

**Comment by jkirklan** [comment] 2018-02-13 10:43
yes with xhyve.  not with minikube

**Comment by praveenkumar** [comment] 2018-02-14 06:29
@jkirklan Can you use docker-machine or minikube along with xhyve driver and see if you face same issue. Today I again tried all the steps and still not able to reproduce it. 

Also make sure next time you try then do following.

```
$ minishift delete -f; rm -rf ~/.minishift;
$ minishift start  (default will be xhyve)
```

Another thing you can try is to use virtualbox as driver and then check if that is driver specific issue.

**Comment by jkirklan** [comment] 2018-02-21 00:10
I did the minishift delete and rm -rf..  the started failed as below, so I followed its instructions. 

`$ minishift start
You need to run 'minishift setup-cdk' first to install required CDK components.
captkirk-mbp:~ jkirklan$ minishift setup-cdk
Setting up CDK 3 on host using '/Users/jkirklan/.minishift' as Minishift's home directory
Copying minishift-rhel7.iso to '/Users/jkirklan/.minishift/cache/iso/minishift-rhel7.iso'
Copying oc to '/Users/jkirklan/.minishift/cache/oc/v3.6.173.0.21/oc'
Creating configuration file '/Users/jkirklan/.minishift/config/config.json'
Creating marker file '/Users/jkirklan/.minishift/cdk'
Default add-ons anyuid, admin-user, xpaas, registry-route, che installed
Default add-ons anyuid, admin-user, xpaas enabled
CDK 3 setup complete.
captkirk-mbp:~ jkirklan$ sudo minishift start --show-libmachine-logs -v5 2>&1
Password:
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
...Plugin server listening at address 127.0.0.1:51771
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
() Calling .GetMachineName
() Calling .DriverName
() Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
..... FAIL E0221 01:06:45.832908    5503 start.go:356] Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s`

I then tried it with virtual box

`$ sudo minishift start --vm-driver=virtualbox --show-libmachine-logs -v5
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at /usr/local/bin/minishift
Launching plugin server for driver virtualbox
..... FAIL E0221 01:08:33.929529    5648 start.go:356] Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s`

**Comment by jkirklan** [comment] 2018-02-21 00:29
Just for fun I installed minikube.  It works just fine.

**Comment by jkirklan** [comment] 2018-02-21 00:35
I downloaded 1.13 off the openshift origin website.  It works.  It is an issue with the Red Hat provided CDK version.

**Comment by praveenkumar** [comment] 2018-02-21 05:26
@jkirklan Good to know that upstream minishift is working as expected. I hope that there shouldn't be any issue with CDK also. Can you please let us know which version of CDK you are using?

**Comment by jkirklan** [comment] 2018-02-24 20:18
CDK 3.3.0-GA

**Comment by jkirklan** [comment] 2018-02-24 20:18
minishift v1.11.0+d7f374a
CDK v3.3.0-1

specifically
