### ISSUE TITLE
CentOS nightly integration test failed while deploying ruby-ex application

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1879] opened 2018-01-03 08:34 UTC
### General information

  * Minishift version: Latest Master
  * OS: Linux 
  * Hypervisor: KVM 

Link to the nightly test: https://ci.centos.org/job/minishift-nightly-centos/15/console

### Actual

```
00:57:36 
00:57:36   Scenario: User can deploy application ruby-ex to namespace ruby                                        # features/proxy.feature:40
00:57:36     Given Minishift has state "Running"                                                                  # integration_test.go:164 -> *Minishift.shouldHaveState
00:57:38     When executing "oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git" succeeds # integration_test.go:695 -> executingOcCommandSucceedsOrFails
00:57:38     Then stdout should contain                                                                           # integration_test.go:649 -> commandReturnShouldContainContent
00:57:38       """
00:57:38       Success
00:57:38       """
01:57:59     When executing "oc rollout status deploymentconfig ruby-ex --watch" succeeds                         # integration_test.go:695 -> executingOcCommandSucceedsOrFails
01:57:59     Command 'rollout status deploymentconfig ruby-ex --watch' did not execute successfully. cmdExit: 1, cmdErr: error: watch closed before Until timeout
01:57:59 
01:57:59     Then stdout should contain                                                                           # integration_test.go:649 -> commandReturnShouldContainContent
01:57:59       """
01:57:59       "ruby-ex-1" successfully rolled out
01:57:59       """
01:57:59     And proxy log should contain "Accepting CONNECT to registry-1.docker.io:443"                         # integration_test.go:781 -> proxyLogShouldContain
01:57:59     And proxy log should contain "Accepting CONNECT to bundler.rubygems.org:443"                         # integration_test.go:781 -> proxyLogShouldContain
01:57:59     And proxy log should contain "Accepting CONNECT to rubygems.org:443"                                 # integration_test.go:781 -> proxyLogShouldContain
01:58:00 
```

**Comment by agajdosi** [comment] 2018-01-03 10:50
Never seen this issue before, however might be connected to: https://github.com/kubernetes/kubernetes/issues/40224.

**Comment by budhrg** [comment] 2018-01-31 12:02
It is not reproducible in last 13 nighly jobs. 
https://ci.centos.org/job/minishift-nightly-centos/  
Build no 40 is due to minishift didn't start properly in `cmd-docker-env.feature` file.

/cc @LalatenduMohanty @agajdosi

**Comment by budhrg** [comment] 2018-02-09 06:44
Closing it as the above-mentioned issue is not reproducible in CentOS ISO. It might have happened that with recent changes in integration tests has fixed it.

**Closed by budhrg** 2018-02-09 06:44 UTC
Labels: component/integration-test, kind/bug, priority/major, status/needs-investigation
