### ISSUE TITLE
Is it possible to configure add-ons globally for all profiles?

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#1482] opened 2017-10-03 13:07 UTC
The following does not enable my admin user addon
```
./minishift addons enable admin-user
./minishift addons enable anyuid
./minishift start --profile 2G_demo --cpus 2 --memory 3G --vm-driver virtualbox 
```

```
./minishift addons list
```
reports that admin-user is enabled BUT it does not work with `oc login admin`, admin (admin is just a vanilla user)

**Comment by gbraad** [comment] 2017-10-03 13:21
Marking as question

**Comment by hferentschik** [comment] 2017-10-03 16:15
This seems very much a duplicate of #1480. Your add-on enable commands don't specify a profile, but then you start a 2G_demo profile. Your enable commands apply to the currently active profile at time of execution.

**Comment by LalatenduMohanty** [comment] 2017-10-09 12:55
Related #1517

**Comment by gbraad** [comment] 2017-11-07 01:50
Do we need to keep this issue open? We know we want something like #1517, and we can enable this as:

```
$ minishift profile set 2g_demo
$ minishift addons enable ...
$ minishift start ...
```

**Comment by gbraad** [comment] 2017-11-07 01:52
Closing

**Closed by gbraad** 2017-11-07 01:52 UTC
Labels: component/profile, kind/question, priority/major
