### ISSUE TITLE
Provide --skip-registration and --skip-unregistration flag for subscription based iso's

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#812] opened 2017-04-24 11:24 UTC
Right now we are forcefully imposing to do the subscription register for RHEL iso and don't provide a mechanism to `skip` it. This might be helpful for a user who already have setup ready and want to do now try offline then they can use these `--skip` parameters.

Source: https://issues.jboss.org/projects/CDK/issues/CDK-102

**Comment by LalatenduMohanty** [comment] 2017-04-24 13:23
Duplicate of https://github.com/minishift/minishift/issues/688

**Closed** 2017-04-24 13:29 UTC
Labels: kind/feature, priority/minor, resolution/duplicate
