### ISSUE TITLE
Minishift code defect, not able to match with expected SHA256 Checksum value

### ISSUE THREAD

**Issue by ankitverma123** [minishift/minishift#3379] opened 2019-11-25 06:14 UTC
@mik-dass 
Minishift code at https://github.com/minishift/minishift/blob/master/pkg/util/github/github.go#L162
Generates a SHA key like a802eb5364fcfda76dd297c2138409fcb0e6dca60ed4cecfa2fc5bfe16a20732
which doesn't match with openshift actual release checksum that is downloaded from some github url.
It will never match because everytime generating a new checksum and tries to match it with defined checksum value for openshift oc cli.

**Comment by gbraad** [comment] 2019-11-28 05:31
This is most likely an issue with the OpenShift release.
We will see ifwe can prioritise this ...

However, does overriding the OpenShift version to deploy work?

**Comment by ankitverma123** [comment] 2019-12-02 07:30
I am not sure @gbraad  could you please guide on this how to perform this. i tried --openshift 3.9.0 which doesn't work

**Comment by anjannath** [comment] 2019-12-05 10:25
You can override the version of OpenShift while starting, `minishift start --openshift-version 3.10.0`

**Comment by ankitverma123** [comment] 2019-12-07 18:02
C:\minishift-1.34.1-windows-amd64>minishift start --openshift-version 3.10.0
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.10.0'
-- Downloading OpenShift v3.10.0 checksums ... OKError starting the cluster: Error attempting to download and cache 'oc': Failed to validate hash - expected: 46ae5ccccc7f774ba5b0d8e1621a428e2c3fae7b7c0c78872cb1b37e4495b2e3, actual: c1b33aa535b88898d0622e0af2aa673bb814c354fb438c21c18155afc51acf87

Issue still persist

**Comment by anjannath** [comment] 2019-12-18 05:41
Duplicate of #3378

**Closed by anjannath** 2019-12-18 05:41 UTC
