### ISSUE TITLE
minishift start --insecure-registry doesn't allow oc new-build to work with insecure registries

### ISSUE THREAD

**Issue by svenstaro** [minishift/minishift#2544] opened 2018-07-02 13:44 UTC
### General information

  * Minishift version: 1.20.0
  * OS: Linux
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Have a non-default registry called `MY-REGISTRY` somewhere.
  2. Push some base image called `MY-BASE` to it.
  3. Create a local `Dockerfile` that has `FROM MY-REGISTRY/MY-BASE`.
  4. `minishift start --insecure-registry MY-REGISTRY`
  5. `eval $(minishift oc-env)`
  6. `cat Dockerfile | oc new-build -D - --name something1`

### Expected

It should work as the registry should be added to the insecure registries.

### Actual

It doesn't work.

### Logs

```
error: can't lookup images: ImageStreamImport.image.openshift.io "newapp" is invalid: spec.images[0].from.name: Forbidden: importing images from registry "MY-REGISTRY" is forbidden: registry "MY-REGISTRY" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 5 more ...
error: unable to locate any images in image streams, local docker images with name "MY-REGISTRY/MY-BASE"

The 'oc new-build' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to force the use of an image that was not matched

See 'oc new-build -h' for examples.
```

Doing `minishift ssh docker info` _does_ list this registry there. The problem has got to be somewhere with OpenShift inside minishift.

**Comment by sergeiwaigant** [comment] 2018-07-30 12:24
Same problems here, but with "oc new-app" command.

### General information
Minishift version: v1.21.0+a8c8b37
OS: MacOS
Hypervisor: xhyve

### Steps to reproduce
1. Have a non-default registry called MY-REGISTRY:18443 somewhere.
2. Push some image called MY-IMAGE to it from an external running Jenkins.
3. Set insecure-registry config for minishift or start with parameter, both dont work.
3.1. minishift config set insecure-registry MY-REGISTRY:18443
3.2. minishift start --insecure-registry MY-REGISTRY:18433
4. eval $(minishift oc-env)
5. oc new-app --insecure-registry=true --docker-image=MY-REGISTRY:18433/MYFOLDER/MY-IMAGE:TAG

### Expected
It should work as the registry should be added to the insecure registries to the underlying docker daemon in the Minishift VM.
Reference: [Minishift documentation](https://docs.openshift.org/latest/minishift/using/basic-usage.html#setting-persistent-configuration-values)

### Actual
It doesn't work.
It seems the option isnt routed correctly to the docker daemon.

### Logs
```
oc new-app --insecure-registry=true --docker-image=MY-REGISTRY:18443/MY-FOLDER/MY-IMAGE:TAG
error: can't lookup images: ImageStreamImport.image.openshift.io "newapp" is invalid: spec.images[0].from.name: Forbidden: importing images from registry "hub.itgo-devops.org:18443" is forbidden: registry "MY-REGISTRY:18443" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 5 more ...
error: unable to locate any local docker images with name "MY-REGISTRY:18443/MY-FOLDER/MY-IMAGE:TAG"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.

minishift config view
- insecure-registry                  : [MY-REGISTRY:18443]

minishift ssh docker info
Containers: 24
 Running: 9
 Paused: 0
 Stopped: 15
Images: 7
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: e9c345b3f906d5dc5e8100b05ce37073a811c74a (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-862.6.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 1.953 GiB
Name: minishift
ID: W2BG:ZDSJ:NJB3:IZAU:DHTZ:4JKR:O536:IMJT:EAEY:4JKQ:M6LJ:Q3Z4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=xhyve
Experimental: false
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Comment by praveenkumar** [comment] 2018-08-23 11:16
@svenstaro If I am not wrong you said that this is something you want to document. Do you have steps to overcome this issue?

**Comment by svenstaro** [comment] 2018-08-23 13:26
Right, so what I did was write a script which did essentially:

```bash
minishift start --insecure-registry my.domain
minishift openshift config set --patch '{"imagePolicyConfig": {"allowedRegistriesForImport": [{"domainName": "my.domain"}]}}'
```

I didn't find a better way but this was good enough for me at least.

**Comment by praveenkumar** [comment] 2018-08-23 13:32
@svenstaro Thanks good to know.

**Comment by svenstaro** [comment] 2018-08-23 13:37
Maybe put this into the docs somewhere as I imagine this is a common problem.

**Comment by tmds** [comment] 2018-10-05 09:30
Is there a way to patch the allowedRegistriesForImport so it appends instead of overwriting the defaults?
```
imagePolicyConfig:
  allowedRegistriesForImport:
  - domainName: docker.io
  - domainName: '*.docker.io'
  - domainName: '*.redhat.com'
  - domainName: gcr.io
  - domainName: quay.io
  - domainName: registry.centos.org
  - domainName: registry.redhat.io
  - domainName: '*.amazonaws.com'
```

**Comment by tmds** [comment] 2018-10-09 11:47
> Is there a way to patch the allowedRegistriesForImport so it appends instead of overwriting the defaults?

With OpenShift 3.10+ it is no longer required to do this. By default, any host is allowed for import.

**Comment by praveenkumar** [comment] 2018-10-09 12:09
Looks like then we should close this isue.

**Comment by tmds** [comment] 2018-10-11 06:57
Yes, the issue may be closed.

**Closed** 2018-10-11 07:08 UTC
Labels: component/documentation, kind/task

**Comment by randy-aimco** [comment] 2019-06-21 21:19
> Is there a way to patch the allowedRegistriesForImport so it appends instead of overwriting the defaults?
> 
> ```
> imagePolicyConfig:
>   allowedRegistriesForImport:
>   - domainName: docker.io
>   - domainName: '*.docker.io'
>   - domainName: '*.redhat.com'
>   - domainName: gcr.io
>   - domainName: quay.io
>   - domainName: registry.centos.org
>   - domainName: registry.redhat.io
>   - domainName: '*.amazonaws.com'
> ```

Not everyone is using 3.10+ and testing on a different version of the CDK/minishift other than what you have deployed in production is not a very good idea unless you like inconsistency and having to make excuses about why what you've tested locally doesn't work elsewhere. 

You'll have to add all these repos to the patch unless there is a way to patch using operations other than replace. It would be nice if the 'minishift openshift config' was documented somewhere.
