### ISSUE TITLE
Unable to start minishift on Window 10+Hyper-V

### ISSUE THREAD

**Issue by mukul4u2005** [minishift/minishift#1571] opened 2017-10-16 13:41 UTC
I followed the steps given on this url: 
https://docs.openshift.org/latest/minishift/getting-started/installing.html

I paired the virtual switch with a network card (wireless)

I set up the configuration as per this url:
https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html

I am not able to  start cluster using command : minishift start

Getting this error in the last:

FAIL
   Error: cannot access master readiness URL https://192.168.0.9:8443/healthz
/ready

Could you please suggest what can be the issue ?

**Comment by mukul4u2005** [comment] 2017-10-16 22:46
PS C:\Users\mukul\minishift-1.7.0-windows-amd64\minishift-1.7.0-windows-amd64> .\minishift.exe start
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ................................................................................................. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
Pulled 1/4 layers, 26% complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ...
   Pulling image openshift/origin:v3.6.0
   Pulled 1/4 layers, 26% complete
FAIL
   Error: error pulling Docker image openshift/origin:v3.6.0
   Caused By:
     Error: read tcp 192.168.0.9:63755->192.168.0.14:2376: wsarecv: An established connection was aborted by the software in your host machine.
Error during 'cluster up' execution: Error starting the cluster.

**Comment by mukul4u2005** [comment] 2017-10-17 01:15
I am getting this error:

PS C:\Users\mukul\minishift-1.7.0-windows-amd64\minishift-1.7.0-windows-amd64> .\minishift.exe start
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Starting Minishift VM ............................. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 11% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ...
   Deleted existing OpenShift container
-- Checking for openshift/origin:v3.6.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.0.17 as the server IP
-- Starting OpenShift container ...
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.0.17:8443/healthz/ready
   Details:
     No log available from "origin" container

   Caused By:
     Error: Get https://192.168.0.17:8443/healthz/ready: x509: certificate is valid for 127.0.0.1, 172.17.0.1, 172.30.0.1, 192.168.0.16, not 192.168.0.17
Error during 'cluster up' execution: Error starting the cluster.
PS C:\Users\mukul\minishift-1.7.0-windows-amd64\minishift-1.7.0-windows-amd64>

**Comment by gbraad** [comment] 2017-10-17 03:36
This is a restart of the Minishift instance? If so, #1508 might be related.

"192.168.0.16, not 192.168.0.17"

If you use the latest version of minishift, you can use the functionality as described in #1316. You can start minishift with:

```
$ minishift start --network-ipaddress 192.168.0.16 --network-gateway 192.168.0.1 --network-nameserver 8.8.8.8
```

Note: please check the values of nameserver and gateway to match your own environment,.

**Comment by gbraad** [comment] 2017-10-17 04:02
Duplicate of #343

**Closed** 2017-10-17 04:02 UTC

**Comment by mukul4u2005** [comment] 2017-10-19 02:28
I just start the minishift and again getting this issue , Please suggest.

PS C:\Users\mukul\minishift-1.7.0-windows-amd64\minishift-1.7.0-windows-amd64> .\minishift.exe start
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ................................................................................................ OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 56% complete
Pulled 2/4 layers, 81% complete
Pulled 3/4 layers, 87% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ...
   Pulling image openshift/origin:v3.6.0
   Pulled 1/4 layers, 26% complete
   Pulled 1/4 layers, 56% complete
   Pulled 2/4 layers, 81% complete
   Pulled 3/4 layers, 87% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.0.20 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.0.20:8443/healthz/ready
   Details:
     No log available from "origin" container

   Caused By:
     Error: Get https://192.168.0.20:8443/healthz/ready: dial tcp 192.168.0.20:8443: connectex: No connection could be made because the target machine actively refused it.
Error during 'cluster up' execution: Error starting the cluster.

**Comment by gbraad** [comment] 2017-10-19 02:50
@mukul4u2005 please create a new issue
