### ISSUE TITLE
Cannot add "developer" user to sudoers

### ISSUE THREAD

**Issue by ALRubinger** [minishift/minishift#556] opened 2017-03-15 19:12 UTC
When running:

`minishift start --vm-driver=virtualbox`

Startup completes, throwing this error onto the console:

`E0315 14:59:07.313545    4912 start.go:192] Error adding developer user to sudoers exit status 1`

OpenShift Console is available for all operations I've tested under the `admin` user as expected.

**Comment by gastaldi** [comment] 2017-03-15 19:17
Same happens with kvm driver

**Comment by gastaldi** [comment] 2017-03-15 19:20
Happens only in 1.0.0-beta.5.

1.0.0-beta.4 does not show this message

**Comment by hferentschik** [comment] 2017-03-15 19:53
> 1.0.0-beta.4 does not show this message

Correct, that's because it is a new feature of Beta 5. See issue #509. It is supposed to allow you to impersonate system:admin which is quite nice when executing a lot of _oc_ commands. 

Since we run this provisioning at the very end of the bootstrap, nothing should be really broken in terms of the old functionality. Obviously there seems to be an issue setting the sudoer role, so we need to look into this.

Could you try whether this is a repeatable error and it occurs each time you create a new Minishift instance?

**Comment by ALRubinger** [comment] 2017-03-15 21:31
@hferentschik After deleting my `$HOME/.minishift` folder, I saw the error go away in Beta5.  So maybe it's just a migration issue?  I had a prior `.minishift` folder from Beta4 installations.

**Comment by gbraad** [comment] 2017-03-16 03:31
Duplicate of #555

**Comment by LalatenduMohanty** [comment] 2017-03-16 04:15
@ALRubinger @hferentschik @gbraad From now onward we should test the update path and add a note in the release notes.

**Comment by gbraad** [comment] 2017-03-16 04:17
@LalatenduMohanty agree. In coming release we should prevent doing a `rm -rf ~/.minishift`. Especially getting closer to the actual release of 1.0.0, we need to get into this drill.

**Comment by hferentschik** [comment] 2017-03-16 08:14
> In coming release we should prevent doing a rm -rf ~/.minishift. 

+1, I think we might need a `minishift delete --all` though. Also, once we look into re-enabling auto-update we get more control on what's happening.

**Comment by hferentschik** [comment] 2017-03-16 08:18
>  After deleting my $HOME/.minishift folder, I saw the error go away in Beta5. So maybe it's just a migration issue? I had a prior .minishift folder from Beta4 installations.

@ALRubinger, ooh did you try to create a new Minishift instance or did you try to restart an exiting one?

**Comment by gbraad** [comment] 2017-03-16 08:21
> create a new Minishift instance or did you try to restart an exiting one?

It has to be a new one, as the provisioning step is important for the
sudoers functionality of openshift. The existing configuration would
prevent this from working as expected... (TL;dr provisioning only runs
once).

**Comment by hferentschik** [comment] 2017-03-16 09:05
@gbraad, yeah, but my guess was that it is related to the new json config file we use to store the path to oc. If I would be using an existing machine w/o this config file, the sudoer provisioning would fail. But you are probably right, that if the machine existed, we would not even end up in the part which tries to configure sudoer permissions.

**Comment by gbraad** [comment] 2017-03-16 09:17
@ALRubinger @gastaldi The resolution for now it is perform a delete of ~/.minishift. Could you try this?

**Comment by gastaldi** [comment] 2017-03-16 11:18
Yes, I did this and it worked. Thanks

Em 16 de mar de 2017 06:17, "Gerard Braad" <notifications@github.com>
escreveu:

**Comment by gbraad** [comment] 2017-03-16 14:39
Closing issue...

**Closed by gbraad** 2017-03-16 14:39 UTC
Labels: component/cli, kind/bug, priority/major, status/needs-info

**Comment by jorgemoralespou** [comment] 2017-03-17 14:41
In coming release we should prevent doing a rm -rf ~/.minishift.

+1, I think we might need a minishift delete --all though. Also, once we
look into re-enabling auto-update we get more control on what's happening.

I would have maybe an option to delete profiles and config but not cached
files (iso, oc, and eventually images) as that will avoid network time for
the next start.

**Comment by gbraad** [comment] 2017-03-17 14:55
@jorgemoralespou should `minishift delete --all` remove just ALL the instances (in the future we might have), or really the whole folder. because as you said, I would not like to blow my cache away... or should this become

```
$ minishift delete [cache|machines|config|all] [-y] 
```

much like the `yum clean` or `dnf clean` commands. the `-y` will confirm the deletion... as I miss the confirmation.

**Comment by jorgemoralespou** [comment] 2017-03-17 15:08
I don't see the value to delete the folder as a command. But I do se the
value to delete things that might have issues when upgrading to be formats,
to delete instancesv and even the cache, although this last one not so
common.

**Comment by gbraad** [comment] 2017-03-17 15:11
@jorgemoralespou deleting the cache at the moment is quite a narly one. it is actually needed when you have a cached images, as the new commandline specification will ignore if an image with boot2docker.iso already exist in this folder. However, this will be addressed.

**Comment by jorgemoralespou** [comment] 2017-03-17 15:18
@gbraad
Right now you can rm -rf the folder. I think that adding a command for
something that will be addressed is not good decision.

Let's think how this will remain with the end state in mind if this is
closer than a year. I think people can live with rm -rf.

**Comment by quintesse** [comment] 2017-03-17 17:17
Btw after deleting `~/.minishift` I got the following error (which didn't seem to affect the final result):

```
E0317 18:15:47.695180    7351 start.go:160] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-9] [Domain-20] operation failed: domain 'minishift' already exists with uuid bc19d9fd-654a-4e76-86e9-499b8babb760. Retrying.
```

**Comment by gbraad** [comment] 2017-03-17 17:49
execute:

sudo virsh destroy minishift; sudo virsh undefine minishift
