### ISSUE TITLE
Cache is not shared between profiles

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1661] opened 2017-11-04 19:55 UTC
If I create a profile, set all the config (image-caching=true), download all the images, stop the profile, and create a new one with same config, ISO and images are download again.

```
./bin/minishift/minishift-create.sh istio
Profile 'istio' set as active profile
No Minishift instance exists. New vm-driver setting will be applied on next 'minishift start'
No Minishift instance exists. New memory setting will be applied on next 'minishift start'
No Minishift instance exists. New cpus setting will be applied on next 'minishift start'
Cannot find property name image-cache
Add-on 'admin-user' enabled
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [==============================================================================================] 100.00% 0s
-- Starting Minishift VM ..................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- Downloading OpenShift binary 'oc' version 'v3.7.0-rc.0'
 38.15 MiB / 38.15 MiB [==============================================================================================] 100.00% 0s-- Downloading OpenShift v3.7.0-rc.0 checksums ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.7.0-rc.0
-- Checking `oc` support for startup flags ...
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   version ... OK
   routing-suffix ... OK
   host-config-dir ... OK
Starting OpenShift using openshift/origin:v3.7.0-rc.0 ...
Pulling image openshift/origin:v3.7.0-rc.0
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 31% complete
Pulled 1/4 layers, 36% complete
Pulled 1/4 layers, 41% complete
Pulled 1/4 layers, 46% complete
Pulled 1/4 layers, 50% complete
Pulled 1/4 layers, 54% complete
Pulled 1/4 layers, 58% complete
Pulled 1/4 layers, 62% complete
∆Pulled 1/4 layers, 66% complete
Pulled 1/4 layers, 68% complete
Pulled 1/4 layers, 71% complete
Pulled 1/4 layers, 73% complete
∆Pulled 1/4 layers, 75% complete
Pulled 1/4 layers, 79% complete
Pulled 1/4 layers, 83% complete
Pulled 2/4 layers, 86% complete
Pulled 3/4 layers, 89% complete
Pulled 3/4 layers, 92% complete
Pulled 3/4 layers, 94% complete
Pulled 3/4 layers, 96% complete
Pulled 3/4 layers, 98% complete
Pulled 3/4 layers, 100% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.6:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Applying addon 'admin-user':..

-- Exporting of OpenShift images is occuring in background process with pid 49806.



./bin/minishift/minishift-create.sh istio2
Profile 'istio2' set as active profile
No Minishift instance exists. New vm-driver setting will be applied on next 'minishift start'
No Minishift instance exists. New memory setting will be applied on next 'minishift start'
No Minishift instance exists. New cpus setting will be applied on next 'minishift start'
Cannot find property name image-cache
Add-on 'admin-user' enabled
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    8 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [==============================================================================================] 100.00% 0s
-- Starting Minishift VM ..................... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- Downloading OpenShift binary 'oc' version 'v3.7.0-rc.0'
 38.15 MiB / 38.15 MiB [==============================================================================================] 100.00% 0s-- Downloading OpenShift v3.7.0-rc.0 checksums ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.7.0-rc.0
-- Checking `oc` support for startup flags ...
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   version ... OK
   routing-suffix ... OK
   host-config-dir ... OK
Starting OpenShift using openshift/origin:v3.7.0-rc.0 ...
Pulling image openshift/origin:v3.7.0-rc.0
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 31% complete
Pulled 1/4 layers, 36% complete
Pulled 1/4 layers, 41% complete
Pulled 1/4 layers, 46% complete
Pulled 1/4 layers, 50% complete
Pulled 1/4 layers, 54% complete
Pulled 1/4 layers, 58% complete
Pulled 1/4 layers, 62% complete
∆Pulled 1/4 layers, 66% complete
Pulled 1/4 layers, 68% complete
Pulled 1/4 layers, 71% complete
Pulled 1/4 layers, 73% complete
∆Pulled 1/4 layers, 75% complete
Pulled 1/4 layers, 79% complete
Pulled 1/4 layers, 83% complete
Pulled 2/4 layers, 86% complete
Pulled 3/4 layers, 89% complete
Pulled 3/4 layers, 92% complete
Pulled 3/4 layers, 94% complete
Pulled 3/4 layers, 96% complete
Pulled 3/4 layers, 98% complete
Pulled 3/4 layers, 100% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.7:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

-- Applying addon 'admin-user':..

-- Exporting of OpenShift images is occuring in background process with pid 42603.
```

Here's my script to create a new profile (./bin/minishift/minishift-create.sh):

```
#!/bin/bash

PROFILE=$1

[ "$PROFILE" == "" ] && echo "You must provide a profile name" && exit 1

minishift profile set $PROFILE
minishift config set vm-driver xhyve
minishift config set memory 8G
minishift config set cpus 2
minishift config set image-caching true
minishift addons enable admin-user
minishift config set openshift-version 3.7.0-rc.0
minishift start
```

Downloading images every time is getting very unusable. Why would the things get downloaded on the profile and not globally?

This is an automatic upgrade from 1.7 to 1.8.

I'll try to delete the whole .minishift, but got same behavior

**Comment by jorgemoralespou** [comment] 2017-11-04 19:57
Starting with a new minishift HOME, I create just a profile, and minishift global caches are empty, meaning that if I create a new profile, everything will get downloaded again. 

I'm falling back to "oc cluster" until this issue is fixed, as traveling and using low bandwidth makes minishift in this mode unusable.

**Comment by gbraad** [comment] 2017-11-05 11:06
Closing as duplicate of #1408 
Please place comments on that issue instead.

**Closed by gbraad** 2017-11-05 11:06 UTC
