### ISSUE TITLE
When using VirtualBox 6.0 hypervisor, minishift vm grabs the audio input and output causing sound distortion and microphone always listening

### ISSUE THREAD

**Issue by felts94** [minishift/minishift#3304] opened 2019-07-24 16:32 UTC
### General information

  * Minishift version: minishift v1.33.0+ba29431
  * OS: macOS 
  * Hypervisor: VirtualBox 6.0

When running `minishift start --vm-driver=virtualbox` VirtualBox enables audio by default and it grabs the microphone, it distorts audio output and allows the minishift vm to listen in on the microphone at any time

### Steps to reproduce

  1. `minishift start --vm-driver=virtualbox`

### Expected

Don't try to use the microphone by default
![Screen Shot 2019-07-24 at 12 14 54 PM](https://user-images.githubusercontent.com/30238027/61810168-ae61db00-ae0c-11e9-8c90-2b654bcc3376.png)

### Actual

Grabs microphone access by enabling audio in the VM
![Screen Shot 2019-07-24 at 12 17 43 PM](https://user-images.githubusercontent.com/30238027/61810362-1adcda00-ae0d-11e9-98c9-264acaaebe92.png)

This can be fixed by shutting down the vm and manually editing the audio settings and disabling the check box

### Logs
https://gist.github.com/felts94/f77d6389aa9560302a040c74d4907ff8

**Comment by gbraad** [comment] 2019-07-25 07:34
Duplicate of #3157. This is related to the upstream machine driver.

**Closed by gbraad** 2019-07-25 07:34 UTC
