### ISSUE TITLE
Minishift Error During Cluster Up

### ISSUE THREAD

**Issue by HouJaI** [minishift/minishift#1325] opened 2017-08-29 14:23 UTC
Error message is:
```
-- Starting OpenShift container ...
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.0.103:8443/healthz/ready
   Details:
     No log available from "origin" container

   Caused By:
     Error: Get https://192.168.0.103:8443/healthz/ready: x509: certificate is valid for 127.0.0.1, 172.17.0.1, 172.30.0.1, 192.168.43.2, not 192.168.0.103
Error during 'cluster up' execution: Error starting the cluster.
```

i managed to start minishift using 192.168.43.2. but when i connect to a different wifi connection, the minishift is started with 192.168.0.103. hence, this error. appreciate any help on this, or redirect be to a duplicate issue. thank you for your help!

**Comment by gbraad** [comment] 2017-08-30 03:44
Duplicate of #343 #593 

When the IP address changes, OpenShift seems to fail to start properly. This is more likely to occur to Hyper-V as the IP address is dependent of the DHCP lease on the external network

**Closed by gbraad** 2017-08-30 03:44 UTC
Labels: kind/bug, resolution/duplicate

**Comment by gbraad** [comment] 2017-08-30 03:49
@csrwng Is there a way to recreate the certificate?
