### ISSUE TITLE
Error from server: json: cannot unmarshal string into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by Slyke** [minishift/minishift#1273] opened 2017-08-16 15:09 UTC
Was following this guide: https://blog.openshift.com/deploying-from-private-git-repositories/

But got the following error:

```

> oc patch buildConfig blog-fe -p '{"spec":{"source":{"sourceSecret":{"name":"sshsecret"}}}}'
Error from server: json: cannot unmarshal string into Go value of type map[string]interface {}

```

Tried escaping the double quotes, but didn't help.

I'm using Windows command line and running Minishift:

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://192.168.2.219:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

```

Update: [Workaround Here](https://github.com/minishift/minishift/issues/1273#issuecomment-323138763)

**Comment by gbraad** [comment] 2017-08-17 08:19
Although it occurred on Windows, I do not think this is a Windows-specific issue. The issue here seems to be with the `oc` client. Recommend to remove the Windows tag, and ask someone from OpenShift to have a look. /cc: @budhrg

**Comment by gbraad** [comment] 2017-08-17 08:23
@jorgemoralespou @deads2k Any idea what could be wrong here?

**Comment by hferentschik** [comment] 2017-08-17 09:06
> Tried escaping the double quotes, but didn't help.

How did you do the escaping? When using the patch command, the biggest problem is understanding how your shell is intervening (in terms of interpolations, etc) with the string you want to pass to the patch command. 

You can also edit the config file to start with, verifying that the JSON config matches your expectations.  Something like:

    $ oc edit  -n <namespace> bc <build-config>

Once you have confirmed that the config matches your expectations and the patch "should" apply, you can try to work out  how the shell interferes.

**Comment by deads2k** [comment] 2017-08-17 12:57
@fabianofranz

**Comment by gbraad** [comment] 2017-08-17 13:03
The command prompt does not really need escaping as it has limited scripting capability. AFAIR the given command is valid as-is.

**Comment by hferentschik** [comment] 2017-08-17 13:12
I think you do. See also https://docs.openshift.org/latest/minishift/openshift/openshift-client-binary.html#example-config-cors. AFAIR @agajdosi did a fair amount of testing around how to use the patch command on Windows.

**Comment by budhrg** [comment] 2017-08-17 15:19
@Slyke , could you try following

`oc patch buildConfig blog-fe -p '{\"spec\":{\"source\":{\"sourceSecret\":{\"name\":\"sshsecret\"}}}}'` 

which is similar to what we mentioned here https://docs.openshift.org/latest/minishift/openshift/openshift-client-binary.html#example-config-cors.

**Comment by Slyke** [comment] 2017-08-17 15:20
@budhrg @hferentschik 

> How did you do the escaping?

I tried it like this:
` oc patch buildConfig blog-fe -p '{\"spec\":{\"source\":{\"sourceSecret\":{\"name\":\"sshsecret\"}}}}' `

But it produced the same result.

**Comment by gbraad** [comment] 2017-08-17 15:22
If the escaping would have been the issue, it should also have been addressed in the documentation. However, I do not think this is the problem... as the server would have mentioned the JSON would have been malformed in that case IIRC.

**Comment by Slyke** [comment] 2017-08-17 15:44
@gbraad Yeah, I know, but I was following the post and noticed in some of the comments that some people were having issues with escaping, so I tried just in case. Is anyone else able to reproduce this?

**Comment by gbraad** [comment] 2017-08-17 15:55
Well, did you use minishift 1.4.1 to deploy OpenShift 3.6, or did you use an earlier version passing the `--openshift-version` option?

Some steps to reproduce as you have deployed it would be appreciated.

**Comment by Slyke** [comment] 2017-08-17 16:01
These are the steps I did from start to finish, I used no special parameters or set any versions:

1. Download Minishift and add to PATH
2. Follow steps on for installing Hyper-V: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
3. Follow steps on For creating a VSwitch (Created with HYPER-V UI): https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/connect-to-network
4. In Administrator cmd type $ set HYPERV_VIRTUAL_SWITCH=External VM Switch
5. In the same cmd window execute: $ minishift oc-env
6. From the previous command, copy the readout, it tells you to add oc to PATH, execute that (it'll be something like SET PATH=C:\Users\slyke\.minishift\cache\oc\v3.6.0;%PATH%)
7. To get access to the UI console in the browser you need to get the URL from the console by typing: $ oc status
8. Generate SSH Key Pair (use ssh-keygen on gitbash). Ensure you upload the public key to your git repo settings
9. Run this command (ensure you put your home dir on the path): $ oc secrets new-sshauth sshsecret --ssh-privatekey=~/.ssh/id_rsa
10. Add the command: $ oc secrets add serviceaccount/builder secrets/sshsecret
11 Type and follow prompts to login: $ oc login
12. Install key to build config: $ oc patch buildConfig app=YOUR-APP-NAME -p '{"spec":{"source":{"sourceSecret":{"name":"sshsecret"}}}}' < --- This is as far as I've gotten.

**Comment by gbraad** [comment] 2017-08-17 16:04
OK, so I do notice something... you are not using the Windows command prompt... but you are using the Console client to use git-bash? Just to be sure, as in step 5 you wrote "In the same cmd window execute: $ minishift oc-env"

First of all, `$` would indicate a unix shell, and second this command on itself does only echo what you need to do.

**Comment by gbraad** [comment] 2017-08-17 16:07
Also, where did you create the actual app you are patch the buildconfig for?

**Comment by gbraad** [comment] 2017-08-17 16:12
I did this quickly again on a Linux host, and used `oc` from zsh:

```
$ minishift start
$ eval `minishit oc-env`
$ oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git   
$ oc patch buildConfig ruby-ex -p '{"spec":{"source":{"sourceSecret":{"name":"sshsecret"}}}}' 
"ruby-ex" patched
```

will quickly try again on a Windows 10 host.

**Comment by Slyke** [comment] 2017-08-17 16:28
@gbraad I only used gitbash to generate the ssh key pairs. The $ was only to denote where the command started, as I was typing this in notepad and didn't want to put quotes around the commands which could look confusing. I used command line through and through, except for generating the key pairs (and I closed gitbash after they were generated).

**Comment by gbraad** [comment] 2017-08-17 16:38
```
C:\> set HYPERV_VIRTUAL_SWITCH=Wireless
C:\> minishift start
C:\> SET PATH=C:\Users\gbraad\.minishift\cache\oc\v3.6.0;%PATH%
C:\> oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
C:\> oc patch buildConfig ruby-ex -p '{"spec":{"source":{"sourceSecret":{"name":"sshsec
ret"}}}}'
Error from server: json: cannot unmarshal string into Go value of type map[string]interface {}
```

**Comment by gbraad** [comment] 2017-08-17 16:53
trying different ways to send the patch...
```
C:\> oc patch buildConfig ruby-ex -p {"spec":{"source":{"sourceSecret":{"name":"sshsecret"}}}}
Error from server: invalid character 's' looking for beginning of object key string
```

**Comment by gbraad** [comment] 2017-08-17 17:01
@Slyke can you try to use double quotes for the string, instead of a single quote. And escape any other `"` with a back-slash like `\"`. This makes the winning solution look as follows:

```
C:\> oc patch buildConfig ruby-ex -p "{\"spec\":{\"source\":{\"sourceSecret\":{\"name\":\"sshsecret\"}}}}"
```

**Comment by Slyke** [comment] 2017-08-17 17:22
```

> oc patch buildConfig blog-fe -p "{\"spec\":{\"source\":{\"sourceSecret\":{\"name\":\"sshsecret\"}}}}"
buildconfig "blog-fe" not patched

```

Yep, that seems to work now! So it needs to be double quotes encapsulating the string, and use escaped double quotes within the string due to it being JSON.

**Comment by gbraad** [comment] 2017-08-17 17:24
I do believe some of this could have been handled by validation by the `oc` client, but had some difficulty locating the sources for this command.

**Comment by hferentschik** [comment] 2017-08-22 07:22
Closing this issue. Seemed to have been an escaping problem.

**Closed by hferentschik** 2017-08-22 07:22 UTC
Labels: kind/bug, os/windows, priority/major
