### ISSUE TITLE
using `oc --as system:admin` no longer works with 3.6.x of openshift due to `Unable to add sudoer role`

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#1053] opened 2017-06-21 11:54 UTC
if you create a cluster using a 3.6.x. distro like this:
```
$ minishift start --vm-driver=xhyve --memory=7000 --cpus=4 --disk-size=50g --openshift-version=v3.6.0-alpha.1
Starting local OpenShift cluster using 'xhyve' hypervisor...
oc login -u developer -p developer
Starting OpenShift using openshift/origin:v3.6.0-alpha.1 ...
Pulling image openshift/origin:v3.6.0-alpha.1
Pulled 0/3 layers, 3% complete
Pulled 0/3 layers, 31% complete
Pulled 0/3 layers, 59% complete
Pulled 0/3 layers, 87% complete
Pulled 1/3 layers, 89% complete
Pulled 2/3 layers, 92% complete
Pulled 3/3 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.82:8443

You are logged in as:
    User:     developer

To login as administrator:
    oc login -u system:admin

Error during post cluster up configuration: Unable to add sudoer role
```
Notice the last line!!!

then if you try and use `oc --as system:admin` it barfs

```
$ oc --as system:admin get oauthclient
Error from server (Forbidden): User "developer" cannot "impersonate" "systemusers.user.openshift.io" with name "system:admin" in project ""
```

whereas if we use `oc login` instead:
```
$ oc login -u system:admin
Logged into "https://192.168.64.82:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-system
  * myproject
    openshift
    openshift-infra

Using project "myproject".
$ oc get oauthclient
NAME                           SECRET                                 WWW-CHALLENGE   REDIRECT URIS
openshift-browser-client       1a617cd4-c463-4110-805c-06f5610877f3   FALSE           https://192.168.64.82:8443/oauth/token/display
openshift-challenging-client                                          TRUE            https://192.168.64.82:8443/oauth/token/implicit
openshift-web-console                                                 FALSE           https://192.168.64.82:8443/console/,https://localhost:9000
```

**Comment by budhrg** [comment] 2017-06-21 13:10
@jstrachan , which version you are using here? Did you build the binary from master branch ?

**Comment by jstrachan** [comment] 2017-06-21 13:17
I was using the latest release (1.1.0) - but can workaround now with a snapshot build: http://artifacts.ci.centos.org/minishift/minishift/master/198/darwin-amd64/minishift

**Comment by hferentschik** [comment] 2017-06-21 18:11
Duplicate of #1011

**Closed by hferentschik** 2017-06-21 18:11 UTC
Labels: kind/bug, priority/major, resolution/duplicate
