### ISSUE TITLE
Support driver options through environment variables

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#739] opened 2017-04-12 08:55 UTC
This issue is the result of discussion happened in this issue https://github.com/minishift/minishift/issues/590.
Particularly this comment https://github.com/minishift/minishift/issues/590#issuecomment-293397120 .

IMO, it is better to track here then #590 .

Each driver support few environment variables like [hyperv options](https://docs.docker.com/machine/drivers/hyper-v/#options) for virtual switch `HYPERV_VIRTUAL_SWITCH`.

Similar for virtualbox driver https://docs.docker.com/machine/drivers/virtualbox/#options.

Most of these driver options are part of `minishift start` options and handled from there but for few options like `HYPERV_VIRTUAL_SWITCH` we need to implement explicitly.

Now, this also creates multiple ways of achieving the same for some options like iso url to choose.

So, suppose one want to use specific iso url, then user can do : 
1. Specifiy `--iso-url` provided as `start` option
2. Set env variable _MINISHIFT_ISO_URL_ map to above option
3. Specify `config set` to set url before start

With this driver option implementation, we might have one more way to provide iso url 
4. Set env variable _HYPERV_BOOT2DOCKER_URL_  or _DRIVERNAME_BOOT2DOCKER_URL_

The priority I am assuming here is :  
`--iso-url` -> MINISHIFT_ISO_URL  -> DRIVERNAME_BOOT2DOCKER_URL -> `config set`

WDYT ? @hferentschik  @LalatenduMohanty @gbraad @praveenkumar

**Comment by budhrg** [comment] 2017-04-12 09:03
Not sure whether it is a duplicate of https://github.com/minishift/minishift/issues/305 

@hferentschik  could you confirm please?

**Comment by hferentschik** [comment] 2017-04-12 09:12
Closing this issue, since it is a duplicate of #305

**Closed** 2017-04-12 09:12 UTC
Labels: kind/task, priority/major
