### ISSUE TITLE
metrics with OCP: pulls wrong image version

### ISSUE THREAD

**Issue by rbaumgar** [minishift/minishift#890] opened 2017-05-12 11:25 UTC
I have create a new minishift environment with a OC v3.5.5.8 (OCP). works perfect!
When I create the cluster with metrics, metrics does not work!
Metrics-deployer tries to pull the images with v3.5.5.8, but they do not exist. Only v3.5.0 exists
```
openshift3/ose-metrics-hawkular-metrics v3.5.0-14
openshift3/ose-metrics-heapster v3.5.0-9
openshift3/ose-metrics-cassandra  v3.5.0-10
```
Yes, I know metrics is experimental.
With the oc v1.5.0 (Origin) no problem.

**Comment by hferentschik** [comment] 2017-05-12 11:53
This is a known CDK issue - https://issues.jboss.org/browse/CDK-118. AFAIU the problem is that the metrics images are not properly tagged in registry.access.redhat.com.

I think the "workaround" to provision an earlier version of OCP (3.4?).

I am going to close this issue in favour of CDK-118.

**Closed by hferentschik** 2017-05-12 11:53 UTC

**Comment by jorgemoralespou** [comment] 2017-05-12 14:15
If you use --openshift-version=v3.5 should work as everything has that tag in the repository.

The problem is that by default the "oc" client will use the complete version to pull down images, and there the difference in tagging is hit. If you use the tag v3.5 it will pull down the ocp containers 3.5.5.x and the metrics containers 3.5.0.x

**Comment by rbaumgar** [comment] 2017-05-12 14:39
Jorge,

this is not that simple!
```
$ minishift start --vm-driver virtualbox --metrics --openshift-version=v3.5
Minishift does not support Openshift version v3.5 .You need to use a version >=v1.4.1
```
```
$ minishift start --vm-driver virtualbox --metrics --openshift-version=v3.5.0
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Error starting the cluster:  Error attempting to download and cache oc: Cannot get the OpenShift release version v3.5.0: GET https://api.github.com/repos/openshift/origin/releases/tags/v3.5.0: 404 Not Found []
```
when I create a directory .minishift/cache/oc/v3.5.0 with the OC
```
$ minishift start --vm-driver virtualbox --metrics --openshift-version=v3.5.0
Starting local OpenShift cluster using 'virtualbox' hypervisor...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.5.0 image ... 
   Pulling image registry.access.redhat.com/openshift3/ose:v3.5.0
FAIL
   Error: error pulling Docker image registry.access.redhat.com/openshift3/ose:v3.5.0
   Caused By:
     Error: API error (404): {"message":"error parsing HTTP 404 response body: invalid character 'F' looking for beginning of value: \"File not found.\\\"\""}
Error starting the cluster.
```
same when I create v3.5.5! and
```
$ minishift start --vm-driver virtualbox --metrics --openshift-version=v3.5.5.8
Minishift does not support Openshift version v3.5.5.8 .You need to use a version >=v1.4.1
```
Any further tip?

**Comment by jorgemoralespou** [comment] 2017-05-12 16:49
@rbaumbar you're using minishift. The trading problem is for CDK, and only fixed there.
OCP is Enterprise release of openshift.
You could specify the --image to point to the specific Enterprise repository to use minishift with ocp.

**Comment by sputnik-1** [comment] 2017-05-26 18:36
@jorgemoralespou 

thanks for that pointer to this issue.

I had a similar problem with trying to start the docker container cluster, and the fix was to leave off the tag version, so docker defaulted to downloading the 'latest' version.

`
spock@laptop ~ $ oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.5.5.10 image ... 
   Pulling image registry.access.redhat.com/openshift3/ose:v3.5.5.10
FAIL
   Error: error pulling Docker image registry.access.redhat.com/openshift3/ose:v3.5.5.10
   Caused By:
     Error: API error (404): {"message":"error parsing HTTP 404 response body: invalid character 'F' looking for beginning of value: \"File not found.\\\"\""}

spock@laptop ~ $ docker search registry.access.redhat.com/openshift3/ose
NAME                                              DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
openshift3/ose                                    OpenShift Container Platform base image. P...   0                    
openshift3/ose-logging-deployer                   Deployer container for deploying the aggre...   0                    
openshift3/ose-pod                                Infrastructure pod used to reserve resourc...   0                    
openshift3/ose-docker-builder                     Docker build strategy implementation for O...   0                    
openshift3/ose-logging-deployment                 Container used to configure the Aggregated...   0                    
openshift3/ose-metrics-cassandra                  Database used to persist historical metric...   0                    
openshift3/ose-metrics-deployer                   Handles configuration and deployment of th...   0                    
openshift3/ose-metrics-heapster                   Retrieves container and node metrics from ...   0                    
openshift3/ose-sti-builder                        OpenShift Container Platform Source-To-Ima...   0                    
openshift3/ose-docker-registry                    Supports the V2 Docker Registry API. Inclu...   0                    
openshift3/ose-logging-elasticsearch              Log aggregation container using Elasticsea...   0                    
openshift3/ose-logging-fluentd                    Used to aggregate and add metadata to log ...   0                    
openshift3/ose-metrics-hawkular-metrics           Metric engine for managing the storage and...   0                    
openshift3/ose-logging-auth-proxy                 Container used to enable authorization and...   0                    
openshift3/ose-logging-kibana                     Provides a UI for interacting with and que...   0                    
openshift3/ose-recycler                           Called by the Master in an OpenShift Conta...   0                    
openshift3/ose-keepalived-ipfailover              Optional Pod providing keepalived support ...   0                    
openshift3/ose-logging-curator                    Provides a way to trim indices from Elasti...   0                    
openshift3/ose-egress-router                      The OpenShift egress router runs a service...   0                    
openshift3/ose-f5-router                          The F5 router plug-in integrates with an e...   0                    
openshift3/ose-deployer                           Default deployer pod for OpenShift.  Handl...   0                    
openshift3/ose-haproxy-router                     Default router implementation for OpenShif...   0                    
openshift3/ose-metrics-hawkular-openshift-agent   Hawkular OpenShift Agent is a Hawkular fee...   0                    
spock@laptop ~ $ 
spock@laptop ~ $ 
spock@laptop ~ $ docker pull registry.access.redhat.com/openshift3/ose
Using default tag: latest
latest: Pulling from openshift3/ose
8642dd241e54: Pull complete 
fdd633d880f7: Pull complete 
a78b450e6b25: Pull complete 
7724366529fe: Pull complete 
Digest: sha256:e8b8260ced95de762029c0af53032612d1a7a0977afe7373f42528050ca1470e
Status: Downloaded newer image for registry.access.redhat.com/openshift3/ose:latest
`

**Comment by sputnik-1** [comment] 2017-05-27 14:33
It's possible to pass the oc command parameters for the image registry and version number, with:

--image=registry.access.redhat.com/openshift3/ose --version=latest

spock@laptop ~ $ oc cluster up --image=registry.access.redhat.com/openshift3/ose --version=latest
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:latest image ... OK
-- Checking Docker daemon configuration ... FAIL
   Error: did not detect an --insecure-registry argument on the Docker daemon
   Solution:

     Ensure that the Docker daemon is running with the following argument:
        --insecure-registry 172.30.0.0/16

**Comment by LalatenduMohanty** [comment] 2017-05-29 06:49
@sputnik-1 Sorry did not get your question. Also for `oc cluster up` queries please open issues in https://github.com/openshift/origin. I am sure if you open an issue in https://github.com/openshift/origin about `oc cluster up` you will get quicker response.

**Comment by sputnik-1** [comment] 2017-05-29 10:49
Hi Lalatendu,

this was a comment about how I fixed starting the docker cluster by passing the 'latest' tag to the oc command line.

Sorry for any confusion, and yes I have opened an issue for this on the OpenShift origin bug tracker now here:

https://github.com/openshift/origin/issues/14392

Regards,

Keith
