### ISSUE TITLE
VM fails to start properly using xhyve or hyperkit on macOS.

### ISSUE THREAD

**Issue by mikz** [minishift/minishift#2916] opened 2018-10-22 08:49 UTC
### General information

  * Minishift version: v1.25.0+90fb23e
  * OS: macOS
  * Hypervisor: xhyve (0.3.3_1) / hyperkit (1.0.0)

### Steps to reproduce

  1. `minishift start`

### Expected

To succeed in starting a VM.

### Actual

Failure. See logs.

VM's fail to resolve external hostnames:
```
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... (minishift) Calling .GetSSHHostname
About to run SSH command:
curl -s -m 5 http://minishift.io/index.html > /dev/null 2>&1
SSH cmd err, output: exit status 6:
FAIL
   VM cannot connect to external URL with HTTP
```

From `curl` man page: 
```
   6      Couldn't resolve host. The given remote host was not resolved.
```

### Logs

https://gist.github.com/mikz/413ecf6cc1fd5b2f1e287abf22f32e3e

Starting an instance using virtualbox works.

**Comment by amitkrout** [comment] 2018-10-23 12:55
@mikz It could be a temporary network issue by that time, as I am not able to reproduce this. Can you remove ```~./minishift``` directory and try it again.

**Comment by mikz** [comment] 2018-10-23 13:15
@amitkrout It is not a temporary network issue. It works fine in virtualbox on the same machine. 
Also, it is happening for a long time (months). Reproduced it again just now. 

If you see the logs, there is another failure when pulling the docker image:

```
-- Pulling the Openshift Container Image .I1023 15:02:31.507970   11627 docker.go:205] Executing docker command: 'docker pull openshift/origin-control-plane:v3.10.0'
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/mikz/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@192.168.64.15 -o IdentitiesOnly=yes -i /Users/mikz/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
docker pull openshift/origin-control-plane:v3.10.0
SSH cmd err, output: exit status 1: Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.15:41562->192.168.64.1:53: read: connection refused

Error pulling the openshift container image: ssh command error:
command : docker pull openshift/origin-control-plane:v3.10.0
err     : exit status 1
output  : Trying to pull repository docker.io/openshift/origin-control-plane ...
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.15:41562->192.168.64.1:53: read: connection refused
```

I can reproduce it sshing to the machine and trying to `docker pull openshift/origin-control-plane:v3.10.0`.

```
curl https://minishift.io
curl: (6) Could not resolve host: minishift.io; Unknown error
```

```
[docker@minishift ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.64.1
```

Not sure what is supposed to be this `192.168.64.1`, but it definitely does not provide DNS server.

**Comment by amitkrout** [comment] 2018-10-23 13:40
Are you able to ping any external traffic like google.com from that VM ?

**Comment by mikz** [comment] 2018-10-23 14:44
@amitkrout as shown in the attached logs it can route traffic outside VM (to 8.8.8.8 for example).

There is no DNS server on `192.168.64.1`, so nothing can be resolved.

**Comment by praveenkumar** [comment] 2018-10-23 15:20
@mikz can you use following command for xhyve? make sure you delete existing minishift instance which is running on virtualbox?

```
$ minishift start --vm-driver xhyve --logtostderr --v 5 --show-libmachine-logs --network-nameserver 8.8.8.8
```

**Comment by mikz** [comment] 2018-10-23 16:46
@praveenkumar explicitly setting network-nameserver indeed fixes the issue, thanks!

**Comment by gbraad** [comment] 2018-10-24 02:19
Closing the issue as this is a local networking/setup issue

@mikz are you by any chance running a dnsmasq service for local development? like `.dev` etc?

**Closed by gbraad** 2018-10-24 02:19 UTC

**Comment by mikz** [comment] 2018-10-24 08:56
@gbraad yes, I'm running dnsmasq locally.

How this is a local networking/setup issue? It is common to run dnsmasq locally and minishift should not fail utterly on this setup. Especially when it worked in previous releases. It should at least fail and give some information about what to do to fix it.
