### ISSUE TITLE
minishift start --deploy-registry --deploy-router on existing instance failed

### ISSUE THREAD

**Issue by abouchama** [minishift/minishift#57] opened 2016-08-25 15:32 UTC
Using minishift 0.4.1, i have performed the following commands on existing instance that don't have router or registry installed:

```
minishift stop
minishift start --deploy-registry --deploy-router
Starting local OpenShift cluster...
E0825 11:21:14.608549   17105 start.go:104] Error starting cluster:  Something went wrong running an SSH command!
command : 
cd /var/lib/minishift;
sudo /usr/local/bin/openshift admin policy add-scc-to-user hostnetwork -z router --config=openshift.local.config/master/admin.kubeconfig;
sudo /usr/local/bin/openshift admin router --service-account=router --config=openshift.local.config/master/admin.kubeconfig

err     : exit status 1
output  : info: password for stats user admin has been set to JRRKM8qdZv
--> Creating router router ...
    error: serviceaccounts "router" already exists
    clusterrolebinding "router-router-role" created
    deploymentconfig "router" created
    service "router" created
--> Failed

```

Even if the command failed, when i have started the OpenShift cluster with **minishift start** only,
the router & registry has been deployed correctly:

```
$ oc get pods 
NAME                            READY     STATUS    RESTARTS   AGE
docker-registry-1-zcscb         1/1       Running   0          6h
fabric8-docker-registry-f7md5   1/1       Running   6          8d
fabric8-forge-nr9nm             1/1       Running   6          8d
fabric8-re8ps                   1/1       Running   6          8d
gogs-xo7uk                      1/1       Running   7          8d
jenkins-ss9yg                   1/1       Running   5          8d
nexus-0iqsx                     1/1       Running   15         8d
router-1-43h6y                  1/1       Running   0          6h
```

**Comment by cmoulliard** [comment] 2016-09-08 07:32
I can reproduce the error on 0.5 using this option `--deploy-registry=true` issued after the creation of minishift

```
minishift start --memory=6000  --deploy-registry=true
Starting local OpenShift cluster...
`E0908 09:08:41.582629   38554 start.go:110] Error starting cluster:  Something went wrong running an SSH command!
command : 
cd /var/lib/minishift;
sudo /usr/local/bin/openshift admin registry --service-account=registry --config=openshift.local.config/master/admin.kubeconfig

err     : exit status 1
output  : --> Creating registry registry ...
    error: serviceaccounts "registry" already exists
    clusterrolebinding "registry-registry-role" created
    deploymentconfig "docker-registry" created
    service "docker-registry" created
--> Failed
error: exit directly
```

**Comment by jimmidyson** [comment] 2016-09-08 16:51
I can't seem to reproduce - can you let me know how I can repro from a clean install (`minishift delete` before repro steps please).

**Comment by cmoulliard** [comment] 2016-09-12 08:16
I can't reproduce it anymore ....

Here are the commands that I have used now successfully with 0.6.0 this morning

```
minishift delete
minishift start --vm-driver="xhyve" --memory=2048
oc login --username=admin --password=admin
oc get pods
oc get service
minishift stop
minishift start --memory=6000  --deploy-registry=true
Starting local OpenShift cluster...
oc is now configured to use the cluster.
Run this command to use the cluster:
oc login --username=admin --password=admin
oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-1-finrf   1/1       Running   0          7m
```

**Comment by budhrg** [comment] 2017-01-20 07:36
@abouchama , Could you try the latest minishift? 
With [latest minishift version](https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.2), `docker-registry` and `router` are part of default namespace.

```
$ minishift version
Minishift version: 1.0.0-beta.2

 $ oc get pods -n default
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-1-7po5f   1/1       Running   0          30m
router-1-93xg4            1/1       Running   0          30m
```

Let us know if your use case is different.

**Comment by abouchama** [comment] 2017-01-20 09:13
@budhrg , I confirm with the last one 1.0.0-beta.2 include router & docker-registry by default.
Thanks

**Comment by budhrg** [comment] 2017-01-20 09:22
@abouchama  Great to know that it is what you are expecting. Thanks.

Closing issue now.

**Closed by budhrg** 2017-01-20 09:22 UTC
Labels: status/needs-info
