### ISSUE TITLE
Misleading message when starting Minishift

### ISSUE THREAD

**Issue by jeffmaury** [minishift/minishift#266] opened 2017-01-10 13:48 UTC
I had a minishift created before with virtualbox on Win10.
I installed 1.0.0-beta.2 but when I tried minishift start I had the following message:

`Starting local OpenShift instance using 'hyperv' hypervisor...`

I checked with Virtualbox GUI and the VM has been started by Virtualbox

**Comment by budhrg** [comment] 2017-01-10 14:02
@jeffmaury  , If I understood correct here,

You had minishift VM created before with `1.0.0-beta.1` version which might be in stopped state.

Now, you updated minishift to `1.0.0-beta.2` version and performed start as
```
minishift start
```
 ?

If yes, you need to perform start on previously stopped state as
```
minishift start [previous options] 
```

**Comment by jeffmaury** [comment] 2017-01-10 14:21
Yes this is what is did (--username and --password) but if the VM is already created then --vm-driver is not needed so I did not pass it and got it started to Virtualbox despite the message

**Comment by budhrg** [comment] 2017-01-10 14:28
> but if the VM is already created then --vm-driver is not needed so I did not pass it and got it started to Virtualbox despite the message

Unfortunately, it is needed to be passed at the moment to make sure [not to break persistence of the OpenShift configuration](https://github.com/minishift/minishift/issues/210).

We are tracking all these usability issues as part of this issue https://github.com/minishift/minishift/issues/179.

**Comment by budhrg** [comment] 2017-01-10 14:33
After confirming with @jeffmaury about the steps to reproduce, I think it was expected to get that error since `minishift start` will take default driver which is `hyperv` in windows.

Expected command to fire to start here is `minishift start --vm-driver virtualbox` which was used previously to start minishift VM.

We know this as usability issue and already tracking as part of #179 . 

With this, I feel we can close this issue.

**Closed** 2017-01-11 10:00 UTC
Labels: invalid
