### ISSUE TITLE
Error starting minishift with CDK 3.0 on mac OS Sierra

### ISSUE THREAD

**Issue by praskrish** [minishift/minishift#1008] opened 2017-06-08 17:55 UTC
Hello,

I am seeing an error while starting minishift using CDK: 
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0608 10:40:20.559121    3552 start.go:176] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.

https://pastebin.com/pDUdYPmX

kprasann-OSX:~ kprasann$ minishift version
Minishift version: 1.0.0+4f8cb6d
CDK Version: 3.0.0

**Comment by hferentschik** [comment] 2017-06-08 18:41
A couple of questions. Do you have VirtualBox installed as well and can you try starting with VirtualBox?

    $ minishift start --vm-driver virtualbox

Basically just trying to isolate whether this is a driver issues (which it kind of looks like) or an actual Minishift issue. 
Also you can try to download the latest Minishift community release and try with that version. Again, just to narrow down the problem. If this turns out to be a CDK specific issue, it should really be reported in the CDK issue tracker - https://issues.jboss.org/projects/CDK/summary

Last but not least, do you have any firewalls or similar in place?

**Comment by praskrish** [comment] 2017-06-08 18:55
Hi,
I have Virtualbox installed and have tried the command as below:
```
kprasann-OSX:~ kprasann$ minishift start --vm-driver virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0608 11:52:27.891760    3663 start.go:176] Error starting the VM: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
```
let me try wth latest minishift community release and let you know. I have disabled the firewalls.

**Comment by hferentschik** [comment] 2017-06-08 19:01
Try `minishift delete` first. You might now already have some stale data in your $MINISHIFT_HOME directory.

    $ minishift delete
    $ minishift start --vm-driver virtualbox

**Comment by praskrish** [comment] 2017-06-08 21:16
Here is what I get now

```
$ minishift start --logtostderr --show-libmachine-logs
Starting local OpenShift cluster using 'xhyve' hypervisor...
I0608 14:15:30.330335    4713 cluster.go:74] Machine exists!
I0608 14:15:30.533941    4713 cluster.go:82] Machine state:  Error
(minishift) Waiting for VM to come online...
(minishift) Waiting on a pseudo-terminal to be ready... virtio_net: Could not create vmnet interface, permission denied or no entitlement?
```

**Comment by praskrish** [comment] 2017-06-09 00:08
ok. Here are the steps I followed on my mac.

#1 Instead of using the CDK 3.0 GUI to install minishift. I downloaded the executable from  :https://access.redhat.com/downloads/content/293/ver=3.0/rhel---7/3.0/x86_64/product-software
#2 ran the command with minishift start --vm-driver virtualbox and it works well.

minishift start which by default uses xhyve fails with the error:
$ minishift start --logtostderr --show-libmachine-logs
Starting local OpenShift cluster using 'xhyve' hypervisor...
I0608 14:15:30.330335    4713 cluster.go:74] Machine exists!
I0608 14:15:30.533941    4713 cluster.go:82] Machine state:  Error
(minishift) Waiting for VM to come online...
(minishift) Waiting on a pseudo-terminal to be ready... virtio_net: Could not create vmnet interface, permission denied or no entitlement?

**Comment by praveenkumar** [comment] 2017-06-09 03:42
> Waiting on a pseudo-terminal to be ready... virtio_net: Could not create vmnet interface, permission denied or no entitlement?

@praskrish This mean xhyve driver doesn't have required permission. Which instruction you followed to install it https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#xhyve-driver-install ?

**Comment by praskrish** [comment] 2017-06-09 03:47
@praveenkumar I followed the steps below:

$ brew install docker-machine-driver-xhyve

$ sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
$ sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

**Comment by praveenkumar** [comment] 2017-06-09 03:52
@praskrish Can you check which version of xhyve driver you have installed using `brew info docker-machine-driver-xhyve` and put output here?

**Comment by praskrish** [comment] 2017-06-09 04:18
@praveenkumar $ This is what I see below. looks like a permission issue like you noted.
```
brew info docker-machine-driver-xhyve
docker-machine-driver-xhyve: stable 0.3.2 (bottled), HEAD
Docker Machine driver for xhyve
https://github.com/zchee/docker-machine-driver-xhyve
/usr/local/Cellar/docker-machine-driver-xhyve/0.3.2 (3 files, 10.3MB) *
  Poured from bottle on 2017-06-07 at 23:25:32
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-driver-xhyve.rb
==> Dependencies
Build: go ✘
Required: opam ✔, libev ✔
Recommended: docker-machine ✔
==> Requirements
Build: git ✔
Required: macOS >= 10.10 ✔
==> Options
--without-docker-machine
	Build without docker-machine support
--without-qcow2
	Do not support qcow2 disk image format
--HEAD
	Install HEAD version
==> Caveats
This driver requires superuser privileges to access the hypervisor. To
enable, execute
    sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
    sudo chmod u+s /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

```

**Comment by praveenkumar** [comment] 2017-06-09 05:12
@praskrish please try https://docs.openshift.org/latest/minishift/using/troubleshooting.html#create-vmnet-interface-permission troubleshoot and let me know if still don't work. I am not able to reproduce it.

**Comment by praveenkumar** [comment] 2017-06-13 12:09
@praskrish Any luck?

**Comment by hferentschik** [comment] 2017-08-22 07:30
Closing this since there is no more info and is reported against CDK.

**Closed by hferentschik** 2017-08-22 07:30 UTC
Labels: kind/bug, os/darwin, priority/major, resolution/out-of-date
