### ISSUE TITLE
Unable to start minishift  C:\Program Files\minishift-1.34.1-windows-amd64>minishift start --vm-driver=virtualbox -- Starting profile 'minishift' -- Check if deprecated options are used ... OK -- Checking if https://github.com is reachable ... OK -- Checking if requested OpenShift version 'v3.11.0' is valid ... OK -- Checking if requested OpenShift version 'v3.11.0' is supported ... OK -- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK -- Checking if VirtualBox is installed ...

### ISSUE THREAD

**Issue by dileep-dev** [minishift/minishift#3380] opened 2019-11-29 22:11 UTC
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment] 2019-12-06 05:28
Duplicate of #3381

**Closed by anjannath** 2019-12-06 05:28 UTC
