### ISSUE TITLE
Allow Minishift to be easily configured to use `nip.io` instead of `xip.io`

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#501] opened 2017-03-02 10:04 UTC
I find `xip.io` to be pretty flaky really - it often goes dark on me for a few minutes. I've found `nip.io` to be much more stable. 

Whats the simplest way to get minishift to use it for route postfixes?

**Comment by jstrachan** [comment] 2017-03-02 10:05
we maybe wanna make nip.io the default anyways?

**Comment by hferentschik** [comment] 2017-03-02 11:46
> Whats the simplest way to get minishift to use it for route postfixes?

    $ minishift openshift config set --patch '{"routingConfig": {"subdomain": "192.168.99.101.nip.io"}}'

The IP differs. That's the IP of your VM. You can get it via `minishift ip`. 

There is also a `--routing-suffix` flag as part of the `minishift start` command, which would set the specified prefix as part of the _cluster up_. However, since IP are dynamic, you would not know beforehand what IP you get. This relates to issue #41 

> we maybe wanna make nip.io the default anyways?

Do you run some actual tests that nip.io is more stable?

**Comment by jorgemoralespou** [comment] 2017-03-02 12:01
FYI,
oc-cluster has moved from xip.io to nip.io in master code. Not sure what
version will bring it, but I doubt it will be 1.5.

cc/ @csrwng

**Comment by hferentschik** [comment] 2017-03-02 12:08
> oc-cluster has moved from xip.io to nip.io in master code

Interesting, I guess they did some tests then. 

Not sure whether we should put something in the Minishift right now or whether we just wait that oc-cluster uses nip.io

**Comment by jorgemoralespou** [comment] 2017-03-02 12:10
A correction, the PR is not yet merged.

https://github.com/openshift/origin/pull/13023

I would think that we should want to set nip.io as default if no
--routing-suffix has been set, so would make the transition to this
easier/smoother for users.

https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L51

**Comment by hferentschik** [comment] 2017-03-02 12:13
> I would think that we should want to set nip.io as default if no --routing-suffix has been set, so would make the transition to this easier/smoother for users.

Fair enough. Easy enough change to make on our side.

**Comment by jstrachan** [comment] 2017-03-02 13:04
@hferentschik there's the catch 22 as you don't know the IP address until you run `minishift start`. Is there a way to pass in the `route-suffix-suffix`? ;) so that `route-suffix` gets set to use the dynamically created IP + the `route-suffix-suffix` as part of the regular `minishift start` CLI?

**Comment by LalatenduMohanty** [comment] 2017-03-03 07:28
@hferentschik did `minishift start --routing-suffix nip.io` work for you? I got the route with .nip.io but it did not work.  I think first we need to check why `--routing-suffix` does not work ( I have not looked in to the code yet and not sure if it works for others). As @jorgemoralespou mentioned `cluster up` is moving to nip.io and I can see https://github.com/openshift/origin/pull/13023 merged , So do we want to do the change in Minishift now? I am not seeing any extra value if we set it in Minishift if `cluster up` is doing it.

**Comment by LalatenduMohanty** [comment] 2017-03-03 07:45
So the issue is https://github.com/minishift/minishift/issues/501#issuecomment-283648141 as @jstrachan mentioned.

**Comment by LalatenduMohanty** [comment] 2017-03-03 08:53
I believe this is a change we should drive in upstream i.e. in oc cluster up (which is already done). If nip.io is better than xip.io then it should be true for Minishift and "cluster up". I would be inclined to wait for "cluster up" to bring the feature and fix the -routing-suffix

**Comment by hferentschik** [comment] 2017-03-03 08:54
>  I got the route with .nip.io but it did not work

If you got the route, then all should be good. Did you do a dig on the hostname? 

> So do we want to do the change in Minishift now?

Sure, it seems nip.io is more stable and even OpenShift is moving to it, however, it is not clear when this change will arrive. Since this is a simple change, we might as well be a bit proactive.

**Comment by hferentschik** [comment] 2017-03-03 09:00
> I believe this is a change we should drive in upstream i.e. in oc cluster up (which is already done).

It is driven upstream. We just want to be proactive. Also more consistent in fact. Say the feature comes in 1.5. If people then use OpenShift 1.4 they get xip.io and when they use 1.5, they get nip.io. If we apply the route suffix it is consistent.


> I would be inclined to wait for "cluster up" to bring the feature and fix the -routing-suffix

Why? Here is one of the points where we could benefit how we are setting things up with Minishift. For once something is easy to do.

**Comment by praveenkumar** [comment] 2017-03-03 09:08
> If you got the route, then all should be good. Did you do a dig on the hostname?

Did a test so if we just use --routing-suffix nip.io then subdomain will not have vm ip and not able to route properly. 

```
$ ./minishift openshift config view | grep nip
  subdomain: nip.io
```

Default run
```
$ ./minishift openshift config view | grep xip
  subdomain: 192.168.99.100.xip.io
```

**Comment by hferentschik** [comment] 2017-03-03 09:12
> Did a test so if we just use --routing-suffix nip.io

that cannot work per definition. nip.io and xip.io require the IP to return to be encoded in the hostname/route. Unless I made a mistake this is also not what I did in the pull request, but I combine IP + nip.io

**Comment by jorgemoralespou** [comment] 2017-03-03 11:18
Correct.

e.g. "--routing-suffix 127.0.0.1.nip.io" as that will give back from nip
127.0.0.1.

So if you provide a --routing-suffix you should preserve that one, else,
you should provide (hostIP).nip.io to "oc cluster" so that versions < 1.6
will use nip.io and not xip.io

**Comment by LalatenduMohanty** [comment] 2017-03-07 12:58
The default is changed to nip.io in commit  https://github.com/minishift/minishift/commit/aafa268f4965dda559cb7c16bc6817b5bb93aae1

**Closed by LalatenduMohanty** 2017-03-07 12:58 UTC
Labels: kind/feature, priority/major

**Comment by vegai** [comment] 2018-01-17 08:12
So nip.io is currently down, and xip.io is working :)
