### ISSUE TITLE
Confusing message for 'minishift profile delete'

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1706] opened 2017-11-16 13:39 UTC
When deleting a profile with no existing VM, the output is confusing:

    $ minishift profile delete ttt --force
    VM for profile 'ttt' does not exist
    Deleted:  /Users/hardy/.minishift/profiles/ttt
    Profile 'ttt' deleted successfully

I am confused about the "VM for profile 'ttt' does not exist". What is this supposed to mean? I think this can be removed. 

I also suggest to combine the two remaining lines of output into one:

"Profile 'ttt' (/Users/hardy/.minishift/profiles/ttt) deleted successfully."

Please, also end messages with a full stop.

**Comment by gbraad** [comment] 2017-11-17 04:36
> "Profile 'ttt' (/Users/hardy/.minishift/profiles/ttt) deleted successfully."

Personally, I think this looks very cluttered. Nowhere else do we show the Minishift home folder. Why do we need to show it in this case?

**Comment by praveenkumar** [comment] 2017-11-17 06:43
We could just say `Profile 'ttt' deleted successfully` rather than specify the location of profile folder.

**Comment by gbraad** [comment] 2017-11-17 06:50
@praveenkumar This also has my preference

**Comment by LalatenduMohanty** [comment] 2017-11-17 07:02
I agree that for a profile which does not have the VM , we should not show `VM for profile 'ttt' does not exist`. But for profiles which has a VM instance we should show it is getting deleted to keep the delete process transparent. Basically it gives the user more understanding and confidence about what is getting deleted. Same for the directory structure.

**Comment by LalatenduMohanty** [comment] 2017-11-17 07:05
Also we need to keep `profile delete` inline to the output of `minishift delete` command output. `minishift delete` gives information about what is actually getting deleted e.g. `minishift delete --clear-cache`.

**Comment by budhrg** [comment] 2017-11-17 10:02
> I am confused about the "VM for profile 'ttt' does not exist". What is this supposed to mean? I think this can be removed.

Sure, looks like unnecessary info. User will not care if VM exists or doesn't exist if he/she decided to remove it.

How about? 

```
$ minishift profile delete ttt --force
Profile folder  '/Users/hardy/.minishift/profiles/ttt' deleted successfully.
Profile 'ttt' deleted successfully.
```

**Comment by gbraad** [comment] 2017-11-17 10:07
As a developer, I do not care about the folder structure the profile was in. i only care that it contains a VM and that it reclaimed my space. Because of the data inside it, is hypervisor specific anyways. It does not provide more to a user to know this.

**Comment by budhrg** [comment] 2017-11-17 10:10
> i only care that it contains a VM and that it reclaimed my space. Because of the data inside it, is hypervisor specific anyways.

Sure. Let's keep
```
$ minishift profile delete ttt --force
Profile 'ttt' deleted successfully.
```

Simple and straight.

**Comment by gbraad** [comment] 2017-11-17 10:11
That is what @praveenkumar (and I) also prefer; short and concise.

**Comment by hferentschik** [comment] 2017-11-17 10:13
> That is what @praveenkumar (and I) also prefer; short and concise.

+1, make it four.

**Comment by LalatenduMohanty** [comment] 2017-11-17 10:15
I feel strongly that we should communicate user about what we are deleting. Don't you feel at adds to the transparency of the command execution.

**Comment by hferentschik** [comment] 2017-11-17 10:20
There are other ways to add this transparency. We have been talking several times about the ability for example to get more insight into the cache and potentially prune it. When it comes to profiles, I could image a `minishift profile list --verbose` which on top of the name and state also reports on the profile location and how much data it consumes. 

Let's try to add some more transparency into some dedicated commands, but leave other output short and concise.

**Comment by gbraad** [comment] 2017-11-17 10:29
> Let's try to add some more transparency into some dedicated commands, but leave other output short and concise.

Exactly, as this is more of a power user use-case. The vox populi (sorry for the generalisation) shouldn't have to care about this.

**Comment by hferentschik** [comment] 2017-11-17 10:30
> Exactly, as this is more of a power user use-case. The vox populi (sorry for the generalisation) shouldn't have to care about this.

+1

**Comment by LalatenduMohanty** [comment] 2017-11-17 10:44
> There are other ways to add this transparency. We have been talking several times about the ability for example to get more insight into the cache and potentially prune it. When it comes to profiles, I could image a minishift profile list --verbose which on top of the name and state also reports on the profile location and how much data it consumes.

I am fine with this. But this is not something planned for near future.  So if we reduce the output now there is no way we can track what should be added to the verbose output in future.  

May be we can add these outputs to be visible for glog.V(2). That's the compromise I will accept.  

I am still do not understand why we need to shorten the output. I guess we are expecting it would add to the user experience. Which I think is not be the case. Because deleting profile is an expensive command and user needs to understand that. 

As I said before `I agree that for a profile which does not have the VM , we should not show VM for profile 'ttt' does not exist` but completing removing what files we are deleting is an optimization which is not required.

**Comment by gbraad** [comment] 2017-11-17 10:52
It is not an optimization, but an unnecessity. User experience is about telling the user what he cares about, at the moment he takes an action.

**Comment by LalatenduMohanty** [comment] 2017-11-17 18:25
> . Especially when it concerns a delete action... as after this, it would be gone anyways. What do we expect the user to do with this, check if the folder is really gone? This is what he expects in the first place...

I agree. But as I mentioned delete is a command which user should know what the command is doing. Because the actions are pretty serious. So telling user what actually happened is good idea IMO.  Sometimes we need to tell user things to keep the user aware of what is happening. 

However I can live with the information moving in to `-V2` but I wont be very happy about it.

**Comment by gbraad** [comment] 2017-11-21 11:50
> actions are pretty serious. 
> user what actually happened

This argument does not hold, as the information is ONLY provoided after a confirmation is given. If the informatiin is important, it should be given beforehand, as this would aid the user in making an informed decision. Now, it is an after the fact message, and is therefore of no importance to the user about the decision making process. Since the user already has to confirm, he can understand that the action will remove associated data on saying yes. He expects the application to remove what he confirmed, but I am sure he does not care where you removed it. If you want it to be meaningful, it should have been part of the feedback loop in a much earlier stage.

**Comment by LalatenduMohanty** [comment] 2017-11-23 20:02
Resolved via https://github.com/minishift/minishift/pull/1711

**Closed by LalatenduMohanty** 2017-11-23 20:02 UTC
Labels: component/profile, kind/task, priority/major
