### ISSUE TITLE
Getting 404 while trying to udpate itself Cannot download checksum (macosX / brew)

### ISSUE THREAD

**Issue by chmouel** [minishift/minishift#622] opened 2017-03-29 12:46 UTC
I have installed the stable minishift version with the brew method : 

     brew cask install minishift

When starting minishift I am getting a checksum when answering Y if I want to update : 

```
$ minishift start
There is a newer version of minishift available. Do you want to
automatically update from v0.9.0 to v1.0.0-beta.5 now? [y/N] y
Updating to version 1.0.0-beta.5
Downloading updated binary checksum to validate updated binary
E0329 14:42:40.172524   84258 update.go:155] Cannot download checksum: received 404
```

**Comment by chmouel** [comment] 2017-03-29 13:02
may be a duplicate from https://github.com/minishift/minishift/issues/204 but I am not sure!

**Comment by LalatenduMohanty** [comment] 2017-03-30 06:47
@chmouel Right, it is a duplicate of #204 . Please check [1] for steps to install latest Beta
`  $ brew cask install minishift-beta` 
[1] https://github.com/minishift/minishift#with-homebrew

**Closed by LalatenduMohanty** 2017-03-30 06:47 UTC
Labels: resolution/duplicate
