### ISSUE TITLE
After restart, can't push to Minishift registry

### ISSUE THREAD

**Issue by apitt** [minishift/minishift#757] opened 2017-04-16 17:27 UTC
Enviromment:
Minishift 1.0.0-rc.0
oc 1.5.0-rc.1
MacOS
Docker for Mac 1.12.6 (but Docker turned off, just using the client)
MINISHIFT_CPUS=4
MINISHIFT_MEMORY=10240
MINISHIFT_VM_DRIVER=xhyve

Steps to reproduce:

1. From a clean system (no .kube or .minishift), run 
    `minishift start`
2. Connect to minishift Docker: 
    `eval $(minishift docker-env)`
3. Pull an image, for example: 
    `docker pull nginx:alpine`
4. Tag the image for the minishift registry: 
    `docker tag nginx:alpine 172.30.1.1:5000/myproject/nginx:alpine`
5. Login to the minishift registry.
    MINI_TOKEN=$(oc whoami -t)
    docker login -u developer -p ${MINI_TOKEN} 172.30.1.1:5000
    Login succeeded.
6. Push the image: 
    `docker push 172.30.1.1:5000/myproject/nginx:alpine`
7. After push completes, do a `docker logout`, then a `minishift stop`

So far, so good.  The problem comes when you start minishift again.

1. Run `minishift start`
2. Connect to minishift Docker: 
    `eval $(minishift docker-env)`
5. Login to the minishift registry.
    MINI_TOKEN=$(oc whoami -t)
    docker login -u developer -p ${MINI_TOKEN} 172.30.1.1:5000
    Login succeeded.
6. Push the image: 
    `docker push 172.30.1.1:5000/myproject/nginx:alpine`
7. Push won't happen.  It just keeps retrying the push but never succeeds.
    The push refers to a repository [172.30.1.1:5000/myproject/nginx]
    e6983b701b8b: Retrying in 8 seconds
    90e9f0ac3473: Retrying in 8 seconds 
    9f654519d2ae: Retrying in 8 seconds 
    9f8566ee5135: Retrying in 8 seconds

I noticed the same behavior on my system at work using the same version of Minishift, but on Windows 7 with VirtualBox and Docker client 1.12.6.

**Comment by hferentschik** [comment] 2017-04-16 19:00
I think this is due to the fact that the registry is not properly persisting the images. This is related to the fact that issue #389 and not setting _host-pv-dir_. This problem should be fixed after merging pull request #754, but needs to be confirmed.

**Comment by apitt** [comment] 2017-04-17 15:15
Just to be clear, this can be reproduced without attempting a push after the original start.  The first steps were just to show that it was possible to push to the Minishift registry before the first restart.

It seems that simply stopping and starting Minishift is what causes the registry to stop accepting connections.  I find it strange that "docker login" still works, though.

**Comment by jorgemoralespou** [comment] 2017-04-17 18:32
@apitt works cause it's managed by different component

**Comment by apitt** [comment] 2017-04-17 19:31
Thanks for the clarification.

**Comment by hferentschik** [comment] 2017-04-18 12:37
Alternatively you can grab the appropriate binary for your OS from here - http://artifacts.ci.centos.org/minishift/minishift/master/96/

**Comment by pittar** [comment] 2017-04-18 13:12
Thanks guys.  I'll give it a shot later today. (@apitt from my work account).

**Comment by pittar** [comment] 2017-04-18 14:46
Hi all,

I downloaded the binary as suggested by @hferentschik on my Windows 7 work station and started fresh.  I can confirm that the registry now works as expected after minishift restarts.

I'll try this on my Mac tonight, but I'm confident this has resolved the issue.  Thanks!

**Comment by budhrg** [comment] 2017-04-18 15:53
@pittar , Good to know that .

If it works in Mac too, then we can close this  issue.

**Comment by pittar** [comment] 2017-04-18 17:07
@budhrg , I decided to burn some mobile data at lunch and tried the latest binary on my Mac.  Everything looks good now.  I can push images after multiple restarts of Minishift.  Same config and process as detailed in the original report, but using the new binary from http://artifacts.ci.centos.org/minishift/minishift/master/96/

Thanks again.

**Comment by budhrg** [comment] 2017-04-18 17:20
Great @pittar ,

I am closing this issue now since seems to be fix by later changes in master. :+1:

**Closed by budhrg** 2017-04-18 17:20 UTC
Labels: kind/bug, priority/major
