### ISSUE TITLE
LIBVIRT_2.0.0' not found error in Fedora 24

### ISSUE THREAD

**Issue by supriya-bharadwaj** [minishift/minishift#1116] opened 2017-07-10 14:01 UTC
Getting error on using minishift 1.2.0 in Fedora 24

```
$ minishift start -v 5 --show-libmachine-logs
Starting local OpenShift cluster using 'kvm' hypervisor...
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 
() DBG | /usr/local/bin/docker-machine-driver-kvm: /lib64/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm)
E0710 19:29:09.712772    7352 start.go:275] Error starting the VM: dial tcp: missing address. Retrying.
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 
E0710 19:29:09.715376    7352 start.go:275] Error starting the VM: dial tcp: missing address. Retrying.
() DBG | /usr/local/bin/docker-machine-driver-kvm: /lib64/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm)
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
() DBG | /usr/local/bin/docker-machine-driver-kvm: /lib64/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm)
Plugin server listening at address 
E0710 19:29:09.717634    7352 start.go:275] Error starting the VM: dial tcp: missing address. Retrying.
Error starting the VM: dial tcp: missing address
dial tcp: missing address
dial tcp: missing address
[supriya@dhcp193-111 cdk3]$ minishift start -v 5 --show-libmachine-logs

```

**Comment by budhrg** [comment] 2017-07-10 14:06
More info, 

- Recently upgraded to Fedora 24
- User is not able to run any command via `sudo`.
- Also, not able to get VM in Virtualbox driver too

**Comment by hferentschik** [comment] 2017-07-10 19:37
I am not sure whether this is a Minishift issue per se. Do virtualisation in general work using libvirt?

**Comment by gbraad** [comment] 2017-07-11 03:50
What is the cause of "User is not able to run any command via sudo"?
Also, what is the error that is shown when using Virtualbox?

**Comment by praveenkumar** [comment] 2017-07-11 11:31
So I got access to @supriya-bharadwaj laptop and looks like there was some issue when running virtualbox along with kvm and she removed virtualbox yesterday and rebooted system and now I didn't find any issue. Closing this issue.

**Closed by praveenkumar** 2017-07-11 11:31 UTC
Labels: kind/bug, priority/major

**Comment by gbraad** [comment] 2017-07-11 14:11
having both installed at the same time they can conflict; when virtualbox has a VM running, it prevents libvirt to be used, and vice versa. So I can imagine this is likely a situation somewhere in the middle of both. Better to describe in the troubleshooting guide that you should have only one hypervisor installed.
