### ISSUE TITLE
weird profile created under ~/.minishift/profiles/istio 08.38.16

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#1946] opened 2018-01-26 05:46 UTC
### General information

  * Minishift version: v1.11.0+4459917
  * OS: macOS
  * Hypervisor:Xhyve

### Weird profile created which can't be deleted

The following profile has been created for an unknown reason and can't be deleted

```
minishift profile list
- .DS_Store		Error getting the VM status: stat /Users/dabou/.minishift/profiles/.DS_Store/machines/.DS_Store: not a directory
- istio			Running		(Active)
- istio 08.38.16	Does Not Exist
- minishift		Stopped

minishift profile delete "istio 08.38.16"
Profile names must consist of alphanumeric characters only.
```

**Comment by LalatenduMohanty** [comment] 2018-01-26 18:38
@cmoulliard In that case you can delete it by running `rm -rf ~/.minishift/profiles/istio 08.38.16` but I am not sure how this directory got created. Lets see if you hit the issue again.

**Comment by gbraad** [comment] 2018-01-27 11:24
Spaces should not br allowed. Likely an escape character was used.

**Comment by cmoulliard** [comment] 2018-01-28 13:25
Here is the script that I'm using where no spaces are defined. https://goo.gl/oSANcz

**Comment by praveenkumar** [comment] 2018-01-29 03:29
I did try to use the escape character to set a profile but it errors out as expected. I think this profile is not set/created by the command but somehow script which @cmoulliard  use create a folder under `~/.minishift/profile` and list it when user use `profile list` same as `.DS_Store`.

@minishift/minishift-dev should we use the same regex to list the profile which we are now using to create them so that there would be no confusion about it?

```
$ ./minishift profile set foo\ bar
Profile names must consist of alphanumeric characters only.

 $ ./minishift profile set "foo bar"
Profile names must consist of alphanumeric characters only.
```

**Comment by gbraad** [comment] 2018-01-29 03:34
Also, the script also did not conclusively indicate the folder was created with this way

**Comment by anjannath** [comment] 2018-01-29 03:52
@praveenkumar +1 for using the same regex as the one used during the creation of profiles. We should skip files, and stuff that is not matched by the regex while listing profiles.

**Comment by LalatenduMohanty** [comment] 2018-02-14 11:56
@praveenkumar `profile list` gets the actual directory name from the filesystem. personally, I do not feel we need to fix anything. As the profile is not created by minishift, we do not need a way to clean it. We can always delete the actual directory using `rm -rf` command. 

@cmoulliard I am inclined to close this issue as not a bug as `minishift`  have not created this profile. WDYT?

**Closed** 2018-02-14 13:44 UTC
Labels: kind/bug, priority/major
