### ISSUE TITLE
Add command to reuse configs from existing profiles

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1649] opened 2017-11-01 19:38 UTC
As discussed in https://github.com/minishift/minishift/issues/1517 I would suggest that we add `minishift profile clone/copy  SRC_PROFILE  PROFILE`. It should copy the config.json file, add-ons (including the enabled/disabled state), cache.

**Comment by budhrg** [comment] 2017-11-06 07:23
IMO, this can be added via flag in start command.

```
$ minishift --profile foo start --copy[--clone] <existing-profile-name> 
```
If `existing-profile-name` doesn't exists then print error message.

**Comment by gbraad** [comment] 2017-11-06 08:10
another flag to handle feels bad, but I also some of the other stuff feels not right. a profile is a collection of files and configuration, but what you are copying is the configuration, not the cache 9as this should be shared anyways), and the same not for the addons, but only the enablement. therefore, it makes sense to copy configuration between profiles. I would say: `minishift config copy new4`...

**Comment by LalatenduMohanty** [comment] 2017-11-12 17:59
@gbraad Even if we have global cache, we still need to copy cache If there is any because when we introduce the global cache we need to provide some mechanism to use non-global cache if required. For example global cache uses x version of ISO image but the profile wants to use a different ISO image. I guess practically it would be used more with container images. I am not sure if we can handle different versions of container images in global cache.

**Comment by gbraad** [comment] 2017-11-13 04:13
other versions should of the image should not be an issue. The PR from
@hardy stores the metadata in the index.json and this will refer to the
blobs. So different version will have different blobs.

However, I am not following why 'cache' would have to be copied.

**Comment by hferentschik** [comment] 2017-11-13 08:49
> Even if we have global cache, we still need to copy cache If there is any because when we introduce the global cache we need to provide some mechanism to use non-global cache if required. 

Why? Our whole efforts are to be able to cater for all these cases. That's why we restructure the ISO cache directory and that's partly why we want to use OCI for image storage.

> For example global cache uses x version of ISO image but the profile wants to use a different ISO image.

Sure, that's why we keep the ISO versioned in the cache. Same as _oc_. They co-exist happily together.

>  I guess practically it would be used more with container images. I am not sure if we can handle different versions of container images in global cache.

Sure we can. Is this not the whole point?

**Comment by LalatenduMohanty** [comment] 2017-11-27 18:01
> Why? Our whole efforts are to be able to cater for all these cases. That's why we restructure the ISO cache directory and that's partly why we want to use OCI for image storage.

Makes sense. I was wrong. I think is is more cleaner and simpler.

**Comment by praveenkumar** [comment] 2018-01-04 09:35
@gbraad @LalatenduMohanty Since now global cache is in place and I do like the idea of `minishift config copy <profileA> <profileB>` if both profiles exist. I am not sure about should we create `profileB` if not exist and then copy the config. Also we have addons specific to profile do we need to add a command in addon context `m addon copy profileA profileB` or something else?

**Comment by budhrg** [comment] 2018-02-19 08:39
> I am not sure about should we create profileB if not exist and then copy the config.

How we can copy config without creating `profileB` if it doesn't exist. If profile exists then we just copy config.

> do we need to add a command in addon context m addon copy profileA profileB or something else?

I think origin requirement include copying the config.json file, add-ons (including the enabled/disabled state) etc. I am against creating new command. We can add flag to copy command to tweak this behavior.

I think the part of discussion here is **if profile exists**, do we 
- overwrite the config or addons
- prompt user and behave accordingly.

**Comment by LalatenduMohanty** [comment] 2018-02-19 08:48
> Since now global cache is in place and I do like the idea of minishift config copy <profileA> <profileB> if both profiles exist. I am not sure about should we create profileB if not exist and then copy the config. Also we have addons specific to profile do we need to add a command in addon context m addon copy profileA profileB or something else?

@praveenkumar Lets go back to the requirement/use case.  We need a way to clone all settings (config, add-ons) from a profile because user has created a profile with some custom settings which works for him and he should be able to reuse the profile settings easily. So I would suggest we add this option to `minishift profile set \<New Profile`> --copy-config-of \<Existing Profile\>`. While using `minishift start --profile` user can use the flags for non default settings. 

In place of `--copy-config-of` we can think of something more intuitive. Here are some other options `--use-config-of` or `--clone-config`


@jorgemoralespou  WDYT

**Comment by jorgemoralespou** [comment] 2018-02-19 09:04
@LalatenduMohanty in my opinion getting the global options should be the default when creating a new profile, as this would be what's most common and would require less typing. In case one wants a totally new profile, then one would add a flag. When one creates a new profile I would explicitly call out the options being copied so that the user is aware and can change one seeing for that profile or for the global config.
I know there's no concept of global config, yet, but this is what I would do, create a global config that could hold whatever configuration a profile would inherit at creation time.
It would be similar to having an empty profile from which you would always copy, as you wrote, but being the default and not an opt-in option.

Why I favour this option? Because I think this is what would be most used and useful and hence I would minimized the typing for this option.

**Comment by praveenkumar** [comment] 2018-02-19 09:53
>  Why I favour this option? Because I think this is what would be most used and useful and hence I would minimized the typing for this option.

@jorgemoralespou I agree, but since we don't have the global config in place yet and that will require a bit more work just adding another config file. We were thinking to go one step back and at least provide an option to copy config and addons for profile for users so they don't have to set each options for simillar configurations.

**Comment by budhrg** [comment] 2018-02-19 10:31
> Why I favour this option? Because I think this is what would be most used and useful and hence I would minimized the typing for this option.

@jorgemoralespou I think is another independent requirement. Even though, I know I get default configs when creating new profile but there can be a use case as below:

```
// Assuming I have default config
$ minishift profile set foo   # Getting default config

// I added addons
// I added few configs

// Now, I want to create another profile based on this existing profile
minishift profile set foo-v2 --copy-config-of foo
```

IMO, both makes sense.

**Comment by jorgemoralespou** [comment] 2018-02-19 23:17
I'm not saying that copy a profile don't make sense, I'm only trying to say
that in most cases the profile you want to copy from will be a global
profile and that you will most likely always want to copy from that
profile, so make that requirement before this one.

The underlying behavior is the same, though.

**Comment by budhrg** [comment] 2018-02-20 06:39
>  I'm only trying to say that in most cases the profile you want to copy from will be a global
profile and that you will most likely always want to copy from that
profile, so make that requirement before this one.

I would like to agree here with you @jorgemoralespou that global profile use case is more useful here and it makes sense to implement it first then profile copy.

**Comment by anjannath** [comment] 2018-06-06 07:08
If we want to have a feature like this the user would like to move his entire set-up (including the vm) as in #2439.

So we can simplify this to just `minishfit export` and `minishift import` and the whole set-up is re-created in the new host. but this has to work for every hypervisor or initially we can support just kvm as it is straight forward. also we can add `--profile` flag to the command to export just that profile.

@minishift/minishift-dev WDYT guys?

**Comment by jorgemoralespou** [comment] 2018-06-06 09:34
I don't think the purpose of this issue is to clone a profile, VM included,
but to clone profile's config for reusability.

**Comment by anjannath** [comment] 2018-06-07 05:42
@jorgemoralespou Yes.. initially i thought #2439 is a duplicate of this one so i mentioned. In #2439 the user wanted to move the profile (vm) also, in that case these are not duplicates...

**Comment by praveenkumar** [comment] 2018-08-17 05:41
@jorgemoralespou since now we have a global config option, do you still think this will add any more value from profile perspective?

**Comment by LalatenduMohanty** [comment] 2018-08-21 18:37
> @jorgemoralespou since now we have a global config option, do you still think this will add any more value from profile perspective?

Yes, it would be still useful. Because it copies add-ons and its state too.

**Comment by LalatenduMohanty** [comment] 2018-08-31 02:00
I am going ahead with `minishift profile set \<profile name`> --clone-config-from \<existing profile\>`. Let me know if you have better suggestion.

**Comment by LalatenduMohanty** [comment] 2019-01-23 08:37
As per the latest discussion we are adding `minishift profile copy SRC_PROFILE_NAME NEW_PROFILE_NAME`.

**Comment by gbraad** [comment] 2019-01-23 09:45
Reference the issue... ?

**Closed** 2019-02-13 12:56 UTC
Labels: component/profile, kind/feature, priority/major
