### ISSUE TITLE
Cannot login to minishift as admin

### ISSUE THREAD

**Issue by ibaboo** [minishift/minishift#2107] opened 2018-03-09 13:00 UTC
### General information

  * Minishift version: minishift v1.14.0+1ec5877

  * OS: Linux
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. minishift start
  2. oc login -u system:admin

### Expected
login as admin

### Actual
Does not login 

oc login -u system:admin
Authentication required for https://192.168.99.100:8443 (openshift)
Username: system:admin

### Workaround

https://github.com/minishift/minishift/issues/2107#issuecomment-396160071

Here is the work around: 

```
$ minishift addon apply admin-user

$ oc login -u admin
Authentication required for https://192.168.64.2:8443 (openshift)
Username: admin
Password: admin
Login successful.

```
Or

```
 $ minishift addon list
- admin-user	 : enabled	P(0)

 $ minishift start 

$ oc login -u admin
Authentication required for https://192.168.64.2:8443 (openshift)
Username: admin
Password: admin
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "myproject".

```

**Comment by tylerauerbeck** [comment] 2018-03-11 23:55
@ibaboo I'm not seeing those issues:

$ minishift version
minishift v1.14.0+1ec5877

**Comment by amitkrout** [comment] 2018-03-12 11:19
@ibabooI am not able to reproduce the issue you are facing. What I m suspecting, in your case there might be old oc reference present in the path. Please try these steps

1. ./minishift start
2. eval $(./minishift oc-env)
3. oc login -u system:admin

**Comment by ibaboo** [comment] 2018-03-13 11:23
> minishift start
> -- Starting profile 'minishift'
> -- Checking if requested OpenShift version 'v3.7.1' is valid ... OK
> -- Checking if requested OpenShift version 'v3.7.1' is supported ... OK
> -- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
> -- Checking if KVM driver is installed ... 
>    Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
>    Checking driver binary is executable ... OK
> -- Checking if Libvirt is installed ... OK
> -- Checking if Libvirt default network is present ... OK
> -- Checking if Libvirt default network is active ... OK
> -- Checking the ISO URL ... OK
> -- Checking if provided oc flags are supported ... OK
> -- Starting local OpenShift cluster using 'kvm' hypervisor ...
> -- Starting Minishift VM ................... OK
> -- Checking for IP address ... OK
> -- Checking if external host is reachable from the Minishift VM ... 
>    Pinging 8.8.8.8 ... FAIL
>    VM is unable to ping external host
> -- Checking HTTP connectivity from the VM ... 
>    Retrieving http://minishift.io/index.html ... FAIL
>    VM cannot connect to external URL with HTTP
> -- Checking if persistent storage volume is mounted ... OK
> -- Checking available disk space ... 8% used OK
> -- OpenShift cluster will be configured with ...
>    Version: v3.7.1
> Starting OpenShift using openshift/origin:v3.7.1 ...
> OpenShift server started.
> 
> The server is accessible via web console at:
>     https://192.168.99.100:8443
> 
> WARNING: You specified an HTTP proxy for cluster up, but one is not configured for the Docker daemon
> WARNING: You specified an HTTPS proxy for cluster up, but one is not configured for the Docker daemon
> Could not set oc CLI context for: 'minishift'


> eval $(minishift oc-env)
> f2969831@ninja ~ $ oc login -u system:admin
> The server uses a certificate signed by an unknown authority.
> You can bypass the certificate check, but any data you send to the server could be intercepted by others.
> Use insecure connections? (y/n): y
> 
> Authentication required for https://192.168.99.100:8443 (openshift)
> Username: system:admin
> Password:

**Comment by praveenkumar** [comment] 2018-03-14 03:57
@ibaboo which ISO are you using, I can see below logs for your explanation. https://github.com/openshift/origin/issues/18596

```
WARNING: You specified an HTTP proxy for cluster up, but one is not configured for the Docker daemon
WARNING: You specified an HTTPS proxy for cluster up, but one is not configured for the Docker daemon
Could not set oc CLI context for: 'minishift'
```

**Comment by ibaboo** [comment] 2018-03-14 06:25
I am using Virtual Box

**Comment by praveenkumar** [comment] 2018-03-15 05:43
@ibaboo as per logs you are using `kvm` if you want to use the VirtualBox then `--vm-driver virtualBox` is needed as start option.

**Comment by ibaboo** [comment] 2018-03-15 09:51
@praveenkumar, actually I have tried with both Vbox and kvm with the same results

**Comment by LalatenduMohanty** [comment] 2018-03-16 12:17
@ibaboo Can you please uninstall Minishift https://docs.openshift.org/latest/minishift/getting-started/uninstalling.html and try again with `minishift start --vm-driver virtualbox`

**Comment by ibaboo** [comment] 2018-03-20 10:35
I have tried to uninstall and reinstall but now I get the error below. However you can close this issue as minishift is not working for me, I have installed openshift all in one on a VM which is working. 

   Error: Cannot get TCP port information from Kubernetes host
   Caused By:
     Error: cannot create container using image openshift/origin:v3.7.1
     Caused By:
       Error: Error: No such image: openshift/origin:v3.7.1
Error during 'cluster up' execution: Error starting the cluster.

**Comment by deepforu47** [comment] 2018-05-01 07:25
Having same issue -

$ minishift start --vm-driver virtualbox
```
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ........................ OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 9% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
Deleted existing OpenShift container
Using Docker shared volumes for OpenShift volumes
Using 192.168.99.101 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.101:8443

Could not set oc CLI context for: 'minishift'
```
```
$ minishift version
minishift v1.16.1+d9a86c9
```
```
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth
```
```
$ oc login -u system:admin https://192.168.99.101:8443
Authentication required for https://192.168.99.101:8443 (openshift)
Username: system:admin
Password:
```

**Comment by gbraad** [comment] 2018-05-01 11:55
When the errors shows 'no such image' you are unable to download the
OpenShift container image. Please verify your internet connection.

**Comment by gbraad** [comment] 2018-05-01 11:58
Kuldeep, you have a different issue then from what I see from the output.
Please verify your ~/.kube directory for old config. Best to clean both
.kube and .minishift when you try again.

**Comment by deepforu47** [comment] 2018-05-03 13:48
Everything is working after removing ~/.kube and ~/.minishift folders.
Thank you for the response !

**Comment by budhrg** [comment] 2018-05-03 13:56
@ibaboo  Can you retry by removing ~/.kube and ~/.minishift folders?

**Comment by ibaboo** [comment] 2018-05-04 04:52
@budhrg thanks for the tip, however I am removed minishit totally from my laptop.

**Comment by gbraad** [comment] 2018-05-04 05:04
@ibaboo 

> minishit 

was that necessary?

**Comment by ibaboo** [comment] 2018-05-04 05:09
That was a honest typo , Apologies.

**Comment by MinSung-TheBest** [comment] 2018-06-01 07:51
I also have the same issue...

**Comment by carbonin** [comment] 2018-06-01 19:42
I'm also seeing this issue:

```
$ minishift version
minishift v1.18.0+756b128
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.9:8443
openshift v3.9.0+8e3cb9b-8
kubernetes v1.9.1+a0ce1bc657
$ oc login $(minishift ip):8443 -u system:admin
Authentication required for https://192.168.42.9:8443 (openshift)
Username: system:admin
Password: 
error: username system:admin is invalid for basic auth
```

Is there some alternate way to login as admin? Should I reopen this bug because I'm using a new minishift version?

**Comment by carbonin** [comment] 2018-06-01 20:28
I can login as `system:admin` on version 1.17 so something in 1.18 seems to have broken this.

Ad per the docs:

> To login as administrator, use the system account:

> $ oc login -u system:admin
>In this case, client certificates are used. The certificates are stored in ~/.kube/config. The cluster up command installs the appropriate certificates as a part of the bootstrap.

I removed my `.kube` directory and restarted minishift.

Now my `~/.kube/config` looks like this:
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.42.128:8443
  name: 192-168-42-128:8443
contexts:
- context:
    cluster: 192-168-42-128:8443
    namespace: myproject
    user: developer/192-168-42-128:8443
  name: minishift
- context:
    cluster: 192-168-42-128:8443
    namespace: myproject
    user: developer/192-168-42-128:8443
  name: myproject/192-168-42-128:8443/developer
current-context: minishift
kind: Config
preferences: {}
users:
- name: developer/192-168-42-128:8443
  user:
    token: gHnOXLDsTK_AhX1WSsuloUAmj1zI1ardkAclszQ92hQ
```

Doesn't seem to have any certificates for the admin user.

I also found this comment https://github.com/minishift/minishift/pull/741#issuecomment-293812310 on the PR which added the admin-user addon which seems to suggest that we should not be using the `system:admin` account.

After seeing that, I thought to try the username `admin` with password `admin` and that seems to work with minishift version 1.18

So is this a bug or something that needs to be updated in the documentation? If nothing else hopefully this helps the next person to come googling this way :smile: 

@LalatenduMohanty just pinging you because you happened to write the comment I found. Hope you can help.

**Comment by praveenkumar** [comment] 2018-06-02 00:40
@carbonin you should try to use admin user addon and then you can able to login as `admin` with password `admin`

```
$ minishift addon apply admin-user
```

**Comment by praveenkumar** [comment] 2018-06-02 00:42
> So is this a bug or something that needs to be updated in the documentation? If nothing else hopefully this helps the next person to come googling this way

It's not a bug but we do need to update our documents and possibly add this addon as part of post cluster up directly (need to discuss first).

**Comment by fogartyp** [comment] 2018-06-04 00:15
Thanks, @praveenkumar I was able to login once the addon was installed.

```
$ minishift addon apply admin-user
-- Applying addon 'admin-user':..

oc login -u admin
Logged into "https://192.168.64.2:8443" as "admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

..................
..................

$ minishift version
minishift v1.18.0+756b128

$oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.64.2:8443
openshift v3.9.0+ee4d1e7-20
kubernetes v1.9.1+a0ce1bc657```

**Comment by tkashem** [comment] 2018-06-05 15:56
I used the above workaround `minishift addon apply admin-user` to get by. But login for `system:admin` is still an issue, I believe.

This is what I run into when I try to log in as `system:admin`
```bash
$ minishift version
minishift v1.18.0+756b128
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.141:8443
openshift v3.9.0+ee4d1e7-20
kubernetes v1.9.1+a0ce1bc657
$ oc login -u system:admin
Authentication required for https://192.168.42.141:8443 (openshift)
Username: system:admin
Password: 
 ```

**Comment by aravindhp** [comment] 2018-06-05 16:29
I am running into this issue too. I see a difference in ```~/.kube/config``` between v1.17.0+f974f0c and v1.18.0+756b128. With v1.17, after doing ```minishift start```, if I check ```~/.kube/config``` I see that it has the following section for users:

```
users:
- name: developer/192-168-42-166:8443
  user:
    token: YQSovKc82xd61TAIDKsE40r9xLhz0GCgoNH_7G2UMmE
- name: system:admin/127-0-0-1:8443
  user:
    client-certificate-data: <data>
    client-key-data: <data>
```
If I then delete ```~/.kube/``` and ```~/.minishift/``` and try ```minishift start``` with v1.18, I see the following in ```~/.kube/config```:
```
users:
- name: developer/192-168-42-117:8443
  user:
    token: W0HLMgNMG3uuanznSn3TzcfBhA5PDWy2YO4xAxef9Do
```
The ```system:admin``` user is missing which I think is the cause of the issue. Was this change done on purpose between releases or is it a regression?

**Comment by yanngit** [comment] 2018-06-07 13:49
I'm having the same issue! Is there any workaround because I really need to get cluster scope admin rights...

**Comment by containscafeine** [comment] 2018-06-11 07:54
Removing .minishift and .kube directories do not help. It's weird that right after you get the message -
```
The server is accessible via web console at:
    https://192.168.42.5:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
```
when you try to log in as system:admin, it won't let you -
```console
$ oc login -u system:admin
Authentication required for https://192.168.42.5:8443 (openshift)
Username: system:admin
Password: 
error: username system:admin is invalid for basic auth
```

**Comment by LalatenduMohanty** [comment] 2018-06-11 08:01
@containscafeine and others Do you have `admin-user` add-on enabled in your setup?

**Comment by LalatenduMohanty** [comment] 2018-06-11 08:15
Here is the work around

```
 minishift addon list
- admin-user	 : enabled	P(0)

$ oc login -u admin
Authentication required for https://192.168.64.2:8443 (openshift)
Username: admin
Password:
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "myproject".

```

**Comment by nodje** [comment] 2018-06-18 13:11
```
$ minishift addon list
- admin-user	 : disabled	P(0)

$ oc login -u admin
Authentication required for https://192.168.64.2:8443 (openshift)
Username: admin
Password:
Login successful.

Logged into "https://192.168.64.3:8443" as "admin" using existing credentials.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

$ oc login -u system
Authentication required for https://192.168.64.2:8443 (openshift)
Username: system
Password:
Login successful.

Logged into "https://192.168.64.3:8443" as "system" using existing credentials.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

$ oc login -u system:admin
Authentication required for https://192.168.64.3:8443 (openshift)
Username: system:admin
Password: 
error: username system:admin is invalid for basic auth
```
when using `admin` as a password

**Comment by containscafeine** [comment] 2018-06-18 14:16
@nodje not sure what you mean, but you need to login as user: admin pass: admin after enabling the admin-user addon to get admin privileges.
On the other hand, you can log in to OpenShift with any user and any password and that account gets created dynamically.
`system:admin` user is a special admin user which is now disabled by default, hence this issue.

**Comment by nodje** [comment] 2018-06-18 14:23
I may be mistaken, but I never had to enable addons and was always able to log as `system:admin` and see system projects.
I had to reinstall minishift cause I couldn't get access to the webconsole anymore, and now I just can't get access to the `system:admin` user anymore.
I can log as `admin`, as `system` but can't see the system projects.

I can enable the `admin-user` addon, it doesn't give me access to the `system:admin`.
So I don't see the connection.

**Comment by containscafeine** [comment] 2018-06-18 14:49
All of us used to be able to login as `system:admin` previously. They have decided to take that power away from us now, and hence this issue was opened.
Till this issue is fixed or a conclusion is reached, the workaround to become an admin of your cluster is to enable the `admin-user` addon, and then login as user: admin and pass: admin. It won't give you our favorite `system:admin` user, but give the `admin` user admin rights. You'll be able to see the system projects after enabling the `admin-user` addon.
Any other user, is well, just any other user.

**Comment by LalatenduMohanty** [comment] 2018-06-18 15:25
@nodje AS @containscafeine mentioned this issue got introduced because we changed  how we use the oc binary to provision the OpenShift. We are going to fix the issue and till than the workaround of admin-user add-on should work for you.  Sorry for the inconvenience caused.

**Comment by nodje** [comment] 2018-06-19 09:16
Thank you for the details, sorry I wasn't clear enough. 
I get that enabling the admin-user addon is a work around, but I'm just surprised I still don't get access to the system "default projects" as shown above:

This is what I get:
```
$ minishift addon list
- admin-user	 : enabled	P(0)

$  oc login -u admin
Logged into "https://192.168.64.3:8443" as "admin" using existing credentials.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
```
andi would like to get the "classic" list of system projects:
```
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "myproject".
```

**Comment by dagniel** [comment] 2018-06-19 17:14
Hello all!

I'm not sure about the admin-user addon and its capabilities; for me it didn't work.

As a workaround for this issue I connected to the openshift-origin pod and added the cluster-admin user role to the standard "developer" user. This effectively turns developer into cluster admin with full access to infrastructure projects/namespaces.

with minishift VM up and running:
`minishift ssh #to connect to the VM
[docker@minishift docker]#sudo -s #to have access to the docker daemon(not sure if absolutely necessary)
[root@minishift docker]# docker ps -f "name=origin" --format "{{.ID}}" #to get the ID of the Origin pod
8d63f6fb9b34
[root@minishift docker]# docker exec -it $(docker ps -f "name=origin" --format "{{.ID}}") "/bin/bash" #to attach to the running container with a bash shell interactive tty
[root@minishift origin]# oc whoami
system:admin
[root@minishift origin]# oc adm policy add-cluster-role-to-user cluster-admin developer #to effectively give admin rights to the "developer" user
`

This is also persistent, so the policy config does not neet to be reapplied upon minishift restart.

**Comment by Valien** [comment] 2018-06-20 13:55
So saw this on another issue linked to the system:admin error. You need to run the following to get the admin-use addon to work properly:

1. `minishift addon enable admin-user`
2. `minishift addon apply admin-user`

Once done you should be able to login as admin/admin and see all the cluster projects.

Thanks for the workaround as I was bashing my head against the desk with the system:admin bug.

Switching to minishift from the normal `oc cluster up` docker containers since Docker broke the proxy issues.

**Comment by LalatenduMohanty** [comment] 2018-06-21 14:58
@dagniel Did you follow work around mentioned in https://github.com/minishift/minishift/issues/2107#issuecomment-396160071 ?

**Comment by alexellis** [comment] 2018-06-21 15:31
I have a similar issue here:

```
alexellis-a02:~ alexellis$  minishift addon list
- admin-user	 : enabled	P(0)
- anyuid	 : disabled	P(0)
- registry-route : disabled	P(0)
- xpaas		 : disabled	P(0)
alexellis-a02:~ alexellis$ minishift version
minishift v1.19.0+1750702
alexellis-a02:~ alexellis$  oc login -u admin
Authentication required for https://192.168.99.104:8443 (openshift)
Username: admin
Password: 
alexellis-a02:~ alexellis$ oc login -u system:admin
Authentication required for https://192.168.99.104:8443 (openshift)
Username: system:admin
Password: 
error: username system:admin is invalid for basic auth
alexellis-a02:~ alexellis$ 
```

Running `minishift addon apply admin-user` had no effect.

**Comment by dagniel** [comment] 2018-06-21 17:04
@LalatenduMohanty I haven't really used the addon feature and your workaround mentions the "addon enable" **OR** "addon apply" operations.

I've just tested and indeed it works. You first need to enable the admin-user addon, then start the minishift VM and then to apply the addon on the running machine. It didn't work for me as I only ran the enable command.

**Comment by LalatenduMohanty** [comment] 2018-06-22 04:21
@alexellis  Recently we have changed the way we used to provision OpenShift in Minishift hence `oc login -u system:admin` is breaking. However the admin-user creates a separate `admin` user which you can login by running `oc login -u admin` (password is `admin`).  The add-on is will not return error if the admin user already exists. Can you confirm that `oc login -u admin` works for you?

**Comment by LalatenduMohanty** [comment] 2018-06-22 04:23
> I've just tested and indeed it works. You first need to enable the admin-user addon, then start the minishift VM and then to apply the addon on the running machine. It didn't work for me as I only ran the enable command.

@dagniel  If you enable an add-on before `minishift start` it automatically runs after the `start` and you do not have to run `apply` explicitly. It is similar to systemd commands i.e. if you enable a service after machine start it automatically runs it.

**Comment by LalatenduMohanty** [comment] 2018-06-26 06:53
Resolved by #2492

**Closed by LalatenduMohanty** 2018-06-26 06:53 UTC
Labels: kind/bug, priority/critical

**Comment by gbraad** [comment] 2018-06-26 08:41
The new release would be two weeks from now.
We are looking into doing a minor release... @lalatenduMohanty are we going
ahead with this?

**Comment by LalatenduMohanty** [comment] 2018-06-26 09:38
@gbraad @nilarte Yes, it is released as part of https://github.com/minishift/minishift/releases/tag/v1.20.0.

**Comment by nilarte** [comment] 2018-06-26 15:25
Got it and it fixes "oc login -u system:admin"
Thanks!

**Comment by alexellis** [comment] 2018-06-29 12:49
Thanks for your help. I'll be trying this again soon.

**Comment by paoloantinori** [comment] 2018-10-19 13:20
Hi, I'm hitting this old issue with recent versions. Can I ask someone to verify it works correctly with you?

my versions are:

```
15:19 $ minishift version
minishift v1.25.0+90fb23e

-- OpenShift cluster will be configured with ...
   Version: v3.11.0
```

and `system:admin` cannot log in.

**Comment by budhram** [comment] 2018-11-26 08:46
@paoloantinori , I just verified with new installation of Fedora and Minishift. I am not able to reproduce this issue.

```
$ minishift version
minishift v1.27.0+707887e

$ minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
[...]
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.111:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin


-- Exporting of OpenShift images is occuring in background process with pid 2555.

$ eval $(minishift oc-env)

$ oc login -u system:admin
Logged into "https://192.168.42.111:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-dns
    kube-proxy
    kube-public
    kube-system
  * myproject
    openshift
    openshift-apiserver
    openshift-controller-manager
    openshift-core-operators
    openshift-infra
    openshift-node
    openshift-service-cert-signer
    openshift-web-console

Using project "myproject".

$ oc whoami
system:admin
```

Having said that we do have few issues with `~/.kube/config` conflicts in previous cases.

If `~/.kube/config` is not having important configurations from other Kubernetes project, I would recommend you to delete it and restart.
It should work.

**Comment by picorealm** [comment] 2019-05-30 06:08
What dmitrievav said in his [comment](https://github.com/minishift/minishift/issues/2107#issuecomment-441332761) is the correct solution

**Comment by tukeshwar** [comment] 2020-11-30 10:13
> minishift addon apply admin-user

I tried this but does not help. Below is error I am getting

> 
OpenShift server started.

The server is accessible via web console at:
    https://172.29.96.175:8443/console


error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: Unable to login to cluster
PS C:\minishift\minishift-1.34.3-windows-amd64>
PS C:\minishift\minishift-1.34.3-windows-amd64> C:\Users\TukeshwarBhardwaj\.minishift\cache\oc\v3.11.0\windows\oc.exe login -u system:admin
Server [https://localhost:8443]: https://172.29.96.175:8443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): yes

Authentication required for https://172.29.96.175:8443 (openshift)
Username: system:admin
Password:
error: username system:admin is invalid for basic auth
PS C:\minishift\minishift-1.34.3-windows-amd64> .\minishift.exe addon apply admin-user
-- Applying addon 'admin-user':..Error applying the add-on: Error executing command 'oc adm policy add-cluster-role-to-user cluster-admin admin'.
PS C:\minishift\minishift-1.34.3-windows-amd64> oc adm policy add-cluster-role-to-user cluster-admin admin
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
PS C:\minishift\minishift-1.34.3-windows-amd64> C:\Users\TukeshwarBhardwaj\.minishift\cache\oc\v3.11.0\windows\oc.exe login -u system:admin
Authentication required for https://172.29.96.175:8443 (openshift)
Username: system:admin
Password:
error: username system:admin is invalid for basic auth
PS C:\minishift\minishift-1.34.3-windows-amd64> .\minishift.exe addon apply admin-user
-- Applying addon 'admin-user':..Error applying the add-on: Error executing command 'oc adm policy add-cluster-role-to-user cluster-admin admin'.
PS C:\minishift\minishift-1.34.3-windows-amd64> oc adm policy add-cluster-role-to-user cluster-admin admin
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:anonymous" cannot list clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: no RBAC policy matched
PS C:\minishift\minishift-1.34.3-windows-amd64> oc login -u admin -p admin
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

PS C:\minishift\minishift-1.34.3-windows-amd64> oc adm policy add-cluster-role-to-user cluster-admin admin
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "admin" cannot list clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: no RBAC policy matched

**Comment by unmeshdesale** [comment] 2021-02-05 10:25
Just in case "minishift start" not able to create kube config file then this [comment](https://github.com/minishift/minishift/issues/2107#issuecomment-441332761) would help you set it.
