### ISSUE TITLE
Permission of certificates is altered after using the Minikube provisioner

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2063] opened 2018-02-23 11:53 UTC
### General information

  * Minishift version: v1.7.0+ (Since we start support of Minikube ISO) 
  * OS: Windows
  * Hypervisor: Hyper-V / Virtualbox

### Steps to reproduce

  1. `minishift.exe start --iso-url minikube`

### Expected

Minikube ISO should work.

### Actual

Minikube ISO fails to start minishift VM.

### Logs

```
PS C:\> minishift.exe version
minishift v1.7.0+1549135

PS C:\> minishift.exe start --iso-url minikube
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://storage.googleapis.com/minikube/iso/minikube-v0.24.0.iso'
 141.81 MiB / 141.81 MiB [=================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ......................................................... FAIL E0223 17:17:23.720221    1592 start.go:355] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc0422de018 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\ca.pem: chmod C:\Users\budhram\.minishift\ca.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e028 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\cert.pem: chmod C:\Users\budhram\.minishift\cert.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc042110038 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\ca.pem: remove C:\Users\budhram\.minishift\ca.pem: The process cannot access the file because it is being used by another process.
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e050 Length:0 AssetName:C:\Users\budhram\.minishift\certs\key.pem TargetDir:C:\Users\budhram\.minishift TargetName:key.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\key.pem: chmod C:\Users\budhram\.minishift\key.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e070 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\cert.pem: remove C:\Users\budhram\.minishift\cert.pem: The process cannot access the file because it is being used by another process.. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc0422de018 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\ca.pem: chmod C:\Users\budhram\.minishift\ca.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e028 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\cert.pem: chmod C:\Users\budhram\.minishift\cert.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc042110038 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\ca.pem: remove C:\Users\budhram\.minishift\ca.pem: The process cannot access the file because it is being used by another process.
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e050 Length:0 AssetName:C:\Users\budhram\.minishift\certs\key.pem TargetDir:C:\Users\budhram\.minishift TargetName:key.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\key.pem: chmod C:\Users\budhram\.minishift\key.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e070 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\cert.pem: remove C:\Users\budhram\.minishift\cert.pem: The process cannot access the file because it is being used by another process.
```

**Comment by LalatenduMohanty** [comment] 2018-02-23 12:02
@budhrg Did you test with Virtualbox? My guess is this might be related to HyperV.

**Comment by budhrg** [comment] 2018-02-23 12:04
> Did you test with Virtualbox? My guess is this might be related to HyperV.

Ya trying now.

**Comment by budhrg** [comment] 2018-02-23 12:12
@LalatenduMohanty Reproducible with Virtualbox too.

**Comment by anjannath** [comment] 2018-02-23 12:16
I could reproduce this with *Hyper-V* driver, now trying with *VirtualBox*

**Comment by budhrg** [comment] 2018-02-24 17:57
@amitrout also able to reproduce. He commented here https://github.com/minishift/minishift/issues/1993#issuecomment-368028915

**Comment by praveenkumar** [comment] 2018-02-26 05:17
@budhrg @anjannath Can you please check one of the older version of ISO?

- https://storage.googleapis.com/minikube/iso/minikube-v0.24.0.iso

**Comment by budhrg** [comment] 2018-02-28 12:31
> Can you please check one of the older version of ISO?

@praveenkumar , I was using v0.24.0 version only. Please check logs section in issue description.
It is reproducible from Minishift v1.7.0.

**Comment by gbraad** [comment] 2018-03-07 08:46
it seems to use chmod? but this is not possible... maybe started from cygwin?
it feels from the amounts of dots that the VM started, but it tried to do a first connection to provision and the connection with SSH is failing

**Comment by gbraad** [comment] 2018-03-29 11:03
This is likely a duplicate of #2098.
The provisioner modifies the permissions of the certificates, which likely causes and issue on Windows when redeploying.

**Closed** 2018-04-11 10:36 UTC
Labels: kind/bug, os/windows, priority/major
