### ISSUE TITLE
file permission issue in application container

### ISSUE THREAD

**Issue by mhabrnal** [minishift/minishift#2058] opened 2018-02-21 15:11 UTC
### General information

  * Minishift version: minishift-1.12.0-linux-amd64
    - openshift v3.6.1+008f2d5
    - kubernetes v1.6.1+5115d708d7
  * OS: Linux
  * Hypervisor: KVM and VirtualBox

I've prepared docker image [1] with suided application which just takes an argument and writes it into /proc/1/fd/2. 

[1] https://hub.docker.com/r/mhabrnal/logger-test/

Dockerfile looks like this:
```
FROM fedora:27
MAINTAINER "Matej Habrnal" <mhabrnal@redhat.com>

COPY suid-logger /usr/libexec/suid-logger
RUN chown root:root /usr/libexec/suid-logger
RUN chmod 4755 /usr/libexec/suid-logger

CMD while :; do sleep 1000; done
```

### Steps to reproduce
```
$ oc new-app mhabrnal/logger-test
$ oc rsh <POD>
sh-4.4$ ls -al /usr/libexec/suid-logger 
-rwsr-xr-x 1 root root 816112 Feb 21 13:03 /usr/libexec/suid-logger
sh-4.4$ ls -al /proc/1/fd/2
l-wx------ 1 1000070000 root 64 Feb 21 13:55 /proc/1/fd/2 -> pipe:[74878]
sh-4.4$ echo test | /usr/libexec/suid-logger
Failed to open '/proc/1/fd/2': Permission denied
``` 

### Expected
write to '/proc/1/fd/2'

### Actual
Failed to open '/proc/1/fd/2': Permission denied

If the application is not suided everything works.

EDIT:
sh-4.4$ /usr/libexec/suid-logger test
UID=1000070000
EUID=0

changed to:
sh-4.4$ echo test | /usr/libexec/suid-logger

**Comment by anjannath** [comment] 2018-02-21 16:42
Please take a look at the `anyuid` addon
https://github.com/minishift/minishift-addons/addon/anyuid/

HTH

**Comment by praveenkumar** [comment] 2018-02-22 06:44
@mhabrnal As per your Dockerfile, image which created it only going to run as root user which OpenShift doesn't allow by default. As part of minishift, we have an addon called `anyuid` as @anjannath mentioned. After applying this addon you can run an image with root user also.

**Comment by mhabrnal** [comment] 2018-02-22 09:45
@praveenkumar All is about the suided application. I don't care if the image runs as root or nonroot users. I've got suited binary in a container and it doesn't work as expected.

Or you are saying there is no root in a running container in minishift (unless `anyuid`) so suided applications owned by root don't work as on the host.

**Comment by praveenkumar** [comment] 2018-02-22 13:47
@mhabrnal OpenShift has the policy as default not to run any image as root user. when you applying `anyuid` addon then it change the security context and then you are able to run it. For production environment this is not recommended so by default we also don't enable this.

**Comment by xsuchy** [comment] 2018-02-22 14:56
The image can be run as unprivileged user - that is ok. We do not want to run the application as root or some specific user. So anyuid addon will not help here.

Inside of the image, there is setuid binary (similar to /usr/bin/sudo). When you execute setuid binary owned by root, you should get EUID=0. That works as expected.

So we have binary with EUID=0. But when this binary tries to write to file which is owned by 1000070000:root then it gets "permission denied". This is IMO bug because process with EUID should be able to write to such file.

**Comment by xsuchy** [comment] 2018-02-22 14:59
To be precise, this setuid binary is not executed directly by OpenShift, it is called somewhere deep inside of the application.

**Comment by praveenkumar** [comment] 2018-02-26 05:23
@xsuchy, Thanks for explaining @mhabrnal so this is not related to minishift then because we don't set any different permission for OpenShift cluster. This might be related to origin and bug should be filed under https://github.com/openshift/origin/issues tracker.

**Comment by gbraad** [comment] 2018-02-26 05:34
if the user is not allowed to perform the setuid call, it will fail...
since OpenShift runs as an aribitrary user, it will be impossible to
perform setuid. If the container can run as root, and then allow to use the
setuid call i think it would solve your problem. But in short, this is not
a Minishift issue, but related to what OpenShift does... Have a look at SCC
(Security Context Constraints) for more info:
https://blog.openshift.com/understanding-service-accounts-sccs/

**Comment by mhabrnal** [comment] 2018-02-26 15:22
@praveenkumar @gbraad  It works in Docker and OpenShift, I found the issue only in minishift.

I've updated the docker image mhabrnal/logging-test
You can test it like the this:
```
$ oc new-app mhabrnal/logger-test
$ oc rsh <POD>
sh-4.4$ echo test | /usr/libexec/suid-logger 
Failed to open '/proc/1/fd/2' as root: Permission denied
```

**Comment by mhabrnal** [comment] 2018-03-01 08:30
@LalatenduMohanty I have OpenShift with logging system deployed in my VM by ansible playbook  https://github.com/openshift/openshift-ansible/

**Comment by mtttcgcg** [comment] 2018-03-05 23:34
Same issue here. I installed and enabled the anyuid plugin, and restarted my minishift cluster, but it still does not seem to be running my deploys with root.  

minishift addons install --defaults
Minishift addons enable anyuid

When I run this command as either developer or system: 
oc adm policy add-scc-to-group anyuid system:authenticated

I get Error from server (Forbidden): User "developer" cannot get securitycontextconstraints.security.openshift.io at the cluster scope: User "developer" cannot get securitycontextconstraints.security.openshift.io at the cluster scope (get securitycontextconstraints.security.openshift.io anyuid

I also tried:
oc adm policy add-scc-to-user anyuid -z default

**Comment by mhabrnal** [comment] 2018-03-06 09:41
@mtttcgcg Hi, this is not the same issue (see comments above) :) You still talk about anyuid plugin (?), it's not about the plugin, it's about suid applications [1] (linux permissions) which do not work in minishift properly.


https://www.linuxnix.com/suid-set-suid-linuxunix/ .

**Comment by davidkarlsen** [comment] 2018-03-11 01:48
@LalatenduMohanty Are there any workarounds to the issue @mtttcgcg reported (I get Error from server (Forbidden): User "developer" cannot get securitycontextconstraints.security.openshift.io at the cluster scope: User "developer" cannot get securitycontextconstraints.security.openshift.io at the cluster scope (get securitycontextconstraints.security.openshift.io anyuid) - I have the same issue.

**Comment by LalatenduMohanty** [comment] 2018-04-19 05:02
@davidkarlsen sorry for the late reply. I am not aware of any workaround for this. Do you still face the issue?

**Comment by mtttcgcg** [comment] 2018-04-19 15:11
I never found a solution.

**Comment by FantomX1** [comment] 2018-04-29 22:26
`oc login -u system:admin -n default ` issuing this log-in as admin prior command sorts out all the issues and as follows I could  issue administrative command `oc adm policy add-scc-to-user anyuid -z default -n projectname` successfully, without the error message `... securitycontextconstraints.security.openshift.io at the cluster scope: User "developer"`

**Comment by praveenkumar** [comment] 2018-06-21 11:28
@mhabrnal does https://github.com/minishift/minishift/issues/2058#issuecomment-385286832 works for you? If yes then we might have to update our addon.

**Comment by praveenkumar** [comment] 2018-06-26 14:41
@davidkarlsen @mtttcgcg @xsuchy Can anyone of you folks let us know if https://github.com/minishift/minishift/issues/2058#issuecomment-385286832 works for you, if not we need to look much deeper?

**Comment by mtttcgcg** [comment] 2018-06-26 15:10
I would try to test, but first I need to get minishift working again on my machine (win 10/ hyperV). Cluster creation is failing due to https://github.com/minishift/minishift/issues/2279

**Comment by praveenkumar** [comment] 2018-06-26 15:25
@mtttcgcg please update to 1.20.0 and that would solve this issue for you I hope because now cluster up process is running in the VM.

**Comment by davidkarlsen** [comment] 2018-06-26 15:41
Not using openshift any longer so I can't tell.

**Comment by xsuchy** [comment] 2018-06-27 07:11
@praveenkumar I will let @mhabrnal to re-test this. But it will take few days to get to this.

**Comment by praveenkumar** [comment] 2018-06-27 13:56
@xsuchy Sure, since @mhabrnal filled this issue so we want to make sure if some action we required from our side.

**Comment by mhabrnal** [comment] 2018-07-03 14:08
@praveenkumar I followed instruction mentioned in issue's description and it still doesn't work.

I think you still don't understand the issue we've tried to explain with @xsuchy .
@mtttcgcg added a comment related to a totally different issue.

**Comment by anjannath** [comment] 2018-07-04 10:55
@mhabrnal  This not only reproducible in minishift but also on Openshift online. I suggest you file a bug in https://github.com/openshift/origin/issues .
```
$ oc projects
You have one project on this server: "lkdsjflslfdjsdkf".

Using project "lkdsjflslfdjsdkf" on server "https://api.starter-ca-central-1.openshift.com:443".

$ oc new-app mhabrnal/logger-test
--> Found Docker image b2d2381 (4 months old) from Docker Hub for "mhabrnal/logger-test"

    * An image stream will be created as "logger-test:latest" that will track this image
    * This image will be deployed in deployment config "logger-test"
    * The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/logger-test --port=[port]' later
    * WARNING: Image "mhabrnal/logger-test" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources ...
    imagestream "logger-test" created
    deploymentconfig "logger-test" created
--> Success
    Run 'oc status' to view your app.
$ oc get pods
NAME                  READY     STATUS    RESTARTS   AGE
logger-test-1-sgj9t   1/1       Running   0          28s
$ oc rsh logger-test-1-sgj9t
sh-4.4$ ls
bin  boot  dev	etc  home  lib	lib64  lost+found  media  mnt  opt  proc  root	run  sbin  srv	sys  tmp  usr  var
sh-4.4$ /usr/libexec/suid-logger 
Failed to open '/proc/1/fd/2' as root: Permission denied
sh-4.4$ echo "1" | /usr/libexec/suid-logger 
sh-4.4$ ls -l /usr/libexec/suid-logger      
-rwsr-xr-x. 1 root root 816080 Feb 26 15:09 /usr/libexec/suid-logger
sh-4.4$ ls -l /proc/1/fd/2             
l-wx------. 1 1050940000 root 64 Jul  4 10:40 /proc/1/fd/2 -> pipe:[1906988953]
```

**Comment by mhabrnal** [comment] 2018-07-04 16:08
@anjannath Ok, thank you, will dig little in deep in this issue.

**Comment by anjannath** [comment] 2018-07-10 09:58
Closing this as it is not minishift specific, https://github.com/openshift/origin/issues/20204#issuecomment-403145282

**Closed by anjannath** 2018-07-10 09:58 UTC
Labels: kind/bug, priority/major
