### ISSUE TITLE
Configuration is not preserved between multiple runs

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#1150] opened 2017-07-19 15:26 UTC
I have created a new VM instance, from scratch, with:

```
$ minishift start --vm-driver=virtualbox --openshift-version=v3.6.0-rc.0 --cpus=2 --memory=8192
Starting local OpenShift cluster using 'virtualbox' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.2/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [===================================================================================================================================================================================================] 100.00% 0s
Downloading OpenShift binary 'oc' version 'v3.6.0-rc.0'
 33.74 MiB / 33.74 MiB [===================================================================================================================================================================================================] 100.00% 0s
Starting OpenShift using openshift/origin:v3.6.0-rc.0 ...
Pulling image openshift/origin:v3.6.0-rc.0
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 64% complete
Pulled 3/4 layers, 77% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.100:8443

You are logged in as:
    User:     developer
    Password: [any value]

To login as administrator:
    oc login -u system:admin

-- Applying addon 'admin-user':..
```

Then I have stopped, and started again, but this time without flags, as the VM is already created:

```
$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
Downloading OpenShift binary 'oc' version 'v1.5.1'
 18.94 MiB / 18.94 MiB [===================================================================================================================================================================================================] 100.00% 0s
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ...
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.5.1 image ...
   Pulling image openshift/origin:v1.5.1
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 63% complete
   Pulled 2/3 layers, 98% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.99.100 as the server IP
-- Starting OpenShift container ... FAIL
   Error: Docker run error rc=2
   Details:
     Image: openshift/origin:v1.5.1
     Entrypoint: [/bin/bash]
     Command: [-c for name in 192.168.99.100 minishift; do ls /var/lib/origin/openshift.local.config/node-$name &> /dev/null && echo $name && break; done]

OpenShift provisioning failed. origin container failed to start.
```

Configuration should be preserved. Either there should be a config file for the instance with the configuration with which was initially started, or should just use whatever the VM has, without passing additional parameters.

**THIS IS A BLOCKER ISSUE FOR ME**

**Comment by praveenkumar** [comment] 2017-07-20 02:33
@jorgemoralespou if you want to preserve those options then you need to set it using config so it persistent across run. We currently don't have any way to preserve start options if those mentioned explicit using arguments.

```
$ ./minishift config set openshift-version v3.6.0-rc.0
$ ./minishift config set vm-driver virtualbox
$ ./minishift config set cpus 2
$ ./minishift config set memory 8192

$ ./minishift config view
- cpus                 : 2
- memory               : 8192
- openshift-version    : v3.6.0.rc.0
- vm-driver            : virtualbox
```

**Comment by jorgemoralespou** [comment] 2017-07-20 06:02
@praveenkumar, I understand the current state and limitation, and I think it's a usability issue

**Comment by gbraad** [comment] 2017-07-20 06:07
which we could solve by including a `--save-config` option maybe? note: config is currently for all instances, and not instance specific, and is therefore not related to the instance that was started.

**Comment by jorgemoralespou** [comment] 2017-07-20 06:15
I would prefer not to have an additional flag. People is used to how tools
like vagrant work. If you look into it, the first time a VM is created it
gets all the flags and does the provisioning. Then it just starts the VM.
In casa new flags need to be provided (which is the less frequent use
case), then you can pass a flag to --provision.

Usability is about having the most used use case using the less flags and
being the easier the possible.

With the multiple profile there is a need to have a global and a local
config files. Maybe this should not be solve until then, or can be
currently easily solved. Up to you, although I would prefer not to delay
that work as I think many things will be solved as part of that work.

**Comment by gbraad** [comment] 2017-07-20 06:26
Agree with the usability aspect... so maybe we have to look into this as part of the multiple instances, and maybe follow-up with this task after that work is done.

I also believe this is a duplicate of #179... Is this correct?

**Comment by jorgemoralespou** [comment] 2017-07-20 06:37
Not in the initial characterization of the issue, but then the discussion
deviates to this same issue. I guess we can close it here.

**Closed** 2017-07-20 06:37 UTC

**Comment by gbraad** [comment] 2017-07-20 06:40
I believe the title of #179 is now slightly misleading, as noted the discussion does mention the preservation of configuration options, such as ISO, memory, etc. This mention has created a link and duplication tag on that issue
