### ISSUE TITLE
Missing web-console when using openshift-version v3.9.0

### ISSUE THREAD

**Issue by vinicius-martinez** [minishift/minishift#2639] opened 2018-07-29 04:04 UTC
### General information

  * Minishift version: v1.21.0+a8c8b37
  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. Start minishift using openshift-version v3.9.0: minishift start --openshift-version v3.9.0
  2. Try to access OCP webconsole (example): https://192.168.64.3:8443/console

### Expected

Openshift webconsole should be displayed

### Actual

When trying to access Openshift Console, the following error shows up:

**missing service (service "webconsole" not found)
missing route (service "webconsole" not found)**

vmartine][skylab][~]
└─▪ curl -k https://192.168.64.3:8443/console
missing service (service "webconsole" not found)
missing route (service "webconsole" not found)

It looks like the webconsole pod is not deployed/missing as well as it's namespace/project:

┌─[vmartine][skylab][~]
└─▪ oc get pods --all-namespaces -o wide
NAMESPACE   NAME                            READY     STATUS      RESTARTS   AGE       IP             NODE
default     docker-registry-1-2trnn         1/1       Running     1          12m       172.17.0.2     localhost
default     persistent-volume-setup-r55wg   0/1       Completed   0          14m       172.17.0.3     localhost
default     router-1-7f72l                  1/1       Running     1          12m       192.168.64.3   localhost

─[vmartine][skylab][~]
└─▪ oc get project -o wide
NAME              DISPLAY NAME   STATUS
default                          Active
kube-public                      Active
kube-system                      Active
myproject         My Project     Active
openshift                        Active
openshift-infra                  Active
openshift-node                   Active

### Logs

Full logs available on:

- https://gist.github.com/vinicius-martinez/48722af990b99d6122995eedd6b5ead6
- https://gist.github.com/vinicius-martinez/907d4793d7e2a67c00f75a4dc1f50a28

**Comment by praveenkumar** [comment] 2018-07-30 08:50
@vinicius-martinez Is it reproducible for you? Can you try to do `minishift delete` and `minishift start` again?

**Comment by praveenkumar** [comment] 2018-07-31 04:50
Also, check https://bugzilla.redhat.com/show_bug.cgi?id=1608505 looks like there is a bug already filed against it.

**Comment by gbraad** [comment] 2018-08-01 02:58
Is this reproducible? Do not see the same behaviour

**Comment by amitkrout** [comment] 2018-08-02 10:53
Unable to reproduce it on latest minishift release [v1.22.0](https://github.com/minishift/minishift/releases/tag/v1.22.0)

**Comment by vinicius-martinez** [comment] 2018-08-04 00:44
Ho @praveenkumar, thanks for jumping in.

I don't believe this is the same issue/bug because in my case, both pod and even the openshift webconsole namespace is not deployed, therefore, i think it must be something wrong with the ansible playbook maybe ? How can I debug/trace/view the playbook that is used to deploy OCP ?

┌─[vmartine][skylab][~]
└─▪ oc get pods --all-namespaces
NAMESPACE   NAME                            READY     STATUS      RESTARTS   AGE
default     docker-registry-1-2trnn         1/1       Running     5          5d
default     persistent-volume-setup-r55wg   0/1       Completed   0          5d
default     router-1-7f72l                  1/1       Running     5          5d

─[vmartine][skylab][~]
└─▪ oc get project
NAME              DISPLAY NAME   STATUS
default                          Active
kube-public                      Active
kube-system                      Active
myproject         My Project     Active
openshift                        Active
openshift-infra                  Active
openshift-node                   Active

**Comment by vinicius-martinez** [comment] 2018-08-04 00:59
Hi @amitkrout , you're right. After updating minishift to the latest version, everything seems to work just fine.

─[vmartine][skylab][~]
└─▪ minishift version
minishift v1.22.0+7163416
┌─[vmartine][skylab][~]
└─▪ minishift config view
- iso-url                            : centos
- memory                             : 6144
- openshift-version                  : v3.9.0
- vm-driver                          : xhyve
┌─[vmartine][skylab][~]
└─▪ oc get pods --all-namespaces
NAMESPACE               NAME                            READY     STATUS      RESTARTS   AGE
default                 docker-registry-1-r2z6t         1/1       Running     0          6m
default                 persistent-volume-setup-qwwh6   0/1       Completed   0          6m
default                 router-1-vxn4d                  1/1       Running     0          6m
openshift-web-console   webconsole-7dfbffd44d-rsccx     1/1       Running     0          6m

**Comment by amitkrout** [comment] 2018-08-14 16:28
@vinicius-martinez I am not able to reproduce it on minishift v1.21.0 too. Might be some temporary issue you faced that moment. As of now i am closing the issue, will reopen it or create a new one if this occurs again and again.

**Closed by amitkrout** 2018-08-14 16:28 UTC
Labels: kind/bug, priority/minor
