### ISSUE TITLE
Add support for creating resources on start

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#29] opened 2016-07-19 12:51 UTC
it'd be awesome if we could easily do a `minishift start` which would automatically install fabric8 as well; using a command line flag maybe? 

We could maybe get gofabric8 to generate a big blob of YAML we could use to install everything or something to minimise the extra code required inside minishift

**Comment by jimmidyson** [comment] 2016-07-20 08:29
I'm thinking that there should be a flag/config that you can set to create resources on startup. This will let us just use this to install fabric8 from the packaged apps, while at the same time not making it specific to fabric8. What do you think?

**Comment by jstrachan** [comment] 2016-07-20 09:46
its worth a try; even just getting a single blob of resources to create is kinda complex right now (its really about 5 different independent tarballs of yaml files). Maybe whenever any part of fabric8 gets released, we need to re-release the 'big ass YAML file' used by minishift/minikube to install fabric8?

**Comment by jimmidyson** [comment] 2016-07-20 09:50
Can't that just be a single package, ala management package in devops?

**Comment by jimmidyson** [comment] 2016-07-20 09:50
If we can also link to latest somehow, perhaps with a custom service on fabric8.io subdomain then we can point to that for install?

**Comment by jstrachan** [comment] 2016-07-20 09:54
I guess we can have an uber-package which is regenerated whenever an upstream dependency is released. Agreed on the point-to-latest idea; that'd simplify things greatly.

It'd also mean folks could use `kubectl apply -f http://get.fabric8.io/` or whatever the canonical URL is. We could create one for kubernetes + one for openshift to make things easier for the installer.

Right now we need to parameterise things by namespace (e.g. so that the global SCC's generated don't overwrite each other if you install fabric8 into different namespaces) so we maybe wanna add a namespace parameter to the URL

**Comment by jstrachan** [comment] 2016-07-20 09:56
I'm sure there's loads of devils in the details too btw; e.g. we need to parameterise the domain too (e.g. for github's external links), or whether or not we should create Ingress or Routes etc

**Comment by jorgemoralespou** [comment] 2016-07-21 07:14
@jimmidyson I think this is a good thing to generalize, since there will be people wanting to use minishift not only for fabric8 but maybe to also do workshops/demos with minishift which could create their own packages that could be shared.

**Comment by hferentschik** [comment] 2017-01-09 15:28
I guess this is related / a duplicate of issue #59

**Comment by budhrg** [comment] 2017-03-09 12:55
This is related to #177  and might be duplicate it too. @hferentschik please confirm and do the needful action.

**Comment by budhrg** [comment] 2017-03-30 09:25
@hferentschik ,  reminding you again for needful action.

**Comment by hferentschik** [comment] 2017-05-10 09:01
I think this customisation of Minishift at startup is now provided via add-ons. Also there is issue #860 to create an add-on for Fabric8. 

Going to close this issue in favour of #860.

**Closed by hferentschik** 2017-05-10 09:01 UTC
Labels: kind/feature, priority/major
