### ISSUE TITLE
Improve preflight check message for Hyper-V virtual switch

### ISSUE THREAD

**Issue by FrederikBrinckTruelsen** [minishift/minishift#1256] opened 2017-08-10 07:30 UTC
Minishift 1.4.1
Windows 10 PRO
Virtualization: Hyper-V

I run minishift start and get the following error message
```
-- Checking if Hyper-V driver is configured ... FAIL
   Hyper-V virtual switch is not set
```

**Comment by budhrg** [comment] 2017-08-10 07:34
@FrederikBrinckTruelsen , Could you add logs by running `minishift start --show-libmachine-logs -v 5` ?

**Comment by FrederikBrinckTruelsen** [comment] 2017-08-10 07:36
@budhrg  gives the exactly the same result

**Comment by FrederikBrinckTruelsen** [comment] 2017-08-10 07:40
I tried minishift start --vm-driver=virtualbox and I get the following error 

Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.

I cannot get this flag to work as I get Error: unknown flag: --virtual-no-vtx-back

**Comment by budhrg** [comment] 2017-08-10 07:46
> Error with pre-create check: "This computer is running Hyper-V. 

This means you are using HyperV. Could you able to join #minishift in IRC freenode with irc client or use https://webchat.freenode.net/ ?

**Comment by budhrg** [comment] 2017-08-10 07:46
This is a weird issue so would like to go little deep.

**Comment by gbraad** [comment] 2017-08-10 07:46
did you set the environment variable as mentioned in the installation guide?
https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-driver-plugin.adoc#hyper-v-driver

**Comment by budhrg** [comment] 2017-08-10 07:47
> https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-driver-plugin.adoc#hyper-v-driver

+1

Have you created virtual switch ?

**Comment by gbraad** [comment] 2017-08-10 07:50
We do not support using DockerNAT (see #418), so you need to create an external virtual switch and set the configuration accordingly

**Comment by gbraad** [comment] 2017-08-10 07:51
Note: I guess the error message should refer to the Driver plugin install guide, just like the other errors.

**Comment by budhrg** [comment] 2017-08-10 07:53
> Note: I guess the error message should refer to the Driver plugin install guide, just like the other errors.

:+1:

**Comment by gbraad** [comment] 2017-08-10 07:53
@dgolovin How does the installer handle the Virtual Switch for Hyper-V?

**Comment by gbraad** [comment] 2017-08-10 08:22
OP suggested that the message might also need to be "Hyper-V external virtual switch is not set".

**Comment by FrederikBrinckTruelsen** [comment] 2017-08-10 08:24
The issue got resovled  by adding and external switch and set HYPERV_VIRTUAL_SWITCH

**Comment by gbraad** [comment] 2017-08-10 08:26
I'll leave the issue open to deal with the message and the documentation around this. Will be minor, but hopefully will prevent this in the future ;-)

**Comment by gbraad** [comment] 2017-08-10 15:56
* [ ] Change documentation to show `C/:>` or `PS>` for the Windows+HyperV entry for the preflight checks
 * [ ] Change message in code to include `external` and refer to Drive plugin guide
 * [ ] See if we can mention DockerNAT for not being a valid option (unsure)

**Comment by budhrg** [comment] 2017-08-10 16:00
> See if we can mention DockerNAT for not being a valid option (unsure)

For this, we need to detect if DockerNAT switch is present or not.

I think, we can do this, 
- Check the available list of switch
- If first is not external switch, then check environment variable.
- If environment variable is not set, then inform user to set environment variable to external switch

**Comment by gbraad** [comment] 2017-08-10 16:16
@budhrg We can check, but I'd rather not want to activate PowerShell to perform `get-vmswitch` by ourselves. This is mostly duplicating what libmachine does.

In https://github.com/minishift/minishift/issues/485#issuecomment-314679696 I also mentioned to check if HyperV was installed in the first place. This hasn;t been implemented as it seems to duplicate efforts. Also, this is something the Installer will do.

BTW, this is what libmachine does:

  * Check if a switch exists 
    https://github.com/docker/machine/blob/master/drivers/hyperv/hyperv.go#L268
  * if so, the first is returned when non is specified  
    https://github.com/docker/machine/blob/master/drivers/hyperv/hyperv.go#L273
  * if specified, we will try to get this by name  
    https://github.com/docker/machine/blob/master/drivers/hyperv/hyperv.go#L277  
    else error
    https://github.com/docker/machine/blob/master/drivers/hyperv/hyperv.go#L285

**Comment by gbraad** [comment] 2017-08-10 16:18
The goal would be not to need an external switch in the first place, as an internal or NAT based one is more resilient to the changing IP problem we are having.

Not sure if the effort is best spent on refining the test or fixing the underlying problem. ;-)

**Comment by lucastheisen** [comment] 2017-08-17 16:37
@gbraad , not supporting NAT is one of the 2 things that is preventing my team from adopting minishift over docker for development (the other is docker command uses npipe which gets around corporate vpn routing problems)...  I would love to see any effort going toward implementing NAT rather than detecting it to let us know it doesnt work.  Thanks for all the hard work on this.

**Comment by gbraad** [comment] 2017-08-17 17:04
@lucastheisen please upvote #418

**Comment by hferentschik** [comment] 2017-08-21 07:34
> We can check, but I'd rather not want to activate PowerShell to perform get-vmswitch by ourselves. This is mostly duplicating what libmachine does.

Why not? As you show in you links libmachine does it as well. However, it has the behaviour you describe. This was one of the driving forces for #739 and making sure custom driver options can be picked up from the environment.

If libmachine is not exporting the low level functions to deal with Hyper-V configuration (query and configure it), I don't see an issue to create our own utility functions.

**Comment by gbraad** [comment] 2017-08-21 08:07
However, yes... The reason why I am a little skeptical about adding a test to check the selected switch, is because the real problem here is not the detection, but the support we have for Hyper-V. Sure, we could break execution and inform that the user has no "external switch"... however, as mentioned... I'd rather see us working on NAT support. If that task seems to take more time than expected, we can defer and work on the detection more.

**Comment by hferentschik** [comment] 2017-08-21 08:20
> Sure, we could break execution and inform that the user has no "external switch"... however, as mentioned... I'd rather see us working on NAT support

I get that part. I agree that if possible working NAT would be nicer.

**Comment by gbraad** [comment] 2017-09-13 07:51
Partially addressed with #1373

**Comment by manh2000** [comment] 2017-10-11 18:21
I experience the same error when starting up the minishift using the command "manishift start --vm-driver=virtualox".  I have tried to disable/uninstall Hyper-V and still getting this error. This is part of the CDK installation and setup that I follow (https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.1/html-single/getting_started_guide/index).

This setup is within a Windows Server 2016 VM and Oracle VM VirtualBox was installed. One big issue that I experienced is that if I enable Hyper-V and run the Vagrant "vagrant up", most of the time the VM crashes; therefore, using Hyper-V will not work for me, and rather rely on VirtualBox. Thanks.

The error:
E1011 10:44:35.107582     380 start.go:282] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.

**Comment by softandbyte** [comment] 2017-10-16 18:35
I encounter the same issue, hope following log be helpfull

PS C:\Users\Sven.Blommaert\Downloads\minishift-1.7.0-windows-amd64> .\minishift.exe start --show-libmachine-logs -v 5 --vm-driver virtualbox
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at C:\Users\Sven.Blommaert\Downloads\minishift-1.7.0-windows-amd64\minishift.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51765
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
(minishift) Calling .SetConfigFromFlags
(minishift) Trying to access option engine-install-url which does not exist
Running pre-create checks...
(minishift) Calling .PreCreateCheck
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) DBG | COMMAND: C:\Apps\Oracle\VirtualBox\VBoxManage.exe --version
(minishift) Type assertion did not go smoothly to string for key engine-install-url
(minishift) Trying to access option swarm-master which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to bool for key swarm-master
(minishift) Trying to access option swarm-host which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-host
(minishift) Trying to access option swarm-discovery which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-discovery
(minishift) Type assertion did not go smoothly to bool for key virtualbox-host-dns-resolver
(minishift) Type assertion did not go smoothly to bool for key virtualbox-hostonly-no-dhcp
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-share
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | 5.1.12r112440
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-dns-proxy
(minishift) Type assertion did not go smoothly to bool for key virtualbox-no-vtx-check
(minishift) DBG | }
(minishift) DBG | STDERR:
(minishift) DBG | {
(minishift) DBG | }
(minishift) DBG | COMMAND: wmic computersystem get hypervisorpresent
(minishift) DBG | STDOUT:
(minishift) DBG | {
(minishift) DBG | HypervisorPresent
(minishift) DBG | TRUE
(minishift) DBG |
(minishift) DBG | }
. FAIL E1016 20:30:20.909392   15784 start.go:355] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is
activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disab
le the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
PS C:\Users\Sven.Blommaert\Downloads\minishift-1.7.0-windows-amd64>

**Comment by gbraad** [comment] 2017-10-24 07:52
@softandbyte you still have HyperV enabled
```
. FAIL E1016 20:30:20.909392 15784 start.go:355] Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is
activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disab
le the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
```

**Comment by xqianwang** [comment] 2017-12-05 19:42
`(minishift) DBG | [stderr =====>] :
(minishift) DBG | Writing magic tar header
(minishift) DBG | Writing SSH key tar header
(minishift) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Convert-VHD -Path 'C:\Users\xqian\.minishift\machines\minishift\fixed.vhd' -DestinationPath 'C:\Users\xqian\.minishift\machines\minishift\disk.vhd' -VHDType Dynamic -DeleteSource
(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Resize-VHD -Path 'C:\Users\xqian\.minishift\machines\minishift\disk.vhd' -SizeBytes 20000MB
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] :
(minishift) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive New-VM minishift -Path 'C:\Users\xqian\.minishift\machines\minishift' -SwitchName 'NATSwitch' -MemoryStartupBytes 8192MB
.(minishift) DBG | [stdout =====>] :
(minishift) DBG | [stderr =====>] : New-VM : Sequence contains more than one element
(minishift) DBG | At line:1 char:1
(minishift) DBG | + New-VM minishift -Path 'C:\Users\xqian\.minishift\machines\minishift' ...
(minishift) DBG | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(minishift) DBG |     + CategoryInfo          : InvalidOperation: (:) [New-VM], VirtualizationException
(minishift) DBG |     + FullyQualifiedErrorId : InvalidOperation,Microsoft.HyperV.PowerShell.Commands.NewVM`

**Comment by gbraad** [comment] 2018-07-12 11:08
Closing as comments have been off-topic.

**Closed by gbraad** 2018-07-12 11:08 UTC
Labels: component/hyperv, kind/bug, os/windows, priority/minor
