### ISSUE TITLE
Che workspace like Python, PHP ... deployment fails

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2973] opened 2018-11-05 06:46 UTC
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. make integration GODOG_OPTS="-tags addon-che"
  2. 
  3. 
  4. 

### Expected
Should go through

### Actual
Fails - https://ci.centos.org/job/minishift-nightly-centos/328/consoleFull
           https://ci.centos.org/job/minishift-nightly-centos/329/consoleFull

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by amitkrout** [comment] 2018-11-05 06:52
@agajdosi ^

**Comment by amitkrout** [comment] 2018-11-05 07:56
I am not able to reproduce it locally, however the same issue is hit twice [1] [2] in CI.

[1]  https://ci.centos.org/job/minishift-nightly-centos/328/consoleFull
[2] https://ci.centos.org/job/minishift-nightly-centos/329/consoleFull

**Comment by agajdosi** [comment] 2019-01-28 14:09
Changed the order of workspaces to see whether it is bound to particular workspaces and it seems that it is not - if VertX is 1st it is OK, however when it is 2nd, then it fails. Similar with Java CentOS which on 2nd place fails, but on 1st is OK.

Printed the workspace info to console and found this statement in the JSON:
`"attributes":{"errorMessage":"Operation: [create]  for kind: [PersistentVolumeClaim]  with name: [null]  in namespace: [mini-che]  failed."`

Was not able to found any relevant issue, but as the issue happens only on some machines, I am trying now to put a sleep between each deployments to see whether that helps.

**Comment by agajdosi** [comment] 2019-01-28 16:44
Persistent volume claim problem is now gone with 60s sleep between workspace deployments, however there is a new problem:

```
"attributes":{"errorMessage":"Waiting for Kubernetes environment \u0027default\u0027 of the workspace\u0027workspacemw2wn3tfqnt80fb5\u0027 reached timeout"
```

**Comment by agajdosi** [comment] 2019-01-30 13:17
Even with higher timeout the workspaces are not able to start consistently. I've added more debug outputs and found out that the first workspace is not properly deleted. Even though Che API confirms it is deleted, the `oc` says something slightly different (Vert.X workspace is running for 40 minutes even though it was deleted 3 workspace deployments ago):

```
12:54:41       | CentOS WildFly Swarm | https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http |
12:54:41         time limit (10m) exceeded: workspace did not get into state 'RUNNING', current state: '{STOPPED}'

12:55:44 NAME                                                    READY     STATUS    RESTARTS   AGE
12:55:44 che-1-xfrfl                                             1/1       Running   0          44m
12:55:44 workspacen79p9px0dkcauptp.dockerimage-bb48dcd64-6k5gc   1/1       Running   0          40m
```

The Che logs shows that the error occurs probably during the stop, maybe a deployment config then is still present and thus killed node is redeployed after the deletion? Here's the log:

```
12:33:23 2019-01-30 12:20:35,731[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 473]   - Workspace 'che/vert.x-stack-test' with id 'workspacen79p9px0dkcauptp' is stopping by user 'che'
12:33:23 2019-01-30 12:20:46,801[aceSharedPool-1]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 536]   - Error occurred during stopping of runtime 'workspacen79p9px0dkcauptp:default:che' by user 'che'. Error: Error(s) occurs while cleaning up the namespace. Operation: [patch]  for kind: [Deployment]  with name: [workspacen79p9px0dkcauptp.dockerimage]  in namespace: [mini-che]  failed.
12:33:23 org.eclipse.che.api.workspace.server.spi.InfrastructureException: Error(s) occurs while cleaning up the namespace. Operation: [patch]  for kind: [Deployment]  with name: [workspacen79p9px0dkcauptp.dockerimage]  in namespace: [mini-che]  failed.
12:33:23 	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:192)
12:33:23 	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:100)
12:33:23 	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:619)
12:33:23 	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:177)
12:33:23 	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:506)
12:33:23 	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
12:33:23 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
12:33:23 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:33:23 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:33:23 	at java.lang.Thread.run(Thread.java:748)
12:33:23 2019-01-30 12:20:51,497[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 274]    - Workspace 'workspacen79p9px0dkcauptp' removed by user 'che'
```

**Comment by agajdosi** [comment] 2019-02-01 11:08
Tried to secure the deletion of deployment and pvc by adding oc commands, however all oc commands fails:
```
Command 'get pod -l app=che -o NAME' did not execute successfully. cmdExit: 1, cmdErr: error: You must be logged in to the server (Unauthorized)
```

It was fixed by adding 60 second sleep after the deletion of workspace => seems like some components of OpenShift are down at that time? Might that be the reason for the failures on Che side?

**Comment by agajdosi** [comment] 2019-02-12 10:48
Issue is no longer reproducible with and without anyuid addon enabled.

**Closed** 2019-02-26 16:19 UTC
Labels: component/integration-test, kind/bug, priority/major
