### ISSUE TITLE
Unable to Start minishift

### ISSUE THREAD

**Issue by as0077749** [minishift/minishift#920] opened 2017-05-18 11:52 UTC
Have tried to install and and start the minishift locally on Ubuntu system but it giving me below error while start, have followed below steps.
1 - Installed docker
2 - Placed minishift in PATH
3 run "minishift start --vm-driver=virtualbox"

Now I am getting below error
-------------------------------------------------------
_root@INPUHJPC09049:~# minishift start --vm-driver=virtualbox_
Starting local OpenShift cluster using 'virtualbox' hypervisor...
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     Ensure that Docker is installed and accessible in your environment.
     Use your package manager or follow instructions at:

        https://docs.docker.com/linux/

   Caused By:
     Error: Get https://192.168.99.106:2376/_ping: Tunnel or SSL Forbidden
Error starting the cluster.
----------------------------------------------------------------------------------------------
Have checked the minishift status and its showing running
Even tried with minishift ssh to check docker, it also working.

Now i got stuck here to proceed further, please suggest what to do next.

Thanks,
Ashish Singh

**Comment by LalatenduMohanty** [comment] 2017-05-22 08:50
Seems like  the setup is broken somehow. Is this the first time you are running minishift or it had worked for you before. I would suggest a clean uninstall and then you should try it again.

**Comment by as0077749** [comment] 2017-05-22 11:50
thanks Mohanty fro response,

Yes this is first time I am using minishift, have tried to clean delete and uninstall minishift but still problem is same.

Please suggest.
Ashish Singh

**Comment by kiranhk** [comment] 2017-05-22 17:20
I am getting the same error. I am on OSX 10.12.4. 

Using minishift for the first time. I tried deleting and installing it multiple times but the error is coming. Also tried with both xhyve and virtualbox, both give the same error.

minishift start --vm-driver=virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     To create a new Docker machine to run OpenShift, run this command again with
     the --create-machine argument. This will create a Docker machine named
     'openshift'.

     To use a different machine name, specify the --machine-name=NAME argument.

     If you wish to use an existing Docker machine, enable it before running this
     command by executing:

        eval $(docker-machine env NAME)

     where NAME is the name of your Docker machine.

   Caused By:
     Error: Get https://192.168.99.104:2376/_ping: net/http: TLS handshake timeout
Error starting the cluster.

**Comment by as0077749** [comment] 2017-05-24 07:45
Still i am facing the same issue, below are few more information's.
-------------------------------------------------
- getent group docker
         docker:x:999:ashish,root
- docker version
                 Client:
                           Version:      17.05.0-ce
                           API version:  1.29
                           Go version:   go1.7.5
                           Git commit:   89658be
                           Built:        Thu May  4 22:10:54 2017
                           OS/Arch:      linux/amd64

                 Server:
                           Version:      17.05.0-ce
                           API version:  1.29 (minimum version 1.12)
                          Go version:   go1.7.5
                          Git commit:   89658be
                          Built:        Thu May  4 22:10:54 2017
                          OS/Arch:      linux/amd64
                          Experimental: false
-  docker-machine env
        export DOCKER_TLS_VERIFY="1"
        export DOCKER_HOST="tcp://192.168.99.107:2376"
        export DOCKER_CERT_PATH="/root/.docker/machine/machines/default"
        export DOCKER_MACHINE_NAME="default"
        # Run this command to configure your shell:
        # eval $(docker-machine env)

--------------------------------------------------------
Now i am getting below error.
--------------------------------------------------------
minishift --show-libmachine-logs  start
Starting local OpenShift cluster using 'kvm' hypervisor...
(minishift) Check network to re-create if needed...
(minishift) Waiting for an IP...
Waiting for SSH to be available...
Detecting the provisioner...
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     Ensure that Docker is installed and accessible in your environment.
     Use your package manager or follow instructions at:

        https://docs.docker.com/linux/

   Caused By:
     Error: Get https://192.168.99.107:2376/_ping: Tunnel or SSL Forbidden
Error starting the cluster.

Now i am stuck here, any suggestions.

**Comment by hferentschik** [comment] 2017-05-24 07:51
Do you have any system proxies enabled or any other firewall rules in place which would prevent to connect to Docker via  192.168.99.107?

**Comment by as0077749** [comment] 2017-05-24 08:00
Yes we do have system proxy here.

**Comment by hferentschik** [comment] 2017-05-24 08:08
This is most likely the issue. I assume you export HTTP_PROXY in your environment. The Docker verification checks uses HTTP to try to connect to the Docker daemon. The default Go implementation does per default honour proxy settings defined in your environment. This means the check goes via the proxy which won't be able to deal with the VM IP. 

Actually there is a bug in Minishift related to this, but it should be fixed by pull request #942

You probably can work around this for now by adding the VM IP to the no proxy list:

    export NO_PROXY="192.168.99.107"

Pull request #942 will take care of this transparently.

**Comment by hferentschik** [comment] 2017-05-24 08:09
@as0077749, could you please let me know whether the workaround works?

**Comment by hferentschik** [comment] 2017-05-24 08:17
@as0077749, actually since you are in a proxied environment, you will also have to explicitly use the --http-proxy and --https-proxy flags of the start command. The workaround mentioned will most likely get you past the Docker daemon check, but Docker and OpenShift need the proxy settings as well and at the moment they are only taking the command line switches into consideration. One cpu;d argue that we should honour system settings here as well.

**Comment by as0077749** [comment] 2017-05-24 10:24
Now followed below steps
------------------------------------------
 - minishift stop
              Stopping local OpenShift cluster...
         Cluster stopped.

- minishift delete
         Deleting the Minishift VM...
         Minishift VM deleted.

- docker-machine env openshift
- docker-machine regenerate-certs openshift

- docker-machine ls
          NAME        ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
          default     -        virtualbox   Running   tcp://192.168.99.107:2376           v17.05.0-ce
          openshift   -        virtualbox   Running   tcp://192.168.99.109:2376           v17.05.0-ce

-  minishift start --vm-driver=virtualbox --docker-env=openshift --http-proxy=XX.XXX.XX.XXX:8080 --https-proxy XX.XXX.XX.XXX:8080

               Starting local OpenShift cluster using 'virtualbox' hypervisor...
               -- Checking OpenShift client ... OK
               -- Checking Docker client ... FAIL
             Error: cannot communicate with Docker
             Solution:
                    Ensure that Docker is installed and accessible in your environment.
                    Use your package manager or follow instructions at:
                 https://docs.docker.com/linux/
           Caused By:
           Error: Get https://192.168.99.114:2376/_ping: Tunnel or SSL Forbidden
           Error starting the cluster.

I can see this time minishift is not using existing docker machine(Name - Open shift) IP

**Comment by hferentschik** [comment] 2017-05-24 10:31
btw, you should not be creating a docker-machine instance (or you don't have to). Minishift is using libmachine under the hood, but it creates its own VM independently of the docker-machine managed VMs. That you are creating and exporting environment settings for docker-machine instance is irrelevant here. OOI, how come that you think it is required?

Regarding the start command, it is basically ok, but as mentioned before, there is currently a bug which means that Minishift tries to reach your VM via the proxy which will fail, hence my suggestion to use --no-proxy as well.

> I can see this time minishift is not using existing docker machine(Name - Open shift) IP

It is not. It creates its own, in its own MINISHIFT_HOME directory.

**Comment by as0077749** [comment] 2017-05-24 11:19
Have tried with no proxy and still problem is same.
------------------------------------------------------------------------
-minishift start --vm-driver=virtualbox  --no-proxy=192.168.99.116

     Starting local OpenShift cluster using 'virtualbox' hypervisor...
      -- Checking OpenShift client ... OK
      -- Checking Docker client ... FAIL
     Error: cannot communicate with Docker
     Solution:
      Ensure that Docker is installed and accessible in your environment.
      Use your package manager or follow instructions at:
      https://docs.docker.com/linux/
     Caused By:
       Error: Get https://192.168.99.116:2376/_ping: Tunnel or SSL Forbidden
       Error starting the cluster.

**Comment by go101** [comment] 2017-06-01 09:18
same problem for me.
Debian amd64.

**Comment by as0077749** [comment] 2017-06-01 11:18
yes I am also stuck with same problem :(

**Comment by aberhallo** [comment] 2017-06-28 20:59
Me too (on a Windows 7 system)

**Comment by john30** [comment] 2017-07-13 06:14
had the same problem. basically a newly assigned IP address from virtualbox dhcp was the root cause. solved by forcing a fix address as stated here:
https://github.com/minishift/minishift/issues/343#issuecomment-314117881

**Comment by hferentschik** [comment] 2017-08-22 07:31
Closing this since there was not more info.

**Closed by hferentschik** 2017-08-22 07:31 UTC
Labels: kind/bug, priority/major
