### ISSUE TITLE
Add a new verification method to test port range for sshfs

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#2136] opened 2018-03-15 08:57 UTC
Currently, we are testing port defined for sshfs as a positve value but this check should be defined a range of port which is allowed 1024-65536 so that we can tell user at early stage about which port should be used for config.

**Comment by anjannath** [comment] 2018-03-16 13:44
Looks like this is a duplicate of #2125, as both has the same purpose of verifying the port number for sftp server. am i right @praveenkumar ?

**Comment by budhrg** [comment] 2018-03-18 07:53
@anjannath @praveenkumar Yes it seems to be.

**Comment by gbraad** [comment] 2018-03-18 15:46
Closing and adding comments to the other issue

**Closed by gbraad** 2018-03-18 15:46 UTC
Labels: component/hostfolder, kind/task, priority/major
