### ISSUE TITLE
Automatic version upgrade is broken

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#204] opened 2016-12-20 11:47 UTC
OC : MacOS El Capitan - 10.11.6

```
minishift start
Starting local OpenShift cluster...
Downloading ISO
 36.00 MB / 36.00 MB [========================================================================================================================================================================================] 100.00% 0s
E1220 12:44:16.250063    2462 start.go:130] Error starting host: Error creating. Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
```

**Comment by astefanutti** [comment] 2016-12-20 12:04
Maybe a duplicate of #110 and #160.

**Comment by hferentschik** [comment] 2016-12-20 12:56
@cmoulliard which hypervisor are you trying to target? VirtualBox or xhyve? Can you try with an explicit --vm-driver option

     $ minishift start --vm-driver [virtualbox|xhyve]

Also, if you are using xhyve, make sure to get the latest release. 

Last but not least, make sure to call `minishift delete` prior to starting or even more aggressively delete the _~/.minishift_ directory.

**Comment by hferentschik** [comment] 2016-12-20 14:30
@cmoulliard btw, the default on OS X is the xhyve hypervisor. Is this what you want to use?

**Comment by cmoulliard** [comment] 2016-12-20 16:56
yes xhyve hypervisor.

**Comment by astefanutti** [comment] 2016-12-20 17:04
@cmoulliard I faced the same issue and reinstalled / upgraded xhyve and docker-machine-driver-xhyve and it worked for me.

**Comment by cmoulliard** [comment] 2016-12-21 08:25
I experiment a new problem now

```
minishift start
There is a newer version of minishift available. Do you want to
automatically update from v0.9.0 to v1.0.0-beta.1 now? [y/N] y
Updating to version 1.0.0-beta.1
Downloading updated binary checksum to validate updated binary
E1221 09:07:44.140066    9558 update.go:155] Cannot download checksum: received 404
```

**Comment by jimmidyson** [comment] 2016-12-21 08:46
See https://github.com/minishift/minishift/blob/6b83d570d5f3c4b5f1680dc436f236c018146344/pkg/minikube/update/update.go#L48

**Comment by LalatenduMohanty** [comment] 2016-12-21 09:02
@cmoulliard for workaround you can download the latest binary from https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.1 and use it and it will work.

**Comment by LalatenduMohanty** [comment] 2016-12-21 09:09
The update process from 0.9.0 to 1.0.0-beta1 is broken as @cmoulliard  @jimmidyson mentioned.

`
Lalatendus-MacBook-Pro:minishift_090 lmohanty$ ./minishift version
minishift version: 0.9.0
Lalatendus-MacBook-Pro:minishift_090 lmohanty$ ./minishift status
There is a newer version of minishift available. Do you want to
automatically update from v0.9.0 to v1.0.0-beta.1 now? [y/N] y
Updating to version 1.0.0-beta.1
Downloading updated binary checksum to validate updated binary
E1221 14:36:54.314413   14894 update.go:155] Cannot download checksum: received 404
`

**Comment by hferentschik** [comment] 2016-12-21 11:28
Let's step back here for a second. There are first of all tow different processes to distinguish. The automatic update of the ISO and the automatic update of the minishift binary.

    There is a newer version of minishift available. Do you want to
    automatically update from v0.9.0 to v1.0.0-beta.1 now? [y/N] y
    Updating to version 1.0.0-beta.1
    Downloading updated binary checksum to validate updated binary
    E1221 09:07:44.140066    9558 update.go:155] Cannot download checksum: received 404

We see the latter here. Minishift tries to upgrade itself. IMO this feature is broken and has not been working for quite some time and it has nothing to do with the owner of the repo.

> See https://github.com/minishift/minishift/blob/6b83d570d5f3c4b5f1680dc436f236c018146344/pkg/minikube/update/update.go#L48

Yes, the owner should be minishift, but this is not the reason why this fails. Try accessing https://github.com/jimmidyson/minishift/releases/download/v1.0.0-beta.1/minishift-1.0.0-beta.1-linux-amd64.tgz.sha256. It works. GitHub puts an automatic redirect in place. 

The problem start with the call made to _MaybeUpdate_ in update.go:

    MaybeUpdate(output, githubOwner, githubRepo, githubRepo, lastUpdateCheckFilePath, localVersion)

Passing _githubRepo_ as third parameter to _MaybeUpdate_ tells the code to update the _minishift_ binary. Literally. The code then goes on into _updateBinary_ where it will try to get the sha for the binary it is supposed to get:

    checksum, err := downloadChecksum(v, downloadBinary, downloadLinkFormat)

Effectively this will try to access https://github.com/jimmidyson/minishift/releases/download/v1.0.0-beta.1/minishift.sha256

This in turn will return the 404 we are seeing. This will fail for us on multiple levels. First off, we are now publishing archives. The right archive link would need to be generated, the archive needs to be downloaded and extracted. Then the binaries can be switched.

The reason I am saying that this has not been working for some time is, that the code literally looks afaict for _minishift_. However, the artifacts were (even before switching to archives) minishift-linux-amd64, minishift-windows-amd64.exe and minishift-darwin-amd64. Hence trying to access the checksum would have failed even then. AFAICS there is no code in place which would take the OS into account, so I would think updating the _minishift_ binary has been broken for some time.

Also note, there is an _update_test.go_ were all tests are commented out. My guess is for this very reason. 

So to make this happen, several things have to change, least importantly the repo owner. Also we need to re-enable the tests (or at least look at them). 

For me this has a quite low priority, but maybe it makes sense to disable the automatic minishift upgrade until we can look at this again and implement it properly.

**Comment by jimmidyson** [comment] 2016-12-21 11:43
This was working fine before, see https://github.com/minishift/minishift/blob/master/pkg/minikube/update/update.go#L67 for how the binary os & arch is included in target download name.

The name of the running binary is only used to figure out the local file that needs to be updated, regardless of name of download file.

**Comment by jimmidyson** [comment] 2016-12-21 11:45
It's the addition of tgz that's causing the issue, plus the fact you're going to have to uncompress somehow to do the in place update better re-execing. That was one reason it was a raw binary download, not bundled.

**Comment by hferentschik** [comment] 2016-12-21 19:48
> This was working fine before, see https://github.com/minishift/minishift/blob/master/pkg/minikube/update/update.go#L67 

ahh, that's what I was looking for. So yes, in this problem it is the new packaging which breaks it.

**Comment by hferentschik** [comment] 2016-12-21 19:48
> That was one reason it was a raw binary download, not bundled.

fair enough

**Comment by luebken** [comment] 2017-02-05 11:15
+1

```
$ minishift start
There is a newer version of minishift available. Do you want to
automatically update from v0.9.0 to v1.0.0-beta.3 now? [y/N] y
Updating to version 1.0.0-beta.3
Downloading updated binary checksum to validate updated binary
E0205 12:12:42.299120    2368 update.go:155] Cannot download checksum: received 404
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
```

**Comment by praveenkumar** [comment] 2017-05-31 08:41
@hferentschik I am closing this issue because we now have a dedicated `update` command in place.

**Closed by praveenkumar** 2017-05-31 08:41 UTC
Labels: kind/bug, priority/major

**Comment by hferentschik** [comment] 2017-05-31 08:58
+1 This is really a duplicate of issue #72 which is fixed.
