### ISSUE TITLE
minishift fails to find hyper-v virtual switch on windows with spanish locale

### ISSUE THREAD

**Issue by jojuva** [minishift/minishift#2401] opened 2018-05-23 19:19 UTC
### General information

  * Minishift version: v1.17.0+f974f0c
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1. have windows with Spanishlocale
  2. set HYPERV_VIRTUAL_SWITCH="Modificador predeterminado"
  3. minishift start
  4. 

### Expected
minishift starts

### Actual
minishift fails to find virtual switch

### Logs
https://gist.github.com/jojuva/15d537ad4ddad600f68187066e0869b0

**Comment by praveenkumar** [comment] 2018-05-24 05:17
@gbraad Can we ask @jojuva to try https://github.com/minishift/minishift/pull/2291 for locale issue?

**Comment by jojuva** [comment] 2018-05-24 20:17
Of course, I can do that if you can guide me.

**Comment by LalatenduMohanty** [comment] 2018-05-31 05:59
@gbraad Can we mark this duplicate of #2096?

**Comment by gbraad** [comment] 2018-05-31 06:38
The patch does work, and this means we could merge... let's create a new issue for the non-ASCII issue.
And yes, it is a duplicate.

**Comment by gbraad** [comment] 2018-06-13 03:05
This can be closed, as #2437 should have solved this issue.

**Closed by gbraad** 2018-06-13 03:05 UTC
Labels: component/hyperv, kind/bug, priority/major
