### ISSUE TITLE
Minishift cannot delete or stop VM after it's started with invalid values for ram, cpu

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#271] opened 2017-01-10 16:17 UTC
**Environment**
minishift: v1.0.0-beta.2
OS: Fedora 24
provider: kvm

**About**
This is more a feature request than a bug I think. When minishift is used to start with invalid values (e.g. `minishift start --memory 0`) and fails to do so, then it is unable to recover itself from this state with `minishift delete` command. Deleting ~/.minishift folder helps to overcome this issue. 

```
[agajdosi@dhcp-24-156 ~]$ minishift start --memory 0
Starting local OpenShift instance using 'kvm' hypervisor...
E0110 14:35:55.007275   12197 start.go:135] Error starting machine: Error creating. Error creating machine: Error in driver during machine creation: [Code-27] [Domain-20] XML error: Memory size must be specified via <memory> or in the <numa> configuration. Retrying.
E0110 14:35:55.045724   12197 start.go:135] Error starting machine: Error getting state for host: unexpected EOF. Retrying.
E0110 14:35:55.079158   12197 start.go:135] Error starting machine: Error getting state for host: unexpected EOF. Retrying.
E0110 14:35:55.079267   12197 start.go:141] Error starting machine:  Error creating. Error creating machine: Error in driver during machine creation: [Code-27] [Domain-20] XML error: Memory size must be specified via <memory> or in the <numa> configuration
Error getting state for host: unexpected EOF
Error getting state for host: unexpected EOF
[agajdosi@dhcp-24-156 ~]$ minishift delete
Deleting local OpenShift instance...
Error unregistring machine: connection is shut down[agajdosi@dhcp-24-156 ~]$ minishift start
Starting local OpenShift instance using 'kvm' hypervisor...
E0110 14:36:03.706948   12262 start.go:135] Error starting machine: Error getting state for host: unexpected EOF. Retrying.
E0110 14:36:03.737379   12262 start.go:135] Error starting machine: Error getting state for host: unexpected EOF. Retrying.
E0110 14:36:03.766466   12262 start.go:135] Error starting machine: Error getting state for host: unexpected EOF. Retrying.
E0110 14:36:03.766486   12262 start.go:141] Error starting machine:  Error getting state for host: unexpected EOF
Error getting state for host: unexpected EOF
Error getting state for host: unexpected EOF
```

**Comment by budhrg** [comment] 2017-01-30 13:56
We should have some minimum value for RAM, CPUs, memory and validate against it with valid input provided.

**Comment by LalatenduMohanty** [comment] 2017-02-02 15:22
I can reproduce the issue.  The issue is `minishift delete` should clean up properly so that the next `minishift start` should not effected by the previous VM.

```
$ minishift start --memory 0
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0202 19:48:55.628580   23894 start.go:140] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: unexpected EOF. Retrying.
E0202 19:50:56.992648   23894 start.go:140] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
E0202 19:52:58.381636   23894 start.go:140] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
E0202 19:52:58.381693   23894 start.go:146] Error starting the VM:  Error creating the VM. Error creating machine: Error in driver during machine creation: unexpected EOF
Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting

$ minishift delete
Deleting the Minishift VM...
Error unregistring the VM: Host is not running

$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0202 20:41:33.949093   23969 start.go:140] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
E0202 20:43:35.327715   23969 start.go:140] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
E0202 20:45:36.731899   23969 start.go:140] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.
E0202 20:45:36.731972   23969 start.go:146] Error starting the VM:  Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting
```

**Comment by LalatenduMohanty** [comment] 2017-02-03 08:04
The issue seems to be that `minishift delete` is not deleting the artifacts which were created during `start`.

```
├── machines
│   ├── minishift
│   │   ├── boot2docker.iso
│   │   ├── config.json
│   │   ├── id_rsa
│   │   ├── id_rsa.pub
│   │   ├── initrd.img
│   │   ├── root-volume.sparsebundle
│   │   │   ├── Info.bckup
│   │   │   ├── Info.plist
│   │   │   ├── bands
│   │   │   │   ├── 0
│   │   │   │   ├── 19
│   │   │   │   ├── 9b3
│   │   │   │   └── 9c3
│   │   │   └── token
│   │   └── vmlinuz64
│   ├── server-key.pem
│   └── server.pem
```

**Comment by hferentschik** [comment] 2017-02-12 19:53
So what's the bottom line here and what's the solution?

Looking at the output, there seems registration involved as well. Is this occurring when using the CDK? If so, is the problem re-producable with the default B2D ISO? Could it be that the VM is in a state which is not stopped and hence the un-registration fails and hence the delete is not cleaning up?

@praveenkumar could this be due to issue #318 and be fixed by pull request #384.

**Comment by budhrg** [comment] 2017-02-14 08:38
> could this be due to issue #318 and be fixed by pull request #384.

@hferentschik ,   I confirm from my end that latest master(which include above PR) had resolved this issue. cc @agajdosi .

However, @hferentschik , @praveenkumar , I saw interesting thing here. 
`minishift delete` fails with error but actually it is performing its operation.

```
$ minishift start --memory 0
Starting local OpenShift cluster using 'kvm' hypervisor...
E0214 14:03:59.463779    7406 start.go:150] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-27] [Domain-20] XML error: Memory size must be specified via <memory> or in the <numa> configuration. Retrying.
E0214 14:03:59.489324    7406 start.go:150] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
E0214 14:03:59.515712    7406 start.go:150] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
E0214 14:03:59.515744    7406 start.go:156] Error starting the VM:  Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-27] [Domain-20] XML error: Memory size must be specified via <memory> or in the <numa> configuration
Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF

$ tree ~/.minishift 
/home/budhram/.minishift
├── cache
....
├── machines
│   └── minishift
│       ├── boot2docker.iso
│       ├── config.json
│       ├── id_rsa
│       ├── id_rsa.pub
│       └── minishift.img
└── tmp

11 directories, 15 files


$ minishift delete   
Deleting the Minishift VM...
Error deleting the VM:  connection is shut down


$ tree ~/.minishift
/home/budhram/.minishift
├── cache
...
├── machines                                     ######## Machine data deleted
└── tmp

10 directories, 10 files

$ minishift start  
Starting local OpenShift cluster using 'kvm' hypervisor...
------------ Works fine -----------

$ minishift delete 
Deleting the Minishift VM...
Minishift VM deleted.
```

**Comment by LalatenduMohanty** [comment] 2017-02-14 08:50
I had reproduced the issue on boot2docker iso. I will cross check again with the above mentioned PR to see if it can be reproducible.

**Comment by hferentschik** [comment] 2017-02-14 08:51
> I saw interesting thing here. minishift delete fails with error but actually it is performing its operation.

I guess this might just be a misleading message. There are two parts in delete. Potentially stopping the VM and then deleting the actual VM files. Given that the start failed, there is no working VM. In fact my guess is that there are just some cert files in the directory. Hence the message "connection is shut down". After the that the delete command will just continue and delete the files. If you look at _cluster.DeleteHost_, you see two calls made which map to what I just described. At the same time all errors are collected and reported in the end. That's what we see here.

Not sure whether we can improve on the message here!? Might be tricky since we first would need to determine the various failure cases. If we want to do something about this, then I think we should do this in a different issue.

@budhrg Did you try with community and CDK version to make sure it works in both cases? 
@agajdosi Could you also try to re-produce?

**Comment by hferentschik** [comment] 2017-02-14 08:51
> I had reproduced the issue on boot2docker iso. I will cross check again with the above mentioned PR to see if it can be reproducible.

You tried it just now again? The pull request I mentioned is merged. We are testing against master.

**Comment by LalatenduMohanty** [comment] 2017-02-14 08:53
> You tried it just now again? The pull request I mentioned is merged. We are testing against master.

Nope, it was before the PR mentioned here got merged.

**Comment by LalatenduMohanty** [comment] 2017-02-14 09:07
I did a quick test and it seems minishift delete is able to delete the VM.  Lets wait for @agajdosi to see if it is working for him. 

```
$ minishift start --memory 0
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0214 14:31:32.001880   34872 start.go:150] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
E0214 14:33:33.375185   34872 start.go:150] Error starting the VM: Error starting stopped host: Machine didn't return an IP after 120 seconds, aborting. Retrying.

Lalatendus-MacBook-Pro:~ lmohanty$ tree ~/.minishift/
/Users/lmohanty/.minishift/
├── ca.pem
├── cache
│   ├── iso
│   │   └── minishift-b2d.iso
│   ├── oc
│   │   └── v1.4.1
│   │       └── oc
│   └── openshift
├── cert.pem
├── certs
│   ├── ca-key.pem
│   ├── ca.pem
│   ├── cert.pem
│   └── key.pem
├── config
│   └── config.json
├── key.pem
├── logs
├── machines
│   ├── minishift
│   │   ├── boot2docker.iso
│   │   ├── config.json
│   │   ├── id_rsa
│   │   ├── id_rsa.pub
│   │   ├── initrd.img
│   │   ├── root-volume.sparsebundle
│   │   │   ├── Info.bckup
│   │   │   ├── Info.plist
│   │   │   ├── bands
│   │   │   │   ├── 0
│   │   │   │   ├── 19
│   │   │   │   ├── 9b3
│   │   │   │   └── 9c3
│   │   │   └── token
│   │   └── vmlinuz64
│   ├── server-key.pem
│   └── server.pem
└── tmp

13 directories, 25 files

Lalatendus-MacBook-Pro:~ lmohanty$ minishift delete
Deleting the Minishift VM...
Minishift VM deleted.


Lalatendus-MacBook-Pro:~ lmohanty$ tree ~/.minishift/
/Users/lmohanty/.minishift/
├── ca.pem
├── cache
│   ├── iso
│   │   └── minishift-b2d.iso
│   ├── oc
│   │   └── v1.4.1
│   │       └── oc
│   └── openshift
├── cert.pem
├── certs
│   ├── ca-key.pem
│   ├── ca.pem
│   ├── cert.pem
│   └── key.pem
├── config
│   └── config.json
├── key.pem
├── logs
├── machines
│   ├── server-key.pem
│   └── server.pem
└── tmp

10 directories, 12 files
```

**Comment by agajdosi** [comment] 2017-02-14 09:29
@LalatenduMohanty I have build from master now and I am no longer able to reproduce this issue. Unlikely from you in my case with kvm provider the VM is not created at all, which seems good.
```
[agajdosi@dhcp-24-156 bin]$ minishift start --memory 0
Starting local OpenShift cluster using 'kvm' hypervisor...
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.0.0/minishift-b2d.iso'
 40.00 MB / 40.00 MB [=============================================================================================================================================] 100.00% 0
E0214 10:21:31.132235    9877 start.go:150] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-27] [Domain-20] XML error: Memory size must be specified via <memory> or in the <numa> configuration. Retrying.
E0214 10:21:31.187376    9877 start.go:150] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
E0214 10:21:31.220399    9877 start.go:150] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
E0214 10:21:31.220432    9877 start.go:156] Error starting the VM:  Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-27] [Domain-20] XML error: Memory size must be specified via <memory> or in the <numa> configuration
Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF
[agajdosi@dhcp-24-156 bin]$ minishift delete
Deleting the Minishift VM...
Error deleting the VM:  connection is shut down
[agajdosi@dhcp-24-156 bin]$ virsh list
 Id    Name                           State
----------------------------------------------------
```

**Comment by LalatenduMohanty** [comment] 2017-02-14 12:05
@agajdosi Thanks. Closing the issue.

**Closed by LalatenduMohanty** 2017-02-14 12:05 UTC
Labels: kind/bug, priority/major, status/needs-info

**Comment by kishansag** [comment] 2017-09-15 06:39
Any known fix for these errors?

```
[ksagathi@ksagathi ~]$ minishift delete
Deleting the Minishift VM...
Error deleting the Minishift VM: unexpected EOF
```
```
[ksagathi@ksagathi ~]$ minishift start
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... \ FAIL E0915 12:05:07.360682   11698 start.go:344] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: read /home/ksagathi/.minishift/cache/iso/minishift-b2d.iso: input/output error. Retrying.
FAIL E0915 12:05:07.411535   11698 start.go:344] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
FAIL E0915 12:05:07.445298   11698 start.go:344] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: read /home/ksagathi/.minishift/cache/iso/minishift-b2d.iso: input/output error
Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF
```
I have tried manually deleting ~/minishift folder and re-deploying, but that would also lead to the same error on running these commands

**Comment by budhrg** [comment] 2017-09-15 07:00
@kishansag , could you run `minishift start --show-libmachine-logs -v 5`?

**Comment by kishansag** [comment] 2017-09-15 07:08
dump of `minishift start --show-libmachine-logs -v 5` is below.
```
[ksagathi@ksagathi ~]$ minishift start --show-libmachine-logs -v 5
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... Found binary path at /usr/local/bin/docker-machine-driver-kvm
| Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:46215
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:39188
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetMachineName
(minishift) Calling .DriverName
(minishift) Calling .SetConfigFromFlags
(minishift) DBG | SetConfigFromFlags called
(minishift) Trying to access option swarm-master which does not exist
(minishift) DBG | AK: resolvestorepath: /home/ksagathi/.minishift
Running pre-create checks...
(minishift) DBG | AK: resolvestorepath: /home/ksagathi/.minishift
(minishift) Calling .PreCreateCheck
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to bool for key swarm-master
(minishift) Trying to access option swarm-host which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-host
(minishift) Trying to access option swarm-discovery which does not exist
(minishift) THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
(minishift) Type assertion did not go smoothly to string for key swarm-discovery
(minishift) DBG | About to check libvirt version
(minishift) DBG | Validating private network
(minishift) DBG | Validating network default
(minishift) Calling .GetConfigRaw
Creating machine...
(minishift) Calling .Create
(minishift) Downloading /home/ksagathi/.minishift/cache/boot2docker.iso from file:///home/ksagathi/.minishift/cache/iso/minishift-b2d.iso...
- FAIL E0915 12:31:15.212523   12327 start.go:344] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: read /home/ksagathi/.minishift/cache/iso/minishift-b2d.iso: input/output error. Retrying.
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
\ Plugin server listening at address 127.0.0.1:40427
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 22 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a140)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8201340e0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200e7de0, 0xe0d430, 0xc8201608f0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc820036ef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc820036ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc82001bb00, 0xc82001b8c0, 0xc820160060, 0xc8200af680, 0xc820154640, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc8201608f0, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
FAIL E0915 12:31:15.260343   12327 start.go:344] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:38865
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 9 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a140)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8201400e0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200f3de0, 0xe0d430, 0xc82000b7b0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc82003cef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc82003cef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc82001bb00, 0xc82001b8c0, 0xc82015a060, 0xc8200bb680, 0xc82014e640, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc82000b7b0, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
FAIL E0915 12:31:15.286055   12327 start.go:344] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: read /home/ksagathi/.minishift/cache/iso/minishift-b2d.iso: input/output error
Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF
```

Also tried reinstalling kvm, but same result.

**Comment by budhrg** [comment] 2017-09-15 11:37
> (minishift) Failed to fetch machine
> (minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
> (minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]

This is weird.

**Comment by gbraad** [comment] 2017-09-15 12:00
@kishansag
Can you create a new issue? The one you responded on is closed and unrelated. We would like to keep information easy to find for others.

**Comment by budhrg** [comment] 2017-09-15 12:03
> Can you create a new issue? The one you responded on is closed and unrelated. We would like to keep information easy to find for others.

+1

**Comment by khoukhaa** [comment] 2018-03-26 14:13
can any one help me plz??
![heeeelp](https://user-images.githubusercontent.com/37330719/37911537-9c4fe198-3110-11e8-92ae-7010110fb4e6.PNG)

**Comment by ragava0786** [comment] 2018-07-11 10:12
minishift) Failed to create the VM: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm 
. FAIL E0711 10:11:06.231264    4109 start.go:368] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm . Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm

**Comment by ragava0786** [comment] 2018-07-11 10:12
iam also face same error

**Comment by agajdosi** [comment] 2018-07-11 10:24
Hi @ragava0786, @khoukhaa thank for the report. Unfortunately the original issue seems unrelated to the problems you are facing. If you could please open new issue then it would be great. Solving the issues here would make it much more unclear to the team and other users. Thank you for understanding.
