### ISSUE TITLE
Starting OpenShift container ... FAIL

### ISSUE THREAD

**Issue by suiwenfeng** [minishift/minishift#1087] opened 2017-06-29 15:55 UTC
```
-- Starting OpenShift container ... FAIL
   Error: Docker run error rc=2
   Details:
     Image: openshift/origin:v1.5.1
     Entrypoint: [/bin/bash]
     Command: [-c for name in 192.168.1.106 minishift; do ls /var/lib/origin/openshift.local.config/node-$name &> /dev/null && echo $name && break; done]
```

before restart, i can see the console by run `minishift.exe console`.
after restart, i checked `minishift.exe status`, it return "RUNNING". but the web console is not accessible.
then i shutdown the VM from Hyper-V management, and rerun `minishift.exe start`
the error throw then.

**Comment by LalatenduMohanty** [comment] 2017-06-30 08:29
@suiwenfeng When you restart you mean `minishift stop` then `minishift start` right? Also using HyperV console for stopping the VM is not rerecorded. The right way is `minishift stop`.

**Comment by LalatenduMohanty** [comment] 2017-06-30 08:31
To debug you can login to the VM usng `minishift ssh` and see if the OpenShift containers are running by running `docker ps` command.

**Comment by gbraad** [comment] 2017-07-05 08:21
When did you create this Minishift instance? Has it been operational for some time?

It looks a lot like #593 or other issues reported when the IP address of the instance has changed.

**Comment by suiwenfeng** [comment] 2017-07-05 10:03
Let me check this weekend.

**Comment by gbraad** [comment] 2017-07-05 15:26
Duplicate of and related to #343 and #593,

**Comment by gbraad** [comment] 2017-08-28 02:16
No update from the OP. Closing the issue as the issue is this is likely a duplicate.
If the issue is reproducible, you can reopen or file a new issue.

**Closed by gbraad** 2017-08-28 02:16 UTC
Labels: kind/bug, priority/major, resolution/duplicate
