### ISSUE TITLE
Console blocked when there is no internet connection

### ISSUE THREAD

**Issue by cescoffier** [minishift/minishift#166] opened 2016-11-29 13:48 UTC
When you have no internet, `minishift console` is blocked. 

@jimmidyson said on IRC that is may come from the auto-update, and the timeout might be too long. I didn't try to kept is running for minutes, after 20-30 seconds, I've killed it as I've easy enough to get the URL directly in the browser.

to reproduce the issue:

1. turn off your Internet connection (WIFI, Eth0...)
2. launch `minishift console`

**Comment by budhrg** [comment] 2017-01-06 11:06
@cescoffier 

Hi, could you try with latest minishift release `1.0.0-beta.1`?

It is not reproducible now and `minishift console` works fine.

**Comment by cescoffier** [comment] 2017-01-07 09:25
It's still the issue with `minishift stop`:

```
E0107 10:24:59.797440    7290 update.go:76] Get https://api.github.com/repos/jimmidyson/minishift/releases/latest: dial tcp: i/o timeout
```

**Comment by cescoffier** [comment] 2017-01-07 09:28
`minishift start` however react immediately:

```
E0107 10:25:59.691034    7541 update.go:76] Get https://api.github.com/repos/jimmidyson/minishift/releases/latest: dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:49539->[::1]:53: read: connection refused
```

`minishift console` still have the issue. It waits for a couple of seconds (30 ?) before going through. So the issue is NOT fixed in 1.0.0-beta.1.

**Comment by cescoffier** [comment] 2017-01-07 09:29
Step to reproduce:

* turn off internet (wifi)
* launch `minishift start`
* once started, execute `minishift console`. The command is stuck for 30 seconds or so before opening the browser. 
* `minishift stop` will also be stuck for 30 seconds of so before stopping minishift.

**Comment by cescoffier** [comment] 2017-01-07 09:30
Also I'm not sure about the checked url too. Seems to be the old repo from @jimmidyson.

**Comment by hferentschik** [comment] 2017-01-09 10:25
I think this is really a duplicate of the various other issues we have seen where the automatic updates checks either exceed the Git Hub API rate limit or cause error when the check does not work at all due to network issues.

**Comment by hferentschik** [comment] 2017-01-09 10:27
This will be "fixed" by issue #246 which (temporarily) disables automatic update checks.

**Comment by budhrg** [comment] 2017-01-18 07:07
Hi @cescoffier

We have disabled automatic update checks in [`v1.0.0-beta.2`](https://github.com/minishift/minishift/releases/tag/v1.0.0-beta.2) and this issue should be fix by now.

Could you confirm?

**Comment by hferentschik** [comment] 2017-01-20 09:05
Closing this issue as we cannot re-produce this anymore.

**Closed by hferentschik** 2017-01-20 09:05 UTC
Labels: status/needs-info

**Comment by cescoffier** [comment] 2017-01-20 09:37
Confirmed, thanks !
