### ISSUE TITLE
"getsockopt: connection refused" error on mac

### ISSUE THREAD

**Issue by imne** [minishift/minishift#1746] opened 2017-11-23 18:49 UTC
Hi 

I just installed minishift on my mac the installation went fine but after I try run the "minishift start" command I get the below error, I've attached the log output.

```
Senzos-MacBook-Pro:~ iMNE$ minishift start
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ............................ OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 30% complete
Pulled 1/4 layers, 33% complete
Pulled 1/4 layers, 38% complete
Pulled 1/4 layers, 40% complete
Pulled 1/4 layers, 45% complete
Pulled 1/4 layers, 48% complete
Pulled 2/4 layers, 55% complete
Pulled 2/4 layers, 58% complete
Pulled 2/4 layers, 60% complete
Pulled 2/4 layers, 66% complete
Pulled 2/4 layers, 69% complete
Pulled 2/4 layers, 73% complete
Pulled 2/4 layers, 78% complete
Pulled 2/4 layers, 79% complete
Pulled 2/4 layers, 81% complete
Pulled 2/4 layers, 84% complete
Pulled 3/4 layers, 79% complete
Pulled 3/4 layers, 82% complete
Pulled 3/4 layers, 89% complete
Pulled 3/4 layers, 95% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ... 
   Pulling image openshift/origin:v3.6.0
   Pulled 1/4 layers, 26% complete
   Pulled 1/4 layers, 30% complete
   Pulled 1/4 layers, 33% complete
   Pulled 1/4 layers, 38% complete
   Pulled 1/4 layers, 40% complete
   Pulled 1/4 layers, 45% complete
   Pulled 1/4 layers, 48% complete
   Pulled 2/4 layers, 55% complete
   Pulled 2/4 layers, 58% complete
   Pulled 2/4 layers, 60% complete
   Pulled 2/4 layers, 66% complete
   Pulled 2/4 layers, 69% complete
   Pulled 2/4 layers, 73% complete
   Pulled 2/4 layers, 78% complete
   Pulled 2/4 layers, 79% complete
   Pulled 2/4 layers, 81% complete
   Pulled 2/4 layers, 84% complete
   Pulled 3/4 layers, 79% complete
   Pulled 3/4 layers, 82% complete
   Pulled 3/4 layers, 89% complete
   Pulled 3/4 layers, 95% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.64.3 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.64.3:8443/healthz/ready
   Details:
     No log available from "origin" container

   Caused By:
     Error: Get https://192.168.64.3:8443/healthz/ready: dial tcp 192.168.64.3:8443: getsockopt: connection refused
Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by praveenkumar** [comment] 2017-11-24 05:12
@imne Was it the restart or first time you started the minishift? Also are you behind a vpn or corporate proxy?

Can you try following if that resolves your issue?

```
$ minishift delete --force
$ minishift start 
```

**Comment by praveenkumar** [comment] 2018-01-18 09:52
@imne I am closing this issue due to lack of information, please reopen if you think this is still an issue.

**Comment by praveenkumar** [comment] 2018-01-18 09:53
@imne I am closing this issue due to lack of information, please reopen if you think this is still an issue.

**Comment by lalitha2** [comment] 2018-09-06 06:14
Please reopen this issue. I get the same issue I am trying to execute this command from command prompt.
machine : windows10. configuring through virtualbox installation.
 "minishift config set vm-driver virtualbox"
> minishift start
getting below error
C:\Users\lselvaraj>minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM .................................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 14% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.10.0
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --public-hostname 192.168.99.102 --routing-suffix 192.168.99.102.nip.io
err     : Process exited with status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.102 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0906 02:00:13.975609    2393 flags.go:30] Running "create-kubelet-flags"
I0906 02:00:16.160687    2393 run_kubelet.go:48] Running "start-kubelet"
I0906 02:00:16.711281    2393 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0906 02:05:16.744910    2393 run_self_hosted.go:542] API server error: Get https://192.168.99.102:8443/healthz?timeout=32s: dial tcp 192.168.99.102:8443: getsockopt: connection refused ()

**Comment by lalitha2** [comment] 2018-09-06 06:16
I would like to know the reason for this and the solution. Please help as i have given this command for 5 times and more and still get same error.

**Comment by praveenkumar** [comment] 2018-09-06 07:03
@lalitha2 can you try https://github.com/minishift/minishift/issues/1746#issuecomment-346744442 steps and also let us know if you are behind a proxy or vpn environment.

**Comment by praveenkumar** [comment] 2018-09-06 10:56
@lalitha2 Have a look to https://github.com/minishift/minishift/issues/1588 issue thread and check if something works for you.

**Comment by lalitha2** [comment] 2018-09-07 07:39
Downgrading virtual box version to 5.1.14 did not help.
It worked fine with minishift version downgraded 
minishift version : 1.21
Virtual box version : 5.1.14 or 5.2.8( new version also works)

**Comment by praveenkumar** [comment] 2018-09-07 07:59
@amitkrout @agajdosi can you folks verify this and also if you need any more details about the setup please ask @lalitha2

**Comment by amitkrout** [comment] 2018-09-07 08:32
@lalitha2 I am looking into it...

**Comment by amitkrout** [comment] 2018-09-07 10:18
@lalitha2 I am not able to reproduce the same on minishift v1.23.0 + Win10 + VirtualBox. Hope you checked all the suggestion from #1588. Can you please try with these above combinations, if not yet tried. Otherwise clean up your setup i mean delete ```.minishift``` and ```.kube``` then start minishift freshly.  

Might be a network glitch by that time when you faced the issue. Also similar inconsistent issue is being tracked in https://github.com/openshift/origin/issues/20617

**Comment by gbraad** [comment] 2018-09-07 10:26
BTW, I have seen a similar issue today on my system too... But only with v3.10 of openshift. I suggest to open a new issue for this.

**Closed by gbraad** 2018-09-07 10:26 UTC
Labels: kind/bug, os/darwin, priority/major, status/needs-info

**Comment by gbraad** [comment] 2018-09-07 10:30
Please follow up at #2781
