### ISSUE TITLE
Minishift start goes well using default driver when staring a stopped openshift cluster created on non default hypervisor(VirtualBox)

### ISSUE THREAD

**Issue by amitkrout** [minishift/minishift#2609] opened 2018-07-17 10:56 UTC
### General information

  * Minishift version: master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox/generic

### Steps to reproduce

  1. Setup virtual box on macOS or Linux so that user can switch between drivers
  2. Run ./minishift start —vm-driver virtualbox
  3. ./minishift stop
  4. ./mishift start

### Expected
Should fail because this will run on default driver as no driver is added to the persistent config in the first m start

### Actual
Passing

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment] 2018-07-17 11:01
This is expected. VM is not created because of https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster.go#L69-L90 so it just checks if already exist => state of VM => if stopped => just start it without creating a new one. VM creation happen https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/cluster.go#L327 here

I am planning to close this issue as not a bug.

**Comment by gbraad** [comment] 2018-07-17 11:03
Do not completely understand the issue here. This is a restart... It should pass

**Comment by praveenkumar** [comment] 2018-07-17 11:05
> This is a restart... It should pass

That's right.

**Closed** 2018-07-17 11:20 UTC
Labels: kind/bug, priority/major
