### ISSUE TITLE
Error while installing an addon from local ditrectory and simultaneously enabling it. 

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#748] opened 2017-04-13 05:54 UTC
If I try to install an addon from local directory and simultaneously enable I am getting following error. 

```
$ minishift addons install addons/expose-registry --enable
Unable to enable add-on registry: Unable to find addon registry in addon directory /Users/lmohanty/.minishift/addons
```

However in-spite of the error the addon is getting installed and enabled. Check below steps to reproduce this. 

Minishift Version: Latest compiled from master commit c8507e2a75c6c96e310e9b9b7a96b55cf49e4e1b

Host: OS X Seirra

Hypervisor: Xhyve

```
$ tree addons/expose-registry/
addons/expose-registry/
└── expose-registry.addon

$ minishift status
Does Not Exist

$ rm -rf ~/.minishift/addons

$ minishift addons install addons/expose-registry --enable
Unable to enable add-on registry: Unable to find addon registry in addon directory /Users/lmohanty/.minishift/addons

$ minishift addons list
- registry       : enabled    P(0)

```

However If I break it down to two steps it works fine. 

```
$ minishift addons install addons/expose-registry
Addon registry installed

$ minishift addons enable registry

$ minishift addons list
- registry       : enabled    P(0)
```

Also

**Comment by agajdosi** [comment] 2017-05-12 11:33
Tried this with CDK RC2 and registry-route addon on Windows 7 in CMD, I am also seeing the same problem, but addon is then disabled not enabled:

```
C:\Users\CDK>minishift addons install registry-route --enable
Unable to enable add-on registry-route: Unable to find addon registry-route in addon directory C:\Users\CDK\.minishift\addons

C:\Users\CDK>minishift addons list
- admin-user     : enabled    P(0)
- anyuid         : enabled    P(0)
- eap            : enabled    P(0)
- fuse           : enabled    P(0)
- registry-route : disabled   P(0)
```

**Comment by budhrg** [comment] 2017-05-12 12:37
The fix for it has been merged today https://github.com/minishift/minishift/pull/886.

This issue seems to duplicate of https://github.com/minishift/minishift/issues/885 or vice-versa.

Since, the respective PR is merged I am closing it. 

Feel free to reopen it if it is not working.

> Tried this with CDK RC2 and registry-route addon on Windows 7 in CMD, I am also seeing the same problem, but addon is then disabled not enabled:

@agajdosi , it should be tracked as CDK issue.

**Closed by budhrg** 2017-05-12 12:37 UTC
Labels: kind/bug, priority/minor
