### ISSUE TITLE
export KUBECONFIG

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#2982] opened 2018-11-07 14:17 UTC
respect the KUBECONFIG env variable. This works well with minikube but not minishift.  I have a LOT of minishift instances on my machine, where I would like to have a different KUBECONFIG per minishift instance.  Plus I constantly "minishift delete" and recreate the VM,. 

Here are my minikube env vars
export MINIKUBE_HOME=/Users/burrsutter/minikube_0.30.0/bin;
export PATH=$MINIKUBE_HOME:$PATH
export KUBECONFIG=$MINIKUBE_HOME/.kube/config:$MINIKUBE_HOME/.kube/kubconfig2
export KUBE_EDITOR="code -w"

### General information

  * Minishift version: 1.26.1
  * OS: macOS 
  * Hypervisor: VirtualBox

**Comment by burrsutter** [comment] 2018-11-07 14:22
there is a nice tool called "kubectx" that allows the end-user to more easily see and navigate the KUBECONFIG file.   Here is what has shown up inside of my KUBECONFIG after just about 7 weeks old
kubectx
/192-168-99-100:8443/admini
artemis-jms/192-168-99-101:8443/admin
ci/192-168-99-102:8443/developer
default/13-56-49-163:8443/admin
default/192-168-99-100:8443/admin
default/192-168-99-101:8443/admin
default/192-168-99-102:8443/admin
default/192-168-99-104:8443/admin
default/35-230-115-194:8443/admin
default/40-78-82-99:8443/admin
demo/192-168-99-104:8443/admin
demo2-amq/13-56-49-163:8443/admin
demo2-amq/192-168-99-100:8443/admin
demo2-amq/192-168-99-101:8443/admin
demo2-amq/192-168-99-102:8443/admin
demo2-amq/192-168-99-104:8443/admin
demo2-amq/35-230-115-194:8443/admin
demo2-amq/40-78-82-99:8443/admin
faas/192-168-99-102:8443/admin
faas/192-168-99-102:8443/developer
faas125
helloworld-msa/192-168-99-102:8443/admin
helloworld-msa/192-168-99-102:8443/developer
helloworldmsa
istio-operator/192-168-99-100:8443/admin
istio-system/192-168-99-101:8443/admin
istio-system/192-168-99-102:8443/admin
istio-system/192-168-99-104:8443/admin
istio-tutorial
istio124Oct9
istio125
istio1261
knative125
knative1261
mykafka/192-168-99-101:8443/admin
myproject/192-168-99-100:8443/admin
myproject/192-168-99-100:8443/developer
myproject/192-168-99-100:8443/system:admin
myproject/192-168-99-101:8443/admin
myproject/192-168-99-101:8443/developer
myproject/192-168-99-101:8443/system:admin
myproject/192-168-99-102:8443/admin
myproject/192-168-99-102:8443/developer
myproject/192-168-99-102:8443/system:admin
myproject/192-168-99-103:8443/system:admin
myproject/192-168-99-104:8443/admin
myproject/192-168-99-104:8443/developer
myproject/192-168-99-104:8443/system:admin
myproject/192-168-99-105:8443/system:admin
myproject/192-168-99-106:8443/system:admin
myproject/192-168-99-107:8443/system:admin
myproject/192-168-99-108:8443/system:admin
myproject/192-168-99-109:8443/admin
myproject/192-168-99-109:8443/developer
myproject/192-168-99-109:8443/system:admin
myproject/192-168-99-110:8443/system:admin
myproject/192-168-99-111:8443/system:admin
myspace/192-168-99-101:8443/admin
openshift-web-console/192-168-99-100:8443/admin
openshift/192-168-99-102:8443/admin
popmovies/35-230-115-194:8443/admin
sso/192-168-99-102:8443/developer
tutorial/192-168-99-100:8443/admin
tutorial/192-168-99-101:8443/admin
tutorial/192-168-99-102:8443/admin
tutorial/192-168-99-104:8443/admin
validate/192-168-99-100:8443/admin

**Comment by praveenkumar** [comment] 2018-11-12 05:13
@burrsutter we are already implemented to respect `KUBECONFIG` environment variable part in minishift.

Can you try below and let us know where it is now failing and what error you are getting?

```console
export MINISHIFT_HOME=/Users/burrsutter/minishift_1.26.1/bin
export PATH=$MINISHIFT_HOME:$PATH
export KUBECONFIG=$MINISHIFT_HOME/.kube/config:$MINISHIFT_HOME/.kube/kubconfig2
export KUBE_EDITOR="code -w"
```

**Comment by LalatenduMohanty** [comment] 2018-11-15 05:59
IMO this is duplicate of https://github.com/minishift/minishift/issues/2871 .

**Comment by LalatenduMohanty** [comment] 2019-01-04 07:15
Closing this as a duplicate.

**Closed by LalatenduMohanty** 2019-01-04 07:15 UTC
Labels: kind/feature, priority/major, status/needs-info
